### ISSUE TITLE
希望添加对于 behavior 为 ipcidr 的 rule-provider 的支持

### ISSUE THREAD

**Issue by yjh1021317464** [Fndroid/clash_for_windows_pkg#1017]
**描述**
clash premium 支持添加 behavior 为 ipcidr 的 rule-provider https://github.com/Dreamacro/clash/wiki/premium-core-features#rule-providers
如
```
china-ip:
  type: http
  behavior: ipcidr
  interval: 86400
  path: ./ChinaIp.yaml
  url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaIp.yaml
```

**其他说明**

目前 cfw 不支持，添加配置后会报错
clash for android 支持这个功能，希望尽量能添加这个功能以方便在多平台共用一个配置文件
