### ISSUE TITLE
Win10企业版2004版本无法使用TAP模式

### ISSUE THREAD

**Issue by fngoo** [Fndroid/clash_for_windows_pkg#1030]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Win10 2004版本
企业版

**描述**

开启tap模式，cfw-tap显示网络电缆被拔出。
除此之外，与关闭tap模式时无区别

**复现**

1.双击打开Clash for Windows（或使用管理员模式）
2.打开TAP模式，确认网络适配器cfw-tap已安装
3.按照[文档](https://docs.cfw.lbyczf.com/contents/tap.html)更改profiles中DNS设置，物理网卡名称无误
```
dns:
   enable: true
   enhanced-mode: redir-host # 或 fake-ip
   listen: 0.0.0.0:53
   nameserver:
      - 223.5.5.5
interface-name: WLAN # 物理网卡名称
```

**Comment by fngoo** [comment]
开启mixin，
配置如下：
```
mixin: 
  dns:
    enable: true
    enhanced-mode: redir-host # 或 fake-ip
    listen: 0.0.0.0:53
    nameserver:
      - 223.5.5.5
  interface-name: WLAN # 物理网卡名称
```
cfw-tap被成功识别，win10弹窗提示网络可被发现，点击“是”

之后就网络连接中断，无法访问谷歌或者百度：
```
无法访问此网站www.baidu.com 意外终止了连接。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_CLOSED
```
