### ISSUE TITLE
开启系统代理某些情况下会导致无法正常连接

### ISSUE THREAD

**Issue by CGQAQ** [Fndroid/clash_for_windows_pkg#1175]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
windows10 1909
![image](https://user-images.githubusercontent.com/15936231/94520305-98487980-025e-11eb-9254-4fb4f55e3dec.png)

**描述**
## 开启后，握手错误 EOF（我怀疑是mixed-port的锅)
![image](https://user-images.githubusercontent.com/15936231/94511441-ef911e80-024b-11eb-847c-e5341adaf5bf.png)
![image](https://user-images.githubusercontent.com/15936231/94511437-e99b3d80-024b-11eb-8e83-3dbd3048943d.png)
## 关闭后，正常连接
![image](https://user-images.githubusercontent.com/15936231/94511453-f61f9600-024b-11eb-854e-ff413ea7b375.png)
![image](https://user-images.githubusercontent.com/15936231/94511466-fddf3a80-024b-11eb-837c-1086beade01f.png)

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)
开启tap模式
```yaml
mixin: # object
  dns:
    enable: true
    enhanced-mode: redir-host # 或 fake-ip
    listen: 0.0.0.0:53
    nameserver:
      - 114.114.114.114
    fallback:
      - tls://8.8.8.8
      - tls://1.1.1.1
```
开启或关闭系统代理

**预期行为**

[//]: # (清晰地描述期望看到的行为)
正常连接

**日志**

[//]: # (上传触发问题对应的日志文件)
日志是空的
![sR6RiyxNaI](https://user-images.githubusercontent.com/15936231/94511690-a68d9a00-024c-11eb-9fcb-f902084bb819.gif)
