### ISSUE TITLE
DIRECT模式下无法访问http://tool.mkblog.cn/dns/

### ISSUE THREAD

**Issue by LittleRey** [Fndroid/clash_for_windows_pkg#1200]
### Clash for windows 12.0:
环境：Win10
安装TAP，无法访问http://tool.mkblog.cn/dns/
未安装TAP，无法访问http://tool.mkblog.cn/dns/
log： error cloud not find ip

我试了，用DIRECT，也无法访问，并且，换了其他的配置也无法访问

### Clash For Android:
环境：安卓10.0  未开启自带Dns Over Tls
同样的配置，可以访问

### 配置
```
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
ipv6: true


dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
#  fake-ip-range: 198.18.0.1/16
#  fake-ip-filter:
#    - '*.lan'
#    - localhost.ptlogin2.qq.com
#  default-nameserver:
#    - 114.114.114.114
  nameserver:
#    - https://dns.alidns.com/dns-query
#    - https://doh.pub/dns-query
#    - https://ea-dns.rubyfish.cn/dns-query
#    - https://uw-dns.rubyfish.cn/dns-query
#    - https://doh.360.cn/dns-query

    - https://doh.dns.sb/dns-query
    - https://dns.cloudflare.com/dns-query
    - https://doh.opendns.com/dns-query
    - https://dns-unfiltered.adguard.com/dns-query
    - https://dns.nextdns.io/dnscrypt-proxy
    - https://dns10.quad9.net/dns-query
    - https://doh.crypto.sx/dns-query
    - https://dns.containerpi.com/dns-query
    - https://dns.pumplex.com/dns-query
    - https://doh.rixcloud.dev/dns-query


#    - tls://1dot1dot1dot1.cloudflare-dns.com:853
#    - tls://dns-unfiltered.adguard.com:853

#    - tls://dns.sb:853
#    - tls://dns.pub:853
#    - tls://dns.alidns.com:853
#    - tls://ea-dns.rubyfish.cn:853
#    - tls://uw-dns.rubyfish.cn:853
#    - tls://dot.360.cn:853
#    - tls://dns.google:853
  fallback:
    - https://dns.cloudflare.com/dns-query
    - https://dns-unfiltered.adguard.com/dns-query
#    - https://dns.alidns.com/dns-query
#    - https://dns.google.com/dns-query
#    - tls://dns.google:853
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
  experimental:
    ignore-resolve-fail: false
    
  interface-name:
  
proxies:
、、、、、、
、、、
、、、
、、、
proxy-groups:

  - name: Proxy
    type: select
    proxies:
      - PingTest
      - DirectConnect
      - HK-MyQnapCloud
      - US-Heroku V2ray
      - TW-01 D3/VR/IPLC
      - JP-01 D3/VR/IPLC
      - SG-01 D3/VR/IPLC
      - US-01 D3/VR/IPLC
      - HK-01 D3/VR/IPLC
      - HK-02 D3/VR/IPLC
      - HK-03 D3/VR/IPLC
      - HK-Microsoft
      - JP-Tokyo 12
  - name: PingTest
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - HK-MyQnapCloud
      - US-Heroku V2ray
      - TW-01 D3/VR/IPLC
      - JP-01 D3/VR/IPLC
      - SG-01 D3/VR/IPLC
      - US-01 D3/VR/IPLC
      - HK-01 D3/VR/IPLC
      - HK-02 D3/VR/IPLC
      - HK-03 D3/VR/IPLC
      - HK-Microsoft
      - JP-Tokyo 12
  
  - name: Netease
    type: select
    proxies:
      - DirectConnect
      - NeteaseUnblock-1
      - NeteaseUnblock-2
      - NeteaseUnblock-3
      - NeteaseUnblock-4
      - NeteaseUnblock-CN-HHHT-PC
      - NeteaseUnblock-CN-HHHT-IOS


  - name: DirectConnect
    type: select
    proxies:
      - DIRECT
      - HK-MyQnapCloud
      - US-Heroku V2ray
      - TW-01 D3/VR/IPLC
      - JP-01 D3/VR/IPLC
      - SG-01 D3/VR/IPLC
      - US-01 D3/VR/IPLC
      - HK-01 D3/VR/IPLC
      - HK-02 D3/VR/IPLC
      - HK-03 D3/VR/IPLC
      - HK-Microsoft
      - JP-Tokyo 12

  - name: Final
    type: select
    proxies:
      - DirectConnect
      - Proxy
      - HK-MyQnapCloud
      - US-Heroku V2ray
      - TW-01 D3/VR/IPLC
      - JP-01 D3/VR/IPLC
      - SG-01 D3/VR/IPLC
      - US-01 D3/VR/IPLC
      - HK-01 D3/VR/IPLC
      - HK-02 D3/VR/IPLC
      - HK-03 D3/VR/IPLC
      - HK-Microsoft
      - JP-Tokyo 12
rules:




 - DOMAIN-SUFFIX,local,DirectConnect
 - DOMAIN-SUFFIX,localhost,DirectConnect
 - IP-CIDR,0.0.0.0/8,DirectConnect
 - IP-CIDR,10.0.0.0/8,DirectConnect
 - IP-CIDR,100.64.0.0/10,DirectConnect
 - IP-CIDR,127.0.0.0/8,DirectConnect
 - IP-CIDR,169.254.0.0/16,DirectConnect
 - IP-CIDR,172.16.0.0/12,DirectConnect
 - IP-CIDR,192.0.0.0/24,DirectConnect
 - IP-CIDR,192.0.2.0/24,DirectConnect
 - IP-CIDR,192.88.99.0/24,DirectConnect
 - IP-CIDR,192.168.0.0/16,DirectConnect
 - IP-CIDR,198.18.0.0/15,DirectConnect
 - IP-CIDR,198.51.100.0/24,DirectConnect
 - IP-CIDR,203.0.113.0/24,DirectConnect
 - IP-CIDR,224.0.0.0/4,DirectConnect
 - IP-CIDR,240.0.0.0/4,DirectConnect
 - IP-CIDR,255.255.255.255/32,DirectConnect
 - IP-CIDR6,::1/128,DirectConnect
 - IP-CIDR6,fc00::/7,DirectConnect
 - IP-CIDR6,fe80::/10,DirectConnect



 
# Google
 - DOMAIN-KEYWORD,google,Proxy
 
 
# Dns Over Https直连
 - DOMAIN,dns.cloudflare.com,DirectConnect
 - DOMAIN,doh.opendns.com,DirectConnect
 - DOMAIN,dns-unfiltered.adguard.com,DirectConnect
 - DOMAIN,ddns.nextdns.io,DirectConnect
 - DOMAIN,dns10.quad9.net,DirectConnect
 - DOMAIN,doh.crypto.sx,DirectConnect
 - DOMAIN,dns.containerpi.com,DirectConnect
 - DOMAIN,dns.alidns.com,DirectConnect
 - DOMAIN,doh.pub,DirectConnect
 - DOMAIN,doh.dns.sb,DirectConnect
 - DOMAIN,dns.sb,DirectConnect
 - DOMAIN,ea-dns.rubyfish.cn,DirectConnect
 - DOMAIN,uw-dns.rubyfish.cn,DirectConnect
 - DOMAIN,doh.360.cn,DirectConnect
 - DOMAIN,dns.google,DirectConnect
 - DOMAIN,dns.pumplex.com,DirectConnect
 - DOMAIN,doh.rixcloud.dev,DirectConnect

 
# Github走代理
 - DOMAIN-KEYWORD,github,Proxy
 - DOMAIN-SUFFIX,github.com,Proxy
 - DOMAIN-SUFFIX,github.io,Proxy
 - DOMAIN-SUFFIX,githubapp.com,Proxy
 - DOMAIN-SUFFIX,githubassets.com,Proxy
 - DOMAIN-SUFFIX,githubusercontent.com,Proxy
 - DOMAIN-SUFFIX,home-intl.console.aliyun.com,Proxy
 - DOMAIN,ip.skk.moe,Proxy
 - DOMAIN,ip.sb,Proxy
 - DOMAIN-SUFFIX,googleapis.cn,Proxy


# 网易云规则
 - DOMAIN,p1.music.126.net,DirectConnect
 - DOMAIN,p2.music.126.net,DirectConnect
 - DOMAIN,p3.music.126.net,DirectConnect
 - DOMAIN,p4.music.126.net,DirectConnect
 - DOMAIN,p5.music.126.net,DirectConnect
 - DOMAIN,p6.music.126.net,DirectConnect
 - DOMAIN,p7.music.126.net,DirectConnect
 - DOMAIN,p8.music.126.net,DirectConnect
 - DOMAIN,p9.music.126.net,DirectConnect
 - DOMAIN,p10.music.126.net,DirectConnect

 - DOMAIN-SUFFIX,163yun.com,Netease
 - DOMAIN-SUFFIX,music.163.com,Netease
 - DOMAIN-SUFFIX,music.126.net,Netease
 - DOMAIN-SUFFIX,api.iplay.163.com,Netease
 - DOMAIN-SUFFIX,apm.music.163.com,Netease
 - DOMAIN-SUFFIX,apm3.music.163.com,Netease
 - DOMAIN-SUFFIX,interface.music.163.com,Netease
 - DOMAIN-SUFFIX,interface3.music.163.com,Netease
 - DOMAIN-SUFFIX,mam.netease.com,Netease
 - DOMAIN-SUFFIX,hz.netease.com,Netease
 - IP-CIDR,39.105.63.80/32,Netease
 - IP-CIDR,45.254.48.1/32,Netease
 - IP-CIDR,47.100.127.239/32,Netease
 - IP-CIDR,59.111.21.14/31,Netease
 - IP-CIDR,59.111.179.214/32,Netease
 - IP-CIDR,59.111.181.38/32,Netease
 - IP-CIDR,59.111.181.60/32,Netease
 - IP-CIDR,59.111.160.195/32,Netease
 - IP-CIDR,59.111.160.197/32,Netease
 - IP-CIDR,59.111.181.35/32,Netease
 - IP-CIDR,59.111.238.29/32,Netease
 - IP-CIDR,101.71.154.241/32,Netease
 - IP-CIDR,103.126.92.132/32,Netease
 - IP-CIDR,103.126.92.133/32,Netease
 - IP-CIDR,112.13.119.17/32,Netease
 - IP-CIDR,112.13.122.1/32,Netease
 - IP-CIDR,115.236.118.33/32,Netease
 - IP-CIDR,115.236.121.1/32,Netease
 - IP-CIDR,118.24.63.156/32,Netease
 - IP-CIDR,193.112.159.225/32,Netease
 - IP-CIDR,223.252.199.66/32,Netease
 - IP-CIDR,223.252.199.67/32,Netease



#GeoIP
 - GEOIP,AF,Proxy
 - GEOIP,AL,Proxy
 - GEOIP,DZ,Proxy
 - GEOIP,AS,Proxy
 - GEOIP,AD,Proxy
 - GEOIP,AO,Proxy
 - GEOIP,AI,Proxy
 - GEOIP,AQ,Proxy
 - GEOIP,AG,Proxy
 - GEOIP,AR,Proxy
 - GEOIP,AM,Proxy
 - GEOIP,AW,Proxy
 - GEOIP,AU,Proxy
 - GEOIP,AT,Proxy
 - GEOIP,AZ,Proxy
 - GEOIP,BS,Proxy
 - GEOIP,BH,Proxy
 - GEOIP,BD,Proxy
 - GEOIP,BB,Proxy
 - GEOIP,BY,Proxy
 - GEOIP,BE,Proxy
 - GEOIP,BZ,Proxy
 - GEOIP,BJ,Proxy
 - GEOIP,BM,Proxy
 - GEOIP,BT,Proxy
 - GEOIP,BO,Proxy
 - GEOIP,BA,Proxy
 - GEOIP,BW,Proxy
 - GEOIP,BV,Proxy
 - GEOIP,BR,Proxy
 - GEOIP,IO,Proxy
 - GEOIP,VG,Proxy
 - GEOIP,BN,Proxy
 - GEOIP,BG,Proxy
 - GEOIP,BF,Proxy
 - GEOIP,MM,Proxy
 - GEOIP,BI,Proxy
 - GEOIP,CV,Proxy
 - GEOIP,KH,Proxy
 - GEOIP,CM,Proxy
 - GEOIP,CA,Proxy
 - GEOIP,KY,Proxy
 - GEOIP,CF,Proxy
 - GEOIP,TD,Proxy
 - GEOIP,CL,Proxy
 - GEOIP,CX,Proxy
 - GEOIP,CC,Proxy
 - GEOIP,CO,Proxy
 - GEOIP,KM,Proxy
 - GEOIP,CD,Proxy
 - GEOIP,CG,Proxy
 - GEOIP,CK,Proxy
 - GEOIP,CR,Proxy
 - GEOIP,CI,Proxy
 - GEOIP,HR,Proxy
 - GEOIP,CU,Proxy
 - GEOIP,CW,Proxy
 - GEOIP,CY,Proxy
 - GEOIP,CZ,Proxy
 - GEOIP,DK,Proxy
 - GEOIP,DJ,Proxy
 - GEOIP,DM,Proxy
 - GEOIP,DO,Proxy
 - GEOIP,EC,Proxy
 - GEOIP,EG,Proxy
 - GEOIP,SV,Proxy
 - GEOIP,GQ,Proxy
 - GEOIP,ER,Proxy
 - GEOIP,EE,Proxy
 - GEOIP,ET,Proxy
 - GEOIP,FK,Proxy
 - GEOIP,FO,Proxy
 - GEOIP,FJ,Proxy
 - GEOIP,FI,Proxy
 - GEOIP,FR,Proxy
 - GEOIP,FX,Proxy
 - GEOIP,GF,Proxy
 - GEOIP,PF,Proxy
 - GEOIP,TF,Proxy
 - GEOIP,GA,Proxy
 - GEOIP,GM,Proxy
 - GEOIP,PS,Proxy
 - GEOIP,GE,Proxy
 - GEOIP,DE,Proxy
 - GEOIP,GH,Proxy
 - GEOIP,GI,Proxy
 - GEOIP,GR,Proxy
 - GEOIP,GL,Proxy
 - GEOIP,GD,Proxy
 - GEOIP,GP,Proxy
 - GEOIP,GU,Proxy
 - GEOIP,GT,Proxy
 - GEOIP,GG,Proxy
 - GEOIP,GN,Proxy
 - GEOIP,GW,Proxy
 - GEOIP,GY,Proxy
 - GEOIP,HT,Proxy
 - GEOIP,HM,Proxy
 - GEOIP,VA,Proxy
 - GEOIP,HN,Proxy
 - GEOIP,HK,Proxy
 - GEOIP,HU,Proxy
 - GEOIP,IS,Proxy
 - GEOIP,IN,Proxy
 - GEOIP,ID,Proxy
 - GEOIP,IR,Proxy
 - GEOIP,IQ,Proxy
 - GEOIP,IE,Proxy
 - GEOIP,IM,Proxy
 - GEOIP,IL,Proxy
 - GEOIP,IT,Proxy
 - GEOIP,JM,Proxy
 - GEOIP,JP,Proxy
 - GEOIP,JE,Proxy
 - GEOIP,JO,Proxy
 - GEOIP,KZ,Proxy
 - GEOIP,KE,Proxy
 - GEOIP,KI,Proxy
 - GEOIP,KP,Proxy
 - GEOIP,KR,Proxy
 - GEOIP,XK,Proxy
 - GEOIP,KW,Proxy
 - GEOIP,KG,Proxy
 - GEOIP,LA,Proxy
 - GEOIP,LV,Proxy
 - GEOIP,LB,Proxy
 - GEOIP,LS,Proxy
 - GEOIP,LR,Proxy
 - GEOIP,LY,Proxy
 - GEOIP,LI,Proxy
 - GEOIP,LT,Proxy
 - GEOIP,LU,Proxy
 - GEOIP,MO,Proxy
 - GEOIP,MK,Proxy
 - GEOIP,MG,Proxy
 - GEOIP,MW,Proxy
 - GEOIP,MY,Proxy
 - GEOIP,MV,Proxy
 - GEOIP,ML,Proxy
 - GEOIP,MT,Proxy
 - GEOIP,MH,Proxy
 - GEOIP,MQ,Proxy
 - GEOIP,MR,Proxy
 - GEOIP,MU,Proxy
 - GEOIP,YT,Proxy
 - GEOIP,MX,Proxy
 - GEOIP,FM,Proxy
 - GEOIP,MD,Proxy
 - GEOIP,MC,Proxy
 - GEOIP,MN,Proxy
 - GEOIP,ME,Proxy
 - GEOIP,MS,Proxy
 - GEOIP,MA,Proxy
 - GEOIP,MZ,Proxy
 - GEOIP,NA,Proxy
 - GEOIP,NR,Proxy
 - GEOIP,NP,Proxy
 - GEOIP,NL,Proxy
 - GEOIP,AN,Proxy
 - GEOIP,NC,Proxy
 - GEOIP,NZ,Proxy
 - GEOIP,NI,Proxy
 - GEOIP,NE,Proxy
 - GEOIP,NG,Proxy
 - GEOIP,NU,Proxy
 - GEOIP,NF,Proxy
 - GEOIP,MP,Proxy
 - GEOIP,NO,Proxy
 - GEOIP,OM,Proxy
 - GEOIP,PK,Proxy
 - GEOIP,PW,Proxy
 - GEOIP,PA,Proxy
 - GEOIP,PG,Proxy
 - GEOIP,PY,Proxy
 - GEOIP,PE,Proxy
 - GEOIP,PH,Proxy
 - GEOIP,PN,Proxy
 - GEOIP,PL,Proxy
 - GEOIP,PT,Proxy
 - GEOIP,PR,Proxy
 - GEOIP,QA,Proxy
 - GEOIP,RE,Proxy
 - GEOIP,RO,Proxy
 - GEOIP,TW,Proxy
 - GEOIP,RU,Proxy
 - GEOIP,RW,Proxy
 - GEOIP,BL,Proxy
 - GEOIP,SH,Proxy
 - GEOIP,KN,Proxy
 - GEOIP,LC,Proxy
 - GEOIP,MF,Proxy
 - GEOIP,VC,Proxy
 - GEOIP,WS,Proxy
 - GEOIP,SM,Proxy
 - GEOIP,ST,Proxy
 - GEOIP,SA,Proxy
 - GEOIP,SN,Proxy
 - GEOIP,RS,Proxy
 - GEOIP,SC,Proxy
 - GEOIP,SL,Proxy
 - GEOIP,SG,Proxy
 - GEOIP,SX,Proxy
 - GEOIP,SK,Proxy
 - GEOIP,SI,Proxy
 - GEOIP,SB,Proxy
 - GEOIP,SO,Proxy
 - GEOIP,ZA,Proxy
 - GEOIP,GS,Proxy
 - GEOIP,SS,Proxy
 - GEOIP,ES,Proxy
 - GEOIP,LK,Proxy
 - GEOIP,SD,Proxy
 - GEOIP,SR,Proxy
 - GEOIP,PM,Proxy
 - GEOIP,SZ,Proxy
 - GEOIP,SE,Proxy
 - GEOIP,CH,Proxy
 - GEOIP,SY,Proxy
 - GEOIP,TJ,Proxy
 - GEOIP,TZ,Proxy
 - GEOIP,TH,Proxy
 - GEOIP,TL,Proxy
 - GEOIP,TG,Proxy
 - GEOIP,TK,Proxy
 - GEOIP,TO,Proxy
 - GEOIP,TT,Proxy
 - GEOIP,TN,Proxy
 - GEOIP,TR,Proxy
 - GEOIP,TM,Proxy
 - GEOIP,TC,Proxy
 - GEOIP,TV,Proxy
 - GEOIP,UG,Proxy
 - GEOIP,UA,Proxy
 - GEOIP,AE,Proxy
 - GEOIP,GB,Proxy
 - GEOIP,US,Proxy
 - GEOIP,UM,Proxy
 - GEOIP,UY,Proxy
 - GEOIP,UZ,Proxy
 - GEOIP,VU,Proxy
 - GEOIP,VE,Proxy
 - GEOIP,VN,Proxy
 - GEOIP,VI,Proxy
 - GEOIP,WF,Proxy
 - GEOIP,PS,Proxy
 - GEOIP,EH,Proxy
 - GEOIP,UN,Proxy
 - GEOIP,EU,Proxy
 - GEOIP,YE,Proxy
 - GEOIP,ZA,Proxy
 - GEOIP,ZM,Proxy
 - GEOIP,ZW,Proxy
 - GEOIP,RO,Proxy
 - GEOIP,WI,Proxy
 - GEOIP,EN,Proxy
 - GEOIP,AZ,Proxy
 - GEOIP,YG,Proxy
 - GEOIP,UR,Proxy
 - GEOIP,DH,Proxy
 - GEOIP,VL,Proxy
 - GEOIP,BO,Proxy
 - GEOIP,TC,Proxy
 - GEOIP,UA,Proxy
 - GEOIP,SG,Proxy

#剩余直连
 - MATCH,Final

```
