### ISSUE TITLE
TAP模式下，在WSL2中仅有第一次请求能被代理

### ISSUE THREAD

**Issue by Macyrate** [Fndroid/clash_for_windows_pkg#1201]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

Windows 10 2004 专业版 19041.508 AMD64

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

TAP模式下，在WSL2中仅有第一次请求能被代理。

第二次及以后的请求均无响应，且会导致整个系统无法上网，重启Clash才能恢复正常。

**复现**

[//]: # (请描述复现问题的步骤)

1. 将Clash设置为TAP模式
```
dns:
   enable: true
   enhanced-mode: fake-ip # 或 fake-ip
   listen: 0.0.0.0:53
   nameserver:
      - 223.5.5.5
      - 114.114.114.114
      - 1.1.1.1
      - 8.8.8.8
interface-name: WLAN # 物理网卡名称
```
3. 访问google.com，连接正常
4. 访问baidu.com，连接正常
5. 启动Windows Terminal
6. 键入`wsl`进入WSL2环境(Ubuntu 20.04.1)
7. 键入`ping google.com`，回车
8. **第一次ping正确返回，但之后完全停滞**
9. 访问google.com，无法连接
10. 访问baidu.com，无法连接
11. 重启Clash
12. 访问google.com，连接正常
13. 访问baidu.com，连接正常

**预期行为**

[//]: # (清晰地描述期望看到的行为)

能够识别并分情况代理来自WSL2的全部流量

**日志**

[//]: # (上传触发问题对应的日志文件)

[2020-10-05-110654.log](https://gist.githubusercontent.com/Macyrate/7a053516459c72d99ead0947db628272/raw/44949bf78ad4b7017f90b7fd82f2c6ebb3ed141d/gistfile1.txt)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

![屏幕截图 2020-10-05 111311.png](https://i.loli.net/2020/10/05/VajCntm3oOycFzZ.png)

**其他说明**

[//]: # (其他补充内容)

经过尝试，如果在进入WSL2之后，执行：

```sh
export hostip=$(cat /etc/resolv.conf | grep -oP '(?<=nameserver\ ).*')
export https_proxy="http://${hostip}:7890"
export http_proxy="http://${hostip}:7890"
export all_proxy="socks5://${hostip}:7891"
```

则可以避免出现该问题。

但这是在Clash的System Proxy关闭情况下用虚拟网卡进行的，为何还需要设置代理？

来自WSL2的第一次请求为何会使Clash完全失去功能？

(也许是tap的锅？)
