### ISSUE TITLE
tap模式无法正常连接网络

### ISSUE THREAD

**Issue by ddspj23** [Fndroid/clash_for_windows_pkg#1243]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows10专业版2004 版本号19041.508(开启Hyper-V)

**描述**

tap模式下，即使选择direct模式也无连接网络。

**复现**

[//]: # (请描述复现问题的步骤)

1. 配置文件不包含dns设置，此时代理和直连均正常连接网络；
2. 在Settings->Profile Mixin->YAML->edit中添加
  ```yaml
  mixin: # object
    dns:
      enable: true
      enhanced-mode: redir-host # redir-host 或 fake-ip
      listen: 0.0.0.0:53
      nameserver:
        - 223.5.5.5
        - 8.8.8.8
        - 1.1.1.1
        - 114.114.114.114
    interface-name: WLAN # 物理网卡名称；
  ```
3. 在General->TAP Device安装虚拟网卡；
4. 打开General->Mixin；
5. 系统无法连接到互联网；
6. 执行ping www.baidu.com

正在 Ping www.a.shifen.com [180.101.49.12] 具有 32 字节的数据:
来自 180.101.49.12 的回复: 字节=32 时间<1ms TTL=64
来自 180.101.49.12 的回复: 字节=32 时间<1ms TTL=64
来自 180.101.49.12 的回复: 字节=32 时间<1ms TTL=64
来自 180.101.49.12 的回复: 字节=32 时间<1ms TTL=64

180.101.49.12 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 0ms，最长 = 0ms，平均 = 0ms

可以解析域名，但延迟显示为0ms。

**预期行为**

打开mixin选项后，正常连接互联网。

**日志**

[2020-10-17-191535.log](https://github.com/Fndroid/clash_for_windows_pkg/files/5395527/2020-10-17-191535.log)

**截图**

![image](https://user-images.githubusercontent.com/16429326/96335756-654f1400-10ad-11eb-9bc9-f8561fbe17e3.png)
![image](https://user-images.githubusercontent.com/16429326/96335759-6bdd8b80-10ad-11eb-9175-c46939a923d1.png)
![image](https://user-images.githubusercontent.com/16429326/96335761-6ed87c00-10ad-11eb-951f-c019f3ec8472.png)

**其他说明**

我所连接的局域网为192.168.31.0，与tap网卡没有ip地址冲突。
