### ISSUE TITLE
解析使用域名的SS/SSR节点会很慢

### ISSUE THREAD

**Issue by ShonStewart** [Fndroid/clash_for_windows_pkg#1306]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
macOS Catalina Version 10.15.4

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

配置节点信息脱敏后如下
```
- name: 某某节点
   type: ssr
   server: aaa.bbb.ccc
   port: 12345
   cipher: rc4-md5
   password: PASSWORD
   protocol: origin
   protocolparam: ''
   obfs: http_simple
   obfs-param: xxx.xxx.xxx
```

我开启了Mixin，禁用了DNS
```
dns:
   enable: false
```
尝试开启过fake-ip模式，无果

**预期行为**

[//]: # (清晰地描述期望看到的行为)
与使用其他SS/SSR客户端一样的速度

**日志**

[//]: # (上传触发问题对应的日志文件)
```
Dial [PROXY] failed
aaa.bbb.ccc:12345 connect error: dial tcp4 xxx.xxx.xxx.xxx:12345: i/o timeout
```
这样的日志很多，但并不是一出现这个日志就无妨访问；有时出现很多类似日志，过了一会儿，网站也能访问。

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

我使用SS/SSR的客户端测试过相同的节点，没有这样的问题。

相同配置，使用Vmess的其他节点没有这样的问题。

**Comment by Fndroid** [comment]
mixin截图看看

**Comment by SiweiShen2019** [comment]
```yml
mixin:
  dns:
    enable: false
  mixed-port: 7890
  allow-lan: false
  log-level: info
  external-controller: '127.0.0.1:9090'
  secret: ''
  ipv6: false
  rule-providers:...
  rules:
    - PROCESS-NAME,v2ray,DIRECT
    - PROCESS-NAME,Surge%203,DIRECT
    - PROCESS-NAME,ss-local,DIRECT
    - PROCESS-NAME,privoxy,DIRECT
    - PROCESS-NAME,trojan,DIRECT
    - PROCESS-NAME,trojan-go,DIRECT
    - PROCESS-NAME,naive,DIRECT
    - PROCESS-NAME,Thunder,DIRECT
    - PROCESS-NAME,DownloadService,DIRECT
    - PROCESS-NAME,qBittorrent,DIRECT
    - PROCESS-NAME,Transmission,DIRECT
    - PROCESS-NAME,fdm,DIRECT
    - PROCESS-NAME,aria2c,DIRECT
    - PROCESS-NAME,Folx,DIRECT
    - PROCESS-NAME,NetTransport,DIRECT
    - PROCESS-NAME,uTorrent,DIRECT
    - PROCESS-NAME,WebTorrent,DIRECT
    - RULE-SET,reject,REJECT
    - RULE-SET,icloud,DIRECT
    - RULE-SET,apple,DIRECT
    - RULE-SET,google,DIRECT
    - RULE-SET,proxy,PROXY
    - RULE-SET,direct,DIRECT
    - GEOIP,CN,DIRECT
    - MATCH,PROXY
```

**Comment by ShonStewart** [comment]
后来我试着配置mixin中的DNS，能够解决上面提到的问题以及与easyconnect兼容的问题，这里贴一下配置
```yml
dns:
    enable: true
    ipv6: false
    listen: 0.0.0.0:53
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter:
      - '*.lan'
      - localhost.ptlogin2.qq.com
    nameserver:
      - 223.5.5.5
      - 180.76.76.76
      - 119.29.29.29
      - 117.50.11.11
      - 117.50.10.10
      - 114.114.114.114
      - https://dns.alidns.com/dns-query
      - https://doh.360.cn/dns-query
    fallback:
      - 8.8.8.8
      - 1.1.1.1
      - tls://dns.rubyfish.cn:853
      - tls://1.0.0.1:853
      - tls://dns.google:853
      - https://dns.rubyfish.cn/dns-query
      - https://cloudflare-dns.com/dns-query
      - https://dns.google/dns-query
    fallback-filter:
      geoip: true
```
目前唯一没能解决的就是无法解析easyconnect中自定义的域名，比如`http://internal-server-08`这种。如果作者觉得合适，就把这个issue关了把。
