### ISSUE TITLE
能正常下载配置文件，测速全部超时，也无法访问网页

### ISSUE THREAD

**Issue by github-h** [Fndroid/clash_for_windows_pkg#1307]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

win10 20H2 x64 clash for windows v0.13.2

**描述**

成功下载配置文件后，列表可以看到节点，但是测速提示全部超时。访问网站提示
![图片](https://user-images.githubusercontent.com/49114731/98456534-d6b84900-21b9-11eb-98e5-7dd94aa9fbc9.png)
![图片](https://user-images.githubusercontent.com/49114731/98456536-dddf5700-21b9-11eb-8019-93e0a64cfec5.png)

**复现**

1. 查看此配置文件，发现其样式为
![图片](https://user-images.githubusercontent.com/49114731/98456567-344c9580-21ba-11eb-9ea4-3dc2cfe1363d.png)

2. 能正常测速+访问网站的另一家的配置文件为
![图片](https://user-images.githubusercontent.com/49114731/98456583-7d044e80-21ba-11eb-9990-5e1ba791ae6e.png)

3. 将不能使用的配置文件按照2中样式转换订阅后也能正常使用（排除节点问题）
4. 将本clash安装在一台全新的虚拟机或其他电脑上，2个配置文件都可以正常使用

**预期行为**

希望在我本机上能正常使用2种格式的配置文件，因为其他电脑经过测试是可以做到的，本机不知道哪里出了问题。用Everything搜索了全盘的clash进行删除，同时注册表搜索所有有关的clash项，然后重新下载解压压缩包还是会有此类问题。

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by github-h** [comment]
让我奇怪的是图1的配置文件是按照
https://lancellc.gitbook.io/clash/clash-config-file/an-example-configuration-file
来写的，这不是应该原生支持么，为什么反而会读取失败呢？

**Comment by Fndroid** [comment]
不是格式问题，访问不了多半是dns设置问题，把dns下面的enable改成false试下吧

**Comment by github-h** [comment]
> 不是格式问题，访问不了多半是dns设置问题，把dns下面的enable改成false试下吧

哇！！真的是这个问题！！！感谢感谢！！请问能麻烦提供一个预处理的的代码嘛？就是替换这个键值的

**Comment by Fndroid** [comment]
```yaml
parsers:
  - url: xxx
    yaml: 
      mix-object:
        dns:
          enable: false       
```

**Comment by github-h** [comment]
谢谢F大！！！

**Comment by github-h** [comment]
> 
> 
> ```yaml
> parsers:
>   - url: xxx
>     yaml: 
>       mix-object:
>         dns:
>           enable: false       
> ```

有个小问题，这个代码不能生效。是因为url的问题嘛？现在大部分订阅链接都是  xxxx?clash=1  这样的，这样好像不符合https://example.com/profile.yaml 这个格式

**Comment by yi-Xu-0100** [comment]
@github-h  url 换成你的订阅链接。

或者改成正则匹配，下面这个会匹配上所有的 https 的订阅链接，谨慎使用

```yaml
parsers:
  - reg: https://.+$
    yaml: 
      mix-object:
        dns:
          enable: false 
```

**Comment by github-h** [comment]
> 
> 
> @github-h url 换成你的订阅链接。
> 
> 或者改成正则匹配，下面这个会匹配上所有的 https 的订阅链接，谨慎使用
> 
> ```yaml
> parsers:
>   - reg: https://.+$
>     yaml: 
>       mix-object:
>         dns:
>           enable: false 
> ```

我这个改成了订阅链接来着，然后并没有预处理  我试试你这个先

**Comment by yi-Xu-0100** [comment]
@github-h 

![image](https://user-images.githubusercontent.com/25523606/98465663-77802600-2205-11eb-9979-1270d0cae5dd.png)
![image](https://user-images.githubusercontent.com/25523606/98465665-79e28000-2205-11eb-9f21-617b53b85d38.png)

看看有没有匹配到

**Comment by github-h** [comment]
> 
> 
> @github-h url 换成你的订阅链接。
> 
> 或者改成正则匹配，下面这个会匹配上所有的 https 的订阅链接，谨慎使用
> 
> ```yaml
> parsers:
>   - reg: https://.+$
>     yaml: 
>       mix-object:
>         dns:
>           enable: false 
> ```

没有预处理成功

**Comment by github-h** [comment]
> 
> 
> @github-h
> 
> ![image](https://user-images.githubusercontent.com/25523606/98465663-77802600-2205-11eb-9979-1270d0cae5dd.png)
> ![image](https://user-images.githubusercontent.com/25523606/98465665-79e28000-2205-11eb-9f21-617b53b85d38.png)
> 
> 看看有没有匹配到

![图片](https://user-images.githubusercontent.com/49114731/98465752-11e06980-2206-11eb-907f-dede2e23c6a8.png)
![图片](https://user-images.githubusercontent.com/49114731/98465743-fc6b3f80-2205-11eb-8229-97be61ca13d3.png)
很奇怪，就这个不行，其他的能匹配到

**Comment by yi-Xu-0100** [comment]
@github-h 订阅链接是否是 http 的？

**Comment by github-h** [comment]
> 
> 
> @github-h 订阅链接是否是 http 的？

软件可能卡住了，我把配置文件全删除了，重新下载匹配到了

**Comment by github-h** [comment]
> 
> 
> @github-h 订阅链接是否是 http 的？

还有个小问题，当我写这个的时候，预处理是将整个dns项都替换为这个，而不是更改enable处的值是么
```
dns:
          enable: false
```

**Comment by yi-Xu-0100** [comment]
@github-h 是的，替换最外面的，会把下级的内容整个替换掉，不过也没有保留的必要。

**Comment by github-h** [comment]
> 
> 
> @github-h 是的，替换最外面的，会把下级的内容整个替换掉，不过也没有保留的必要。

但其实还是希望仅仅替换修改处的值，因为如果后续要更改某些比如说 nameserver 改为自己的dns服务器时候，想保留其他的项。对于多个不同格式的配置文件来说就很麻烦，仅仅是建议。

**Comment by yi-Xu-0100** [comment]
@github-h 那就使用需要的对应配置去替换，例如

```yaml
parsers:
  - reg: https://.+$
    yaml: 
      mix-object:
        dns:
          enable: true
          ipv6：false
          listen：xxx
          enhanced-mode: xxx
          fake-ip-range：xx
          name server:
            - xx
            - xx
```

更改对应正则表达式和对应内容进行处理，更多见 ：<https://docs.cfw.lbyczf.com/contents/parser.html>
