### ISSUE TITLE
节点测试全部 Timeout

### ISSUE THREAD

**Issue by liangchenhe55** [Fndroid/clash_for_windows_pkg#1315]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 2004

**描述**

Proxies 界面点击测试全部 `Timeout`，节点为通过 `proxy-providers` 提供，类型为 `ss`。

在 Providers 界面点击 Health Check 也是全部 `Timeout`。

这些节点绝大部分是可以正常使用的。看了很多相关的 Issues 但是似乎没有明确的解决方案。未开启 TAP 模式。

**TL;DR**

1. 仅 proxy-providers 节点无法测试，写在根配置的节点正常。
2. 仅 CFW 内部无法测试，节点正常，选中节点后也可以正常访问网页。
3. providers url 正常，CFW 已经成功获取到了节点数据。

以下是 proxy-providers 内的配置。通过 `subconverter?list=true` 转换得到：

<details>
<summary>点击展开 proxy-provider</summary>

```yaml
proxies:
  - {name: 🇭🇰 EC 沪港, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, udp: true}
  - {name: 🇭🇰 EC 深港, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, udp: true}
  - {name: 🇭🇰 EC 京港, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, udp: true}
  - {name: 🇭🇰 EC 杭港, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, udp: true}
  - {name: 🇭🇰 EC 青港, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, udp: true}
  - {name: 🇺🇸 EC 沪美, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, plugin: obfs, plugin-opts: {mode: http, host: 5281-ga6NRUHqwiTn.download.microsoft.com}, udp: true}
  - {name: 🇯🇵 EC 深日, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, plugin: obfs, plugin-opts: {mode: http, host: 5281-ga6NRUHqwiTn.download.microsoft.com}, udp: true}
  - {name: 🇰🇷 EC 深韩, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, plugin: obfs, plugin-opts: {mode: http, host: 5281-ga6NRUHqwiTn.download.microsoft.com}, udp: true}
  - {name: 🇨🇳 EC 深台, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, plugin: obfs, plugin-opts: {mode: http, host: 5281-ga6NRUHqwiTn.download.microsoft.com}, udp: true}
  - {name: 🇸🇬 EC 深新, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, plugin: obfs, plugin-opts: {mode: http, host: 5281-ga6NRUHqwiTn.download.microsoft.com}, udp: true}
```
</details>

以下是完整根配置：

<details>
<summary>点击展开 根配置</summary>

```yaml
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
clash-for-android:
  append-system-dns: false
  ui-subtitle-pattern: (GM)|(EC)|(PBGP)|(NBGP)|(SP)|(PVCC)|(IPLC)|(IEPL)
hosts: # only works when `dns.enhanced-mode` is `redir-host`.
  mtalk.google.com: 108.177.125.188
dns:
  enable: true
  listen: 127.0.0.1:45533
  default-nameserver:
    - 156.154.70.1
    - 1.0.0.1
  ipv6: false
  nameserver:
    - https://223.6.6.6/dns-query
    - https://rubyfish.cn/dns-query
    - https://dns.pub/dns-query
  # When `fallback` is present, the DNS server will send concurrent requests
  # to the servers in this section along with servers in `nameservers`.
  # The answers from fallback servers are used when the GEOIP country
  # is not `CN`.
  fallback:
    - https://cloudflare-dns.com/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      # - 240.0.0.0/4
  enhanced-mode: fake-ip
  fake-ip-range: 198.10.0.1/16
  fake-ip-filter:
    - "*.lan"
    - stun.*.*.*
    - stun.*.*
    - time.windows.com
    - time.nist.gov
    - time.apple.com
    - time.asia.apple.com
    - "*.ntp.org.cn"
    - "*.openwrt.pool.ntp.org"
    - time1.cloud.tencent.com
    - time.ustc.edu.cn
    - pool.ntp.org
    - ntp.ubuntu.com
    - ntp.aliyun.com
    - ntp1.aliyun.com
    - ntp2.aliyun.com
    - ntp3.aliyun.com
    - ntp4.aliyun.com
    - ntp5.aliyun.com
    - ntp6.aliyun.com
    - ntp7.aliyun.com
    - time1.aliyun.com
    - time2.aliyun.com
    - time3.aliyun.com
    - time4.aliyun.com
    - time5.aliyun.com
    - time6.aliyun.com
    - time7.aliyun.com
    - "*.time.edu.cn"
    - time1.apple.com
    - time2.apple.com
    - time3.apple.com
    - time4.apple.com
    - time5.apple.com
    - time6.apple.com
    - time7.apple.com
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - "+.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - localhost.ptlogin2.qq.com
    - "*.*.*.srv.nintendo.net"
    - "*.*.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.ipv6.microsoft.com"
    - "*.*.xboxlive.com"

proxy-providers:
  xxx:
    type: http
    path: ***
    url: "******"
    interval: 86400

  yyy:
    type: http
    path: ***
    url: "******"
    interval: 86400
  
  zzz:
    type: http
    path: ***
    url: "******"
    interval: 86400


proxy-groups:
  - name: Proxy
    type: select
    use: 
      - xxx
      - yyy
      - zzz
  - name: Netflix
    type: select
    use:
      - xxx
      - yyy
      - zzz
    proxies:
      - Proxy
      - DIRECT
  - name: 规则外路由选择
    type: select
    proxies:
      - Proxy
      - DIRECT

rule-providers:

  Unbreak:
    type: http
    behavior: classical
    path: ./RuleSet/Unbreak.yaml
    url: "******"
    interval: 86400

  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: "******"
    interval: 86400

  Global:
    type: http
    behavior: classical
    path: ./RuleSet/Global.yaml
    url: "******"
    interval: 86400

  Hijacking:
    type: http
    behavior: classical
    path: ./RuleSet/Guard/Hijacking.yml
    url: "******"
    interval: 86400

  Netflix:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/Video/Netflix.yml
    url: "******"
    interval: 86400

rules:
# 自定义规则
## 您可以在此处插入您补充的自定义规则

- DOMAIN,googleapis.cn,Proxy
- DOMAIN,services.googleapis.cn,Proxy
- DOMAIN,r16---sn-ni57dn7z.xn--ngstr-lra8j.com,DIRECT

# Unbreak
- RULE-SET,Unbreak,DIRECT

# 直连 FCM 推送
## FCM 目前可以直接连接。除此之外由于 FCM 需要保持长连接，多数机场考虑到成本问题不会保持，造成定时重连增加耗电。
- DOMAIN,alt1-mtalk.google.com,DIRECT
- DOMAIN,alt2-mtalk.google.com,DIRECT
- DOMAIN,alt3-mtalk.google.com,DIRECT
- DOMAIN,alt4-mtalk.google.com,DIRECT
- DOMAIN,alt5-mtalk.google.com,DIRECT
- DOMAIN,alt6-mtalk.google.com,DIRECT
- DOMAIN,alt7-mtalk.google.com,DIRECT
- DOMAIN,alt8-mtalk.google.com,DIRECT
- DOMAIN,mtalk.google.com,DIRECT
- IP-CIDR,64.233.177.188/32,DIRECT,no-resolve
- IP-CIDR,64.233.186.188/32,DIRECT,no-resolve
- IP-CIDR,64.233.187.188/32,DIRECT,no-resolve
- IP-CIDR,64.233.188.188/32,DIRECT,no-resolve
- IP-CIDR,64.233.189.188/32,DIRECT,no-resolve
- IP-CIDR,74.125.23.188/32,DIRECT,no-resolve
- IP-CIDR,74.125.24.188/32,DIRECT,no-resolve
- IP-CIDR,74.125.28.188/32,DIRECT,no-resolve
- IP-CIDR,74.125.127.188/32,DIRECT,no-resolve
- IP-CIDR,74.125.137.188/32,DIRECT,no-resolve
- IP-CIDR,74.125.203.188/32,DIRECT,no-resolve
- IP-CIDR,74.125.204.188/32,DIRECT,no-resolve
- IP-CIDR,74.125.206.188/32,DIRECT,no-resolve
- IP-CIDR,108.177.125.188/32,DIRECT,no-resolve
- IP-CIDR,142.250.4.188/32,DIRECT,no-resolve
- IP-CIDR,142.250.10.188/32,DIRECT,no-resolve
- IP-CIDR,142.250.31.188/32,DIRECT,no-resolve
- IP-CIDR,142.250.96.188/32,DIRECT,no-resolve
- IP-CIDR,172.217.194.188/32,DIRECT,no-resolve
- IP-CIDR,172.217.218.188/32,DIRECT,no-resolve
- IP-CIDR,172.217.219.188/32,DIRECT,no-resolve
- IP-CIDR,172.253.63.188/32,DIRECT,no-resolve
- IP-CIDR,172.253.122.188/32,DIRECT,no-resolve
- IP-CIDR,173.194.175.188/32,DIRECT,no-resolve
- IP-CIDR,173.194.218.188/32,DIRECT,no-resolve
- IP-CIDR,209.85.233.188/32,DIRECT,no-resolve

# 常见广告与劫持域名屏蔽
#- RULE-SET,Hijacking,REJECT

# Netflix
- RULE-SET,Netflix,Netflix

# (DNS Cache Pollution) / (IP Blackhole) / (Region-Restricted Access Denied) / (Network Jitter)
- RULE-SET,Global,Proxy

# China Area Network
- RULE-SET,China,DIRECT

# LAN
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
- IP-CIDR,224.0.0.0/4,DIRECT

# Tencent
- IP-CIDR,119.28.28.28/32,DIRECT
- IP-CIDR,182.254.116.0/24,DIRECT

# 最终规则
- GEOIP,CN,DIRECT
- MATCH,规则外路由选择
```
</details>

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入 Proxies 界面。
2. 点击 测试按钮。
3. 触发问题

**预期行为**

显示真实的测试结果。

**日志**

<details>
<summary>点击展开 日志</summary>

```
time="2020-11-10T19:06:16+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-11-10T19:06:16+08:00" level=info msg="RESTful API listening at: 127.0.0.1:29091"
time="2020-11-10T19:06:16+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2020-11-10T19:06:16+08:00" level=info msg="Mixed(http+socks5) proxy listening at: :7890"
time="2020-11-10T19:06:16+08:00" level=info msg="Start initial provider yoyu"
time="2020-11-10T19:06:16+08:00" level=info msg="Start initial provider cnix"
time="2020-11-10T19:06:16+08:00" level=info msg="Start initial compatible provider 规则外路由选择"
time="2020-11-10T19:06:16+08:00" level=info msg="Start initial rule provider Unbreak"
time="2020-11-10T19:06:16+08:00" level=info msg="Start initial rule provider China"
time="2020-11-10T19:06:16+08:00" level=info msg="Start initial rule provider Global"
time="2020-11-10T19:06:16+08:00" level=info msg="Start initial rule provider Hijacking"
time="2020-11-10T19:06:16+08:00" level=info msg="Start initial rule provider Netflix"
time="2020-11-10T19:06:16+08:00" level=info msg="DNS server listening at: 127.0.0.1:45533"
time="2020-11-10T19:06:16+08:00" level=info msg="[TCP] 127.0.0.1:56792 --> arms-retcode.aliyuncs.com match Match() using DIRECT"
time="2020-11-10T19:06:16+08:00" level=info msg="[TCP] 127.0.0.1:56787 --> 91.108.56.170 match RuleSet(Global) using Proxy[备用1]"
time="2020-11-10T19:06:16+08:00" level=info msg="[TCP] 127.0.0.1:56788 --> 91.108.56.170 match RuleSet(Global) using Proxy[ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC A01]"
time="2020-11-10T19:06:16+08:00" level=info msg="[TCP] 127.0.0.1:56789 --> arms-retcode.aliyuncs.com match GeoIP(CN) using DIRECT"
time="2020-11-10T19:06:16+08:00" level=info msg="Start initial provider yoyu"
time="2020-11-10T19:06:16+08:00" level=info msg="Start initial provider cnix"
time="2020-11-10T19:06:17+08:00" level=info msg="Start initial compatible provider 规则外路由选择"
time="2020-11-10T19:06:17+08:00" level=info msg="Start initial rule provider Global"
time="2020-11-10T19:06:17+08:00" level=info msg="[TCP] 127.0.0.1:56805 --> alive.github.com match Match() using DIRECT"
time="2020-11-10T19:06:17+08:00" level=info msg="Start initial rule provider Hijacking"
time="2020-11-10T19:06:17+08:00" level=info msg="Start initial rule provider Netflix"
time="2020-11-10T19:06:17+08:00" level=info msg="Start initial rule provider Unbreak"
time="2020-11-10T19:06:17+08:00" level=info msg="Start initial rule provider China"
time="2020-11-10T19:06:17+08:00" level=info msg="DNS server listening at: 127.0.0.1:45533"
time="2020-11-10T19:06:17+08:00" level=info msg="[TCP] 127.0.0.1:56824 --> api.github.com match RuleSet(Global) using Proxy[ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC A01]"
time="2020-11-10T19:06:17+08:00" level=info msg="[TCP] 127.0.0.1:56823 --> raw.githubusercontent.com match RuleSet(Global) using Proxy[ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC A01]"
time="2020-11-10T19:06:17+08:00" level=info msg="[TCP] 127.0.0.1:56799 --> alive.github.com match RuleSet(Global) using Proxy[ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC A01]"
time="2020-11-10T19:06:17+08:00" level=info msg="[TCP] 127.0.0.1:56811 --> boss.cnwangjie.com match Match() using 规则外路由选择[ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC A01]"
time="2020-11-10T19:06:21+08:00" level=info msg="[TCP] 127.0.0.1:56845 --> mqtt-web.zhihu.com match RuleSet(China) using DIRECT"
time="2020-11-10T19:06:22+08:00" level=info msg="[TCP] 127.0.0.1:56850 --> logger.csslcloud.net match GeoIP(CN) using DIRECT"
time="2020-11-10T19:06:23+08:00" level=info msg="[TCP] 127.0.0.1:56854 --> m-flare.bokecc.com match GeoIP(CN) using DIRECT"
time="2020-11-10T19:06:24+08:00" level=info msg="[TCP] 127.0.0.1:56858 --> config.pinyin.sogou.com match RuleSet(China) using DIRECT"
```
</details>

**截图**

![](https://user-images.githubusercontent.com/10266066/98666451-07e67400-2388-11eb-8991-17892ef4b4db.png)

**Comment by zynowhere** [comment]
same question

**Comment by github-h** [comment]
Duplicate of #1307 
看看这

**Comment by liangchenhe55** [comment]
@github-h 感谢回复，但我的情况和你不一样

1. 仅 proxy-provider 的节点测试失败，写在配置文件的节点测试正常。
2. 选中节点后可以正常访问网页。
3. dns = false 未能解决问题。

**Comment by yi-Xu-0100** [comment]
@liangchenhe55 是否是 provider 的链接无法访问（需要代理）

**Comment by liangchenhe55** [comment]
@yi-Xu-0100 感谢回复，不是。

1. provider 已经正常加载，节点可以显示、可以使用。（也确认大陆可以畅通访问）
2. 仅仅是 CFW 内置的延时测试 timeout.

**Comment by yi-Xu-0100** [comment]
@liangchenhe55 你的测试链接填的什么

**Comment by liangchenhe55** [comment]
> @liangchenhe55 你的测试链接填的什么

未填。应该是程序默认。

**Comment by yi-Xu-0100** [comment]
配置中的 provider 中部分，请去除敏感信息后贴出来看看。

**Comment by liangchenhe55** [comment]
@yi-Xu-0100 

```yaml
proxies:
  - {name: 🇭🇰 EC 沪港, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, udp: true}
  - {name: 🇭🇰 EC 深港, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, udp: true}
  - {name: 🇭🇰 EC 京港, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, udp: true}
  - {name: 🇭🇰 EC 杭港, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, udp: true}
  - {name: 🇭🇰 EC 青港, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, udp: true}
  - {name: 🇺🇸 EC 沪美, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, plugin: obfs, plugin-opts: {mode: http, host: 5281-ga6NRUHqwiTn.download.microsoft.com}, udp: true}
  - {name: 🇯🇵 EC 深日, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, plugin: obfs, plugin-opts: {mode: http, host: 5281-ga6NRUHqwiTn.download.microsoft.com}, udp: true}
  - {name: 🇰🇷 EC 深韩, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, plugin: obfs, plugin-opts: {mode: http, host: 5281-ga6NRUHqwiTn.download.microsoft.com}, udp: true}
  - {name: 🇨🇳 EC 深台, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, plugin: obfs, plugin-opts: {mode: http, host: 5281-ga6NRUHqwiTn.download.microsoft.com}, udp: true}
  - {name: 🇸🇬 EC 深新, server: <****>, port: 0000, type: ss, cipher: chacha20-ietf, password: <****>, plugin: obfs, plugin-opts: {mode: http, host: 5281-ga6NRUHqwiTn.download.microsoft.com}, udp: true}
```

以上就是 proxy-providers 内的全部数据。通过 `subconverter?list=true` 转换得到。

**Comment by yi-Xu-0100** [comment]
@liangchenhe55 https://lancellc.gitbook.io/clash/clash-config-file/proxy-provider/health-check-opinion

**Comment by liangchenhe55** [comment]
@yi-Xu-0100 感谢，已解决问题。还以为这个参数可以省略 （CFA 上允许省略）

相同问题的同学尝试给 provider 添加 health-check 参数：

```yaml
proxy-providers:
  yoyu:
    type: http
    path: xxxxx
    url: xxxx
    interval: 86400
    health-check:
      enable: false #自动检测开关，不影响手动检测
      url: http://www.gstatic.com/generate_204
      interval: 600
```
