### ISSUE TITLE
开启DNS后无法连接本地端口

### ISSUE THREAD

**Issue by kuukisann** [Fndroid/clash_for_windows_pkg#1369]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Microsoft Windows [版本 10.0.19042.630]
v0.13.5

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
在启用dns后所有连接至本机的代理全部超时，且clash不会转发请求至对应应用
dns部分配置如下（使用的是 https://github.com/Hackl0us/SS-Rule-Snippet 提供的配置）：
```
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true # 当此选项为 false 时, AAAA 请求将返回空

  # 以下填写的 DNS 服务器将会被用来解析 DNS 服务的域名
  # 仅填写 DNS 服务器的 IP 地址
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: fake-ip # 或 redir-host
  fake-ip-range: 198.18.0.1/16 # Fake IP 地址池 (CIDR 形式)
  # use-hosts: true # 查询 hosts 并返回 IP 记录

  # 在以下列表的域名将不会被解析为 fake ip，这些域名相关的解析请求将会返回它们真实的 IP 地址
  fake-ip-filter:
    # 以下域名列表参考自 vernesong/OpenClash 项目，并由 Hackl0us 整理补充
    # === LAN ===
    - '*.lan'
    # === Linksys Wireless Router ===
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    # === Apple Software Update Service ===
    - 'swscan.apple.com'
    - 'mesu.apple.com'
    # === Windows 10 Connnect Detection ===
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    # === NTP Service ===
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'

    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'

    - 'ntp.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'

    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'

    - 'time1.cloud.tencent.com'
    # === Music Service ===
    ## NetEase
    - '+.music.163.com'
    - '*.126.net'
    ## Baidu
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    ## Kugou
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    ## Kuwo
    - '*.kuwo.cn'
    ## JOOX
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    ## QQ
    - '+.y.qq.com'
    - '+.music.tc.qq.com'
    - 'aqqmusic.tc.qq.com'
    - '+.stream.qqmusic.qq.com'
    ## Xiami
    - '*.xiami.com'
    ## Migu
    - '+.music.migu.cn'
    # === Game Service ===
    ## Nintendo Switch
    - '+.srv.nintendo.net'
    ## Sony PlayStation
    - '+.stun.playstation.net'
    ## Microsoft Xbox
    - 'xbox.*.microsoft.com'
    - '+.xboxlive.com'
    # === Other ===
    ## QQ Quick Login
    - 'localhost.ptlogin2.qq.com'
    ## Golang
    - 'proxy.golang.org'
    ## STUN Server
    - 'stun.*.*'
    - 'stun.*.*.*'

  nameserver:
    - https://doh.pub/dns-query

  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
```

**复现**

[//]: # (请描述复现问题的步骤)

**预期行为**

[//]: # (清晰地描述期望看到的行为)
想问问为什么会出现这样的情况，在clash项目下也没有看到相似的问题

**日志**

[//]: # (上传触发问题对应的日志文件)
```
time="2020-11-27T17:24:51+09:00" level=warning msg="dial Proxy to www.google.com error: 127.0.0.1:9527 connect error: dial tcp4 10.210.106.173:0->127.0.0.1:9527: connectex: The requested address is not valid in its context."
time="2020-11-27T17:24:51+09:00" level=warning msg="dial Proxy to www.google.com error: 127.0.0.1:9527 connect error: dial tcp4 10.210.106.173:0->127.0.0.1:9527: connectex: The requested address is not valid in its context."
time="2020-11-27T17:24:51+09:00" level=warning msg="dial Proxy to www.google.com error: 127.0.0.1:9527 connect error: dial tcp4 10.210.106.173:0->127.0.0.1:9527: connectex: The requested address is not valid in its context."
time="2020-11-27T17:24:51+09:00" level=warning msg="dial Proxy to www.google.com error: 127.0.0.1:9527 connect error: dial tcp4 10.210.106.173:0->127.0.0.1:9527: connectex: The requested address is not valid in its context."
time="2020-11-27T17:24:51+09:00" level=warning msg="dial Proxy to www.google.com error: 127.0.0.1:9527 connect error: dial tcp4 10.210.106.173:0->127.0.0.1:9527: connectex: The requested address is not valid in its context."
time="2020-11-27T17:24:51+09:00" level=warning msg="dial Proxy to fonts.gstatic.com error: 127.0.0.1:9527 connect error: dial tcp4 10.210.106.173:0->127.0.0.1:9527: connectex: The requested address is not valid in its context."
time="2020-11-27T17:24:51+09:00" level=warning msg="dial Proxy to www.google.com error: 127.0.0.1:9527 connect error: dial tcp4 10.210.106.173:0->127.0.0.1:9527: connectex: The requested address is not valid in its context."
time="2020-11-27T17:24:51+09:00" level=warning msg="dial Proxy to fonts.gstatic.com error: 127.0.0.1:9527 connect error: dial tcp4 10.210.106.173:0->127.0.0.1:9527: connectex: The requested address is not valid in its context."
time="2020-11-27T17:24:51+09:00" level=warning msg="dial Proxy to www.google.co.jp error: 127.0.0.1:9527 connect error: dial tcp4 10.210.106.173:0->127.0.0.1:9527: connectex: The requested address is not valid in its context."
time="2020-11-27T17:24:51+09:00" level=warning msg="dial Proxy to www.google.co.jp error: 127.0.0.1:9527 connect error: dial tcp4 10.210.106.173:0->127.0.0.1:9527: connectex: The requested address is not valid in its context."
time="2020-11-27T17:24:52+09:00" level=warning msg="dial Proxy to cewr error: 127.0.0.1:9527 connect error: dial tcp4 10.210.106.173:0->127.0.0.1:9527: connectex: The requested address is not valid in its context."
time="2020-11-27T17:24:52+09:00" level=warning msg="dial Proxy to www.google.co.jp error: 127.0.0.1:9527 connect error: dial tcp4 10.210.106.173:0->127.0.0.1:9527: connectex: The requested address is not valid in its context."
time="2020-11-27T17:24:53+09:00" level=warning msg="dial Proxy to www.google.co.jp error: 127.0.0.1:9527 connect error: dial tcp4 10.210.106.173:0->127.0.0.1:9527: connectex: The requested address is not valid in its context."
time="2020-11-27T17:24:58+09:00" level=warning msg="dial Proxy to www.google.co.jp error: 127.0.0.1:9527 connect error: dial tcp4 10.210.106.173:0->127.0.0.1:9527: connectex: The requested address is not valid in its context."
time="2020-11-27T17:24:58+09:00" level=warning msg="dial Proxy to www.google.co.jp error: 127.0.0.1:9527 connect error: dial tcp4 10.210.106.173:0->127.0.0.1:9527: connectex: The requested address is not valid in its context."
```

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)
