### ISSUE TITLE
clash上不了网

### ISSUE THREAD

**Issue by ghost** [Fndroid/clash_for_windows_pkg#1456]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10, 20H2
**描述**
今晚重装完系统，clash就不好用。
[//]: # (请具体并清楚地描述遇到的问题)

**复现**
打开clash，输入订阅地址，更新完订阅文件，输入mixin配置：
```yaml
mixin: # object
  dns:
    enable: true
    listen: :53
    enhanced-mode: fake-ip
    nameserver:
      - 58.22.96.66
      - 218.104.128.106
    fake-ip-filter:
      - '*.msftncsi.com'
      - '*.msftconnecttest.com'
      - 'time.windows.com'
      - 'time.nist.gov‘
      - 'localhost.ptlogin2.qq.com'
      - 'music.163.com'
      - '*.music.163.com'
      - 'y.qq.com'
      - '*.y.qq.com'
```
然后安装TAP网卡，然后开启mixin，开始的几秒能上网，紧接着就不行了，出现如下图画面：
![无标题](https://user-images.githubusercontent.com/72952023/103285094-237d0b00-4a18-11eb-8283-05edd28b0b51.png)
尝试修复，重启程序之后还是这样，过几秒就崩溃了。
换了下内核到12.27版的，还是不行。
