### ISSUE TITLE
[QUESTION] How to force all applications to use Clash?

### ISSUE THREAD

**Issue by Omoeba** [Fndroid/clash_for_windows_pkg#147]

**Comment by Fndroid** [comment]
That not a simple question on Windows.

That what Clash for Windows can do right now:
1. Most applications follow the system proxy setting, so what you can do is turning on ``System Proxy``
2. UWP applications follow the system proxy without loopback address, ``EnableLoopback.exe`` is there for break this limitation
3. For thoes applications that do not follow system proxy settings, you can try TAP. It redirect requests to Clash by changing system DNS server.

**Comment by xjasonlyu** [comment]
Use [Proxifier](https://www.proxifier.com/) to make all TCP/UDP traffic through clash.

**Comment by Fndroid** [comment]
@xjasonlyu Proxifier can not hanlde UWPs

**Comment by Omoeba** [comment]
is it possible to force all apps to use Clash now that TAP supports UDP?

**Comment by Fndroid** [comment]
@Omoeba There are some issues right now

**Comment by Omoeba** [comment]
yeah I get something like `time="2019-07-27T19:19:57-07:00" level=warning msg="Proxy[GLOBAL] connect [127.0.0.1 --> www.msftncsi.com] error: *v2ray*:443 connect error"`
my config.yml is this
```
allow-lan: false
mode: Global
log-level: debug
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: true
  listen: 127.0.0.1:53
  enhanced-mode: fake-ip
  nameserver:
    - 1.1.1.1
secret: ""
cfw-bypass:
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 3000
```
