### ISSUE TITLE
TUN模式开启后无法接管系统流量

### ISSUE THREAD

**Issue by byzod** [Fndroid/clash_for_windows_pkg#1500]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 专业版  20H2  (19042.685)  x64

**描述**

根据教程开启TUN模式后，游戏流量没有经过代理

**复现**

[//]: # (请描述复现问题的步骤)

根据[教程](https://docs.cfw.lbyczf.com/contents/tun.html)
1. 进入网站Wintun，下载wintun-0.10.zip，提取`\bin\amd64\wintun.dll` 放入`Home Directory`中
![7](https://user-images.githubusercontent.com/848607/104088461-0f4fce00-52a2-11eb-89ad-9b2d15ac009c.png)

2. 点击General中Service Mode右边Manage，在打开窗口中安装服务模式，安装完成应用会自动重启，Service Mode右边地球图标变为绿色
![5](https://user-images.githubusercontent.com/848607/104088468-3908f500-52a2-11eb-92ad-2207e25217bd.png)

3. 在使用的配置文件中加入教程所述内容
![6](https://user-images.githubusercontent.com/848607/104088479-4de58880-52a2-11eb-899a-35f2f8a6603b.png)

4. 打开mixin开关（经尝试mixin开关和system proxy开关的4种排列组合均不能成功接管系统流量）

5. 下载并运行游戏[Trove](https://store.steampowered.com/app/304050/Trove/)，第一次运行时会要求下载资源文件

**预期行为**

游戏通过代理下载所需资源，速度很快。下图为使用Proxifier实现的透明代理
![1](https://user-images.githubusercontent.com/848607/104088562-d9f7b000-52a2-11eb-9a7f-190663a05104.png)

**实际行为**

游戏试图直连下载所需资源，速度很慢。
![2](https://user-images.githubusercontent.com/848607/104088569-ee3bad00-52a2-11eb-981d-a202c283cff0.png)

**日志**

没有产生任何日志

**截图**

见`复现`部分

**其他说明**

不知道是哪里设置错误还是怎样，或者是需要重启电脑？对这一块完全不懂，希望大家指点一下;_;

**Comment by Fndroid** [comment]
mixin缩进不对

**Comment by byzod** [comment]
> 
> 
> mixin缩进不对

请问正确的配置文件看起来应该是怎样的？教程里只有片段

**Comment by yi-Xu-0100** [comment]
@byzod 

```yaml
mixin: # object
  dns:
    enable: true
    enhanced-mode: redir-host
    nameserver:
      - 1.1.1.1 # 真实请求DNS，可多设置几个
  # interface-name: en0 # 出口网卡名称，或者使用下方的自动检测
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 198.18.0.2:53
    macOS-auto-route: true
    macOS-auto-detect-interface: true # 自动检测出口网卡
```
