### ISSUE TITLE
麻烦大佬帮忙看看这个mixin设置是否有问题

### ISSUE THREAD

**Issue by vitaminx** [Fndroid/clash_for_windows_pkg#1504]
我安装成功TUN后按照以下设置mixin代码，能够接管系统流量，控制进程走代理
但是联网变得很慢
就连以前联网很快的都很慢
直连也蛮
麻烦帮忙看看是否是mixin设置问题
谢谢

```
mixin: #object
  dns:
    enable: true
    enhanced-mode: redir-host
    listen: 0.0.0.0:53
    nameserver:
      - 114.114.114.114 #114dns
      - 223.6.6.6 #阿里dns
      - 119.28.28.28 #腾讯dns
      - 180.76.76.76 #百度dns
      - 8.8.8.8 #谷歌dns
      - 8.8.4.4 #谷歌dns
      - 223.5.5.5 #阿里dns
      - 119.29.29.29 #腾讯dns
      - 114.114.115.115 #114dns
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 114.114.114.114:53
      - 223.6.6.6:53
      - 180.76.76.76:53
      - 119.28.28.28:53
      - 8.8.8.8:53
    macOS-auto-route: true
    macOS-auto-detect-interface: true # 自动检测出口网卡
```
