### ISSUE TITLE
TAP网卡显示网络电缆被拔出 

### ISSUE THREAD

**Issue by kingforme** [Fndroid/clash_for_windows_pkg#1540]
信息

[x ] 已经尝试更新到最新版本，问题依旧存在
[x ] 软件从本仓库下载
[x ] 软件下载后未修改任何安装目录中的文件
描述
TAP网卡安装后显示网络电缆被拔出

复现
启动clash for windows
打开dashboard
点击install tap device
网络连接出现TAP-Windows Adapter V9
显示“网络电缆已被拔出”

预期行为
tap网卡应显示“已连接”

其他补充内容：
已修改clash for windows--Setting--Profile mixin--YAML
修改内容如下：
![Snipaste_2021-01-23_21-35-24](https://user-images.githubusercontent.com/62692476/105579702-f4617b80-5dc2-11eb-93d4-97724325f1e8.png)
interface-name已配置为本机物理网卡（ASIX AX88179 USB 3.0 to Gigabit Ethernet Adapter）
![Snipaste_2021-01-23_21-39-20](https://user-images.githubusercontent.com/62692476/105579762-7b165880-5dc3-11eb-974a-8764ec93f21a.png)

**Comment by yi-Xu-0100** [comment]
enhanced-mode: 没填不知道是不是有影响?

https://docs.cfw.lbyczf.com/contents/tap.html

**Comment by kingforme** [comment]
> 增强模式：没填不知道是不是有影响？
> 
> https://docs.cfw.lbyczf.com/contents/tap.html

https://www.xkww3n.life/2020/02/13/clash-tap-network-adapter/
上面这条链接给了一个模板，但是我不知道怎么添加(代码如下)
```
port: 7890
socks-port: 7891
# redir-port: 7892
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090

Proxy:
- { name: "PROXY", type: vmess, server: example.net, port: 2233, uuid: 0000-0000-0000-0000, alterId: 2, cipher: none, tls: false }

Proxy Group:
- { name: "provider", type: select, proxies: ["PROXY"] }

Rule:
- DOMAIN,example.com,provider

dns:
   enable: true
   enhanced-mode: fake-ip
   listen: 127.0.0.1:53
   nameserver:
      - 1.2.4.8
      - 210.2.4.8
     ```

**Comment by yi-Xu-0100** [comment]
不需要在 profile 中，在 mixin 中添加就好，它是内存混合，mixin 启用，profile 中是不显示的。
```yaml
mixin: 
  dns:
    enable: true
    enhanced-mode: fake-ip
    listen: 0.0.0.0:53
    nameserver:
      - 223.5.5.5
    fake-ip-filter:
      - "dns.msftncsi.com"
      - "www.msftncsi.com"
      - "www.msftconnecttest.com"
```

**Comment by kingforme** [comment]
如果在个人资料中修改，更新后会需要重新写，所以不推荐

按代码修改,还是无法启动TAP（通过google尝试过所以的方法,无解）

**Comment by kingforme** [comment]
> 不需要在 profile 中，在 mixin 中添加就好，它是内存混合，mixin 启用，profile 中是不显示的。
> 
> ```yaml
> mixin: 
>   dns:
>     enable: true
>     enhanced-mode: fake-ip
>     listen: 0.0.0.0:53
>     nameserver:
>       - 223.5.5.5
>     fake-ip-filter:
>       - "dns.msftncsi.com"
>       - "www.msftncsi.com"
>       - "www.msftconnecttest.com"
> ```
> 
> 如果在 profile 中修改，更新后会需要重新写，所以不推荐

已按照要求修改配置代码,但TAP仍然无法启动（google大量方法无效）

**Comment by ra1nbow2000** [comment]
![image](https://user-images.githubusercontent.com/32125748/105625715-034d3a00-5e66-11eb-9442-b44a568f94cf.png)
mixin前有一个空格，注意缩进

**Comment by yi-Xu-0100** [comment]
@kingforme mixin 配置后，无法启动，tap 网卡显示啥？还是显示“网络电缆已被拔出” 吗？尝试直接使用 `interface-name: 以太网 2` 试试
```yaml
mixin: 
  dns:
    enable: true
    enhanced-mode: fake-ip
    listen: 0.0.0.0:53
    nameserver:
      - 223.5.5.5
    fake-ip-filter:
      - "dns.msftncsi.com"
      - "www.msftncsi.com"
      - "www.msftconnecttest.com"
  interface-name: '以太网 2'
```

@ra1nbow2000 mixin 的格式一般符合 yaml 格式要求就行
