### ISSUE TITLE
UDP Traffic Is Not Going Through The Proxy

### ISSUE THREAD

**Issue by RebelliousWhiz** [Fndroid/clash_for_windows_pkg#1544]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 20H2
Clash For Windows 0.14.1
Skye UWP Version (I believe the desktop version is the same, tested it before)

[//]: # (平台及版本号)

**描述**

Clash For Windows is not filtering the Skype traffic, even the last rule is "MATCH, PROXY"

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. Install TUN according to the instruction
2. Set the last rule to MATCH, PROXY
3. Turn on Clash For Windows
4. Turn on Skype, make a call

**预期行为**

Skype traffic goes through the Clash

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

![image](https://user-images.githubusercontent.com/15100865/105716746-3a047c80-5f5a-11eb-97fe-0eb5f8108dbc.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

My configs:

```
mixed-port: 64000
allow-lan: false
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:65000
secret: ********,
interface-name: Ethernet
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: redir-host
  ipv6: false
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback:
    - 8.8.8.8
    - 8.8.4.4
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53
  macOS-auto-route: true
......
rules:
  - DOMAIN-KEYWORD,google,PROXY
  - DOMAIN-KEYWORD,facebook,PROXY
  - DOMAIN-KEYWORD,youtube,PROXY
  - DOMAIN-KEYWORD,twitter,PROXY
  - DOMAIN-KEYWORD,instagram,PROXY
  - DOMAIN-KEYWORD,gmail,PROXY
  - DOMAIN-SUFFIX,twimg.com,PROXY
  - DOMAIN-SUFFIX,t.co,PROXY
  - DOMAIN-SUFFIX,kenengba.com,PROXY
  - DOMAIN-SUFFIX,akamai.net,PROXY
  - DOMAIN-SUFFIX,whatsapp.net,PROXY
  - DOMAIN-SUFFIX,whatsapp.com,PROXY
  - DOMAIN-SUFFIX,snapchat.com,PROXY
  - DOMAIN-KEYWORD,pixiv,PROXY
  - DOMAIN-SUFFIX,fb.com,PROXY
  - DOMAIN-SUFFIX,ampproject.org,PROXY
  - DOMAIN-SUFFIX,scdn.co,PROXY
  - DOMAIN-SUFFIX,line.naver.jp,PROXY
  - DOMAIN-SUFFIX,line.me,PROXY
  - DOMAIN-SUFFIX,line-apps.com,PROXY
  - DOMAIN-SUFFIX,line-cdn.net,PROXY
  - DOMAIN-SUFFIX,line-scdn.net,PROXY
  - DOMAIN-SUFFIX,apple.com,PROXY
  - DOMAIN-SUFFIX,mzstatic.com,PROXY
  - DOMAIN-SUFFIX,itunes.com,PROXY
  - DOMAIN-SUFFIX,icloud.com,PROXY
  - DOMAIN-SUFFIX,icloud-content.com,PROXY
  - DOMAIN-SUFFIX,lcdn-registration.apple.com,PROXY
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-KEYWORD,alipay,DIRECT
  - DOMAIN-KEYWORD,360buy,DIRECT
  - DOMAIN-SUFFIX,jd.com,DIRECT
  - DOMAIN-SUFFIX,126.net,DIRECT
  - DOMAIN-SUFFIX,163.com,DIRECT
  - DOMAIN-SUFFIX,amap.com,DIRECT
  - DOMAIN-SUFFIX,bdimg.com,DIRECT
  - DOMAIN-SUFFIX,bdstatic.com,DIRECT
  - DOMAIN-SUFFIX,cnbeta.com,DIRECT
  - DOMAIN-SUFFIX,douban.com,DIRECT
  - DOMAIN-SUFFIX,gtimg.com,DIRECT
  - DOMAIN-SUFFIX,hao123.com,DIRECT
  - DOMAIN-SUFFIX,haosou.com,DIRECT
  - DOMAIN-SUFFIX,ifeng.com,DIRECT
  - DOMAIN-SUFFIX,iqiyi.com,DIRECT
  - DOMAIN-SUFFIX,netease.com,DIRECT
  - DOMAIN-SUFFIX,qhimg.com,DIRECT
  - DOMAIN-SUFFIX,sogou.com,DIRECT
  - DOMAIN-SUFFIX,sohu.com,DIRECT
  - DOMAIN-SUFFIX,soso.com,DIRECT
  - DOMAIN-SUFFIX,suning.com,DIRECT
  - DOMAIN-SUFFIX,tmall.com,DIRECT
  - DOMAIN-SUFFIX,tudou.com,DIRECT
  - DOMAIN-SUFFIX,youku.com,DIRECT
  - DOMAIN-SUFFIX,xunlei.com,DIRECT
  - DOMAIN-SUFFIX,zhihu.com,DIRECT
  - DOMAIN-SUFFIX,ls.apple.com,PROXY
  - DOMAIN-SUFFIX,weather.com,DIRECT
  - DOMAIN-SUFFIX,weibo.cn,DIRECT
  - DOMAIN-SUFFIX,weibo.com,DIRECT
  - DOMAIN-SUFFIX,sinaimg.cn,DIRECT
  - DOMAIN-SUFFIX,goodread.com,DIRECT
  - DOMAIN-KEYWORD,aka,PROXY
  - DOMAIN,me.com,PROXY
  - DOMAIN-SUFFIX,.me.com,PROXY
  - DOMAIN-SUFFIX,amazonaws.com,PROXY
  - DOMAIN-SUFFIX,android.com,PROXY
  - DOMAIN-SUFFIX,angularjs.org,PROXY
  - DOMAIN-SUFFIX,appspot.com,PROXY
  - DOMAIN-SUFFIX,akamaihd.net,PROXY
  - DOMAIN-SUFFIX,amazon.com,PROXY
  - DOMAIN-SUFFIX,bit.ly,PROXY
  - DOMAIN-SUFFIX,bitbucket.org,PROXY
  - DOMAIN-SUFFIX,blog.com,PROXY
  - DOMAIN-SUFFIX,blogcdn.com,PROXY
  - DOMAIN-SUFFIX,blogger.com,PROXY
  - DOMAIN-SUFFIX,blogsmithmedia.com,PROXY
  - DOMAIN-SUFFIX,box.net,PROXY
  - DOMAIN-SUFFIX,bloomberg.com,PROXY
  - DOMAIN-SUFFIX,chromium.org,PROXY
  - DOMAIN-SUFFIX,cl.ly,PROXY
  - DOMAIN-SUFFIX,cloudfront.net,PROXY
  - DOMAIN-SUFFIX,cloudflare.com,PROXY
  - DOMAIN-SUFFIX,cocoapods.org,PROXY
  - DOMAIN-SUFFIX,crashlytics.com,PROXY
  - DOMAIN-SUFFIX,dribbble.com,PROXY
  - DOMAIN-SUFFIX,dropbox.com,PROXY
  - DOMAIN-SUFFIX,dropboxstatic.com,PROXY
  - DOMAIN-SUFFIX,dropboxusercontent.com,PROXY
  - DOMAIN-SUFFIX,docker.com,PROXY
  - DOMAIN-SUFFIX,duckduckgo.com,PROXY
  - DOMAIN-SUFFIX,digicert.com,PROXY
  - DOMAIN-SUFFIX,dnsimple.com,PROXY
  - DOMAIN-SUFFIX,edgecastcdn.net,PROXY
  - DOMAIN-SUFFIX,engadget.com,PROXY
  - DOMAIN-SUFFIX,eurekavpt.com,PROXY
  - DOMAIN-SUFFIX,fb.me,PROXY
  - DOMAIN-SUFFIX,fbcdn.net,PROXY
  - DOMAIN-SUFFIX,fc2.com,PROXY
  - DOMAIN-SUFFIX,feedburner.com,PROXY
  - DOMAIN-SUFFIX,fabric.io,PROXY
  - DOMAIN-SUFFIX,flickr.com,PROXY
  - DOMAIN-SUFFIX,fastly.net,PROXY
  - DOMAIN-SUFFIX,ggpht.com,PROXY
  - DOMAIN-SUFFIX,github.com,PROXY
  - DOMAIN-SUFFIX,github.io,PROXY
  - DOMAIN-SUFFIX,githubusercontent.com,PROXY
  - DOMAIN-SUFFIX,golang.org,PROXY
  - DOMAIN-SUFFIX,goo.gl,PROXY
  - DOMAIN-SUFFIX,gstatic.com,PROXY
  - DOMAIN-SUFFIX,godaddy.com,PROXY
  - DOMAIN-SUFFIX,gravatar.com,PROXY
  - DOMAIN-SUFFIX,imageshack.us,PROXY
  - DOMAIN-SUFFIX,imgur.com,PROXY
  - DOMAIN-SUFFIX,jshint.com,PROXY
  - DOMAIN-SUFFIX,ift.tt,PROXY
  - DOMAIN-SUFFIX,j.mp,PROXY
  - DOMAIN-SUFFIX,kat.cr,PROXY
  - DOMAIN-SUFFIX,linode.com,PROXY
  - DOMAIN-SUFFIX,linkedin.com,PROXY
  - DOMAIN-SUFFIX,licdn.com,PROXY
  - DOMAIN-SUFFIX,lithium.com,PROXY
  - DOMAIN-SUFFIX,megaupload.com,PROXY
  - DOMAIN-SUFFIX,mobile01.com,PROXY
  - DOMAIN-SUFFIX,modmyi.com,PROXY
  - DOMAIN-SUFFIX,nytimes.com,PROXY
  - DOMAIN-SUFFIX,name.com,PROXY
  - DOMAIN-SUFFIX,openvpn.net,PROXY
  - DOMAIN-SUFFIX,openwrt.org,PROXY
  - DOMAIN-SUFFIX,ow.ly,PROXY
  - DOMAIN-SUFFIX,pinboard.in,PROXY
  - DOMAIN-SUFFIX,ssl-images-amazon.com,PROXY
  - DOMAIN-SUFFIX,sstatic.net,PROXY
  - DOMAIN-SUFFIX,stackoverflow.com,PROXY
  - DOMAIN-SUFFIX,staticflickr.com,PROXY
  - DOMAIN-SUFFIX,squarespace.com,PROXY
  - DOMAIN-SUFFIX,symcd.com,PROXY
  - DOMAIN-SUFFIX,symcb.com,PROXY
  - DOMAIN-SUFFIX,symauth.com,PROXY
  - DOMAIN-SUFFIX,ubnt.com,PROXY
  - DOMAIN-SUFFIX,thepiratebay.org,PROXY
  - DOMAIN-SUFFIX,tumblr.com,PROXY
  - DOMAIN-SUFFIX,twitch.tv,PROXY
  - DOMAIN-SUFFIX,twitter.com,PROXY
  - DOMAIN-SUFFIX,wikipedia.com,PROXY
  - DOMAIN-SUFFIX,wikipedia.org,PROXY
  - DOMAIN-SUFFIX,wikimedia.org,PROXY
  - DOMAIN-SUFFIX,wordpress.com,PROXY
  - DOMAIN-SUFFIX,wsj.com,PROXY
  - DOMAIN-SUFFIX,wsj.net,PROXY
  - DOMAIN-SUFFIX,wp.com,PROXY
  - DOMAIN-SUFFIX,vimeo.com,PROXY
  - DOMAIN-SUFFIX,youtu.be,PROXY
  - DOMAIN-SUFFIX,ytimg.com,PROXY
  - DOMAIN-KEYWORD,blogspot,PROXY
  - DOMAIN-SUFFIX,tapbots.com,PROXY
  - DOMAIN-SUFFIX,ykimg.com,DIRECT
  - DOMAIN-SUFFIX,medium.com,PROXY
  - DOMAIN-SUFFIX,fast.com,PROXY
  - DOMAIN-SUFFIX,nflxvideo.net,PROXY
  - DOMAIN-SUFFIX,clashroyaleapp.com,DIRECT
  - DOMAIN-SUFFIX,bilibili.com,DIRECT
  - DOMAIN-SUFFIX,bilibili.cn,DIRECT
  - DOMAIN-SUFFIX,acgvideo.com,DIRECT
  - DOMAIN-SUFFIX,jianshu.com,DIRECT
  - DOMAIN-SUFFIX,jianshu.io,DIRECT
  - DOMAIN-SUFFIX,jianshuapi.com,DIRECT
  - DOMAIN-SUFFIX,soundcloud.com,PROXY
  - DOMAIN-SUFFIX,sndcdn.com,PROXY
  - DOMAIN-SUFFIX,outlook.com,DIRECT
  - IP-CIDR,91.108.56.0/22,PROXY,no-resolve
  - IP-CIDR,91.108.4.0/22,PROXY,no-resolve
  - IP-CIDR,109.239.140.0/24,PROXY,no-resolve
  - IP-CIDR,149.154.160.0/20,PROXY,no-resolve
  - IP-CIDR,0.0.0.0/8,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,169.254.0.0/16,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.0.0.0/24,DIRECT
  - IP-CIDR,192.0.2.0/24,DIRECT
  - IP-CIDR,192.88.99.0/24,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,192.18.0.0/15,DIRECT
  - IP-CIDR,198.51.100.0/24,DIRECT
  - IP-CIDR,203.0.113.0/24,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,240.0.0.0/4,DIRECT
  - IP-CIDR,255.255.255.255/32,DIRECT
  - DOMAIN-SUFFIX,google.com,PROXY
  - DOMAIN-SUFFIX,msn.com,PROXY
  - DOMAIN-SUFFIX,msn.cn,PROXY
  - DOMAIN-SUFFIX,bing.com,PROXY
  - DOMAIN-SUFFIX,skype.com,PROXY
  - DOMAIN-KEYWORD,qcloud.com,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
```

[//]: # (其他补充内容)
