### ISSUE TITLE
下载文件遇到SSL错误

### ISSUE THREAD

**Issue by Eddddddddy** [Fndroid/clash_for_windows_pkg#1568]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

macOS BigSur 11.1

**描述**

使用cfw从github网页上直接下载仓库的zip压缩包，下载不下来。下载到一半就会中断。Safari提示：“未能完成该操作，在STREAM中无可用信息。”然后再次点击下载依然会中断，Safari提示：“发生SSL错误，无法建立到该服务器...”。通过其他代理软件能够正常进行下载。使用cfw测试其他网站诸如Google可以正常使用，YouTube也可以流畅播放4k。

**复现**

[//]: # 

1. 正常使用软件，允许LAN，port自定义为7890，Service Mode已安装，mixin未开启，系统代理和start with macOS已开启。
2. 设置Parsers为以下内容：

```

 parsers: # array
    - url: https://xxxxxxxxxxxxxxxxxxxxxxxxxxxx
     yaml:
       prepend-rules:
         - DOMAIN-SUFFIX,github.com,CYLINK
         - DOMAIN-SUFFIX,developer.github.com,CYLINK
         - DOMAIN-SUFFIX,pages.github.com,CYLINK
         - DOMAIN-SUFFIX,desktop.github.com,CYLINK
         - DOMAIN-SUFFIX,www.github.com,CYLINK
         - DOMAIN-SUFFIX,help.github.com,CYLINK
         - DOMAIN-SUFFIX,guides.github.com,CYLINK
         - DOMAIN-SUFFIX,education.github.com,CYLINK
         - DOMAIN-SUFFIX,hub.github.com,CYLINK
         - DOMAIN-SUFFIX,enterprise.github.com,CYLINK
         - DOMAIN-SUFFIX,status.github.com,CYLINK
         - DOMAIN-SUFFIX,resources.github.com,CYLINK
         - DOMAIN-SUFFIX,windows.github.com,CYLINK
         - DOMAIN-SUFFIX,classroom.github.com,CYLINK
         - DOMAIN-SUFFIX,lab.github.com,CYLINK
         - DOMAIN-SUFFIX,wikipedia.org,CYLINK
         - DOMAIN-SUFFIX,wikimedia.org,CYLINK
         - DOMAIN-SUFFIX,github.com,CYLINK
         - DOMAIN-SUFFIX,githubusercontent.com,CYLINK
         - DOMAIN-SUFFIX,githubusercontent.com,CYLINK

```
3. 其他均为默认
4. 触发问题

**预期行为**

能够正常对github内容通过Safari下载

**日志**

[//]: # (上传触发问题对应的日志文件)

<img width="850" alt="截屏2021-01-30 上午11 12 48" src="https://user-images.githubusercontent.com/46312408/106345593-5e5eb100-62ec-11eb-9fde-cee34fd15072.png">

**截图**

[//]: # (如果可以，请提供对应问题的截图)
<img width="432" alt="截屏2021-01-30 上午11 11 38" src="https://user-images.githubusercontent.com/46312408/106345547-02942800-62ec-11eb-9d88-89a8da100071.png">

**其他说明**

[//]: # (其他补充内容)
