### ISSUE TITLE
开启TUN模式导致Office无法联网

### ISSUE THREAD

**Issue by mom0a** [Fndroid/clash_for_windows_pkg#1575]
**信息**

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 Build 1909 / CFW 0.14.3

**描述**

开启TUN模式后，Office显示无法联网

**复现**

TUN使用以下代码开启，已配置服务，除Office外其他程序联网正常
```YAML
mixin:
  dns:
    enable: true
    enhanced-mode: redir-host
    ipv6: false
    nameserver:
      - tls://223.5.5.5:853
      - tls://223.6.6.6:853
    fake-ip-range: 198.18.0.0/16
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 198.18.0.2:53
    macOS-auto-route: true
    macOS-auto-detect-interface: true
```

关闭TUN后Office联网恢复正常

**预期行为**

Office和其他应用一样可以正常联网

**日志**

Clash无报错信息

**截图**

![pic1](https://vip1.loli.net/2021/02/01/3NKFAtIjhwP4sm7.png)
![pic2](https://vip2.loli.net/2021/02/01/pdzYNL3r4kcQnoH.png)

**其他说明**

通过查找相似的情况，推测现象可能是Office会对网络可用性进行额外的检查所导致
<https://www.macwheeler.com/windows-10-office-365-cannot-connect-over-openvpn-fixed/>
