### ISSUE TITLE
开启mixin后无法切换profiles

### ISSUE THREAD

**Issue by ANGIANAPR** [Fndroid/clash_for_windows_pkg#1576]
mixin关闭时一切正常，打开mixin功能后切换profiles时出现如下报错：
![image](https://user-images.githubusercontent.com/25098387/106432103-35374f80-64a9-11eb-87a6-3101c1ff1a71.png)

**Comment by yi-Xu-0100** [comment]
@ANGIANAPR 给出 mixin 内容

**Comment by ANGIANAPR** [comment]
```
mixin:
  dns:
    enable: true
    enhanced-mode: redir-host
    # listen: :53
    nameserver:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4
      - 114.114.114.114
      - 114.114.114.115
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 198.18.0.2:53
    macOS-auto-route: true
    macOS-auto-detect-interface: true # 自动检测出口网卡
```
