### ISSUE TITLE
TAP doesn't work

### ISSUE THREAD

**Issue by Omoeba** [Fndroid/clash_for_windows_pkg#158]
here is my config.yml
```
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
secret: ""
dns:
  enable: true
  listen: 127.0.0.1:53
  enhanced-mode: fake-ip
  nameserver:
     - 1.1.1.1
cfw-bypass:
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
cfw-latency-timeout: 3000
Proxy:
  - name: v2ray
    type: vmess
    server: redacted
    port: "443"
    uuid: redacted
    alterId: "64"
    cipher: none
    tls: true
    network: ws
    ws-path: /websocket/
Proxy Group:
  - name: Proxy
    type: select
    proxies:
      - v2ray
Rule:
  - FINAL,v2ray

```
