### ISSUE TITLE
使用配置文件预处理给规则头部加入新的自定义的规则，parsers中的url可以使用正则表达式吗？

### ISSUE THREAD

**Issue by WrathGluttony** [Fndroid/clash_for_windows_pkg#1593]
我要实现以下功能：
**①**先从v2rayN中导出节点，通过subconverter在github上的说明进行转换，然后导入到clash for windows电脑端，每次导入的订阅链接是不同的
**②**使用配置文件预处理，把1个规则加入到①中的订阅链接里的规则中
**③**问题来了，由于订阅订阅链接每次是不同的，“- url：订阅链接”中的“订阅链接”我如何写？写成任意链接？比如：
   “- url: http://*.*"?写成空？比如“- url: null"?
**④**总结：我想实现的是任意订阅链接导入时，都要使用配置文件预处理给规则头部加入新的自定义规则，然后parsers里的”- url： 订阅链接”中的订阅链接是用正则表达式如何写？
**附**：clash for windows在github上的说明文档中的配置文件预处理例子所在网页的链接及例子代码：
(1)所在网页链接：https://docs.cfw.lbyczf.com/contents/parser.html#%E7%89%88%E6%9C%AC%E8%A6%81%E6%B1%82
(2)配置文件预处理例子代码：
```yaml
parsers:
  - url: https://example.com/profile.yaml
    yaml:
      prepend-rules:
        - DOMAIN,test.com,DIRECT # rules最前面增加一个规则
      append-proxies:
        - name: test # proxies最后面增加一个服务
          type: http
          server: 123.123.123.123
          port: 456
```

**Comment by Fndroid** [comment]
```yaml
parsers:
  - reg: ".+"
    file: xxx.js
```

**Comment by WrathGluttony** [comment]
> ```yaml
> parsers:
>   - reg: ".+"
>     file: xxx.js
> ```
①
```yaml
parsers:
  - reg: http://127.0.0.+$
    yaml:
      prepend-rules:
        - DOMAIN-SUFFIX,translate.googleapis.com,DIRECT
```
②
```yaml
parsers:
  - reg: .+
    yaml:
      prepend-rules:
        - DOMAIN-SUFFIX,translate.googleapis.com,DIRECT
```
③
```yaml
parsers:
  - reg: http://127.0.0.1:25500/sub?target=clash&url=.+$
    yaml:
      prepend-rules:
        - DOMAIN-SUFFIX,translate.googleapis.com,DIRECT
```
④上面①②的代码有效，但是③中的代码就无效，③中是我想实现的，就是以”http://127.0.0.1:25500/sub?target=clash&url=”开头的订阅链接通过配置预处理在规则头部加入所示代码中的1条规则.
⑤请问③中在"http://127.0.0.1:25500/sub?target=clash&url="后加的“.+$”是语法上有错误吗？

**Comment by Fndroid** [comment]
```yaml
parsers:
  - reg: http://127\\.0\\.0\\.1:25500/sub\\?target=clash&url=.+$
    yaml: xxx.yaml
```

转义字符前要加``\\``
