### ISSUE TITLE
请问大家在内网环境下都是如何设置前置代理的？

### ISSUE THREAD

**Issue by Craftsman98** [Fndroid/clash_for_windows_pkg#1632]
**描述**
在公司这种内网环境下，访问外网需要通过特定的代理服务器，这种环境下大家是怎么使用clash的呢？

**其他说明**
我目前的方案是cfw配置parsers使内网直连访问，然后使用Proxifier将其他应用的流量转发到cfw，再将cfw的流量转发到内网代理。有没有更优雅的解决方案？

 我看有人说clash的relay功能变相实现了前置代理功能#882，具体是如何实现的？可以给出一个示例吗

**Comment by ygsk10** [comment]
https://github.com/Dreamacro/clash/pull/539

config:

```
proxy-groups:
- name: "relay"
  type: relay
  proxies:
    - http1
    - vmess1
    - ss1
    - ss2
```

traffic:
`clash <-> http1 <-> vmess1 <-> ss1 <-> ss2 <-> Internet`

**Comment by Craftsman98** [comment]
@ygsk10 我尝试了这种配置，
```yaml
proxy-groups:
  - name: 🚀流量转发
    type: relay
    proxies:
      - myhttp
      - 🔰 节点选择
```
myhttp是我的内网出口服务器，按照我的理解这样配置的效果是我的流量： `clash <-> myhttp <-> 🔰 节点选择 <-> Internet`

但是如果我关闭proxifier，则节点测速全部timeout：
![image](https://user-images.githubusercontent.com/38043100/108587123-c43ed580-738c-11eb-8c91-514d046690a3.png)

请问是我配置不正确还是用法不正确？流量转发这个`proxy-group`并不能点击或者选择……

感谢大佬帮忙🙇‍

**Comment by Craftsman98** [comment]
而且，配置了relay的情况下我打开proxifier（将我的流量转发到clash，再将clash流量转发到内网服务器），能够正常访问网络（与之前无异），是不是我配置的relay组没有生效？

**Comment by yi-Xu-0100** [comment]
@Craftsman98 你应该看日志来确定走的什么规则。如果规则配置走的节点选择，怎么走到流量转发呢？

**Comment by yi-Xu-0100** [comment]
@Craftsman98 我这样处理是成功的

```yaml
proxy-groups:
  - name: 🔰 PROXY
    type: select
    proxies:
      - 🎯 LOCAL
      - ♻️ AUTO
      - 🇭🇰 HK
      - 🇯🇵 JP
      - 🇸🇬 SGP
      - 🇺🇸 USA
      - 🎥 NF
      - 🐟 other
      - ⏭ relay
  - name: ⏭ relay
    type: relay
    proxies:
      - 🇯🇵 JP
      - ✅ select
  - name: ✅ select
    type: select
    proxies:
      - 🎯 LOCAL
      - ♻️ AUTO
      - 🇭🇰 HK
      - 🇯🇵 JP
      - 🇸🇬 SGP
      - 🇺🇸 USA
      - 🎥 NF
      - 🐟 other
```

因为原配置中的 rule 规则代理走的 `🔰 PROXY`。我不想动规则，复制了其内容作为 `✅ select`，然后将 `⏭ relay` 作为 `🔰 PROXY` 的一个选择项，你可以将前置代理替换掉 `⏭ relay` 中的 `🇯🇵 JP`, 后面的可以根据自己需求改。
