### ISSUE TITLE
TUN使用问题

### ISSUE THREAD

**Issue by 3035556** [Fndroid/clash_for_windows_pkg#1649]
**描述**
        本人小白很多不是很明白，目前使用一台笔记本通过无线网使用clash，目前可以实现ios手机与电脑端正常上网。ps4上门的youtbe的软件不能够实现，TUN是不是可以解决这个问题，apple TV在是不是也如此。
        目前按照教程已经尝试设置TUN，设置完成后开始只有上行走TUN，下行还是HTTP是不是哪里出问题
谢谢，大佬们的软件与付出
**其他说明**
系统为win10 64位
下载使用 amd64的wintun.dll放入Home Directory然后Service Mode右边Manage然后settings——Profile Mixin——YAML
输入
```yaml
mixin: 
  dns:
    enable: true
    enhanced-mode: redir-host
    nameserver:
    - 1.1.1.1 
    - 8.8.8.8
    - 114.144.114.114
    - 202.96.64.68
    - 119.29.29.29 
    - 223.5.5.5 
    interface-name: 这个位置复制是网卡的描述
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
    - 198.18.0.2:53
    macOS-auto-route: true
    macOS-auto-detect-interface: true 
```
开启Mixin
晚点上传截图
