### ISSUE TITLE
如何通过mixin将几个proxy-group的type覆盖成url-test

### ISSUE THREAD

**Issue by ForbAvalon** [Fndroid/clash_for_windows_pkg#1698]
如题，我尝试了一下yaml的command指令
  - proxy-groups.HK.type=url-test
 但是没有成功，有没有什么方法可以让配置中的几个分组用url-test类型的？

**Comment by yi-Xu-0100** [comment]
@ForbAvalon 
```yaml
parsers:
  - url: https://example.com/profile.yaml
    yaml:
      commands:
        - proxy-groups.(HK).type=url-test
        - proxy-groups.(HK).url=http://www.gstatic.com/generate_204
        - proxy-groups.(HK).interval=300
```
