### ISSUE TITLE
Windows 10系统PPPoE拨号下TUN模式无法正常工作

### ISSUE THREAD

**Issue by plutonemhikari** [Fndroid/clash_for_windows_pkg#1753]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 Clash.for.Windows-0.15.1-win
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
在WLAN连接下TUN模式可以正常工作，但是如果换成PPPoE就会出问题。redir-host模式完全不能用，fake-ip模式如过使用自动检测则不可用，必须手动指定网卡名，而且手动指定网卡名有时候也会出问题。
**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'....'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

完全按照这个网站配置的过程https://docs.cfw.lbyczf.com/contents/tun.html#windows

**预期行为**

[//]: # (清晰地描述期望看到的行为)
正常连接
**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
@plutonemhikari 是不是那个什么名字是中文的问题

**Comment by plutonemhikari** [comment]
> @plutonemhikari 是不是那个什么名字是中文的问题

没有，我宽带连接的名字就叫PPPoE，没有中文。

**Comment by yi-Xu-0100** [comment]
@plutonemhikari 有日志吗

**Comment by URARUA** [comment]
> @plutonemhikari 有日志吗

以下为部分配置文件设定：
```
dns:
  enable: true
  listen: 0.0.0.0:64800
  ipv6: true
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: redir-host
  fake-ip-range: 172.16.0.0/16
  nameserver:
    - 119.29.29.29:53
    - 223.5.5.5:53
    - 208.67.222.222:5353
  fallback:
    - 1.1.1.1:53
    - 8.8.8.8:53
    - 208.67.222.222:5353
  fallback-filter:
    geoip: true
    ipcidr: null
    domain: null
  experimental:
    ignore-resolve-fail: false
```
以下为部分log：
```
time="2021-04-01T12:18:19+08:00" level=warning msg="[TCP] dial Final (match Match/) to mail.google.com error: 116.129.252.103:1350 connect error: dial tcp4 xxx.xxx.xxx.xxx:xxxx: connectex: A socket operation was attempted to an unreachable host."
time="2021-04-01T12:20:29+08:00" level=warning msg="[TCP] dial DIRECT (match RuleSet/LAN) to 172.16.0.2 error: dial tcp4 192.168.198.112:0->172.16.0.2:53: i/o timeout"
time="2021-04-01T13:08:27+08:00" level=warning msg="[TCP] dial DIRECT (match DomainSuffix/mp.microsoft.com) to licensing.mp.microsoft.com error: all DNS requests failed, first error: dial udp 192.168.198.112:0->208.67.222.222:5353: connect: A socket operation was attempted to an unreachable network."
time="2021-04-01T13:08:55+08:00" level=warning msg="[TCP] dial Final (match Match/) to nav.smartscreen.microsoft.com error: 116.129.252.103:1350 connect error: dial tcp4 192.168.198.112:0->xxx.xxx.xxx.xxx:xxxx: connectex: A socket operation was attempted to an unreachable host."
```

**Comment by yi-Xu-0100** [comment]
@plutonemhikari windows 的 tun 中的 dns-hijack 不用变吧，看下文档：<https://docs.cfw.lbyczf.com/contents/tun.html#windows>

**Comment by URARUA** [comment]
> @URARUA windows 的 tun 中的 dns-hijack 不用变吧，看下文档：https://docs.cfw.lbyczf.com/contents/tun.html#windows
> 
> 又看错人了。。。

改变这个没有影响...（在 wlan 网络试过了）
按照上面说的，只在手动设置 interface name 且 fake-ip 模式，才下能正常使用tun（试了一下确实是这样）
在 redir-host 模式下的log：
'''
time="2021-04-01T17:01:39+08:00" level=warning msg="[UDP] dial DIRECT (match RuleSet/LAN) to 172.16.0.2 error: route ip+net: invalid network interface name"
(在这之后我把宽带连接重命名为PPPOE并重启cfw）
time="2021-04-01T17:01:53+08:00" level=warning msg="Failed to start Redir UDP Listener: not supported on current platform"
time="2021-04-01T17:02:06+08:00" level=warning msg="[UDP] dial Final (match Match/) to 224.0.0.251 error: gateway not found"
'''

**Comment by plutonemhikari** [comment]
> @plutonemhikari 有日志吗
redir-host模式：
![redir-host模式](https://user-images.githubusercontent.com/62335203/113317104-9d879d80-9341-11eb-9644-cd2a4c42431a.png)
fake-ip模式：
![fake-ip模式](https://user-images.githubusercontent.com/62335203/113317179-b1330400-9341-11eb-97c6-2b872dee08f9.png)

配置是直接在mixin里加的，如下：
```
mixin: # object
  dns:
    enable: true
    enhanced-mode: redit-host
    nameserver:
      - 8.8.8.8 # 真实请求DNS，可多设置几个
      - 114.114.114.114
  interface-name: PPPoE # 出口网卡名称，或者使用下方的自动检测
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 198.18.0.2:53
    macOS-auto-route: true
    #macOS-auto-detect-interface: true # 自动检测出口网卡
```

**Comment by plutonemhikari** [comment]
> > @URARUA windows 的 tun 中的 dns-hijack 不用变吧，看下文档：https://docs.cfw.lbyczf.com/contents/tun.html#windows
> > 又看错人了。。。
> 
> 改变这个没有影响...（在 wlan 网络试过了）
> 按照上面说的，只在手动设置 interface name 且 fake-ip 模式，才下能正常使用tun（试了一下确实是这样）
> 在 redir-host 模式下的log：
> `time="2021-04-01T17:01:39+08:00" level=warning msg="[UDP] dial DIRECT (match RuleSet/LAN) to 172.16.0.2 error: route ip+net: invalid network interface name"`
> (在这之后我把宽带连接重命名为PPPOE并重启了cfw）
> 
> ```
> time="2021-04-01T17:01:53+08:00" level=warning msg="Failed to start Redir UDP Listener: not supported on current platform"
> time="2021-04-01T17:02:06+08:00" level=warning msg="[UDP] dial Final (match Match/) to 224.0.0.251 error: gateway not found"
> ```

跟你一样，仅在fake-ip且手动指定网卡名时tun模式可用，也就是说自动检测对PPPoE拨号的网络环境无效？不知道是BUG还是说只能做到这样。因为经常需要在WLAN和PPPoE间切换，如果每次手动改配置里的网卡名也太麻烦了。

**Comment by Robinrocker** [comment]
> > > @URARUA windows 的 tun 中的 dns-hijack 不用变吧，看下文档：https://docs.cfw.lbyczf.com/contents/tun.html#windows
> > > 又看错人了。。。
> > 
> > 
> > 改变这个没有影响...（在 wlan 网络试过了）
> > 按照上面说的，只在手动设置 interface name 且 fake-ip 模式，才下能正常使用tun（试了一下确实是这样）
> > 在 redir-host 模式下的log：
> > `time="2021-04-01T17:01:39+08:00" level=warning msg="[UDP] dial DIRECT (match RuleSet/LAN) to 172.16.0.2 error: route ip+net: invalid network interface name"`
> > (在这之后我把宽带连接重命名为PPPOE并重启了cfw）
> > ```
> > time="2021-04-01T17:01:53+08:00" level=warning msg="Failed to start Redir UDP Listener: not supported on current platform"
> > time="2021-04-01T17:02:06+08:00" level=warning msg="[UDP] dial Final (match Match/) to 224.0.0.251 error: gateway not found"
> > ```
> 
> 跟你一样，仅在fake-ip且手动指定网卡名时tun模式可用，也就是说自动检测对PPPoE拨号的网络环境无效？不知道是BUG还是说PPPoE自身的限制。因为经常需要在WLAN和PPPoE间切换，如果每次手动改配置里的网卡名也太麻烦了。而且每一次PPPoE断线再连后，需要手动关开一次mixin才能正常连接。

大哥我跟你们问题完全一样，求教一个mixin配置文件

**Comment by Fndroid** [comment]
出口网卡名不太可能叫pppoe

**Comment by plutonemhikari** [comment]
> 出口网卡名不太可能叫pppoe。所有网卡截个图看看吧

是笔记本，有一个内置的WLAN网卡，英特尔的，还有一个usb的以太网网卡，pppoe是在这个以太网网卡上的

**Comment by URARUA** [comment]
> 出口网卡名不太可能叫pppoe。所有网卡截个图看看吧

![image](https://user-images.githubusercontent.com/24853208/113378687-2c300500-93aa-11eb-8b2d-60863d91a01f.png)
是这样的截图吗

**Comment by Fndroid** [comment]
```yaml 
interface-name: "以太网 2"
```

**Comment by plutonemhikari** [comment]
> 出口网卡名不太可能叫pppoe。所有网卡截个图看看吧
如下：
![网卡](https://user-images.githubusercontent.com/62335203/113381140-c72bdd80-93b0-11eb-81fb-877ef5449543.png)

WLAN下完全正常。使用PPPoE连接的话仅fake-ip且手动指定网卡名为PPPoE才可用，若指定网卡名为Ethernet也不可用。假如指定网卡名为以太网网卡的话，日志中显示的源ip为169开头的，如下图：

![屏幕截图 2021-04-02 124413](https://user-images.githubusercontent.com/62335203/113381368-5b964000-93b1-11eb-9232-b6ce8f53c2bb.png)

**Comment by Qing-JiuJiu** [comment]
情况一样，PPPOE下无法正常工作，环境因素，需要在WLAN和PPPoE间之间切换，但在PPPOE时无法工作很麻烦。
![QQ截图20210419082134](https://user-images.githubusercontent.com/77143400/115167068-9eae1e00-a0e8-11eb-9dc7-4b8490b25f2b.png)
![QQ截图20210419082213](https://user-images.githubusercontent.com/77143400/115167074-a2da3b80-a0e8-11eb-99ba-10afcfd9d274.png)

**Comment by 78zhanghao87** [comment]
有同样的问题，但是我的Connections里没有任何往公网地址的链接，和 @Qing-JiuJiu 一样的情况
![图片](https://user-images.githubusercontent.com/30895041/116354582-36b7b000-a82b-11eb-9be3-f1fafdd0f735.png)

**Comment by outlier009** [comment]
网上给出的各种解决方法都试了，仍然不行，和 @Qing-JiuJiu 一样的情况

**Comment by lex0bomb** [comment]
> > 出口网卡名不太可能叫pppoe。所有网卡截个图看看吧
> > 如下：
> > ![网卡](https://user-images.githubusercontent.com/62335203/113381140-c72bdd80-93b0-11eb-81fb-877ef5449543.png)
> 
> WLAN下完全正常。使用PPPoE连接的话仅fake-ip且手动指定网卡名为PPPoE才可用，若指定网卡名为Ethernet也不可用。假如指定网卡名为以太网网卡的话，日志中显示的源ip为169开头的，如下图：
> 
> ![屏幕截图 2021-04-02 124413](https://user-images.githubusercontent.com/62335203/113381368-5b964000-93b1-11eb-9232-b6ce8f53c2bb.png)

port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
cfw-latency-url: http://www.gstatic.com/generate_204
allow-lan: false
mode: Rule
log-level: info
ipv6: false
external-controller: 0.0.0.0:9090
clash-for-android:
  append-system-dns: false
dns:
  enable: true
  enhanced-mode: redir-host
  nameserver:
    - 8.8.8.8
    - 114.114.114.114
interface-name: "Unicom"
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53

**Comment by URARUA** [comment]
> 我的拨号设置的名称是 Unicom 然后手动指定 + redir-host 可以用呀

那么看起来应该是自动检测出口的问题……
现在手动指定出口可以正常使用tun模式了（不管是 fake-ip 还是redir-host ）
我这里发现自动检测出口不会指定PPPOE而是指定到WLAN
这就是问题原因了吧？ @Fndroid

**Comment by 78zhanghao87** [comment]
0.15.4版本，目前fake-ip模式下可用，配置如下
`mixin: # object
  dns:
    enable: true
    enhanced-mode: fake-ip
    nameserver:
      - 8.8.8.8 # 真实请求DNS，可多设置几个
      - 114.114.114.114
  interface-name: PPPoE # 出口网卡名称，或者使用下方的自动检测
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 198.18.0.2:53
    macOS-auto-route: true
    #macOS-auto-detect-interface: true # 自动检测出口网卡`

**Comment by lex0bomb** [comment]
现在从本地拨号改成了光猫拨号 settings里面 出口网卡reset 不指定

**Comment by kmahyyg** [comment]
Same problem here. None of the following settings is working here:
- PPPoE network adapter name + redir-host
- PPPoE network adapter name + fake-ip
- Physical network adapter + fake-ip

`tun` settings as:

```yaml
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53
  macOS-auto-route: true
  macOS-auto-detect-interface: true  
```

**Comment by kmahyyg** [comment]
@Fndroid  Is there any method to show debug level logging of `wintun.dll` ? I wanna check more details about how it detect my internet adapter?

**Comment by lengthmin** [comment]
同出现宽带模式下 TUN 无法联网。

配置如下：

```yml
mixin:
  dns:
    enable: true
    enhanced-mode: redir-host
    nameserver:
      - 223.5.5.5
      - 114.114.114.114
      - 8.8.8.8
      - 1.1.1.1
  interface-name: "ljc"
  tun:
    enable: true
    stack: system
    dns-hijack:
      - 198.18.0.2:53
    auto-route: true
    auto-detect-interface: true
```

网卡如下：
![image](https://user-images.githubusercontent.com/13938334/121779944-b4176400-cbd0-11eb-942c-aaf5a8afe7e4.png)

日志如下：
![image](https://user-images.githubusercontent.com/13938334/121779949-b8dc1800-cbd0-11eb-8c1a-93b660d644d8.png)
