### ISSUE TITLE
tun模式会导致看视频和直播音画不同步。

### ISSUE THREAD

**Issue by lemako** [Fndroid/clash_for_windows_pkg#1797]
信息

 已经从issue搜索过类似问题，并未发现重复
 已经阅读过文档相关问题，并未找到解决办法
 已经尝试更新到最新版本，问题依旧存在
 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）
系统

win10

描述

开启tun模式会导致在线视频音画不同步 播放越久则越明显  无论是直播还是视频都会如此  关闭tun模式则正常

复现
```yaml
mixin: 
   hosts:
     'mtalk.google.com': 108.177.125.188
     'services.googleapis.cn': 74.125.203.94
     'raw.githubusercontent.com': 151.101.76.133
   dns:
     enable: true
     default-nameserver:
       - 223.5.5.5
       - 1.0.0.1
     ipv6: false
     enhanced-mode: redir-host #fake-ip
     nameserver:
       - https://dns.rubyfish.cn/dns-query
       - https://223.5.5.5/dns-query
       - https://dns.pub/dns-query
     fallback:
       - https://1.0.0.1/dns-query
       - https://public.dns.iij.jp/dns-query
       - https://dns.twnic.tw/dns-query
     fallback-filter:
       geoip: true
       ipcidr:
         - 240.0.0.0/4
         - 0.0.0.0/32
         - 127.0.0.1/32
       domain:
         - +.google.com
         - +.facebook.com
         - +.twitter.com
         - +.youtube.com
         - +.xn--ngstr-lra8j.com
         - +.google.cn
         - +.googleapis.cn
         - +.gvt1.com
   tun: 
     enable: true
     stack: gvisor
     dns-hijack:
       - 198.18.0.2:53
     macOS-auto-route: true
     macOS-auto-detect-interface: true # 自动检测出口网卡
```
预期行为
不延迟
日志

截图

其他说明
Wintun也是最新版的  win10也是最新的 tap模式也没有此问题
无
