### ISSUE TITLE
我的win clash不能用了, mac可以, 求帮助

### ISSUE THREAD

**Issue by shawchen123** [Fndroid/clash_for_windows_pkg#1820]
我买的qianglie的服务, 然后最近win系统上的clash全都不能用了, 节点都是Timeout状态, 然后重新用订阅地址更新了一下, 无法更新成功. 只能用mac上的clashX.
是不是软件需要设置什么, 我是小白, 我一脸蒙蔽, 我之前都是用得好好的, 我也不想折腾, 有没有大佬救救我, 帮我看看.

**Comment by yi-Xu-0100** [comment]
@shawchen123 重新同步下时间试试

**Comment by shawchen123** [comment]
> @ shawchen123重新同步下时间试试

谢谢, 但是你是指同步电脑系统的时间吗?

**Comment by yi-Xu-0100** [comment]
@shawchen123 是的，如果不用 clash 是否能够上网？在 global 模式下能否上网？

**Comment by shawchen123** [comment]
> @ shawchen123是的，如果不用clash是否能够上网？在global

我同步了, 还是不行, 有一两个节点显示一两百毫秒的延时, 但是还是打不开外网, 不用clash是可以上网的, 用global模式也不可以上外网.

**Comment by shawchen123** [comment]
> @ shawchen123是的，如果不用clash是否能够上网？在global

我同步了，还是不行，有几个节点显示一两百毫秒的延迟，但是还是打不开外网，不用clash是可以上网的，用global模式也不可以上外网。而且我用最新的clash更新订阅文件, 但是在选择节点页面看不到任何节点, 提示我no proxy in this profile

**Comment by yi-Xu-0100** [comment]
@shawchen123 你确定你的订阅链接还有效吗？怕不是跑路了？去浏览器打开订阅链接看看？

**Comment by shawchen123** [comment]
> @ shawchen123你确定自己的订阅链接还有效吗？怕不是跑路了？去浏览器打开订阅链接看看？

应该没问题呀, 因为我的mac上可以用, 然后为了确保订阅有效, 我特意去网站上复制的最新订阅地址.

**Comment by yi-Xu-0100** [comment]
@shawchen123 去 home directory 删除全部文件，重启软件，重新订阅试试

**Comment by shawchen123** [comment]
> @ shawchen123去主目录删除全部文件，重启软件，重新订阅试试

我都卸载软件删除目录重装了还是不行.

**Comment by northword** [comment]
有无可能是你这个网络dns问题，加入dns相关的字段试试呢？
因为我这儿遇到过类似的问题，cfw上全timeout，cfa正常，但是我这不是一个网络环境，同网络下cfa也不正常，排查了一下是电脑连的网的问题。

**Comment by shawchen123** [comment]
> 有无可能是你这个网络dns问题，加入dns相关的字段试试呢？
> 因为我这儿遇到过类似的问题，cfw上全timeout，cfa正常，但是我这不是一个网络环境，同网络下cfa也不正常，排查了一下是电脑连的网的问题。

对不起，才看到你的回复，我是小白，不知道您说的这个加入dns字段是什么意思，怎么操作，求详解。

**Comment by northword** [comment]
> > 有无可能是你这个网络dns问题，加入dns相关的字段试试呢？
> > 因为我这儿遇到过类似的问题，cfw上全timeout，cfa正常，但是我这不是一个网络环境，同网络下cfa也不正常，排查了一下是电脑连的网的问题。
> 
> 对不起，才看到你的回复，我是小白，不知道您说的这个加入dns字段是什么意思，怎么操作，求详解。

在你的`config.yaml`里添加如下内容
```yaml
dns:
  enable: true # 是否启用dns false
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host # 模式：redir-host或fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: # fake ip 白名单列表，如果你不知道这个参数的作用，请勿修改
    - '*.lan'
    - localhost.ptlogin2.qq.com
  nameserver:
    - 223.5.5.5 # 阿里DNS
    - 180.76.76.76 # 百度DNS
    - 119.29.29.29 # 腾讯DNS
    - 117.50.11.11 # ONE DNS拦截版 恶意网站拦截、广告过滤
    - 117.50.10.10 # ONE DNS纯净版 直接返回其真实的响应结果
    - 114.114.114.114 # 114DNS
    - https://dns.alidns.com/dns-query # 阿里 DoH DNS
    - https://doh.360.cn/dns-query # 360 DoH DNS
  fallback:
    - 8.8.8.8 # 谷歌DNS
    - 1.1.1.1 # Cloudflare DNS
    - tls://dns.rubyfish.cn:853
    - tls://1.0.0.1:853
    - tls://dns.google:853
    - https://dns.rubyfish.cn/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true # 默认
    ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
      - 240.0.0.0/4
```

或者，你可以在 [https://blog.northword.cn/sub-web/](https://blog.northword.cn/sub-web/) 进行订阅转换，把你的订阅地址粘贴到`订阅链接`里，其余保持不变，点`生成订阅链接`，然后导入CFW（这个订阅转换用的后端配置中我已经添加了DNS的内容）。

**注意我只是猜测，并不确定可以解决你的问题哈**
