### ISSUE TITLE
[Question] is it possible for dns to listen on an ipv6 address

### ISSUE THREAD

**Issue by Omoeba** [Fndroid/clash_for_windows_pkg#187]
Is it possible for dns to listen on ::1 as well as 127.0.0.1?

**Comment by Fndroid** [comment]
```yaml
dns:
  enable: true
  listen: "[::1]:53"
```
