### ISSUE TITLE
手机版的可以用但是win10的更新以后就没有反应了

### ISSUE THREAD

**Issue by tomchenzi** [Fndroid/clash_for_windows_pkg#1872]
- 
![3](https://user-images.githubusercontent.com/65750232/117573060-88ecb100-b108-11eb-83bd-050ad9fb98d7.png)
![1](https://user-images.githubusercontent.com/65750232/117573065-8b4f0b00-b108-11eb-9a98-dcfafbd0dc2a.png)
![2](https://user-images.githubusercontent.com/65750232/117573067-8d18ce80-b108-11eb-9783-5963c865c34a.png)
参考图

**Comment by yi-Xu-0100** [comment]
@tomchenzi 日志？

**Comment by tomchenzi** [comment]
![N@C3~T_7276)ZZ~WP}{1V%6](https://user-images.githubusercontent.com/65750232/117573170-1cbe7d00-b109-11eb-8ac2-887bd95eadef.png)

**Comment by tomchenzi** [comment]
@yi-Xu-0100

**Comment by yi-Xu-0100** [comment]
@tomchenzi 似乎没有进代理，配置中是否有 dns 字段，将 enable 设置为 false 呢？

**Comment by tomchenzi** [comment]
配置在哪里看呢？ 我刚用 不好意思

**Comment by tomchenzi** [comment]
@yi-Xu-0100

**Comment by yi-Xu-0100** [comment]
@tomchenzi ![image](https://user-images.githubusercontent.com/25523606/117573295-a2422d00-b109-11eb-8086-36e45359736c.png)

**Comment by yi-Xu-0100** [comment]
你可以去这个地址，用记事本打开这个文件 ![image](https://user-images.githubusercontent.com/25523606/117573335-de758d80-b109-11eb-8e85-bc914746f76a.png)

**Comment by tomchenzi** [comment]
@yi-Xu-0100 
![Uploading Y%D~$UJRCB0OLIRSUN1HTK9.png…]()

**Comment by tomchenzi** [comment]
@yi-Xu-0100 
![Y%D~$UJRCB0OLIRSUN1HTK9](https://user-images.githubusercontent.com/65750232/117573405-344a3580-b10a-11eb-864d-00b52194d23e.png)

**Comment by yi-Xu-0100** [comment]
@tomchenzi 把这个回复删掉吧，有节点信息。。。把这个 `enable: true` 改为 false 试试

![image](https://user-images.githubusercontent.com/25523606/117573432-56dc4e80-b10a-11eb-91fa-d07aee1bdde8.png)

**Comment by tomchenzi** [comment]
@yi-Xu-0100  好的谢谢大佬提醒

**Comment by tomchenzi** [comment]
改成了false也没有反应 @yi-Xu-0100

**Comment by yi-Xu-0100** [comment]
@tomchenzi 重新打开日志，日志里面没有东西？用无痕访问 google.com 也没用？

**Comment by tomchenzi** [comment]
@yi-Xu-0100    日志还是一样的    用无痕访问也没用
![6](https://user-images.githubusercontent.com/65750232/117573562-2ea11f80-b10b-11eb-98b0-30fe158a3fac.png)

**Comment by yi-Xu-0100** [comment]
![image](https://user-images.githubusercontent.com/25523606/117573581-48426700-b10b-11eb-8660-f07aa9c4719a.png)

```yml
mixin: # object
  dns:
    enable: true
    ipv6: false
    enhanced-mode: redir-host
    use-hosts: true
    fake-ip-filter:
      - 'dns.msftncsi.com'
      - 'www.msftncsi.com'
      - 'www.msftconnecttest.com'
      - '+.qq.com'
      - '+.music.163.com'
      - '+.music.162.com'
    default-nameserver:
      - 119.29.29.29
      - 114.114.114.114
      - 8.8.8.8
    nameserver:
      - 119.29.29.29
      - 223.5.5.5
      - 8.8.8.8
      - 114.114.114.114
      - 1.1.1.1
    fallback:
      - 'https://1.1.1.1/dns-query'
      - 'https://162.159.36.1/dns-query'
      - 'https://162.14.13.12/dns-query'
      - 'tls://dns.rubyfish.cn:853'
      - 'tls://1.0.0.1:853'
      - 'tls://dns.google:853'
    fallback-filter:
      geoip: true
      ipcidr:
        - 0.0.0.0/32
        - 127.0.0.0/8
        - 240.0.0.0/4
```
将图片中的选项的内容改成上面的内容，然后打开

![image](https://user-images.githubusercontent.com/25523606/117573611-7aec5f80-b10b-11eb-8100-92bce9fa615b.png)
