### ISSUE TITLE
开启tun模式无法打开raw.githubusercontent*，开启系统代理就可以访问，Google啥的没问题

### ISSUE THREAD

**Issue by aLIEz-xue** [Fndroid/clash_for_windows_pkg#1883]
例：https://raw.githubusercontent.com/Fndroid/clash_for_windows_pkg/master/README.md
![image](https://user-images.githubusercontent.com/59567929/118160254-aabf9e00-b450-11eb-9692-0050fc7750ce.png)
clash配置：
![image](https://user-images.githubusercontent.com/59567929/118160631-21f53200-b451-11eb-9140-35345d19d23c.png)
![image](https://user-images.githubusercontent.com/59567929/118160708-3fc29700-b451-11eb-8186-9bb8252b621e.png)
Mixin配置：
```yaml
mixin:
 dns:
   enable: true                   # set true to enable dns (default is false)
   ipv6: false                    # default is false
   listen: 0.0.0.0:53
   enhanced-mode: redir-host      # or fake-ip
   fake-ip-range: 198.18.0.1/16   # if you don't know what it is, don't change it
   use-hosts: true                # lookup hosts and return IP record
   fake-ip-filter:                # fake ip white domain list, aka Always Real IP
     - '*.lan'
     - localhost.ptlogin2.qq.com
     - "dns.msftncsi.com"
     - "www.msftncsi.com"
     - "www.msftconnecttest.com"
   nameserver:
     - 223.5.5.5                  # 阿里DNS
     - 114.114.114.114            # 114DNS   
   fallback:                      # concurrent request with nameserver, 
     - 1.1.1.1                    # cloudflare
     - 8.8.8.8                    # google
   fallback-filter: 
     geoip: true                  # default    
     ipcidr:                      # ips in these subnets will be considered polluted
       - 240.0.0.0/4
 tun:
   enable: true
   stack: gvisor
   dns-hijack:
     - 198.18.0.2:53
   macOS-auto-route: true
   macOS-auto-detect-interface: true
```
