### ISSUE TITLE
proxy-groups 下 use 和 proxies 共存 url-test 模式会忽略 proxies 下的代理

### ISSUE THREAD

**Issue by Jial08** [Fndroid/clash_for_windows_pkg#1922]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ ] 已经尝试更新到最新版本，问题依旧存在
- [ ] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

win10教育版1909，版本：18363.1256

**描述**

proxy-groups 的同一个 name 下有 use 和 proxies 且 type 为 url-test 时，不会测速和选择 proxies 下的节点

**复现**

1. 当用如下配置时：
```yaml
proxies:
  - name: self
    ...

proxy-groups:
  - name: ♻️ auto
    type: url-test
    use:
      - other
    proxies:
      - self
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

proxy-providers:
  other:
    type: http
    url: ...
    path: ./other.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
```

效果如下：
![Snipaste_2021-05-27_13-25-31](https://user-images.githubusercontent.com/25861104/119770757-37f20080-beef-11eb-98a6-89b7d71b3f29.png)
即 self 节点不测数也不选择

2. 当把 proxies 配置写入 my.yaml  文件中时，如下配置：
```yaml
proxy-groups:
  - name: ♻️ auto
    type: url-test
    use:
      - my
      - other
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

proxy-providers:
  my:
    type: file
    path: ./my.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  other:
    type: http
    url: ...
    path: ./other.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
```
效果如下：
![image](https://user-images.githubusercontent.com/25861104/119772605-075f9600-bef2-11eb-85b7-b36794f4f303.png)

测速了也选择了最快的节点 self

**预期行为**

希望在 use 和 proxies 共存时也能达到 2 的效果
