### ISSUE TITLE
reply状态下出现udp流量规则失效

### ISSUE THREAD

**Issue by hunshcn** [Fndroid/clash_for_windows_pkg#1935]
**信息**

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 专业版 20H2 19042.985

**描述**

reply状态下出现udp流量规则失效

**复现**

当前部分配置内容

```yaml
proxy-groups:
  -
    name: '🔰国外流量'
    type: relay
    proxies:
      - '前置代理'
      - '国外代理'
  -
    name: '🚀直接连接'
    type: relay
    proxies:
      - '前置代理'
  -
    name: '前置代理'
    type: select
    proxies:
      - 'server1'
      - 'server2'

rules:
  - MATCH,🚀直接连接
```
**当前表现**

在MATCH为`🚀直接连接`或`🔰国外流量`，在Connections查看连接，udp流量都走的是DIRECT

当MATCH为`前置代理`时，UDP流量可以被前置代理接管

**预期行为**

在MATCH为`🚀直接连接`或`🔰国外流量`，UDP流量应该走前置代理

**日志**

**截图**

### MATCH为前置代理
![MATCH为前置代理](https://user-images.githubusercontent.com/11679819/120428628-93683680-c3a6-11eb-87a3-4bbfe6c04b3c.png)
---
### MATCH为🚀直接连接
![MATCH为🚀直接连接](https://user-images.githubusercontent.com/11679819/120428692-b692e600-c3a6-11eb-9c79-8b5b36a7b13e.png)

**其他说明**
