### ISSUE TITLE
v0.15.9 Providers更新失败

### ISSUE THREAD

**Issue by asdfj2381k** [Fndroid/clash_for_windows_pkg#1947]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)  win7 64

**描述**
![image](https://user-images.githubusercontent.com/56584082/120909592-13ddae80-c6a9-11eb-872c-6a78da33150d.png)

```
rule-providers:
  Telegram:
    type: http
    behavior: classical
    path: ./RuleSet/Extra/Telegram.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Telegram/Telegram.yaml
    interval: 600
  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./RuleSet/Extra/ChinaIP.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 600
```

这些ruleset的url，单独拿出来浏览器是可以访问成功的，但是在clash里面不知道为什么就更新失败。

期望的结果：更新成功。
