### ISSUE TITLE
macOS tun address already in use

### ISSUE THREAD

**Issue by NonXZhu** [Fndroid/clash_for_windows_pkg#1952]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
macOS 11.4

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
无法正常使用tun

**复现**

[//]: # (请描述复现问题的步骤)

1. 安装'Service Mode'
2. 进入'Settings'
3. 点击'Edit YAML Profile Mixin'
4. 使用如下配置
```yaml
mixin:
  dns:
    enable: true
    enhanced-mode: redir-host
    nameserver:
      - 114.114.114.114 # 真实请求DNS，可多设置几个
  # interface-name: en0 # 出口网卡名称，或者使用下方的自动检测
  tun:
    enable: true
    stack: system # 或 gvisor
    dns-hijack: # DNS劫持设置为系统DNS
      - 114.114.114.114 # 可任意设置，但为了保证CFW关闭后能不影响联网，建议设置真实能访问的DNS服务器
    macOS-auto-route: true
    macOS-auto-detect-interface: true # 自动检测出口网卡
```
5. 打开'Mixin'，关闭'System Proxy'
6. 触发问题

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image](https://user-images.githubusercontent.com/31027139/121042857-a768c980-c7e6-11eb-9e81-99ae8fe572ae.png)
![image](https://user-images.githubusercontent.com/31027139/121042974-c8c9b580-c7e6-11eb-8679-3e944ce39c03.png)

**其他说明**

[//]: # (其他补充内容)

本想配合AdGuard一起使用，决定尝试tun + upstream proxy，不过tun就失败了
