### ISSUE TITLE
同vmess配置v2ray正常，CFW超时

### ISSUE THREAD

**Issue by ColorfulNight** [Fndroid/clash_for_windows_pkg#1969]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

Windows 10 Version 20H2

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

同vmess配置v2ray正常，CFW超时，尝试使用各种配置转换依然超时

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入 `Proxies` 
2. 选择我自己唯一的 `vmess` 节点；
3. 点击 `check`；
4. 很快就显示 `timeout`;

按照其他 issus 提供的思路：
1. 时间设置处同步系统时间，问题依旧；
2. 修改 `skip-cert-verify` 的 `true`、`false`或者直接注释，问题依旧；
3. 使用网上提供的各种配置转换工具/网站，转出来配置会带有不应该有的 `ws-path` 等属性，删除与否都为题依旧。

**预期行为**

[//]: # (清晰地描述期望看到的行为)

正常显示连接延时

**日志**

[//]: # (上传触发问题对应的日志文件)

日志中无任何有用信息，且主页处的日志级别一直是 `debug`

```log
time="2021-06-13T20:22:47+08:00" level=info msg="RESTful API listening at: 127.0.0.1:63669"
time="2021-06-13T20:22:47+08:00" level=info msg="Mixed(http+socks5) proxy listening at: :7890"
time="2021-06-13T20:22:47+08:00" level=info msg="Start initial compatible provider PROXY"
time="2021-06-13T20:22:47+08:00" level=info msg="Start initial compatible provider Hijacking"
time="2021-06-13T20:22:47+08:00" level=info msg="Start initial compatible provider HKMTMedia"
time="2021-06-13T20:22:47+08:00" level=info msg="Start initial compatible provider GlobalMedia"
time="2021-06-13T20:22:47+08:00" level=info msg="Start initial compatible provider Apple"
time="2021-06-13T20:22:47+08:00" level=info msg="Start initial compatible provider Final"
time="2021-06-13T20:33:48+08:00" level=info msg="[TCP] 127.0.0.1:58839 --> www.google.com match DomainKeyword(google) using PROXY[BigDogTemp]"
time="2021-06-13T20:33:49+08:00" level=info msg="[TCP] 127.0.0.1:60300 --> www.google.com match DomainKeyword(google) using PROXY[BigDogTemp]"
time="2021-06-13T20:33:50+08:00" level=info msg="[TCP] 127.0.0.1:53389 --> www.google.com match DomainKeyword(google) using PROXY[BigDogTemp]"
time="2021-06-13T20:33:51+08:00" level=info msg="[TCP] 127.0.0.1:58660 --> www.google.com match DomainKeyword(google) using PROXY[BigDogTemp]"
time="2021-06-13T20:33:56+08:00" level=info msg="[TCP] 127.0.0.1:53861 --> www.google.com match DomainKeyword(google) using PROXY[BigDogTemp]"
time="2021-06-13T20:33:58+08:00" level=info msg="[TCP] 127.0.0.1:56404 --> www.google.com match DomainKeyword(google) using PROXY[BigDogTemp]"
time="2021-06-13T20:34:01+08:00" level=info msg="[TCP] 127.0.0.1:57861 --> www.google.com match DomainKeyword(google) using PROXY[BigDogTemp]"
time="2021-06-13T20:34:02+08:00" level=info msg="[TCP] 127.0.0.1:49673 --> www.google.com match DomainKeyword(google) using PROXY[BigDogTemp]"
```

**截图**

[//]: # (如果可以，请提供对应问题的截图)

v2Ray配置，各种信息已打码

![图片](https://user-images.githubusercontent.com/9924394/121807570-42e6b800-cc87-11eb-8837-abed7e7e00f4.png)

**其他说明**

[//]: # (其他补充内容)

v2ray 导出配置中的 outbounds：
```
"outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "ltytoto.tmtl",
            "port": 486,
            "users": [
              {
                "id": "d0bb6d97-559f-43cd-b3c5-c8c94ea8e869",
                "alterId": 23,
                "email": "t@t.tt",
                "security": "auto"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {}
      },
      "mux": {
        "enabled": true,
        "concurrency": 8
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "http"
        }
      }
    }
  ],
```

CFW 配置部分：

```
proxies:
  # vmess
  # cipher support auto/aes-128-gcm/chacha20-poly1305/none
  - name: "BigDogTemp"
    type: vmess
    server: ltytoto.tmtl
    port: 486
    uuid: d0bb6d97-559f-43cd-b3c5-c8c94ea8e869
    alterId: 23
    cipher: auto
    # udp: true
    # tls: false
    # skip-cert-verify: false
    # servername: ltytoto.tmtl # priority over wss host
    network: ws
    # ws-path: /
    # ws-headers:
    #   Host: hyoo.ml
```
