### ISSUE TITLE
tun启用redir-host时的问题。

### ISSUE THREAD

**Issue by lemako** [Fndroid/clash_for_windows_pkg#1978]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [X ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [X ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [X ] 已经尝试更新到最新版本，问题依旧存在
- [ X] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

**描述** WIN10 21H1

[//]: # (请具体并清楚地描述遇到的问题)

**复现**    
偶发

启用redir-host时，进入所有需要使用网络的程序都会延迟，在connections里查看情况时，发现所有的连接都变成了IP形式，如 
 239.255.255.250:1900
 
185.199.111.154:443

改用fake-ip模式 亦或者打开系统代理则无此问题

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志** 关了

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)
```yaml
mixin:
 dns:
   enable: true                   # set true to enable dns (default is false)
   ipv6: false                    # default is false
   listen: 0.0.0.0:53
   enhanced-mode: redir-host     # redir-host  or fake-ip
   fake-ip-range: 198.18.0.1/16   # if you don't know what it is, don't change it
   use-hosts: true                # lookup hosts and return IP record
   fake-ip-filter:                # fake ip white domain list, aka Always Real IP
     - '*.lan'
     - localhost.ptlogin2.qq.com
     - "dns.msftncsi.com"
     - "www.msftncsi.com"
     - "www.msftconnecttest.com"
   nameserver:
     - 114.114.114.114            # 114DNS   
     - 223.5.5.5                  # 阿里DNS
     - 119.29.29.29
   fallback:                      # concurrent request with nameserver, 
     - tls://1.1.1.1:853
     - https://1.1.1.1/dns-query
     - https://dns.google/dns-query
     - tls://dns.google:853
   fallback-filter: 
     geoip: true                  # default    
     ipcidr:                      # ips in these subnets will be considered polluted
       - 240.0.0.0/4
       - 0.0.0.0/32
       - 127.0.0.0/8
 tun:
   enable: true
   stack: gvisor
   dns-hijack:
     - 198.18.0.2:53
   macOS-auto-route: true
   macOS-auto-detect-interface: true
```

**Comment by brianler** [comment]
Win10企业版 20h2，用以下配置可以正常使用Tun模式。之前我也走过很多坑，在Windows下好像是要手动指定出口网卡名称才可以正常使用(见以下代码)。本来网卡名是“以太网”，我怕中文名称有影响，改了个“100Gbps”的名字:joy:。如要重命名网卡，在` 网络和共享中心-更改适配器设置 `里面找到网卡，右键重命名即可。
``` yaml
mixin:
  dns:
    enable: true
    enhanced-mode: redir-host
    nameserver:
      - 119.29.29.29
      - 223.5.5.5
      - 1.0.0.1
      - 8.8.4.4
  interface-name: 100Gbps # 手动指定出口网卡名称(即那个接网线物理网卡的名称)
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 198.18.0.2:53
    auto-route: true
    #auto-detect-interface: true # 自动检测出口网卡，Windows下似乎无效，所以注释掉了使用上面的手动指定
```
