### ISSUE TITLE
本客户端使用透过Cloudflare CDN中转的服务，触发ban ip

### ISSUE THREAD

**Issue by 1-1-2** [Fndroid/clash_for_windows_pkg#2007]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
客户端版本：Clash for Windows  0.16.0 / 0.15.8 / 0.15.5
系统A：Microsoft Windows [版本 10.0.19041.1052]
系统B：macOS Big Sur 11.4 ( 20F71 )

**描述**

[//]: # (请具体并清楚地描述遇到的问题)

配置方式为 vmess+ws+tls, 通过 Cloudflare CDN 中转，已稳定使用近一年。
于2021年6月29日起，发现使用 Clash for Windows 向 CF CDN 发起请求时，会触发ip ban——具体表现为约数分钟内，与我同一拨号网络下的所有设备（有线+无线均有测试，也在路由端尝试过直接 curl），无法通过 CF 任一 (Anycast) CDN 节点收发数据。
同样的节点配置，在V2RAYN(G)和CLASH FOR ANDROID中正常使用时未有触发。
复现方式详下

**复现**

[//]: # (请描述复现问题的步骤)

已测试复现ISP&地域：联通、电信、移动@X圳

1. curl 监测脚本，保存为 bat 文件并运行
功能：通过8个不同的 cf cdn 节点请求https内容，检查返回状态码
```batch
@echo off & Setlocal Enabledelayedexpansion
SET IP[00]=104.19.5.198 
SET IP[01]=104.19.48.92 
SET IP[02]=104.19.32.148
SET IP[03]=104.19.104.11
SET IP[04]=104.19.63.240
SET IP[05]=104.19.84.192
SET IP[06]=104.19.13.59 
SET IP[07]=104.19.68.117
SET DOMAIN=skk.moe

:Loop
FOR /F "usebackq delims== tokens=2" %%I IN (`SET IP`) DO (
    REM set /p="%%I | " < NUL
    curl --silent --max-time 4 --resolve "%DOMAIN%:443:%%I" --write-out "%%I\t|  [%%{http_code}] %%{time_total}s\n" https://%DOMAIN%/ -o NUL
)
goto :Loop
```

2. 测试配置，保存为 yaml 文件
描述：向随意填写的 cf cdn 节点发送 vmess+tls 数据包，这里面除了IP必须是CF的以外，其他项如uuid甚至无需是正确可用的。
```yaml
proxies:
  - {name: CDN, server: 104.21.21.21, port: 443, type: vmess, uuid: eb6bc990-d646-4222-b8b2-3ee76ac6d0ce, alterId: 0, cipher: auto, tls: true, network: ws, ws-path: /ray}

proxy-groups:
  - {name: 通道, type: select, proxies: [CDN, DIRECT]}

rules:
- MATCH,DIRECT

```

3. 全新安装 Clash for Windows，导入2中配置文件并激活使用，无需启用 system proxy 等。
4. Proxies 面版中，点击一次（或多次）延迟测试
5. 数秒后触发ban，无法通过CF任一节点收发任一以CF为CDN的网站的数据。（具体表现为第一次握手即 timeout）

**预期行为**

[//]: # (清晰地描述期望看到的行为)

1. 点击延迟测试前，可以正常通过CDN节点访问http(s)内容，返回 200
2. 点击延迟测试后（一次或多次），开始返回000超时。此时，网络下所有设备都浏览器访问任一在CF CDN上的网站也会无响应。约2~5分钟恢复正常。

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![2021年6月30日22：59](https://user-images.githubusercontent.com/50569812/123985186-d6deb080-d9f7-11eb-9230-2cb3b37456d2.gif)

**其他说明**

[//]: # (其他补充内容)
近期升级到了0.16.0客户端，之后没几天这个情况就出现了。之前很长一段时间都是使用0.15.8的客户端，无奈之下以为是新版的BUG，所以截图中是从最新版的0.16.0回滚到了0.15.8测试的。但经测试两个版本的效果未有明显差别，可以排除。甚至为了排除是0508版本内核的问题，我还尝试了0.15.5版客户端，情况依旧。
其实这里最奇怪的是，测试一圈下来其他也使用clash内核的客户端没有类似的情况，是不是小猫咪客户端有什么特征可以被识别？能力有限，分析不出来。请各位大佬不吝赐教。
