### ISSUE TITLE
tun透明代理，Logs疯狂输出DNS nameserver数据，所有ipv4节点无法使用

### ISSUE THREAD

**Issue by BlademasterQAQ** [Fndroid/clash_for_windows_pkg#2015]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows10 2004

[//]: # (平台及版本号)

**描述**
使用TUN模式透明代理出现问题，Logs 疯狂出现nameserver的数据包，CPU占用100%，昨天相同配置下还是正常的。
一小部分的Log如下：
```
223.5.5.5 match GeoIP(CN) using 🎯 全球直连[DIRECT]"
time="2021-07-02T20:49:16+08:00" level=info msg="[UDP] 192.168.2.244:59543 --> 8.8.8.8 doesn't match any rule using DIRECT"
time="2021-07-02T20:49:16+08:00" level=info msg="[UDP] 192.168.2.244:50659 --> 114.114.114.114 match GeoIP(CN) using 🎯 全球直连[DIRECT]"
time="2021-07-02T20:49:16+08:00" level=info msg="[UDP] 192.168.2.244:50660 --> 223.5.5.5 match GeoIP(CN) using 🎯 全球直连[DIRECT]"
time="2021-07-02T20:49:16+08:00" level=info msg="[UDP] 192.168.2.244:50661 --> 8.8.8.8 doesn't match any rule using DIRECT"
time="2021-07-02T20:49:16+08:00" level=info msg="[UDP] 192.168.2.244:50662 --> 114.114.114.114 match GeoIP(CN) using 🎯 全球直连[DIRECT]"
time="2021-07-02T20:49:16+08:00" level=info msg="[UDP] 192.168.2.244:50663 --> 223.5.5.5 match GeoIP(CN) using 🎯 全球直连[DIRECT]"
```
其中的8.8.8.8、114、223等ip均为tun模式配置中dns nameserver的ip地址。（192.168.2.244是运行此CFW的Windows的ip）

**尝试过：更新到最新的0.16.1版本的CFW，重启电脑，卸载安装Service Mode，更新为2021.6.25版本的Wintun.dll重新安装Service Mode，根据其他issue修改tun配置如下：**
```
mixin:
  dns:
    enable: true
    enhanced-mode: redir-host
    nameserver:
      - 119.29.29.29
      - 223.5.5.5
      - 1.0.0.1
      - 8.8.4.4
  interface-name: 以太网 # 手动指定出口网卡名称(即那个接网线物理网卡的名称)
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 198.18.0.2:53
    auto-route: true
    #auto-detect-interface: true # 自动检测出口网卡，Windows下似乎无效，所以注释掉了使用上面的手动指定
```
**均未能解决问题。**

[//]: # (请具体并清楚地描述遇到的问题)

**复现**
安装Service Mode，在Mimix中增加 https://docs.cfw.lbyczf.com/contents/tun.html#windows 中的配置，开启Mimix。

[//]: # (请描述复现问题的步骤)
