### ISSUE TITLE
0.16.2 版，Steam 商店、社区无法加载

### ISSUE THREAD

**Issue by Maasea** [Fndroid/clash_for_windows_pkg#2035]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows10 20H2

**描述**

配置文件未更改，更新到最新版本（0.16.2）后Steam商店和社区无法加载。降级回0.16.0正常。
Steam 网页端正常加载

[//]: # (请具体并清楚地描述遇到的问题)

**复现**

使用Clash 系统代理打开steam ，100%复现

**预期行为**

开启系统代理后正常启动steam

**日志**

日志似乎无异常

```
time="2021-07-12T10:56:11+08:00" level=info msg="RESTful API listening at: 127.0.0.1:62061"
time="2021-07-12T10:56:11+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2021-07-12T10:56:11+08:00" level=warning msg="[TCP] dial DIRECT to raw.githubusercontent.com error: lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2021-07-12T10:56:11+08:00" level=warning msg="[TCP] dial DIRECT to raw.githubusercontent.com error: lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
time="2021-07-12T10:56:11+08:00" level=info msg="[TCP] 127.0.0.1:62319 --> api.github.com doesn't match any rule using DIRECT"
time="2021-07-12T10:56:11+08:00" level=info msg="Start initial compatible provider HK"
time="2021-07-12T10:56:11+08:00" level=info msg="Start initial compatible provider PROXY"
time="2021-07-12T10:56:11+08:00" level=info msg="Start initial compatible provider Streaming"
time="2021-07-12T10:56:11+08:00" level=info msg="Start initial compatible provider Finally"
time="2021-07-12T10:56:11+08:00" level=info msg="Start initial compatible provider Others"
time="2021-07-12T10:56:11+08:00" level=info msg="Start initial compatible provider SG"
time="2021-07-12T10:56:11+08:00" level=info msg="Start initial compatible provider JP"
time="2021-07-12T10:56:11+08:00" level=info msg="Start initial compatible provider US"
time="2021-07-12T10:56:11+08:00" level=info msg="Start initial rule provider StreamingCN"
time="2021-07-12T10:56:11+08:00" level=info msg="Start initial rule provider China"
time="2021-07-12T10:56:11+08:00" level=info msg="Start initial rule provider ChinaIP"
time="2021-07-12T10:56:11+08:00" level=info msg="Start initial rule provider Unbreak"
time="2021-07-12T10:56:11+08:00" level=info msg="Start initial rule provider Streaming"
time="2021-07-12T10:56:11+08:00" level=info msg="Start initial rule provider Global"
time="2021-07-12T10:56:16+08:00" level=warning msg="[TCP] dial DIRECT to 91.108.56.191 error: dial tcp4 91.108.56.191:80: i/o timeout"
time="2021-07-12T10:56:16+08:00" level=warning msg="[TCP] dial DIRECT to 91.108.56.191 error: dial tcp4 91.108.56.191:443: i/o timeout"
time="2021-07-12T10:56:16+08:00" level=info msg="[TCP] 127.0.0.1:59853 --> 91.108.56.191 match RuleSet(Global) using PROXY[香港 HK 01]"
time="2021-07-12T10:56:16+08:00" level=info msg="[TCP] 127.0.0.1:59855 --> 91.108.56.191 match RuleSet(Global) using PROXY[香港 HK 01]"
time="2021-07-12T10:56:24+08:00" level=debug msg="[DNS] redirector.gvt1.com --> 203.208.41.97"
time="2021-07-12T10:56:24+08:00" level=info msg="[TCP] 127.0.0.1:59860 --> redirector.gvt1.com match RuleSet(ChinaIP) using DIRECT"
time="2021-07-12T10:56:24+08:00" level=info msg="[TCP] 127.0.0.1:59858 --> ipv6check-http.steamcontent.com match DomainKeyword(ipv6) using DIRECT"
time="2021-07-12T10:56:24+08:00" level=debug msg="[DNS] media.st.dl.pinyuncloud.com --> 39.134.70.57"
time="2021-07-12T10:56:24+08:00" level=info msg="[TCP] 127.0.0.1:59862 --> media.st.dl.pinyuncloud.com match RuleSet(ChinaIP) using DIRECT"
time="2021-07-12T10:56:24+08:00" level=info msg="[TCP] 127.0.0.1:59864 --> 91.108.56.191 match RuleSet(Global) using PROXY[香港 HK 01]"
time="2021-07-12T10:56:26+08:00" level=info msg="[TCP] 127.0.0.1:59866 --> 91.108.56.191 match RuleSet(Global) using PROXY[香港 HK 01]"
time="2021-07-12T10:56:36+08:00" level=info msg="[TCP] 127.0.0.1:59868 --> api.steampowered.com match RuleSet(China) using DIRECT"
time="2021-07-12T10:56:37+08:00" level=debug msg="[DNS] steamcdn-a.akamaihd.net --> 23.55.47.228"
time="2021-07-12T10:56:37+08:00" level=info msg="[TCP] 127.0.0.1:59870 --> steamcdn-a.akamaihd.net match Match() using Finally[香港 HK 01]"
time="2021-07-12T10:56:37+08:00" level=debug msg="[DNS] steam-chat.com --> 104.85.201.149"
time="2021-07-12T10:56:37+08:00" level=info msg="[TCP] 127.0.0.1:59872 --> steam-chat.com match Match() using Finally[香港 HK 01]"
time="2021-07-12T10:56:37+08:00" level=debug msg="[DNS] steam-chat.com --> 104.85.201.149"
time="2021-07-12T10:56:37+08:00" level=info msg="[TCP] 127.0.0.1:59874 --> steam-chat.com match Match() using Finally[香港 HK 01]"
time="2021-07-12T10:56:37+08:00" level=info msg="[TCP] 127.0.0.1:59876 --> store.steampowered.com match RuleSet(China) using DIRECT"
time="2021-07-12T10:56:37+08:00" level=info msg="[TCP] 127.0.0.1:59883 --> community.akamai.steamstatic.com match DomainSuffix(steamstatic.com) using PROXY[香港 HK 01]"
time="2021-07-12T10:56:37+08:00" level=info msg="[TCP] 127.0.0.1:59882 --> community.akamai.steamstatic.com match DomainSuffix(steamstatic.com) using PROXY[香港 HK 01]"
time="2021-07-12T10:56:37+08:00" level=info msg="[TCP] 127.0.0.1:59879 --> community.akamai.steamstatic.com match DomainSuffix(steamstatic.com) using PROXY[香港 HK 01]"
time="2021-07-12T10:56:37+08:00" level=info msg="[TCP] 127.0.0.1:59881 --> community.akamai.steamstatic.com match DomainSuffix(steamstatic.com) using PROXY[香港 HK 01]"
time="2021-07-12T10:56:37+08:00" level=info msg="[TCP] 127.0.0.1:59878 --> community.akamai.steamstatic.com match DomainSuffix(steamstatic.com) using PROXY[香港 HK 01]"
time="2021-07-12T10:56:39+08:00" level=info msg="[TCP] 127.0.0.1:59888 --> community.akamai.steamstatic.com match DomainSuffix(steamstatic.com) using PROXY[香港 HK 01]"
time="2021-07-12T10:57:24+08:00" level=debug msg="[DNS] r3---sn-ni5een7s.gvt1.com --> 120.253.253.68"
time="2021-07-12T10:57:24+08:00" level=info msg="[TCP] 127.0.0.1:59890 --> r3---sn-ni5een7s.gvt1.com match RuleSet(ChinaIP) using DIRECT"
time="2021-07-12T10:57:37+08:00" level=info msg="[TCP] 127.0.0.1:59895 --> api.steampowered.com match RuleSet(China) using DIRECT"
```

**截图**

![image](https://user-images.githubusercontent.com/41108003/125310349-12b53680-e365-11eb-98a3-796998f8c580.png)

**其他说明**

[//]: # (其他补充内容)

**Comment by ANDYWANGTIANTIAN** [comment]
我这里也有同样的问题

**Comment by BestRailgun** [comment]
我还以为是服务器或者配置文件的问题...昨天调了一晚上也没搞好

**Comment by yi-Xu-0100** [comment]
将，日志中 有 steam 关键词记录的域名最后匹配走了代理的，设置规则改为代理。

**Comment by Maasea** [comment]
> 将，日志中 有 steam 关键词记录的域名最后匹配走了代理的，设置规则改为代理。

我试过全局代理，没有奏效。
不过我发现一件有趣的事情：打开steam后显示无法加载，这时将clash 里的`connectiong` close all 然后重新加载商店页面，将恢复正常（过程中不退出steam）。
自身配置也很简单，贴一下希望可以帮助解决问题。我在主面板上开启了`IPV6` 其他没有需要补充。
```
external-controller: 127.0.0.1:9090
port: 7890
socks-port: 7891
redir-port: 7892


proxies:
proxy-groups:
  - type: select
    name: PROXY
    proxies:
      - HongKong
      - America
      - Japan
      - Singapore
      - Others
  - type: fallback
    name: HongKong
    proxies:
      - 香港 HK 01
      - 香港 HK 02
      - 香港 HK 03
      - 香港 HK 04
      - 香港 HK 05
      - 香港 HK 06
      - 香港 HK 07
      - 香港 HK 08
      - 香港 HK 09
      - 香港 HK 10
    url: http://cp.cloudflare.com/generate_204
    interval: 1200
  - type: fallback
    name: America
    proxies:
      - 美国 US 01
      - 美国 US 02
      - 美国 US 03
      - 美国 US 04
      - 美国 US 05
      - 美国 US 06
      - 美国 US 07
      - 美国 US 08
    url: http://cp.cloudflare.com/generate_204
    interval: 1200
  - type: fallback
    name: Japan
    proxies:
      - 韩国 KR 01
      - 韩国 KR 02
      - 韩国 KR 03
      - 韩国 KR 04
      - 韩国 KR 05
      - 韩国 KR 06
      - 韩国 KR 07
      - 韩国 KR 08
    url: http://cp.cloudflare.com/generate_204
    interval: 1200
  - type: fallback
    name: Singapore
    proxies:
      - 新加坡 SG 01
      - 新加坡 SG 02
      - 新加坡 SG 03
      - 新加坡 SG 04
      - 新加坡 SG 05
      - 新加坡 SG 06
      - 新加坡 SG 07
      - 新加坡 SG 08
    url: http://cp.cloudflare.com/generate_204
    interval: 1200
  - type: select
    name: Others
    proxies:
      - 韩国 KR 01
      - 韩国 KR 02
      - 韩国 KR 03
      - 韩国 KR 04
      - 韩国 KR 05
      - 韩国 KR 06
      - 韩国 KR 07
      - 韩国 KR 08
      - 香港 HK 01
      - 香港 HK 02
      - 香港 HK 03
      - 香港 HK 04
      - 香港 HK 05
      - 香港 HK 06
      - 香港 HK 07
      - 香港 HK 08
      - 香港 HK 09
      - 香港 HK 10
  - type: select
    name: Streaming
    proxies:
      - HongKong
      - America
      - Japan
      - Singapore
      - Others
  - type: select
    name: Finally
    proxies:
      - PROXY
      - DIRECT


rule-providers:
  Unbreak:
    type: http
    behavior: classical
    path: ./RuleSet/Unbreak.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles/Clash/RuleSet/Unbreak.yaml
    interval: 86400

  Streaming:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/Streaming.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400

  Global:
    type: http
    behavior: classical
    path: ./RuleSet/Global.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles/Clash/RuleSet/Global.yaml
    interval: 86400

  StreamingCN:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/StreamingCN.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles/Clash/RuleSet/StreamingMedia/StreamingCN.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles/Clash/RuleSet/China.yaml
    interval: 86400

  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./RuleSet/Extra/ChinaIP.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 86400

rules:
  - DOMAIN-KEYWORD,ipv6,DIRECT
  - DOMAIN-KEYWORD,torrent,DIRECT
  - DOMAIN-SUFFIX,steamstatic.com,PROXY
  - RULE-SET,Unbreak,DIRECT
  - RULE-SET,Streaming,Streaming
  - RULE-SET,Global,PROXY
  - RULE-SET,StreamingCN,DIRECT
  - RULE-SET,China,DIRECT
  - RULE-SET,ChinaIP,DIRECT

  # LAN
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT

  # Final
  - GEOIP,CN,DIRECT
  - MATCH,Finally
```
