### ISSUE TITLE
CFW访问延时较大甚至不可用

### ISSUE THREAD

**Issue by Sefank** [Fndroid/clash_for_windows_pkg#2055]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 20H2 (19042.1110)

使用过虚拟机与WSL2，因此代理时同时使用虚拟网卡，CFW已设置为自动探测网卡。

相关软件版本：
CFW 0.16.3
Clash 2021.07.03 windows amd64 with go1.16.5 Sat Jul  3 13:23:06 UTC 2021

使用的浏览器：Microsoft Edge 版本 91.0.864.70 (官方内部版本) (64 位)
采用SwitchyOmega指定代理测试（未使用系统代理，使用系统代理结果类似）。

**描述**

使用相同配置文件，Clash Core可以正常使用，CFW则访问延时较大甚至不可用。

**复现**

采用的测试配置文件如下（地址已脱敏处理）：

```yaml
mixed-port: 7890
proxies:
  - name: 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B01'
    type: ss
    server: [地址隐藏，测试时请替换为可用的地址]
    port: 5062
    cipher: rc4-md5
    password: [密码隐藏，测试时请替换为可用的密码]
    udp: true
  - name: 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B02'
    type: ss
    server: [地址隐藏，测试时请替换为可用的地址]
    port: 5062
    cipher: rc4-md5
    password: [密码隐藏，测试时请替换为可用的密码]
    udp: true
  - name: 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B03'
    type: ss
    server: [地址隐藏，测试时请替换为可用的地址]
    port: 5062
    cipher: rc4-md5
    password: [密码隐藏，测试时请替换为可用的密码]
    udp: true
  - name: 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B04'
    type: ss
    server: [地址隐藏，测试时请替换为可用的地址]
    port: 5062
    cipher: rc4-md5
    password: [密码隐藏，测试时请替换为可用的密码]
    udp: true
  - name: 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B05'
    type: ss
    server: [地址隐藏，测试时请替换为可用的地址]
    port: 5062
    cipher: rc4-md5
    password: [密码隐藏，测试时请替换为可用的密码]
    udp: true
  - name: 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B06'
    type: ss
    server: [地址隐藏，测试时请替换为可用的地址]
    port: 5062
    cipher: rc4-md5
    password: [密码隐藏，测试时请替换为可用的密码]
    udp: true
  - name: 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B07'
    type: ss
    server: [地址隐藏，测试时请替换为可用的地址]
    port: 5062
    cipher: rc4-md5
    password: [密码隐藏，测试时请替换为可用的密码]
    udp: true
  - name: 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B08'
    type: ss
    server: [地址隐藏，测试时请替换为可用的地址]
    port: 5062
    cipher: rc4-md5
    password: [密码隐藏，测试时请替换为可用的密码]
    udp: true
  - name: 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B09'
    type: ss
    server: [地址隐藏，测试时请替换为可用的地址]
    port: 5062
    cipher: rc4-md5
    password: [密码隐藏，测试时请替换为可用的密码]
    udp: true
  - name: 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B10'
    type: ss
    server: [地址隐藏，测试时请替换为可用的地址]
    port: 5062
    cipher: rc4-md5
    password: [密码隐藏，测试时请替换为可用的密码]
    udp: true

proxy-groups:
  - name: 🔰国外流量
    type: url-test
    proxies:
      - 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B01'
      - 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B02'
      - 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B03'
      - 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B04'
      - 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B05'
      - 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B06'
      - 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B07'
      - 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B08'
      - 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B09'
      - 'ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B10'
    # tolerance: 150
    # lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300


rules:
  - DOMAIN-KEYWORD,google,🔰国外流量
  - DOMAIN-KEYWORD,github,🔰国外流量
  - MATCH,DIRECT

```

Clash Core 采用 `-f`加载配置文件，CFW则在程序界面中Import配置文件

分别用 Clash Core 和 CFW，访问 [CFW GitHub](https://github.com/Fndroid/clash_for_windows_pkg) 主页。

经测试 Clash Core 可以正常访问。Clash Core 日志：
```
time="2021-07-18T18:40:37+08:00" level=info msg="Start initial compatible provider 🔰国外流量"
time="2021-07-18T18:40:37+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2021-07-18T18:40:37+08:00" level=info msg="[TCP] 127.0.0.1:9965 --> github.com match DomainKeyword(github) using 🔰国外流量[ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B01]"
time="2021-07-18T18:40:37+08:00" level=info msg="[TCP] 127.0.0.1:1618 --> github.githubassets.com match DomainKeyword(github) using 🔰国外流量[ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B01]"
time="2021-07-18T18:40:37+08:00" level=info msg="[TCP] 127.0.0.1:7964 --> alive.github.com match DomainKeyword(github) using 🔰国外流量[ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B01]"
time="2021-07-18T18:40:37+08:00" level=info msg="[TCP] 127.0.0.1:5910 --> github.com match DomainKeyword(github) using 🔰国外流量[ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B01]"
time="2021-07-18T18:40:37+08:00" level=info msg="[TCP] 127.0.0.1:8008 --> assets.msn.cn match Match() using DIRECT"
time="2021-07-18T18:40:37+08:00" level=info msg="[TCP] 127.0.0.1:4073 --> ntp.msn.cn match Match() using DIRECT"
time="2021-07-18T18:40:38+08:00" level=info msg="[TCP] 127.0.0.1:10112 --> assets.msn.cn match Match() using DIRECT"
time="2021-07-18T18:40:38+08:00" level=info msg="[TCP] 127.0.0.1:8036 --> collector.githubapp.com match DomainKeyword(github) using 🔰国外流量[ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B01]"
time="2021-07-18T18:40:38+08:00" level=info msg="[TCP] 127.0.0.1:3063 --> api.github.com match DomainKeyword(github) using 🔰国外流量[ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B01]"
```
访问计时结果如下：
![Clash Core加载时延情况](https://user-images.githubusercontent.com/12670778/126064552-8e94db6e-96a7-42f1-b24a-d0f248a47f0c.png)

---

CFW访问未能完全加载出页面，在`C:\Users\[用户名]\.config\clash\logs`查看相关日志如下：
```
time="2021-07-18T19:23:18+08:00" level=info msg="RESTful API listening at: 127.0.0.1:13804"
time="2021-07-18T19:23:18+08:00" level=info msg="Mixed(http+socks5) proxy listening at: 127.0.0.1:7890"
time="2021-07-18T19:23:18+08:00" level=info msg="[TCP] 127.0.0.1:12905 --> assets.msn.cn doesn't match any rule using DIRECT"
time="2021-07-18T19:23:18+08:00" level=info msg="Start initial compatible provider 🔰国外流量"
time="2021-07-18T19:23:19+08:00" level=info msg="[TCP] 127.0.0.1:2989 --> assets.msn.cn match Match() using DIRECT"
time="2021-07-18T19:23:21+08:00" level=info msg="[TCP] 127.0.0.1:9040 --> github.githubassets.com match DomainKeyword(github) using 🔰国外流量[ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B01]"
time="2021-07-18T19:23:26+08:00" level=info msg="[TCP] 127.0.0.1:3675 --> github.com match DomainKeyword(github) using 🔰国外流量[ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B01]"
time="2021-07-18T19:23:48+08:00" level=info msg="[TCP] 127.0.0.1:4525 --> edge.microsoft.com match Match() using DIRECT"
time="2021-07-18T19:23:52+08:00" level=info msg="[TCP] 127.0.0.1:1418 --> github.com match DomainKeyword(github) using 🔰国外流量[ASYNCHRONOUS TRANSFERMODE 永久虚通路连接PVCC B01]"
time="2021-07-18T19:24:11+08:00" level=info msg="[TCP] 127.0.0.1:8636 --> edge.microsoft.com match Match() using DIRECT"
```

页面计时结果如下（此时浏览器显示Connection Close错误）：

![CFW不可访问时延](https://user-images.githubusercontent.com/12670778/126065210-232358e9-ccf9-4b20-8acc-d5fce772a09c.png)

**预期行为**

CFW进行代理时可以正常使用。

**日志**

见复现部分。

**截图**

见复现部分。

**其他说明**

测试中CFW未使用Service Mode以及TAP Device。
