### ISSUE TITLE
tun 模式 stack 使用 system 无流量经过

### ISSUE THREAD

**Issue by Sentsuki** [Fndroid/clash_for_windows_pkg#2067]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Windows 10 Pro 21H1

**描述**

tun 模式 stack 使用 system 无流量经过。Connections 没有内容，上传下载都是0

**复现**

1. 进入设置
2. Profile Mixin 里 YAML 写入内容
```
dns:
  enable: true
  enhanced-mode: redir-host
  nameserver:
    - 8.8.8.8
    - 114.114.114.114
tun:
  enable: true
  stack: system
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true
  auto-detect-interface: true
```
3. 开启Mixin
4. 触发问题

**预期行为**

正常上网

**日志**

```
time="2021-07-25T01:05:36+08:00" level=debug msg="Generate GUID: {XXXXXXX}"
time="2021-07-25T01:05:37+08:00" level=info msg="[Wintun] CreateAdapter: Creating adapter"
time="2021-07-25T01:05:37+08:00" level=info msg="[Wintun] CreateAdapter: Requested GUID {XXXXXXX} has leftover residue"
time="2021-07-25T01:05:37+08:00" level=info msg="[Wintun] SelectDriver: Using existing driver 0.12"
time="2021-07-25T01:05:37+08:00" level=info msg="Tun Proxy listening at: Clash(198.18.0.1)"
time="2021-07-25T01:05:37+08:00" level=debug msg="[Stack] Failed to dummy bind, retry in 1 second... (1/10)"
time="2021-07-25T01:05:38+08:00" level=debug msg="[Stack] Failed to dummy bind, retry in 1 second... (2/10)"
time="2021-07-25T01:05:39+08:00" level=debug msg="[Stack] Failed to dummy bind, retry in 1 second... (3/10)"
time="2021-07-25T01:05:40+08:00" level=debug msg="[Stack] Failed to dummy bind, retry in 1 second... (4/10)"
time="2021-07-25T01:05:41+08:00" level=debug msg="[Stack] Address %!w(net.IP=[198 18 0 1]) ready for bind"
```

**截图**
<img width="737" alt="1" src="https://user-images.githubusercontent.com/52487960/126876156-2ba37634-6790-4a1e-9846-3f155e911847.png">
<img width="77" alt="2" src="https://user-images.githubusercontent.com/52487960/126876157-329be89f-1c50-44ae-92f0-823d921897d6.png">
