### ISSUE TITLE
最新版支持nameserver-policy吗？

### ISSUE THREAD

**Issue by efaun** [Fndroid/clash_for_windows_pkg#2091]
如题

**Comment by Fndroid** [comment]
支持

**Comment by efaun** [comment]
> 支持

抱歉再次打扰你，我是这样设置的：

```
mixin: # object
  dns:
    enable: true
    enhanced-mode: redir-host
    nameserver-policy:
      "+.abc.com": "172.21.5.5"
    #default-nameserver:
    #  - 223.5.5.5
    #  - 8.8.8.8
    nameserver:
      #- 172.21.5.5
      - 223.5.5.5
      - 8.8.8.8 # 真实请求DNS，可多设置几个
      - 8.8.4.4

  # interface-name: WLAN # 出口网卡名称，或者使用下方的自动检测
  tun:
    enable: true
    stack: gvisor # 使用 system 需要 Clash Premium 2021.05.08 及更高版本
    dns-hijack:
      - 198.18.0.2:53
    auto-route: true
    auto-detect-interface: true # 自动检测出口网卡
```

但是并没有生效，我配置的有问题吗？
