### ISSUE TITLE
Proxy Group添加GLOBAL

### ISSUE THREAD

**Issue by WeirdoShaw** [Fndroid/clash_for_windows_pkg#21]
Clash for Windows的config.yml不能直接给clash使用，因为`Rule`中使用的`GLOBAL`标签没有指定。

**Comment by Fndroid** [comment]
没明白你的意思，cClash for Windows就是用的Clash核心加载配置

**Comment by WeirdoShaw** [comment]
我在config.yml里是这么写的：
```
Proxy Group:
  - name: Boom
    type: select
    proxies:
      - Foo
      - Bar
Rule:
  - 'FINAL,,GLOBAL'
```
C4W用这个配置没有问题，它会自动使用我在Proxies下GLOBAL中选择的代理，例如Foo。
但在clash中，我只有添加GLOBAL，clash才能工作：
```
Proxy Group:
  - name: GLOBAL
    type: select
    proxies: 
      - Foo
  - name: Boom
    type: select
    proxies:
      - Foo
      - Bar
Rule:
  - 'FINAL,,GLOBAL'
```
所以，希望C4W把用户指定的全局代理作为GLOBAL添加到Proxy Group中。
