### ISSUE TITLE
sub转clash下的订阅链接无法使用预处理配置

### ISSUE THREAD

**Issue by DISVGOD** [Fndroid/clash_for_windows_pkg#2145]
**信息**

- [x] 已经从[issues](https://github.com/Fndroid/clash_for_windows_pkg/issues/988)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # windows10
          clash 0.17.1
**描述**

[//]: #无法正常使用Parsers

**复现**

[//]: # (请描述复现问题的步骤)

1. 点击Setting/Profiles/Parsers
2.输入配置
parsers: # array
  - url: 我的ssr托管订阅链接通过sub转换clash订阅链接
    yaml:
      prepend-rules:
  - DOMAIN-SUFFIX,steam-chat.com,🎯 全球直连
  - DOMAIN-SUFFIX,a.akamaihd.net,🎯 全球直连
  - DOMAIN-SUFFIX,steampowered.com,🎯 全球直连
  - DOMAIN-KEYWORD,steamcontent.com,🎯 全球直连
  - DOMAIN-KEYWORD,api.steampowered.com,🎯 全球直连
3. 点击右下角保存
4. 点击Profiles/Update this profiles
5. 显示error

**预期行为**

[//]: # 应更新成功，并根据预配置添加相应规则

**日志**

**截图**

[//]: #
![image](https://user-images.githubusercontent.com/59304605/129709990-bbf6468a-67c6-42e9-9675-8301573bd9af.png)
![image](https://user-images.githubusercontent.com/59304605/129710110-d4dbfe9f-007f-470d-93d0-627c579559a9.png)

**其他说明**

**Comment by yi-Xu-0100** [comment]
parser 的 yaml 缩进有问题

**Comment by DISVGOD** [comment]
> parser 的 yaml 缩进有问题

意思是我多打空格了吗，但是它没报错啊

**Comment by WrathGluttony** [comment]
> parser 的 yaml 缩进有问题

您好，我也有相同的问题，麻烦前辈们给出正确的解决方案，谢谢

**Comment by yi-Xu-0100** [comment]
@WrathGluttony @DISVGOD 参考示例如下，以该 issue 为例：

```yaml
parsers: # array
  url: 我的ssr托管订阅链接通过sub转换clash订阅链接
  yaml:
    prepend-rules:
      - DOMAIN-SUFFIX,steam-chat.com,🎯 全球直连
      - DOMAIN-SUFFIX,a.akamaihd.net,🎯 全球直连
      - DOMAIN-SUFFIX,steampowered.com,🎯 全球直连
      - DOMAIN-KEYWORD,steamcontent.com,🎯 全球直连
      - DOMAIN-KEYWORD,api.steampowered.com,🎯 全球直连
```

其他说明：
1. yaml 以空格缩进，**同一数目的**的为同一缩进。
2. 不同层级间可能有不同隶属关系，建议看看 yaml 语法规则了解基本含义。
3. parser 更多示例看： https://docs.cfw.lbyczf.com/contents/parser.html
