### ISSUE TITLE
请求在Linux版中，增加Service安装脚本的日志界面或能否将tun安装脚本执行时返回的内容单独保存为一个log文件以供排错

### ISSUE THREAD

**Issue by iPixelOldC** [Fndroid/clash_for_windows_pkg#2155]
**描述**
因为我的tun功能工作不正常。我这里开启后，就没网了，而关掉网就回来了（软件里Service的地球图标是绿色的,日志和连接界面也一片空白。主界面是显示Connect的)。感觉是防火墙的设置没在我这里生效或是没安装成功。不过ip addr里面`utun`啥的也有。并且我这里执行安装脚本，等多久他也不重启软件，所以要是安装时能给个窗口显示他脚本命令返回内容的日志或能否将tun安装脚本执行时返回的内容单独保存为一个log文件以供我排查。谢谢 :D

**其他说明**
以及我在尝试手动安装寻找问题时(sudo ./install.sh install)。他显示我在`resources/static/files/linux/common/service-installer/scripts/`目录下缺少`clash-core-service.service`.这个我也不知道怎么生成。或许这也是我用不了的原因？

系统环境 ：

- Linux arcoi3 5.13.10-zen1-1-zen  ZEN SMP PREEMPT Thu, 12 Aug 2021 21:59:17 +0000 x86_64 GNU/Linux
-  Arco Linux + i3wm （i3-gaps 4.19.1 (2021-02-01))
- CFW 版本 0.17.1 （以前的0.17.0也一样)

tun配置 （是使用Mixin的，原配置没有dns和tun的内容)
```
mixin: # object
  dns:
    enable: true
    enhanced-mode: redir-host
    nameserver:
      - 114.114.114.114 # 真实请求DNS，可多设置几个
  tun:
    enable: true
    stack: system # 或 gvisor
    dns-hijack: # DNS劫持设置为系统DNS
      - 1.0.0.1:53 # 请勿更改

```
