### ISSUE TITLE
linux 下tun模式经常无效

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [Fndroid/clash_for_windows_pkg#2171]
**信息**

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

Ubuntu 21.04

**描述**

使用Mixin来打开关闭TUN模式，设置如下：
```yaml
mixin: # object
  dns:
    enable: true
    enhanced-mode: redir-host
    nameserver:
      - 114.114.114.114 # 真实请求DNS，可多设置几个
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
      - 1.0.0.1
  tun:
    enable: true
    stack: system # 或 gvisor
    dns-hijack: # DNS劫持设置为系统DNS
      - 1.0.0.1:53 # 请勿更改
```

有时打开Mixin有效，有时打开无效，大多数时候无效，即使这次有效，重新关闭Mixin再重新打开也会导致无效。

**复现**

打开Mixin，用chrome访问www.google.com，无法访问，而且会导致原本可以访问的cn.bing.com也无法访问。

**预期行为**

打开Mixin则可以访问google

**日志**
time="Thu Aug 26 2021 16:48:40 GMT+0800 (China Standard Time)" level=info msg="app exiting, turn off system proxy"
time="Thu Aug 26 2021 16:48:54 GMT+0800 (China Standard Time)" level=info msg="app start with mode: production"
time="Thu Aug 26 2021 16:48:54 GMT+0800 (China Standard Time)" level=info msg="load data from general config.yaml"
time="Thu Aug 26 2021 16:48:54 GMT+0800 (China Standard Time)" level=info msg="mixed-port changed"
time="Thu Aug 26 2021 16:48:54 GMT+0800 (China Standard Time)" level=info msg="external controller port changed"
time="Thu Aug 26 2021 16:48:54 GMT+0800 (China Standard Time)" level=info msg="clash axios client changed"
time="Thu Aug 26 2021 16:48:54 GMT+0800 (China Standard Time)" level=info msg="restarting clash core..."
time="Thu Aug 26 2021 16:48:54 GMT+0800 (China Standard Time)" level=info msg="check for app update, current: 0.17.1"
time="Thu Aug 26 2021 16:48:54 GMT+0800 (China Standard Time)" level=info msg="clash status change to [connected]"
time="Thu Aug 26 2021 16:48:54 GMT+0800 (China Standard Time)" level=info msg="restore at index: 1"
time="Thu Aug 26 2021 16:48:55 GMT+0800 (China Standard Time)" level=info msg="restore proxy settings"
time="Thu Aug 26 2021 16:49:07 GMT+0800 (China Standard Time)" level=info msg="restore at index: 1"
time="Thu Aug 26 2021 16:49:07 GMT+0800 (China Standard Time)" level=info msg="restore proxy settings"

**截图**

![image](https://user-images.githubusercontent.com/57612792/130933161-93c9a86f-30a9-4e9e-8906-dc1d4bc20130.png)
![image](https://user-images.githubusercontent.com/57612792/130933380-324d746c-bf63-4896-9703-df7abd0d1d9b.png)

**其他说明**

打开Mixin时，ifconfig命令下新增：
```bash
utun: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 9000
        inet 198.18.0.1  netmask 255.255.0.0  destination 198.18.0.1
        inet6 fe80::c227:b733:f87:7f83  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2  bytes 100 (100.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
