### ISSUE TITLE
"Console Output" file didn't contain anything.

### ISSUE THREAD

**Issue by youngzyl** [Fndroid/clash_for_windows_pkg#2220]
### Version:
&ensp;0.17.1

### Assessment:

&ensp;Go to **Settings** -> **Profiles** -> **Console Output** -> Click **Open File**

&ensp;![image](https://user-images.githubusercontent.com/35056356/133067668-80629e80-c609-4724-a35e-f17c89041c09.png)
 
&ensp;CFW will open a file called "cfw-paser.log"

&ensp;Once you start update an profile which is matched parsers.

&ensp;![image](https://user-images.githubusercontent.com/35056356/133068002-fe6846b3-c4f6-4023-b164-f14d9b4a7db3.png)

&ensp;The log file should show something.
&ensp;![image](https://user-images.githubusercontent.com/35056356/133068975-520c814e-fbcd-4476-9144-e7b787dd8931.png)
&ensp;![image](https://user-images.githubusercontent.com/35056356/133069015-19272a63-249b-452a-9c0f-5eb8d49ea48c.png)

&ensp;Since Parsers command :"- proxy-groups.(test).proxies+[]proxyNames|HK" unable to add proxy which name contain "HK" to group "test"
&ensp;I try to check details in log file. But like previous discription. Logs file is empty.

**_Thank you very much for your advise._**

**Comment by yi-Xu-0100** [comment]
> console：日志输出至文件，方便调试，在 Settings 界面中 Parser 设置下方打开

[https://docs.cfw.lbyczf.com/contents/parser.html#工具类对象-方法](https://docs.cfw.lbyczf.com/contents/parser.html#%E5%B7%A5%E5%85%B7%E7%B1%BB%E5%AF%B9%E8%B1%A1-%E6%96%B9%E6%B3%95)

**Comment by youngzyl** [comment]
Thank you very much for the help.

> > console：日志输出至文件，方便调试，在 Settings 界面中 Parser 设置下方打开
> 
> [https://docs.cfw.lbyczf.com/contents/parser.html#工具类对象-方法](https://docs.cfw.lbyczf.com/contents/parser.html#%E5%B7%A5%E5%85%B7%E7%B1%BB%E5%AF%B9%E8%B1%A1-%E6%96%B9%E6%B3%95)
> 
> > Since Parsers command :"- proxy-groups.(test).proxies+[]proxyNames|HK" unable to add proxy which name contain "HK" to group "test"
> 
> Full configuration please.

I'm trying to create a new group called "test" contain every HK proxies.
So I add two value such as "append-proxy-groups" and the command "proxy-groups.test.proxies+[]proxyNames|HK"
And the previous config looks like this:
```
#  - url: https://example.sub/sub?target=clash&url=https%3A%2F%2Fsub.exp.sub
      yaml:
	append-proxy-groups:
          - name: test
            type: url-test
            url: http://www.gstatic.com/generate_204
            interval: 300
            tolerance: 50
            proxies:
              - DIRECT
        commands:
	 - proxy-groups.test.proxies+[]proxyNames|HK
```

There is one thing I didn't understand, is parameter of "console" **boolean** ?
If it's true, I thought this one may work.
```
parsers:
  - console: true
  - reg: https://example.sub.+$ # 正则匹配域名
    yaml:
	append-proxy-groups:
          - name: test
            type: url-test
            url: http://www.gstatic.com/generate_204
            interval: 300
            tolerance: 50
            proxies:
              - DIRECT
        commands:
	 - proxy-groups.test.proxies+[]proxyNames|HK
```

But after I save the config, and update profile again. cfw-parser.log seem still empty.

**Comment by yi-Xu-0100** [comment]
![图片](https://user-images.githubusercontent.com/25523606/133084836-ad981068-47c6-4b37-97f0-f27b1982a425.png)

1. I think there is a problem with the indentation of your YAML code snippet.
2. The log is only for the `console` setting in JS mode for the parser.
3. Only spaces can be used for indentation in YAML. 

Here is the example: 

```yaml
parsers:
  - url: https://example.sub/sub?target=clash&url=https%3A%2F%2Fsub.exp.sub
    yaml:
      append-proxy-groups:
        - name: test
          type: url-test
          url: http://www.gstatic.com/generate_204
          interval: 300
          tolerance: 50
          proxies:
            - DIRECT
      commands:
        - proxy-groups.test.proxies+[]proxyNames|HK
```
