### ISSUE TITLE
预配置parsers不工作

### ISSUE THREAD

**Issue by kevinwang930** [Fndroid/clash_for_windows_pkg#2250]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [ x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
win 10 
[//]: # (平台及版本号)

**描述**

版本18.0 误点击 `profile folder path`导致程序不工作，修复后 `profile parsers`就不能用了，升级到新版本还是这样。 不管是url 还是 reg 都不起作用 以下是parsers内容，链接地址是直接从配置文件设置里面复制。

```
parsers: # array
  - url: https://profile.topspeed.domain/link/xxz
      yaml:
        prepend-rules:
          - DOMAIN,test.domain,Proxy # rules最前面增加一个规则

  - reg: topspeed.+$
      yaml:
            prepend-rules:
              - DOMAIN,test.domain,Proxy # rules最前面增加一个规则
```
[//]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**
![parser-no-found](https://user-images.githubusercontent.com/33874210/134619849-519d8b5b-0eeb-4e9f-a9a8-bebc6dd8dd8f.png)

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)
