### ISSUE TITLE
Tun 连接时断开网络连接导致clash产生大量请求卡死

### ISSUE THREAD

**Issue by QingKongBaiYu** [Fndroid/clash_for_windows_pkg#2279]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 19043.1237, v0.18.3
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
Tun 连接时断开网络连接导致产生大量请求，clash 卡死，cpu、内存占用飙升。
**复现**

[//]: # (请描述复现问题的步骤)

1. 连接网络（wifi或pppoe）
2. 使用Tun模式启动clash
3. 断开网络连接
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为)
clash 正常工作
**日志**

[//]: # (上传触发问题对应的日志文件)
TUN部分配置
```yaml
  tun:
    enable: true
    stack: system # 使用 system 需要 Clash Premium 2021.05.08 及更高版本
    dns-hijack:
      - 198.18.0.2:53 # 请勿更改
    auto-route: true
    auto-detect-interface: true # 自动检测出口网卡
```
**截图**

[//]: # (如果可以，请提供对应问题的截图)
![Clash_for_Windows_20211001_211921](https://user-images.githubusercontent.com/45838887/135629808-88edfe24-04a6-44c2-b37b-0bdd152f4bf1.png)
图中打码请求为服务器地址
![Taskmgr_20211001_211849](https://user-images.githubusercontent.com/45838887/135628869-c6eab5fb-bd4d-4db2-9454-3e4ae62ab3dd.png)

**其他说明**

[//]: # (其他补充内容)
