### ISSUE TITLE
部分网页打不开

### ISSUE THREAD

**Issue by wangyifan349** [Fndroid/clash_for_windows_pkg#2285]
YAML设置如下
```yaml
mixin: # object
  dns:
    enable: true
    enhanced-mode: redir-host
    nameserver: # 真实请求DNS，可多设置几个
    - 223.5.5.5
    - 8.8.8.8
# interface-name: WLAN # 出口网卡名称，或者使用下方的自动检测
  tun:
    enable: true
    stack: gvisor # 使用 system 需要 Clash Premium 2021.05.08 及更高版本
    dns-hijack:
      - 198.18.0.2:53 # 请勿更改
    auto-route: true
    auto-detect-interface: true # 自动检测出口网卡

```

我开启了全局模式并且选择了一个香港的节点(节点没问题)，开启了Mixin
谷歌油管什么的大部分都能上
但https://www.astrill.com/zh/dns-leak-test打不开
除非我打开system proxy才能打开
BUG?
