### ISSUE TITLE
parsers功能实现所有节点sni替换

### ISSUE THREAD

**Issue by ZJMXX** [Fndroid/clash_for_windows_pkg#2346]
大家好！

我订阅的机场是用的Trojan协议，公司内网将机场默认设置的sni网址屏蔽掉了，我每次更新订阅后需要手动将所有节点的sni替换为www.baidu.com。

我知道且已经通过parsers功能实现了一些配置文件预处理功能，但是请问parsers功能能否实现所有节点的sni替换，还是说需要通过JavaScript的for循环来实现？

谢谢！

**Comment by yi-Xu-0100** [comment]
个人感觉 parser 的 js 处理会好点吧。

**Comment by yi-Xu-0100** [comment]
@ZJMXX 

```js
parser:
  - reg: '^.*$'
    code: |
      module.exports.parse = async (raw, { yaml }) => {
        let rawObj = yaml.parse(raw);
        let newSni = 'www.baidu.com';
        rawObj['proxies'].forEach(proxy => {
          if (proxy['sni']) {
            proxy['sni'] = newSni;
          }
        });
        raw = yaml.stringify(rawObj);
        return raw;
      };
```

没试验过，试试看看效果吧。

**Comment by ZJMXX** [comment]
> @ZJMXX
> 
> ```js
> parser:
>   - reg: '^.*$'
>     code: |
>       module.exports.parse = async (raw, { yaml }) => {
>         let rawObj = yaml.parse(raw);
>         let newSni = 'www.baidu.com';
>         rawObj['proxies'].forEach(proxy => {
>           if (proxy['sni']) {
>             proxy['sni'] = newSni;
>           }
>         });
>         raw = yaml.stringify(rawObj);
>         return raw;
>       };
> ```
> 
> 没试验过，试试看看效果吧。

不愧是大佬，一字不改就可以用。
可以直接放在简便方法YAML的下面配合之前的其他parsers设置使用。放在这里供其他同学参考~

**Comment by Blink1024** [comment]
> 个人感觉 parser 的 js 处理会好点吧。
@yi-Xu-0100 
大佬你好,我想把vmess请求头里的`host1.com`全部改成`www.10010.com`,这个js要怎么写呢
配置文件格式如下:
```
proxies:
  - name: A
    type: vmess
    server: example1.com
    port: 80
    uuid: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    alterId: 0
    cipher: auto
    udp: true
    network: ws
    ws-path: /ws
    ws-headers:
      Host: host1.com
```
