### ISSUE TITLE
[Bug] WinTun 模式下，BT软件检测的网络状态为阻塞

### ISSUE THREAD

**Issue by daiyeqi** [Fndroid/clash_for_windows_pkg#2347]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**
Windows 11 专业版 22000.258

[//]: # (平台及版本号)

**描述**
WinTun 模式启用的情况下，BT软件（BitComet）检测的网络为阻塞（黄灯），NAT为端口受限锥型NAT。
关闭Tun模式，使用系统代理的情况下显示端口开发（绿灯），NAT为全锥形NAT。

[//]: # (请具体并清楚地描述遇到的问题)

**复现**
启用Tun模式后出现。

[//]: # (请描述复现问题的步骤)

**预期行为**
与系统代理一样，NAT检测结果未全锥形NAT。

[//]: # (清晰地描述期望看到的行为)

**日志**
无

[//]: # (上传触发问题对应的日志文件)

**截图**
无

[//]: # (如果可以，请提供对应问题的截图)

**其他说明**
配置信息如下：
```
tun:
  enable: true
  stack: system # system or gvisor
  dns-hijack:
    - 198.18.0.2:53 # when `fake-ip-range` is 198.18.0.1/16, should hijack 198.18.0.2:53
  auto-route: true # auto set global route
  # auto-detect-interface: true # conflict with interface-name

interface-name: 以太网
```

[//]: # (其他补充内容)
