### ISSUE TITLE
[Feature Request]: 监听 rule-providers 指定的本地文件变更，重启 Clash 核心

### ISSUE THREAD

**Issue by Bpazy** [Fndroid/clash_for_windows_pkg#2398]
### 功能描述

通过 rule-provider 指定本地文件 `mydomain.yaml`，但当时当更新该文件时，Clash 核心没有重启。导致虽然我在 `mydomain.yaml` 里面增加了配置，但是仍然不能走对应的渠道访问网址。

期望 Clash for Windows 检测到 rule-provider 指定的文件有变更时，也重启 Clash 核心。

配置文件举例：
```yaml
proxy-providers:
  provider1:
    type: http
    url: "https://example.com/"
    interval: 3600
    path: ./providers/provider1.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204

proxy-groups:
  - name: 节点选择
    type: select
    use:
      - provider1
  - name: 默认
    type: select
    proxies:
      - DIRECT

rule-providers:
  mydomain:
    type: file
    behavior: domain
    path: ./ruleset/mydomain.yaml

rules:
  - RULE-SET,mydomain,节点选择
  - MATCH,默认
```
