### ISSUE TITLE
[Bug]: TUN 模式无法正常工作

### ISSUE THREAD

**Issue by FishMagic** [Fndroid/clash_for_windows_pkg#2405]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.18.6 - 0.18.8

### 操作系统

Windows x64

### 系统版本

22000.318

### 问题描述

TUN 网卡正常生成，且日志中可见来源为 TUN 的流量
但是在 TUN 模式下，无需代理的网站可以正常访问，需要代理的网站无法访问
使用 http 或 socks5 代理正常

```
mixin: # object
  tun:
    enable: true
    stack: gvisor
    auto-route: true
    auto-detect-interface: true
    dns-hijack:
      - 198.18.0.2:53
  dns:
    enable: true
    use-hosts: true
    listen: 127.0.0.1:28898
    enhanced-mode: redir-host
    fake-ip-range: 198.18.0.1/16
    default-nameserver:
      - 114.114.114.114
      - 8.8.8.8
    nameserver:
      - https://1.1.1.1/dns-query
      - 1.1.1.1
      - 8.8.8.8
    fallback-filter:
      geoip: true
      geoip-code: CN
      ipcider: []
      domain: []
```

### 复现步骤

未知

### 日志文件

[2021-11-13-152455.log](https://github.com/Fndroid/clash_for_windows_pkg/files/7531615/2021-11-13-152455.log)
