### ISSUE TITLE
[Bug]:TUN模式下，风暴英雄无法登录 

### ISSUE THREAD

**Issue by Erdrian** [Fndroid/clash_for_windows_pkg#2407]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.18.8

### 操作系统

Windows x64

### 系统版本

22489.1000

### 问题描述

如题所述
初步判断为www.battlenet.com.cn该域名走了tun模式的原因，代理模式下无该问题
关闭MIXIN之后，该域名不走CFW即可正常登录
已尝试添加该域名至ByPass和fakeip-filter中
![image](https://user-images.githubusercontent.com/58811190/141651584-d681d695-56b0-4f0f-afca-7d88d9d53589.png)
![image](https://user-images.githubusercontent.com/58811190/141651602-83247fb0-dc9c-4f48-9109-906ac917988c.png)
![image](https://user-images.githubusercontent.com/58811190/141651628-9b77799d-7841-4723-a0fb-9f64672bef36.png)

### 复现步骤

打开TUN模式登录国服风暴

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by shikkoku** [comment]
应该加在parsers里吧？

```
parsers: # array
   - reg: https://api.xxxxx.xx.+$ #匹配订阅连接的规则需要自行修改
     yaml: 
       prepend-rules:
         - DOMAIN-SUFFIX,battlenet.com.cn,DIRECT
```
谁教你加在那两个地方的？
