### ISSUE TITLE
求助: linux 下 tun 不工作

### ISSUE THREAD

**Issue by kevinwang930** [Fndroid/clash_for_windows_pkg#2427]
### 问题描述
系统：RHEL 8
版本：0.18.9

手动设置gnome代理，cfw 正常工作。
service mode 图表已经变绿，outbound 设置为utun。nftables和iproute已安装。
关闭桌面代理，系统直接上网不经过cfw。日志为空，流量显示为零

疑问： service模式必须通过clash-premium-installer重新安装clash-core吗？  

### 其他内容

mixin 内容
```
mixin: # object
  dns:
    enable: true
    enhanced-mode: fake-ip
    nameserver:
      - 114.114.114.114 # 真实请求DNS，可多设置几个
  tun:
    enable: true
    stack: system # 或 gvisor
    dns-hijack: # DNS劫持设置为系统DNS
      - 1.0.0.1:53 # 请勿更改
```
_No response_
