### ISSUE TITLE
[Bug]: TUN 模式下网络中断导致无限请求dns

### ISSUE THREAD

**Issue by wloot** [Fndroid/clash_for_windows_pkg#2454]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

 0.18.10

### 操作系统

Windows x64

### 系统版本

Windows 11 x86_64

### 问题描述

开启 TUN 模式, 如果突然遇到网络中断(比如路由器重启, 插拔网线等)的情况, cfw开始即大量占用cpu, 直至卡死, 从 connections 界面可以观察到上千个活动的 dns 请求.

### 复现步骤

 根据文档配置tun模式, https://docs.cfw.lbyczf.com/contents/tun.html , 我所使用的 mixin 配置参看下文.
断开路由器等其他操作来切断互联网连接
观察到 connections 界面出现大量请求

### 其他补充

Mixin 配置:
```
mixin:
  dns:
    enable: true
    enhanced-mode: fake-ip
    nameserver:
      - 119.29.29.29
      - 223.5.5.5
    fake-ip-filter:
      - "dns.msftncsi.com"
      - "www.msftncsi.com"
      - "www.msftconnecttest.com"
  tun:
    enable: true
    stack: system
    dns-hijack:
      - 198.18.0.2:53
    auto-route: true
    auto-detect-interface: true
```

**Comment by Fndroid** [comment]
手动设置下interface-name

**Comment by CatEricka** [comment]
类似的问题：

平台：windows 10 21H1

网卡：Intel AC-9650

cfw版本：0.18.10

mixin 配置：

```yaml
mixin: # object
  interface-name: WLAN # 出口网卡名称，或者使用下方的自动检测
  dns:
    enable: true
    enhanced-mode: fake-ip
    nameserver:
      - 8.8.8.8 # 真实请求DNS，可多设置几个
      - 114.114.114.114
    fake-ip-filter:
      - "dns.msftncsi.com"
      - "www.msftncsi.com"
      - "www.msftconnecttest.com"
  tun:
    enable: true
    stack: gvisor # 使用 system 需要 Clash Premium 2021.05.08 及更高版本
    dns-hijack:
      - 198.18.0.2:53 # 请勿更改
    auto-route: true
```

网卡只有 WLAN，此时工作正常；

一旦开启 windows 的移动热点功能，打开浏览器，访问任何网站：
任务管理器 `性能` 选项卡可见 `以太网：Clash` 的发送流量异常（最高可达8Mbps），cfw 的 `Logs` 可见大量错误，`clash-win64.exe` 内存占用从 50MB 升高到 1000MB，`Connections` 连接数量过多导致 cfw 界面失去响应。

![image](https://user-images.githubusercontent.com/32029431/144369717-f3d905cc-4a06-4506-8b17-908ca434e877.png)

关闭移动热点功能，网络恢复正常。

若先开启移动热点功能，则 cfw 无法开启 tun 模式，表现为开启 mixin 开关后无法观察到 `Clash Tunnel` 网卡。
