### ISSUE TITLE
[Bug]: dns被自动修改成1.1.1.1

### ISSUE THREAD

**Issue by Binaryify** [Fndroid/clash_for_windows_pkg#2469]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.0

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

12.1 

### 问题描述

启动了软件，dns被自动修改成1.1.1.1，哪怕自己设置过

### 复现步骤

启动了软件，dns就会被自动修改成1.1.1.1

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
开启TUN Mode需要劫持系统DNS，所以会被修改。如果想自定义可以用Mixin

**Comment by henjue** [comment]
@Binaryify 如果你启用了tun，可以再mixin里增加如下配置
```yaml
mixin:
  tun :
    enable : true 
    stack : system
    dns-hijack: 
     #你的dns
      - 223.5.5.5          
      - 223.6.6.6          
      - 1.1.1.1                 
      - 114.114.114.114 
```
