### ISSUE TITLE
[Feature Request]: Providers更新时经过代理

### ISSUE THREAD

**Issue by aozaki-kuro** [Fndroid/clash_for_windows_pkg#2532]
### 功能描述

由于众所周知的原因，常用的 `https://raw.githubusercontent.com/` 连通性很差。
而今天发现 `https://cdn.jsdelivr.net/gh` 也遭到污染，导致 Providers 更新困难。
看了一下发现 Provider 更新时没有走代理。

希望能够在 System Proxy 或 Mixin / TUN 模式开启时，使 Providers 更新遵守代理规则。
谢谢🙏

**Comment by yi-Xu-0100** [comment]
tun 的话，应该是能接管的。前提是已经在 tun 模式下，且是正常代理的。

**Comment by aozaki-kuro** [comment]
> tun 的话，应该是能接管的。前提是已经在 tun 模式下，且是正常代理的。

我这里是已经启用了 TUN 模式，而且正常代理的。
这是我的 mixin 配置，已经手动写入了 `jsdelivr.net` 和 `raw.githubusercontent.com` 代理规则，仍然返回超时或被污染的结果。

```yaml
mixin: # object
  dns:
      enable: true
      enhanced-mode: 
        # redir-host
        fake-ip
      nameserver:
        - https://dns.alidns.com/dns-query
      fallback:
        - https://1.0.0.1/dns-query
  tun:
      enable: true
      stack: 
        gvisor
        # system
      dns-hijack:
        - 198.18.0.2:53
      auto-route: true
      #interface-name: 以太网
      auto-detect-interface: true
```
![image](https://user-images.githubusercontent.com/28428951/146717904-e4bd0597-b734-4912-bd66-9bf2426d0803.png)
