### ISSUE TITLE
[Bug]: 使用全局代理访问国内IP，出现502

### ISSUE THREAD

**Issue by CppXL** [Fndroid/clash_for_windows_pkg#2536]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.2

### 操作系统

Windows x64

### 系统版本

20h2

### 问题描述

使用全局代理访问国内IP，返回502状态码，使用全局代理访问国外网站，如GitHub则无问题

### 复现步骤

使用SwitchyOmega连接代理，访问国内网站出现502（使用IP访问也出现502）

### 日志文件

<details><summary>logs</summary><p>

```
time="2021-12-20T23:24:58+08:00" level=warning msg="[TCP] dial GLOBAL to 116.*.*.230:80 error: us4.edge.boom.party:43000 connect error: i/o timeout"
time="2021-12-20T23:25:12+08:00" level=info msg="[TCP] 127.0.0.1:3025 --> 116.*.*.230:80 using GLOBAL"
time="2021-12-20T23:25:16+08:00" level=info msg="[TCP] 127.0.0.1:3027 --> 116.*.*.230:80 using GLOBAL"
time="2021-12-20T23:25:23+08:00" level=info msg="[TCP] 127.0.0.1:3030 --> 116.*.*.230:80 using GLOBAL"
time="2021-12-20T23:25:47+08:00" level=info msg="[TCP] 127.0.0.1:3034 --> github.githubassets.com:443 using GLOBAL"
time="2021-12-20T23:25:47+08:00" level=info msg="[TCP] 127.0.0.1:3032 --> github.githubassets.com:443 using GLOBAL"
time="2021-12-20T23:25:47+08:00" level=info msg="[TCP] 127.0.0.1:3036 --> github.githubassets.com:443 using GLOBAL"
time="2021-12-20T23:25:47+08:00" level=info msg="[TCP] 127.0.0.1:3038 --> github.githubassets.com:443 using GLOBAL"
time="2021-12-20T23:25:47+08:00" level=info msg="[TCP] 127.0.0.1:3040 --> github.githubassets.com:443 using GLOBAL"
time="2021-12-20T23:25:47+08:00" level=info msg="[TCP] 127.0.0.1:3044 --> avatars.githubusercontent.com:443 using GLOBAL"
time="2021-12-20T23:25:47+08:00" level=info msg="[TCP] 127.0.0.1:3046 --> github.githubassets.com:443 using GLOBAL"
time="2021-12-20T23:25:49+08:00" level=info msg="[TCP] 127.0.0.1:3042 --> github.githubassets.com:443 using GLOBAL"
time="2021-12-20T23:25:51+08:00" level=info msg="[TCP] 127.0.0.1:3048 --> alive.github.com:443 using GLOBAL"
time="2021-12-20T23:25:52+08:00" level=info msg="[TCP] 127.0.0.1:3050 --> collector.githubapp.com:443 using GLOBAL"
time="2021-12-20T23:26:08+08:00" level=warning msg="[TCP] dial GLOBAL to v10.events.data.microsoft.com:443 error: us4.edge.boom.party:43000 connect error: i/o timeout"
time="2021-12-20T23:26:53+08:00" level=info msg="[TCP] 127.0.0.1:3056 --> array503.prod.do.dsp.mp.microsoft.com:443 using GLOBAL"
```

</p></details>

### 其他补充

mixin:
```
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - https://doh.pub/dns-query
    - https://223.5.5.5/dns-query
    - 8.8.8.8
  fallback-filter:
    geoip: false
# interface-name: WLAN # 出口网卡名称，或者使用下方的自动检测
interface-name: "Intel(R) Dual Band Wireless-AC 8265"
tun:
  enable: true
  stack: system # 使用 system 需要 Clash Premium 2021.05.08 及更高版本
  dns-hijack:
    - 198.18.0.2:53 # 请勿更改
  auto-route: true
interinterface-name: "Intel(R) Dual Band Wireless-AC 8265"
```

tun off

system proxy off
