### ISSUE TITLE
[bug] 使用URL 指定配置文件时，parser无法生效

### ISSUE THREAD

**Issue by Ryoria** [Fndroid/clash_for_windows_pkg#2564]
parser编写为：
````
parsers:
  - url: https://api.xxx.dev/link/xxxxx?clash=1&extend=1
    yaml:
      prepend-rules:
        - DOMAIN-SUFFIX,steampowered.com,Proxy
        - DOMAIN-SUFFIX,steam-chat.com,Proxy
        - DOMAIN-KEYWORD,steamcdn,Proxy
        - DOMAIN-KEYWORD,steamstore,Proxy
        - DOMAIN-KEYWORD,steamuserimages,Proxy
        - DOMAIN-KEYWORD,steambroadcast,Proxy
        - DOMAIN-KEYWORD,steamstatic,Proxy
        - DOMAIN-KEYWORD,steamcommunity,Proxy
此时配置文件无法匹配到parser
````
使用reg匹配部分url时，可正常匹配到配置文件
