### ISSUE TITLE
[Bug]: TUN模式下出现大量连接

### ISSUE THREAD

**Issue by FishMagic** [Fndroid/clash_for_windows_pkg#2695]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.4 - 0.19.8

### 操作系统

Windows x64

### 系统版本

10.0.22000.527

### 问题描述

使用TUN模式时出现大量连接, 导致系统资源占用过高, 且无法使用网络
已尝试过升级至最新版本
已尝试过自动检测网卡, 和手动指定网卡
从未开启过网络共享

### 复现步骤

未知

### 日志文件

[2022-02-19-124723.log](https://github.com/Fndroid/clash_for_windows_pkg/files/8101509/2022-02-19-124723.log)
[2022-02-19-131926.log](https://github.com/Fndroid/clash_for_windows_pkg/files/8101510/2022-02-19-131926.log)

### 其他补充
```
mixin: # object
  interface-name: Wi-Fi
  tun:
    enable: true
    stack: gvisor
    auto-route: true
    # auto-detect-interface: true
    dns-hijack:
      - 198.18.0.2:53
  dns:
    enable: true
    use-hosts: true
    listen: 127.0.0.1:28898
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    default-nameserver:
      - 114.114.114.114
      - 8.8.8.8
    nameserver:
      - https://1.1.1.1/dns-query
      - 1.1.1.1
      - 8.8.8.8
    fake-ip-filter:
    - "dns.msftncsi.com"
    - "www.msftncsi.com"
    - "www.msftconnecttest.com"
    - "*.local"
    - "*.lan"
    fallback-filter:
      geoip: true
      geoip-code: CN
      ipcider: []
      domain: []
```
