### ISSUE TITLE
[求助] 如何通过 Clash for windows 配置双网卡使其同时工作

### ISSUE THREAD

**Issue by HaloWang** [Fndroid/clash_for_windows_pkg#2702]
- 我身边有两个不同的网络(`中国联通-4g` 与 `中国电信wifi`)
- 我的电脑可以同时链接这两个网络
- 我想通过 Clash for Windows 使向某些 url 发起的请求都走 wifi, 于此同时向某些 url 发起的请求都走 4g
- 比如在 config.yaml 使某些 suffix 都通过 4g, 某些 suffix 都通过 wifi

1. 请问这是可行的吗? 应该怎么做?
2. 如何验证自己配置已经成功?

**Comment by Fndroid** [comment]
```yaml
proxy-groups:
  - name: A
    type: select
    interface-name: 以太网  # 网卡1名称
    proxies:
      - DIRECT
  - name: B
    type: select
    interface-name: WLAN  # 网卡2名称
    proxies:
      - DIRECT

rules:
  - DOMAIN-SUFFIX,foo.com,A
  - DOMAIN-SUFFIX,bar.com,B
```
