### ISSUE TITLE
[Feature Request]: 小白的自我修行：简单配置分享，像圈x一样使用clash

### ISSUE THREAD

**Issue by Wzieee** [Fndroid/clash_for_windows_pkg#2729]
## 前言
虽然知道clash功能很丰富强大，但是对于一个小白来说，很多东西看的都是懵懵懂懂。
之前使用clash都是把机场链接找个订阅转换网站然后导入clash的，好处是方便，缺点是没法自定义。自己手动添加了一些规则，不久以后就被订阅链接自动更新给重置了，很是苦恼。而手机上面使用的圈x则没有这个烦恼，订阅链接是链接、规则是规则，两者更新互不影响。所以一直心心念念想在电脑上面找到一个类似的软件，早上在issues里面发现了@Iridescent-me分享的一个预[处理配置文件（parser）](https://github.com/Fndroid/clash_for_windows_pkg/issues/2193)，很是感谢。但是他使用的配置不是很符合我的习惯，于是根据自己的使用习惯进行一些修改。

>把最下面的代码复制进去clash-设置-预配置文件覆盖即可。

~~因为还不会复制代码，完整代码复制过来会自动排版导致观感不好，临时有事清空先。~~

唉，好心累。对于一个小白来说，我连怎么在issues粘贴代码都折腾了好久。点击编辑框里面的代码引用一直排版错误，最后终于找到使用方法：代码前后添加3个反引号（`）就可以了，英文状态下tab上面那个。

## 需要注意的点：
1、每个策略组里面都有一个DIRECT（直连），而策略组设置的是延迟优先，默认的延迟地址是可以检测DIRECT的，所以我把延迟检测地址换成了谷歌的，避免软件代理走DIRECT。最好在clash设置里面把延迟检测地址改成谷歌的。**可能有其他方法，但是我不会，最好能在评论区里面说一下，谢谢。**

2、本来是不打算每个策略组都添加一个DIRECT的，但是不添加发现策略组筛选条件无法匹配机场节点时候会报错，~~就这我都懵逼了好久~~，所以只好每个节点都添加一个DIRECT上去了。
>举个例子：策略组筛选所有带“香”字的节点，但是机场节点没有香港节点，这个时候clash就会报错，提示"proxy group:use or proxy is missinig"。

3、目前这个分流规则对于epic、steam不是很好，我刚刚更新游戏的时候发现epic走的是代理，节点流量不够的朋友需要注意点。换成直接模式再更新或者把分流规则添加进来。

4、因为分流规则比较多，可能会提示网络错误，多试几次就行了。或者去分流规则作者那边[下载规则](https://github.com/Loyalsoldier/clash-rules)放在clash目录ruleset文件里。

5、这个配置使用的是白名单模式，假如有一个网站，可以直连访问，但是分流规则里面没有这个网址，那么clash会走代理去访问这个网站。这样对于节点流量不多的朋友可能比较麻烦，你可以把代码中的
> \- MATCH,PROXY

把“PROXY”改成“DIRECT"就好了，即改成黑名单模式。分流规则匹配不到的通通走直连，避免过多浪费节点流量。

## 代码

```
parsers:`` # array
  - reg: ^.*$  
  # - reg: ^.*$ 匹配所有订阅，或  - url: https://example.com/profile.yaml 指定订阅
  # 下面是删除服务商自带的策略组和规则
    code: |
      module.exports.parse = (raw, { yaml }) => {
        const rawObj = yaml.parse(raw)
        const groups = []
        const rules = []
        return yaml.stringify({ ...rawObj, 'proxy-groups': groups, rules })
      } 
  # 建立自己的配置
    yaml:
      prepend-proxy-groups: # 建立策略组
      - name: PROXY
        type: fallback
        url: http://www.google.com/generate_204
        interval: 300
        proxies:
         - 香港
         - 台湾
         - 日本
         - 新加坡
         - 韩国
         - 美国
         - 其他

      - name: Netflix
        type: select
      
      - name: 香港 
        type: url-test
        url: http://www.google.com/generate_204
        interval: 300
      
      - name: 台湾 
        type: url-test
        url: http://www.google.com/generate_204
        interval: 300
       
      - name: 日本
        type: url-test
        url: http://www.google.com/generate_204
        interval: 300
        
      - name: 新加坡 
        type: url-test
        url: http://www.google.com/generate_204
        interval: 300
       
      - name: 韩国 
        type: url-test
        url: http://www.google.com/generate_204
        interval: 300
       
      - name: 美国 
        type: url-test
        url: http://www.google.com/generate_204
        interval: 300
       
      - name: 其他 
        type: url-test
        url: http://www.google.com/generate_204
        interval: 300
              
  # 策略组示例
      # - name: 分组名
        # type: select       # 手动选点   
        # url-test     # 自动选择延迟最低的节点
        # fallback     # 节点故障时自动切换下一个
        # laod-balance # 均衡使用分组内的节点
        # url: http://www.gstatic.com/generate_204 # 测试地址 非select类型分组必要
        # interval: 300 # 自动测试间隔时间，单位秒 非select类型分组必要
        # tolerance: 50 # 允许的偏差，节点之间延迟差小于该值不切换 非必要
        # proxies:  
          # - 节点名称或其他分组套娃
          
      commands:
        - proxy-groups.Netflix.proxies=[]proxyNames|奈飞|nf|解锁
        - proxy-groups.香港.proxies=[]proxyNames|香港 # 向指定策略组添加订阅中的节点名，可使用正则过滤
        - proxy-groups.台湾.proxies=[]proxyNames|台
        - proxy-groups.日本.proxies=[]proxyNames|日本
        - proxy-groups.韩国.proxies=[]proxyNames|韩国
        - proxy-groups.新加坡.proxies=[]proxyNames|新加坡
        - proxy-groups.美国.proxies=[]proxyNames|美国
        - proxy-groups.其他.proxies=[]proxyNames|^[^香日台新韩美]*$ # 这个可以自定义，这个正则的意思是排除节点名字有“香日台新韩美”的节点。

       # 为各个策略组添加一个DIRECT，避免机场节点无法匹配上面的正则筛选而导致配置出错。应该有其他办法避免，但是我不会。
        - proxy-groups.Netflix.proxies.0+DIRECT
        - proxy-groups.香港.proxies.0+DIRECT
        - proxy-groups.台湾.proxies.0+DIRECT
        - proxy-groups.日本.proxies.0+DIRECT
        - proxy-groups.韩国.proxies.0+DIRECT
        - proxy-groups.新加坡.proxies.0+DIRECT
        - proxy-groups.美国.proxies.0+DIRECT
        - proxy-groups.其他.proxies.0+DIRECT

        # - proxy-groups.节点名字.proxies.0+DIRECT # 向指定分组第一个位置添加一个 DIRECT 节点名
        # 一些可能用到的正则过滤节点示例，使分组更细致
        # []proxyNames|a                         # 包含a
        # []proxyNames|^(.*)(a|b)+(.*)$          # 包含a或b
        # []proxyNames|^(?=.*a)(?=.*b).*$        # 包含a和b
        # []proxyNames|^((?!b).)*a((?!b).)*$     # 包含a且不包含b
        # []proxyNames|^((?!b|c).)*a((?!b|c).)*$ # 包含a且不包含b或c
        # 更多正则教程，请看这里：https://deerchao.cn/tutorials/regex/regex.htm#top
        
  # 添加规则
      prepend-rules: # 规则由上往下遍历，如上面规则已经命中，则不再往下处理
        - RULE-SET,netflix,Netflix
        - RULE-SET,applications,DIRECT
        - DOMAIN,clash.razord.top,DIRECT
        - DOMAIN,yacd.haishan.me,DIRECT
        - RULE-SET,private,DIRECT
        - RULE-SET,reject,REJECT
        - RULE-SET,icloud,DIRECT #
        - RULE-SET,apple,DIRECT # 这三个为国内可直连地址，如果希望走代理改为PROXY
        - RULE-SET,google,DIRECT # 
        - RULE-SET,tld-not-cn,PROXY
        - RULE-SET,gfw,PROXY
        - RULE-SET,greatfire,PROXY
        - RULE-SET,telegramcidr,PROXY
        - RULE-SET,lancidr,DIRECT
        - RULE-SET,cncidr,DIRECT
        - GEOIP,,DIRECT
        - GEOIP,CN,DIRECT
        - RULE-SET,direct,DIRECT
        - RULE-SET,proxy,PROXY
        - MATCH,PROXY # 规则之外的，在这里来修改是白名单模式还是黑名单模式，把“PROXY”改成“DIRECT"就好了。
  # 添加规则集
      mix-rule-providers: 
        reject: # 广告域名列表
          type: http
          behavior: domain
          url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
          path: ./ruleset/reject.yaml
          interval: 86400
          
        icloud: # iCloud 域名列表
          type: http
          behavior: domain
          url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
          path: ./ruleset/icloud.yaml
          interval: 86400
          
        apple: # Apple 在中国大陆可直连的域名列表
          type: http
          behavior: domain
          url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
          path: ./ruleset/apple.yaml
          interval: 86400
          
        google: # Google 在中国大陆可直连的域名列表
          type: http
          behavior: domain
          url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
          path: ./ruleset/google.yaml
          interval: 86400
          
        proxy: # 代理域名列表
          type: http
          behavior: domain
          url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
          path: ./ruleset/proxy.yaml
          interval: 86400
          
        direct: # 直连域名列表
          type: http
          behavior: domain
          url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
          path: ./ruleset/direct.yaml
          interval: 86400
          
        private: # 私有网络专用域名列表
          type: http
          behavior: domain
          url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
          path: ./ruleset/private.yaml
          interval: 86400
          
        gfw: # GFWList 域名列表
          type: http
          behavior: domain
          url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
          path: ./ruleset/gfw.yaml
          interval: 86400
          
        greatfire: # GreatFire 域名列表
          type: http
          behavior: domain
          url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
          path: ./ruleset/greatfire.yaml
          interval: 86400
          
        tld-not-cn: # 非中国大陆使用的顶级域名列表
          type: http
          behavior: domain
          url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
          path: ./ruleset/tld-not-cn.yaml
          interval: 86400
          
        telegramcidr: # Telegram 使用的 IP 地址列表
          type: http
          behavior: ipcidr
          url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
          path: ./ruleset/telegramcidr.yaml
          interval: 86400
          
        cncidr: # 中国大陆 IP 地址列表
          type: http
          behavior: ipcidr
          url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
          path: ./ruleset/cncidr.yaml
          interval: 86400
          
        lancidr: # 局域网 IP 及保留 IP 地址列表
          type: http
          behavior: ipcidr
          url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
          path: ./ruleset/lancidr.yaml
          interval: 86400
          
        applications: # 需要直连的常见软件列表
          type: http
          behavior: classical
          url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
          path: ./ruleset/applications.yaml
          interval: 86400

        netflix: # 奈飞的分流规则
          type: http
          behavior: classical
          url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Netflix/Netflix.yaml"
          path: ./ruleset/netflix.yaml
          interval: 86400
```
