### ISSUE TITLE
OneDrive 同步配置文件

### ISSUE THREAD

**Issue by msdurex** [Fndroid/clash_for_windows_pkg#274]
希望能够支持 OneDrive 同步配置文件，这样可以多人之间共享方便共享配置。

**Comment by RunningMelos** [comment]
可以考虑下 github gist 的私密文档功能？

**Comment by xjasonlyu** [comment]
+1，其实只要能自定义profile路径就可以做到用OD，GD之类的进行同步了 @Fndroid

**Comment by Fndroid** [comment]
> +1，其实只要能自定义profile路径就可以做到用OD，GD之类的进行同步了 @Fndroid

https://github.com/Fndroid/clash_for_windows_pkg/releases/tag/0.8.5

**Comment by xjasonlyu** [comment]
### 更新速度给力！

不过这里有个问题：
profile路径下的list.yml配置文件
```yaml
files:
  - url: ""
    time: 1.yml
  - url: ""
    time: 2.yml
index: 0
```
客户端A切换profile的之后`index`值会改变，导致其他客户端也会随着改变profile。
个人感觉profile目录下仅用来存放上下文无关的配置文件会比较好一点。
