### ISSUE TITLE
[Bug]: CFW主面板 `TUN Mode` 设置无法同步 `config.yaml` 配置项内容。

### ISSUE THREAD

**Issue by signigelchan** [Fndroid/clash_for_windows_pkg#2759]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.11

### 操作系统

Windows x64

### 系统版本

Winodws 10 21H2

### 问题描述

查阅了 [CFW Docs](https://docs.cfw.lbyczf.com/contents/quickstart.html) TUN模式相关内容说明；
配置TUN模式过程中发现配置文件 `config.yaml` 中的 `dns` 和 `tun` 配置项内容无法同步显示在 CFW `General` 中的 `TUN mode` 子编辑面板中 （ `config.yaml` 开关 `dns` 及 `tun` 启用状态均无效）；
另外 TUN 面板中只能修改 `DNS` 及 `TUN` 相关设置，无法更改 `enhanced-mode` 类型。

不太清楚CFW的TUN设置逻辑是只能通过面板设置，而忽略 `config.yaml` 文件中的相关配置项？
(记得CFW的设置文件 `cfw-settings.yaml` 会忽略 `config.yaml` 相关的 `Basic Setting` )

> 感谢开发者一直以来的版本迭代及功能更新，对整个CLASH圈子带来的丰富生态！

![image](https://user-images.githubusercontent.com/20301894/156887165-b87332e7-1d8f-4e33-ac54-90fd0159f36d.png)
![image](https://user-images.githubusercontent.com/20301894/156887242-366883d4-3e9f-4c2c-b0b4-8dddb8bd6fed.png)
![image](https://user-images.githubusercontent.com/20301894/156887277-2dd9614f-798e-4570-8974-d827e8222ad6.png)

### 复现步骤

CFW主面板 -> `General` -> `TUN Mode` 右边的小齿轮，打开 TUN设置子面板。
显示为CFW默认的配置，而非 `config.yaml` 中的配置项。

### 日志文件

<details><summary>logs</summary><p>

```
查看的log文件，无有效可参考的日志内容。
```

</p></details>

**Comment by SSgumS** [comment]
Hello
I think your configuration is not right. `tun` section must be declared in the root, not under `dns` section.
But based on my tests, CFW doesn't respect anything about `tun`. If you fix your configuration file, it again uses its own `tun` settings.
What I did to reach to the statement above:
- adding `tun` section to my own configuration -> CFW didn't reflect my `dns-hijack` addresses and still used `192.18.0.2`
- changing `dns-hijack` addresses in CFW GUI -> again nothing changed and the new tun interface, was using `192.18.0.2`

The `tun` interface created:
![image](https://user-images.githubusercontent.com/25867589/156888886-74444a17-ae75-4c9e-b33e-4d329b9aac4f.png)

CFW GUI:
![image](https://user-images.githubusercontent.com/25867589/156888919-0dbe6cbf-46e4-4439-b88f-13b6610746a2.png)

**Comment by Fndroid** [comment]
tun settings不会同步到config.yaml，设计上就是这样，它只作为一个开关，不会更改任何配置文件

**Comment by SSgumS** [comment]
> tun settings are not synced to config.yaml, that's by design, it only acts as a switch and doesn't change any config files

Is this behavior from Core or CFW? Shouldn't it respect the configuration?

Think about this situation:

1. I have a configuration that uses `tun`. Here is an example:
```
mixed-port: 7890
allow-lan: false
bind-address: '*'
mode: rule
log-level: debug
ipv6: true
external-controller: 127.0.0.1:9090

profile:
  store-selected: true

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - 1.1.1.1
    - 208.67.222.222
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://doh.opendns.com/dns-query"

tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - 127.0.0.1:53

proxies:
  - name: "x"
    type: vmess
    server: 100.100.100.100
    port: 2083
    uuid: xyz
    alterId: 0
    cipher: none
    udp: true
    tls: true
    skip-cert-verify: true
    servername: xyz.xyz.xyz

proxy-groups:
  - name: Proxy
    type: select
    lazy: true
    proxies:
      - x

rules:
  - MATCH,Proxy
```

2. Because of my config file (I didn't enable `tun` option in the GUI), CFW creates a `tun` interface. The `dns-hijack` field in the created interface would be `192.18.0.2` (That is not my desired value [127.0.0.1] and I don't use `fake-ip` in my settings). Like the image bellow:
![image](https://user-images.githubusercontent.com/25867589/156890158-74dcab50-81da-43f5-9d87-6e9fd2db6fb3.png)

3. All my Direct dns resolutions will fail! If I use the local proxy created by Clash everything is ok, but traffics that doesn't go through Clash (like Powershell's traffic) can't resolve dns resolutions. Naturally when I doesn't use the proxy in my browser, no websites can get opened.

The behavior I expected is one of these:
- CFW ignore all `tun` settings and even it doesn't enable it if it was specified in the yaml file
- CFW doesn't ignore `tun` settings and create an interface with desired values, not a default `192.18.0.2` dns value.

What do you think?
