### ISSUE TITLE
[Bug]: TUN-监听着16384个UDP端口-路由表好像不对-疯狂建立、断开、重建TCP连接

### ISSUE THREAD

**Issue by slusludy** [Fndroid/clash_for_windows_pkg#2763]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.11

### 操作系统

Windows x64

### 系统版本

21H1 19043.1526 无Hyper-V

### 问题描述

TUN 模式下
- 进程 `clash-win64.exe`
  - 用本机的几个 TCP 端口向墙外服务器及正确的端口成功建立了 TCP 连接，然后断开，然后重连，就这样死循环
  - 监听着本机 UDP `49152 ~ 65535` 端口，共计 `2^14=16384` 个
  - 占满 CPU
  - 占用的内存以大约 2 MiB/s 的速度增加
- 墙内外的网都上不了
- 与开启 TUN 模式前相比，新增了如下的路由表条目，感觉掩码不对，掩码应该是 `0.0.0.0` 吧
```
Network Destination        Netmask          Gateway       Interface  Metric
            0.0.0.0      128.0.0.0       198.18.0.2      198.18.0.1       0
```
于是在仍处于 TUN 模式时把上面的条目的掩码改为了 `0.0.0.0` ，新条目为
```
Network Destination        Netmask          Gateway       Interface  Metric
            0.0.0.0        0.0.0.0       198.18.0.2      198.18.0.1      50
```
50 仍是目的地址为 `0.0.0.0` 的所有条目中最小的 `Metric` ，但仍不能上网， CPU 、内存和网络端口仍被大量占用

禁用 TUN 且禁用 TAP ，将 Clash 设为系统代理，可以正常翻墙
我在 2022 年 1 月成功地运行过 TUN 模式，但不记得那时用的 Clash 的版本，日志文件已不存在，没看过路由表，没看过监听着哪些端口

根据 #2587 #2630 #2695 ，可能是 Clash 内核有 Bug

### 复现步骤

开启 TUN 模式

### 日志文件

<details><summary>logs</summary><p>

```
下面的内容刷屏
time="2022-03-05T20:19:52+08:00" level=warning msg="[TCP] dial GLOBAL to 墙外服务器IP:443 error: dial 墙外服务器IP:443 error: read tcp4 192.168.1.2:14477->墙外服务器IP:443: i/o timeout"
time="2022-03-05T20:19:59+08:00" level=warning msg="[TCP] dial GLOBAL to 墙外服务器IP:443 error: dial 墙外服务器IP:443 error: read tcp4 192.168.1.2:2693->墙外服务器IP:443: wsarecv: An existing connection was forcibly closed by the remote host."
time="2022-03-05T20:20:16+08:00" level=warning msg="[UDP] dial GLOBAL to 223.5.5.5:53 error: new vmess client error: dial 墙外服务器IP:443 error: read tcp4 192.168.1.2:12712->墙外服务器IP:443: i/o timeout"
time="2022-03-05T20:20:18+08:00" level=warning msg="[UDP] dial GLOBAL to 223.5.5.5:53 error: new vmess client error: dial 墙外服务器IP:443 error: read tcp4 192.168.1.2:4012->墙外服务器IP:443: wsarecv: An existing connection was forcibly closed by the remote host."
```

</p></details>

### 其他补充

试过 [#2587 下的这个方法](https://github.com/Fndroid/clash_for_windows_pkg/issues/2587#issuecomment-1013806758) ：将 Clash 内核从默认的 `2022.01.27 Premium` 升级到 [`n2022-03-04-gb1b7648 Premium`](https://clash-nightly.kaslr.com/clash-windows-amd64-n2022-03-04-gb1b7648.zip) ，但仍无法解决问题

无 mixin ， TUN 的配置为默认，配置文件为下列内容 + 墙外服务器信息：
```
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
  use-hosts: false
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - https://dns.alidns.com/dns-query
```

墙外服务器里的 nginx 和 v2ray 日志显示，完全没有收到过 clash 的请求

**Comment by Fndroid** [comment]
tun怎么配置的

**Comment by slusludy** [comment]
> tun怎么配置的

试过默认配置、仅将 `stack` 切换为 `system` 、 仅手动指定接口名称（WLAN、以太网、本地连接等），现在在用默认配置，如下
```
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
  fake-ip-filter:
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
tun:
  enable: true
  stack: gvisor
  auto-detect-interface: true
  auto-route: true
  dns-hijack:
    - 198.18.0.2:53
```
