### ISSUE TITLE
[Bug]: UDP not working at all?

### ISSUE THREAD

**Issue by ifoverload** [Fndroid/clash_for_windows_pkg#2843]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.13

### 操作系统

Windows x64

### 系统版本

Windows 10 Pro x64, Version 21H2, Os Build 19044.1586

### 问题描述

Hi,
Can it traffic UDP? why it seems there is no any UDP connection connected to my computer.
so as a result any udp application cannot open properly. eg: steam, telegram, etc..
I know for telegram i can just set manual proxy and route it to mixed port, and it worked!

But my point is how to make it globally work? as many application are don't have proxy settings.
I read from some related issues that i have to try with "Tap Device" option. But it just not work (or my settings is wrong)
I dont change any settings i keep it default. except for my Profiles & Proxies ofcourse..

UPDATE: Also Cannot connect voice discord.
![code](https://img001.prntscr.com/file/img001/Qugol7i2TvyvNJySVa3bHQ.png)
<br />
<details><summary>myprofiles.txt</summary><p>

```
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
mode: rule
log-level: debug
allow-lan: true
external-controller: 0.0.0.0:9090
bind-address: "*"
unified-delay: true
ipv6: false
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7894
  fallback-filter:
    geoip: false
    ipcidr:
    - 240.0.0.0/4
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - tls://1.1.1.1:853
    - tls://8.8.8.8:853
  fallback:
    - tcp://1.1.1.1
    - tcp://8.8.8.8
    - 1.1.1.1
    - 8.8.8.8
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "+.*"
  - "+.media.dssott.com"
  - "*.mcdn.bilivideo.cn"
  - "*.home.arpa"
  - "*.local"
  - "*.test"
  - "*.localhost"
  - "*.invalid"
  - "*.example"
  - "*.localdomain"
  - "*.lan"

proxies:
  - {name: v2ray-0, server: xxx, port: 443, type: vmess, uuid: xxx, sni: xxx, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: xxx, headers: {Host: xxx }}}
  - {name: v2ray-1, server: xxx, port: 443, type: vmess, uuid: xxx, sni: xxx, alterId: 0, cipher: auto, tls: true, skip-cert-verify: true, udp: true, network: ws, ws-opts: {path: xxx, headers: {Host: xxx }}}

proxy-groups:
  - name: lb-v2ray
    udp: true
    disable-udp: false
    type: load-balance
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    strategy: consistent-hashing
    proxies:
      - v2ray-0
      - v2ray-1
  
rules:
 - MATCH,lb-v2ray
```

</p></details>

<details><summary>pictures</summary><p>

![code](https://img001.prntscr.com/file/img001/ZWTLDKWHQqCRGeJV41Vjjg.jpg)
![code](https://img001.prntscr.com/file/img001/3OH_gGarSnGhWYVjOJHlNA.jpg)
![code](https://img001.prntscr.com/file/img001/nB3_QCeRRKSYiLHWieqM0g.jpg)
![code](https://img001.prntscr.com/file/img001/C2rzwENXRGCYIvJqq3o2Eg.png)
![code](https://img001.prntscr.com/file/img001/Mwcw8pQRSN-Kl0w6tlgmKQ.jpg)

</p></details>

### 复现步骤

--

### 日志文件

<details><summary>logs</summary><p>

```
time="2022-03-30T04:16:33+07:00" level=info msg="RESTful API listening at: 127.0.0.1:1039"
time="2022-03-30T04:16:33+07:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:7890"
time="2022-03-30T04:16:33+07:00" level=info msg="Start initial compatible provider lb-v2ray"
time="2022-03-30T04:16:33+07:00" level=info msg="DNS server listening at: [::]:7894"
time="2022-03-30T04:16:37+07:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2022-03-30T04:16:38+07:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:7890"
time="2022-03-30T04:16:47+07:00" level=info msg="[TCP] 127.0.0.1:1095 --> www.youtube.com:443 using GLOBAL"
time="2022-03-30T04:16:48+07:00" level=info msg="[TCP] 127.0.0.1:1097 --> beacons.gvt2.com:443 using GLOBAL"
time="2022-03-30T04:16:55+07:00" level=warning msg="[TCP] dial GLOBAL to alive.github.com:443 error: id4.v2-ray.com:443 connect error: dial tcp4 210.247.245.115:443: i/o timeout"
time="2022-03-30T04:16:55+07:00" level=info msg="[TCP] 127.0.0.1:1139 --> alive.github.com:443 using GLOBAL"
time="2022-03-30T04:16:56+07:00" level=info msg="Start initial compatible provider lb-v2ray"
time="2022-03-30T04:16:58+07:00" level=info msg="Start initial compatible provider lb-v2ray"
time="2022-03-30T04:16:58+07:00" level=info msg="DNS server listening at: [::]:7894"
time="2022-03-30T04:17:04+07:00" level=info msg="Start initial compatible provider lb-v2ray"
time="2022-03-30T04:17:15+07:00" level=warning msg="[TCP] dial lb-v2ray (match Match/) to alive.github.com:443 error: id-lb.sshkit.org:443 connect error: dial tcp4 41.216.178.204:443: i/o timeout"
time="2022-03-30T04:17:15+07:00" level=info msg="[TCP] 127.0.0.1:1241 --> alive.github.com:443 match Match() using lb-v2ray[v2ray-0]"
time="2022-03-30T04:17:15+07:00" level=info msg="[TCP] 127.0.0.1:1235 --> www.bing.com:443 match Match() using lb-v2ray[v2ray-0]"
time="2022-03-30T06:11:13+07:00" level=info msg="[TCP] 127.0.0.1:5109 --> www.gstatic.com:443 match Match() using lb-v2ray[v2ray-2]"
time="2022-03-30T06:11:18+07:00" level=info msg="[TCP] 127.0.0.1:5116 --> steamcommunity.com:443 match Match() using lb-v2ray[v2ray-3]"
time="2022-03-30T06:11:18+07:00" level=info msg="[TCP] 127.0.0.1:5118 --> steamcommunity.com:443 match Match() using lb-v2ray[v2ray-3]"
time="2022-03-30T06:11:45+07:00" level=info msg="[TCP] 127.0.0.1:5155 --> mtalk.google.com:5228 match Match() using lb-v2ray[v2ray-3]"
```

</p></details>

### 其他补充

--

**Comment by ifoverload** [comment]
any help...

**Comment by yi-Xu-0100** [comment]
The profile seems set the mixed-port as 7893, but the system proxy use the 7890, and the logs show the mixed-port as 7890, I do not konw which is correct.

You said that the proxy setting in telegram with mixed-port work good, maybe you need to use pac mode and set the order for http proxy and socks proxy.

**Comment by ifoverload** [comment]
> The profile seems set the mixed-port as 7893, but the system proxy use the 7890, and the logs show the mixed-port as 7890, I do not konw which is correct.
> 
> You said that the proxy setting in telegram with mixed-port work good, maybe you need to use pac mode and set the order for http proxy and socks proxy.

Yes after i wrote this issue, i looking carefully and i realized that port. so i tried make some changes to my config:
```
mixed-port: 7890 #line 1
allow-lan: true
mode: global
log-level: debug
ipv6: true
profile:
  store-selected: true
  store-fake-ip: true
...
#and turning off the loadbalance method (load only 1 proxy)
```
<details><summary>the log said:</summary><p>

```
level=info msg="RESTful API listening at: 127.0.0.1:65278"
level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
level=info msg="Start initial compatible provider lb-trojan"
level=info msg="DNS server listening at: [::]:7894"
level=info msg="Start initial compatible provider lb-trojan"
level=info msg="Start initial compatible provider lb-trojan"
level=info msg="Start initial compatible provider lb-trojan"
level=info msg="DNS server listening at: [::]:7894"
level=info msg="Mixed(http+socks) proxy listening at: [::]:7890"
level=debug msg="Generate GUID: {***}"
level=info msg="Tun Proxy listening at: Clash(198.18.0.1)"
```

</p></details>
<details><summary>i edited for telegram is working with TCP:</summary><p>

![code](https://img001.prntscr.com/file/img001/TeRATx-ZRfCSY_ZTrDWz5A.png)

</p></details>

i have tried with "PAC" mode of System Proxy option but got the same result.
> and set the order for http proxy and socks proxy.

@yi-Xu-0100 How to do so?
