### ISSUE TITLE
TUN模式开启后，在安卓模拟器里的APP无法联网

### ISSUE THREAD

**Issue by ureuerae** [Fndroid/clash_for_windows_pkg#2874]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.13

### 操作系统

Windows x64

### 系统版本

WIN10专业版20H2

### 问题描述

TUN模式下，安卓模拟器里面浏览器可用正常联网，YouTube APP里无法播放视频，tiktok显示网络错误

### 复现步骤

安装雷电模拟器4 - 开启cfw TUN模式 - 启动雷电模拟器 - 打开相应app测试

### 日志文件

<details><summary>logs</summary><p>

```
mixed-port: 7890
mode: Rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
proxies:
 -  socks#服务器...
 
proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 自动选择
      - socks
  - name: 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 500
    proxies:
      - socks
rules:
 - DOMAIN-SUFFIX,local,DIRECT
 - IP-CIDR,192.168.0.0/16,DIRECT
 - IP-CIDR,10.0.0.0/8,DIRECT
 - IP-CIDR,172.16.0.0/12,DIRECT
 - IP-CIDR,127.0.0.0/8,DIRECT
 - IP-CIDR,100.64.0.0/10,DIRECT
 - IP-CIDR,0.0.0.0/8,DIRECT
 - IP-CIDR,169.254.0.0/16,DIRECT
 - IP-CIDR,192.0.0.0/24,DIRECT
 - IP-CIDR,192.0.2.0/24,DIRECT
 - IP-CIDR,192.88.99.0/24,DIRECT
 - IP-CIDR,198.18.0.0/15,DIRECT
 - IP-CIDR,198.51.100.0/24,DIRECT
 - IP-CIDR,203.0.113.0/24,DIRECT
 - IP-CIDR,224.0.0.0/3,DIRECT
 - IP-CIDR6,::1/128,DIRECT
 - IP-CIDR6,fc00::/7,DIRECT
 - IP-CIDR6,fe80::/10,DIRECT
 - IP-CIDR6,fd00::/8,DIRECT
 - GEOIP,CN,DIRECT
 - MATCH,节点选择
```

</p></details>

### 其他补充

这是什么原因，需要怎么设置吗？
