### ISSUE TITLE
如何使用配置文件预处理删除或者覆盖rules？

### ISSUE THREAD

**Issue by Mistake1126** [Fndroid/clash_for_windows_pkg#2907]
实在不想伸手，小白看不明白CFW的文档，只能来这求助
假设订阅配置的rules有一条“  - DOMAIN-SUFFIX,example.com,Direct”
可以将这条规则覆盖成“  - DOMAIN-SUFFIX,example.com,Proxy”，或是直接将这条规则删除吗
另外可以将配置文件预处理应用于所有订阅的配置吗，目前是这样写的，预处理只能应用于这个域名的订阅的配置
```
parsers:
  - reg: https://example.com.+$
    yaml:
      prepend-rules:
        - DOMAIN-SUFFIX,example.com,Proxy
```
