### ISSUE TITLE
[提问/反馈]: 开启TUN后无法连接至discord语音服务器 (报错"没有路径(no route)")

### ISSUE THREAD

**Issue by ZippyRhys** [Fndroid/clash_for_windows_pkg#2912]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.15 (p核版本4/14/2022)

### 操作系统

Windows x64

### 系统版本

21H1, build 19043.1645

### 问题描述

不开启系统代理并使用TUN模式的情况下连接dc语音会报错`没有路径(no route)`；单独开启系统代理的情况下则正常。重启电脑无效，无论使用自己的mixin配置还是默认TUN配置都报一样的错误，不知道这是什么问题？已搜索过现存的相关issue，但是没能总结出有效的解决方法(也有可能我浏览时有疏漏，有的话请指路)，请求解答，十分感谢！

### 复现步骤

重启电脑，启动CFW，点按TUN模式(或者mixin)开关开启TUN，启动discord后随意进入一个语音频道，报错。

### 日志文件

<details><summary>logs</summary><p>

```
time="2022-04-15T19:41:01+08:00" level=info msg="RESTful API listening at: 127.0.0.1:7658"
time="2022-04-15T19:41:01+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7891"
time="2022-04-15T19:41:02+08:00" level=info msg="Start initial compatible provider 🌍 国外媒体"
.
._此处为省略_
.
time="2022-04-15T19:41:02+08:00" level=info msg="Start initial compatible provider Ⓜ️ 微软云盘"
time="2022-04-15T19:41:02+08:00" level=debug msg="Generate GUID: {330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}"
time="2022-04-15T19:41:02+08:00" level=info msg="Tun Proxy listening at: Clash(198.18.0.1)"
time="2022-04-15T19:41:08+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2022-04-15T19:41:08+08:00" level=debug msg="[Process] discord.com from process \\Device\\HarddiskVolume3\\Users\\zippy\\AppData\\Local\\Discord\\app-1.0.9004\\Discord.exe"
time="2022-04-15T19:41:08+08:00" level=debug msg="[DNS] discord.com --> 108.160.172.1"
time="2022-04-15T19:41:08+08:00" level=info msg="[TCP] 198.18.0.1:12897 --> discord.com:443 match DomainSuffix(discord.com) using 🚀 全局设置[IPLC专线｜沪港 [1.5]]"
time="2022-04-15T19:41:08+08:00" level=debug msg="[TUN] hijack udp dns: 198.18.0.2:53"
time="2022-04-15T19:41:08+08:00" level=debug msg="[Process] hongkong7656.discord.media from process \\Device\\HarddiskVolume3\\Users\\zippy\\AppData\\Local\\Discord\\app-1.0.9004\\Discord.exe"
time="2022-04-15T19:41:08+08:00" level=debug msg="[DNS] hongkong7656.discord.media --> 162.159.137.234"
time="2022-04-15T19:41:09+08:00" level=info msg="[TCP] 198.18.0.1:3108 --> hongkong7656.discord.media:443 match DomainSuffix(discord.media) using 🚀 全局设置[IPLC专线｜沪港 [1.5]]"
time="2022-04-15T19:41:09+08:00" level=debug msg="[Process] 43.239.139.136 from process \\Device\\HarddiskVolume3\\Users\\zippy\\AppData\\Local\\Discord\\app-1.0.9004\\Discord.exe"
time="2022-04-15T19:41:09+08:00" level=debug msg="[Process] 43.239.139.136 from process \\Device\\HarddiskVolume3\\Users\\zippy\\AppData\\Local\\Discord\\app-1.0.9004\\Discord.exe"
time="2022-04-15T19:41:09+08:00" level=info msg="[UDP] 198.18.0.1:56564 --> 43.239.139.136:50005 match Match() using 🐟 其他网站[IPLC专线｜沪港 [1.5]]"
time="2022-04-15T19:41:09+08:00" level=info msg="[UDP] 198.18.0.1:56565 --> 43.239.139.136:50005 match Match() using 🐟 其他网站[IPLC专线｜沪港 [1.5]]"
time="2022-04-15T19:41:17+08:00" level=debug msg="[Process] hongkong7656.discord.media from process \\Device\\HarddiskVolume3\\Users\\zippy\\AppData\\Local\\Discord\\app-1.0.9004\\Discord.exe"
time="2022-04-15T19:41:17+08:00" level=debug msg="[DNS] hongkong7656.discord.media --> 162.159.138.234"
time="2022-04-15T19:41:17+08:00" level=info msg="[TCP] 198.18.0.1:12605 --> hongkong7656.discord.media:443 match DomainSuffix(discord.media) using 🚀 全局设置[IPLC专线｜沪港 [1.5]]"
time="2022-04-15T19:41:17+08:00" level=debug msg="[Process] 43.239.139.136 from process \\Device\\HarddiskVolume3\\Users\\zippy\\AppData\\Local\\Discord\\app-1.0.9004\\Discord.exe"
time="2022-04-15T19:41:17+08:00" level=debug msg="[Process] 43.239.139.136 from process \\Device\\HarddiskVolume3\\Users\\zippy\\AppData\\Local\\Discord\\app-1.0.9004\\Discord.exe"
time="2022-04-15T19:41:17+08:00" level=info msg="[UDP] 198.18.0.1:55153 --> 43.239.139.136:50005 match Match() using 🐟 其他网站[IPLC专线｜沪港 [1.5]]"
time="2022-04-15T19:41:17+08:00" level=info msg="[UDP] 198.18.0.1:55152 --> 43.239.139.136:50005 match Match() using 🐟 其他网站[IPLC专线｜沪港 [1.5]]"
```

</p></details>

### 其他补充

mixin配置: 
```
mixin: 
   hosts:
     'mtalk.google.com': 108.177.125.188
     'services.googleapis.cn': 74.125.203.94
     'raw.githubusercontent.com': 151.101.76.133
   dns:
    enable: true
    ipv6: false
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter:
      - "*.lan"
      - "*.local"
      - dns.msftncsi.com
      - www.msftncsi.com
      - www.msftconnecttest.com
      - stun.*.*.*
      - stun.*.*
      - miwifi.com
      - music.163.com
      - "*.music.163.com"
      - "*.126.net"
      - api-jooxtt.sanook.com
      - api.joox.com
      - joox.com
      - y.qq.com
      - "*.y.qq.com"
      - streamoc.music.tc.qq.com
      - mobileoc.music.tc.qq.com
      - isure.stream.qqmusic.qq.com
      - dl.stream.qqmusic.qq.com
      - aqqmusic.tc.qq.com
      - amobile.music.tc.qq.com
      - "*.xiami.com"
      - "*.music.migu.cn"
      - music.migu.cn
      - netis.cc
      - router.asus.com
      - repeater.asus.com
      - routerlogin.com
      - routerlogin.net
      - tendawifi.com
      - tendawifi.net
      - tplinklogin.net
      - tplinkwifi.net
      - tplinkrepeater.net
      - "*.ntp.org.cn"
      - "*.openwrt.pool.ntp.org"
      - "*.msftconnecttest.com"
      - "*.msftncsi.com"
      - localhost.ptlogin2.qq.com
      - "*.*.*.srv.nintendo.net"
      - "*.*.stun.playstation.net"
      - xbox.*.*.microsoft.com
      - "*.ipv6.microsoft.com"
      - "*.*.xboxlive.com"
      - speedtest.cros.wr.pvp.net
      - www.tsdm39.net
      - "*.steamcontent.com"
      - www.speedrun.com
    default-nameserver:
      - 119.29.29.29
      - 223.5.5.5
      - 8.8.4.4
    nameserver:
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
      - https://dns.google/dns-query
   tun: 
     enable: true
     stack: gvisor
     dns-hijack:
       - 198.18.0.2:53
     auto-route: true
     auto-detect-interface: true  #自动检测出口网卡
```

TUN模式开关内的配置为默认值.
