### ISSUE TITLE
[求助]: 内网配代理使用时，dns解析有问题

### ISSUE THREAD

**Issue by wgf4242** [Fndroid/clash_for_windows_pkg#2916]
### 功能描述

我用这个内网代理访问时上不了网，看log。查到google dns解析不了。怎么配dns?
proxy
```
  - name: "http"
    type: http
    server: proxy.lan.test
    port: 8080
```
config.yml 配了没作用。
```
dns:
  enable: true
  nameserver:
    - 10.10.10.28
```
![image](https://user-images.githubusercontent.com/3336626/163654025-7e3df06f-a4e2-4fcb-b3cd-89f417cc7883.png)

**Comment by yi-Xu-0100** [comment]
nameserver 配置主要看 parser，diff，mixin，tun 配置，和订阅配置默认包含项。建议检查下内容。

**Comment by wgf4242** [comment]
感谢。。试了下好像是要修改clash\profiles内的配置。不是clash\config.yaml

删除掉dns配置时能用了。我要想保留要怎样修改。。局域网的http配到clash上了。可访问页面了。
但其他服务器无法测速。也无法使用。
![image](https://user-images.githubusercontent.com/3336626/163655076-8cb3f712-7dde-4619-8e0e-136eb9049530.png)


```
dns:
    enable: true
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: redir-host
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['tls://1.0.0.1:853', 'https://cloudflare-dns.com/dns-query', 'https://dns.google/dns-query']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
```

C:\Users\Administrator\.config\clash\profiles\1644124013890.xml
```
  - name: lan-proxy
    type: http
    server: 10.10.10.35
    port: "8080"
proxy-groups:
  - name: relay-group 
    type: relay
    proxies:
      - lan-proxy
      - 蜂巢
  - name: 蜂巢
    type: select
    proxies:
      - 自动选择
      - lan-proxy
      - 故障转移
      - 🇮🇳大宽带预留
      - 🇮🇳印度极速001B
      - 🇮🇳印度极速002B
      - 🇮🇳印度极速003B
      - 🇮🇳印度极速004B
```
