### ISSUE TITLE
[求助]: 节点名中包含特殊字符时如何处理

### ISSUE THREAD

**Issue by lilyblessing** [Fndroid/clash_for_windows_pkg#2917]
### 问题描述

帮助文档中关于定位的描述：https://docs.cfw.lbyczf.com/contents/parser.html#定位
可以使用序号或者name值定位。我的应用场景是将组中个别低速节点删除
``` yaml
      commands:
        # 向策略组添加节点
        - proxy-groups.🔮 香港负载均衡.proxies=[]proxyNames|^(?=(.SSR.*(港|HK)))\1((?!(游戏)).)*$ # 香港负载均衡组

        # 从策略组中删除低速节点
        - proxy-groups.🔮 香港负载均衡.proxies.0- # 香港负载均衡组 HKBN A 按序号定位删除
        - proxy-groups.🔮 香港负载均衡.proxies.2- # 香港负载均衡组 HKBN D 有效，但此时序号顺序变为在删除前一个节点后的重排序顺序
        - proxy-groups.🔮 香港负载均衡.proxies.2- # 香港负载均衡组 HKT A 有效，在重排序后序号重复
        - proxy-groups.🔮 香港负载均衡.proxies.4- # 香港负载均衡组 HKT D 有效
        - proxy-groups.🔮 香港负载均衡.proxies.7- # 香港负载均衡组 HKT H 有效

        # 删除多个节点时重新计算顺序非常不便，所以尝试按name值定位删除
        - proxy-groups.🔮 香港负载均衡.proxies.("[SSR] 🇭🇰 [CT/CM] HKT N")- # 香港负载均衡组 HKT N 无效，变为删除第一个即0号位置节点
```
此组中的节点列表：
```yaml
  - name: 🔮 香港负载均衡
    type: load-balance
    url: http://www.gstatic.com/generate_204
    interval: 120
    proxies:
      - "[SSR] 🇭🇰 [CT/CM] HKBN A"
      - "[SSR] 🇭🇰 [CT/CM] HKBN B"
      - "[SSR] 🇭🇰 [CT/CM] HKBN C"
      - "[SSR] 🇭🇰 [CT/CM] HKBN D"
      - "[SSR] 🇭🇰 [CT/CM] HKT A"
      - "[SSR] 🇭🇰 [CT/CM] HKT B"
      - "[SSR] 🇭🇰 [CT/CM] HKT C"
      - "[SSR] 🇭🇰 [CT/CM] HKT D"
      - "[SSR] 🇭🇰 [CT/CM] HKT E"
      - "[SSR] 🇭🇰 [CT/CM] HKT F"
      - "[SSR] 🇭🇰 [CT/CM] HKT G"
      - "[SSR] 🇭🇰 [CT/CM] HKT H"
      - "[SSR] 🇭🇰 [CT/CM] HKT I"
      - "[SSR] 🇭🇰 [CT/CM] HKT J"
      - "[SSR] 🇭🇰 [CT/CM] HKT K"
      - "[SSR] 🇭🇰 [CT/CM] HKT N"
```
查阅yaml语法后猜测是节点名中包含有中括号[ ]、 🇭🇰、斜杠/等特殊字符，

由于节点列表是用subconverter转换而来，所有节点名均以双引号包裹，而双引号似乎是不会对特殊字符转义的

尝试以单引号引用`proxy-groups.🔮 香港负载均衡.proxies.('[SSR] 🇭🇰 [CT/CM] HKT N')-`

反斜杠转义`proxy-groups.🔮 香港负载均衡.proxies.(\[SSR\] \🇭🇰 \[CT\/CM\] HKT N")-`均无效，均被识别为列表中0号位置的节点

请问该如何按name定位到节点？
