### ISSUE TITLE
[Bug]: 使用tun模式后完全不能用了

### ISSUE THREAD

**Issue by Kobe972** [Fndroid/clash_for_windows_pkg#2966]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.16

### 操作系统

Windows x64

### 系统版本

windows 11

### 问题描述

我的clash用了tun，开始还能用，然后重启电脑以后就不能用了。我把tun禁用并删去了原来照网上编写的yaml文件，结果还是不能用。后来我更新了clash和yml文件，重启了电脑，还用ipconfig/flushdns删掉DNS缓存，仍然不能用。具体是github可以正常连接，google上不去，youtube可以进入主页但显示无法联网。然后我关掉代理再登github，发现github也进不去了。

### 复现步骤

settings/mixin/YAML输入TUN模式配置文件
```
mixin: # object
    dns:
        enable: true
        enhanced-mode: redir-host
        nameserver:
            - 8.8.8.8
            - 119.29.29.29
            - 114.114.114.114
    tun:
        enable: true
        stack: gvisor
        dns-hijack:
            -198.18.0.2:53
        auto-route: true
        auto-detect-interface: true
```
下载service mode插件，打开TUN Mode。此时一切正常。重启电脑后立马不能用了，于是删去service mode组件，关掉TUN Mode，仍然不行。

### 日志文件

<details><summary>logs</summary><p>

```
time="Thu Apr 28 2022 15:22:48 GMT+0800 (中国标准时间)" level=info msg="app start with mode: production"
time="Thu Apr 28 2022 15:22:48 GMT+0800 (中国标准时间)" level=info msg="http server started at: 51153"
time="Thu Apr 28 2022 15:22:48 GMT+0800 (中国标准时间)" level=info msg="load data from general config.yaml"
time="Thu Apr 28 2022 15:22:48 GMT+0800 (中国标准时间)" level=info msg="mixed-port changed"
time="Thu Apr 28 2022 15:22:48 GMT+0800 (中国标准时间)" level=info msg="external controller port changed"
time="Thu Apr 28 2022 15:22:48 GMT+0800 (中国标准时间)" level=info msg="clash axios client changed"
time="Thu Apr 28 2022 15:22:48 GMT+0800 (中国标准时间)" level=info msg="external controller port changed"
time="Thu Apr 28 2022 15:22:48 GMT+0800 (中国标准时间)" level=info msg="clash axios client changed"
time="Thu Apr 28 2022 15:22:49 GMT+0800 (中国标准时间)" level=info msg="restarting clash core..."
time="Thu Apr 28 2022 15:22:49 GMT+0800 (中国标准时间)" level=info msg="new outbound interface: WLAN"
time="Thu Apr 28 2022 15:22:49 GMT+0800 (中国标准时间)" level=info msg="restore at index: 1"
time="Thu Apr 28 2022 15:22:49 GMT+0800 (中国标准时间)" level=info msg="check for app update, current: 0.19.16"
time="Thu Apr 28 2022 15:22:49 GMT+0800 (中国标准时间)" level=info msg="clash core startup success!"
time="Thu Apr 28 2022 15:22:49 GMT+0800 (中国标准时间)" level=info msg="clash status change to [connected]"
time="Thu Apr 28 2022 15:22:49 GMT+0800 (中国标准时间)" level=info msg="restore at index: 1"
time="Thu Apr 28 2022 15:22:50 GMT+0800 (中国标准时间)" level=info msg="restore proxy settings"
time="Thu Apr 28 2022 15:22:50 GMT+0800 (中国标准时间)" level=info msg="restore proxy settings"
```

</p></details>

### 其他补充

```
mixin: # object
    dns:
        enable: true
        enhanced-mode: redir-host
        nameserver:
            - 8.8.8.8
            - 119.29.29.29
            - 114.114.114.114
    tun:
        enable: true
        stack: gvisor
        dns-hijack:
            -198.18.0.2:53
        auto-route: true
        auto-detect-interface: true
```
