### ISSUE TITLE
请教 Parsers 批量修改节点里 host 的代码怎么写？

### ISSUE THREAD

**Issue by uoyh** [Fndroid/clash_for_windows_pkg#2973]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.17

### 操作系统

Windows x64

### 系统版本

Windows11 21H2

### 问题描述

更新节点的方式是 proxy-providers，希望更新时也批量修改节点里的 host

`- {name: 节点 port: 65533, type: vmess, uuid: b576e016, alterId: 0, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-opts: {path: /, headers: {Host: ct.com}}, udp: true}`

CFW 文档提到的 Action 或 Parsers 应该能做到这个，但是我不懂相关代码

恳请哪位大佬帮忙写下代码？

### 复现步骤

```
parsers:
  - url: proxies\dddd.yaml
    yaml:
      commands:
        - proxies.Host=vod3.nty.189.cn
```

这么写，错了

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
