### ISSUE TITLE
[Bug]: The requested name is valid, but no data of the requested type was found.

### ISSUE THREAD

**Issue by UrielGGs** [Fndroid/clash_for_windows_pkg#2979]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.17

### 操作系统

Windows x64

### 系统版本

21H2

### 问题描述

应用配置文件时报错。
![报错截屏](https://user-images.githubusercontent.com/37137581/166453200-5f1cab94-55eb-410f-b4c4-55340cd627cd.png)
The requested name is valid, but no data of the requested type was found.

### 复现步骤

- 在Profiles选项卡中点击添加的配置文件
![复现截图](https://user-images.githubusercontent.com/37137581/166455129-e71e99d8-fa52-4391-ad77-cfa7be2b7a80.png)

### 日志文件

<details><summary>logs</summary><p>

```
[2022-05-03-150326.log](https://github.com/Fndroid/clash_for_windows_pkg/files/8610386/2022-05-03-150326.log)
```

</p></details>

### 其他补充

```yaml
# 对应的配置文件
rule-providers:
  Unbreak:
    type: http
    behavior: classical
    path: ./RuleSet/Unbreak.yaml
    url: https://raw.githubusercontent.com/UrielGGs/Profiles/master/Clash/RuleSet/Unbreak.yaml
    interval: 3600

  Ads:
    type: http
    behavior: classical
    path: ./RuleSet/Ads.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyListChina.yaml
    interval: 3600

  Telegram:
    type: http
    behavior: classical
    path: ./RuleSet/Telegram.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Telegram/Telegram.yaml
    interval: 3600

  Speedtest:
    type: http
    behavior: classical
    path: ./RuleSet/Speedtest.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.yaml
    interval: 3600

  Crypto:
    type: http
    behavior: classical
    path: ./RuleSet/Crypto.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Cryptocurrency.yaml
    interval: 3600

  PayPal:
    type: http
    behavior: classical
    path: ./RuleSet/PayPal.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/PayPal.yaml
    interval: 3600

  Twitter:
    type: http
    behavior: classical
    path: ./RuleSet/Twitter.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml
    interval: 3600

  BiliBili:
    type: http
    behavior: classical
    path: ./RuleSet/BiliBili.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Video/bilibili.yaml
    interval: 3600

  Netflix:
    type: http
    behavior: classical
    path: ./RuleSet/Netflix.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Video/Netflix.yaml
    interval: 3600

  Disney+:
    type: http
    behavior: classical
    path: ./RuleSet/Disney+.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Video/DisneyPlus.yaml
    interval: 3600

  YouTube:
    type: http
    behavior: classical
    path: ./RuleSet/YouTube.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Video/YouTube.yaml
    interval: 3600

  TikTok:
    type: http
    behavior: classical
    path: ./RuleSet/TikTok.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Video/TikTok.yaml
    interval: 3600

  Streaming:
    type: http
    behavior: classical
    path: ./RuleSet/Streaming.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 3600

  StreamingSE:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingSE.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
    interval: 3600

  StreamingCN:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingCN.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingCN.yaml
    interval: 3600

  Global:
    type: http
    behavior: classical
    path: ./RuleSet/Global.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
    interval: 3600

  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 3600

  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./RuleSet/ChinaIP.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 3600

rules:
  - RULE-SET,Unbreak,DIRECT
  - RULE-SET,Ads,Ads
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Speedtest,Speedtest
  - RULE-SET,Crypto,Crypto
  - RULE-SET,PayPal,PayPal
  - RULE-SET,Twitter,Twitter
  - RULE-SET,BiliBili,BiliBili
  - RULE-SET,Netflix,Netflix
  - RULE-SET,Disney+,Disney+
  - RULE-SET,YouTube,YouTube
  - RULE-SET,TikTok,TikTok
  - RULE-SET,Streaming,Streaming
  - RULE-SET,StreamingSE,StreamingSE
  - RULE-SET,StreamingCN,StreamingCN
  - RULE-SET,Global,Proxy
  - RULE-SET,China,DIRECT
  - RULE-SET,ChinaIP,DIRECT
  - MATCH,Final
```
