### ISSUE TITLE
localhost问题

### ISSUE THREAD

**Issue by DragonLie** [Fndroid/clash_for_windows_pkg#300]
CFW对localhost中的ipv6条目没有做正确的定向
比如这一条：2600:1417:8000:5aa::2587 www.warframe.com
首先这个网站不在国内 所以clash和服务器配置中让这个网站走代理 但是网站禁止代理服务器连接 显示access denied
cfw中的总配置里有cfw-bypass:- localhost 但是貌似没有起作用（按照道理 应该最终判断这个网址走localhost中定义的直连ipv6地址）
当我将规则配置由规则改成直连，再改成规则后，网站可以成功访问，但还是没有走localhost里的地址

**Comment by Fndroid** [comment]
如果配置文件配置了类似这样的：
```yaml
dns:
  enable: true
  nameserver:
    - 114.114.114.114
```

先把``enable``设置成``false``再试试

还有，``localhost``一般是指``127.0.0.1``，你说的是本地 hosts 文件吧
