### ISSUE TITLE
[Bug]: hosts配置无效

### ISSUE THREAD

**Issue by Bricks-Man** [Fndroid/clash_for_windows_pkg#3004]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.17

### 操作系统

Windows x64

### 系统版本

win 11

### 问题描述

我想用域名的方式访问我的几台主机，因此，我修改了HOME\.config\clash\config.yaml文件，加入了如下代码片段：
```
hosts:
  'master': 172.16.111.105
  'slave1': 172.16.111.104
  'slave2': 172.16.111.103
```
同时，也把master\slave1\salve2加入了Settings -> System Proxy -> Bypass。Proxies选择为Rule。
但是我通过浏览器访问这三个域名页面显示无法打开，通过查看日志，发现并没有走我定义的hosts，而是走了代理服务器。

### 复现步骤

参见问题描述。

### 日志文件

<details><summary>logs</summary><p>

```
[2022-05-12 15:08:55][INFO] [TCP] 127.0.0.1:61339 --> master:8080 match Match() using Proxy[Japan-JP3-Rate:1.0]
[2022-05-12 15:08:56][INFO] [TCP] 127.0.0.1:61338 --> master:8080 match Match() using Proxy[Japan-JP3-Rate:1.0]
[2022-05-12 15:09:05][INFO] [TCP] 127.0.0.1:61351 --> master:8080 match Match() using Proxy[Japan-JP3-Rate:1.0]
[2022-05-12 15:09:16][INFO] [TCP] 127.0.0.1:61354 --> slave1:8080 match Match() using Proxy[Japan-JP3-Rate:1.0]
[2022-05-12 15:09:16][INFO] [TCP] 127.0.0.1:61353 --> slave1:8080 match Match() using Proxy[Japan-JP3-Rate:1.0]
```

</p></details>

### 其他补充

所有配置均为服务提供商提供，未做任何修改。
Profiles中的的dns配置如下：
```
dns:
  enable: true
  ipv6: false
  nameserver:
    - https://dns.rubyfish.cn/dns-query
    - https://223.5.5.5/dns-query
    - https://dns.pub/dns-query
  fallback:
    - https://1.0.0.1/dns-query
    - https://public.dns.iij.jp/dns-query
    - https://dns.twnic.tw/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com
      - +.xn--ngstr-lra8j.com
      - +.google.cn
      - +.googleapis.cn
      - +.gvt1.com
```

**Comment by yi-Xu-0100** [comment]
`master` 有这样的域名？

**Comment by HaloWang** [comment]
> `master` 有这样的域名？
> 
> profile里也加上 host 试试，然后 dns 里面也可以设置 host ，参考 [clash Wiki](https://github.com/Dreamacro/clash/wiki/configuration)

你说的方法有效, 直接在 profile 中家 hosts 字段, 格式和楼主的方式异样

**Comment by AkariiinMKII** [comment]
config的hosts字段不会载入 要写在profile里面

**Comment by PaTTeeL** [comment]
我也碰到差不多的问题，然后是把配置写到了mixin里面，结果发现mixin也不是所有字段都有效的，试过mixed-port, allow-lan, ipv6几个都无效，hosts是有效的，看了网上的一些配置模板，还有把host和ipv6写在dns字段下的，官方的wiki里又是跟dns平级，测试下来发现两种写法都有效也没报错，不太明白咋回事，请教有没有更为清晰的解释mixin的文档呢？对于mixin的机制都是靠摸索来的😂

**Comment by yi-Xu-0100** [comment]
@PaTTeeL Mixin 就是覆盖内容到配置，优先级最高。但是 配置内容的 mixed-port, allow-lan ，ipv6 本来就不行，是由 home directory 中的 config.yaml 决定。一般来说，配置内容中只有 dns 配置，tun 配置，proxies，proxy-groups, rules, proxy-providers, rule-providers, 这些会被启用，其他对于系统来说是一次性设置，不会从配置读取，而是由 home directory 中的 config.yaml 决定，这样保证切换配置不会出现不一样的情况。

**Comment by PaTTeeL** [comment]
@yi-Xu-0100 
感谢，对mixin内容基本了解了！
然后现在对hosts设置还有些疑问：
举例来说，我现在设置了一个网址的hosts如下
```
  hosts:
    'www.goodsync': '::1'
```
然后我在log中发现浏览器在使用代理访问网站时destination是::1:443，hosts设置的确生效了，然后根据规则，判断为DIRECT直连，然后问题就来了，无论是fake-ip模式还是redir-host，也不管代理设置是PAC或者HTTP，直连貌似并不理会hosts的设置，直接网站就给打开了，就没明白其中的原理是什么？
貌似虽然hosts定义了域名的固定解析，但后续访问并未按照hosts的定义直连，而是另外询问了外部dns服务器后进行直连了？
贴一下mixin中的设置：
```
mixin: # object
  hosts:
    'www.goodsync': '::1'
  dns:
    enable: true 
    listen: :53
    enhanced-mode: fake-ip # redir-host or fake-ip
    fake-ip-filter: # Hostnames in this list will always be answered with their real IP addresses.
    - "*.ipv6.microsoft.com"
    - "*.local"
    - "miwifi.com"
    - "netis.cc"
    - "speedtest.cros.wr.pvp.net"
    - "repeater.asus.com"
    - "router.asus.com"
    - "routerlogin.com"
    - "routerlogin.net"
    - "tendawifi.com"
    - "tendawifi.net"
    - "tplinklogin.net"
    - "tplinkrepeater.net"
    - "tplinkwifi.net"
    - '*.nb.gl'
    - '*.morfans.cn'
    - 'dns.rubyfish.cn'
    # === LAN ===
    - '*.lan'
    # === Linksys Wireless Router ===
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    # === Apple Software Update Service ===
    - 'swscan.apple.com'
    - 'mesu.apple.com'
    # === Windows 10 Connnect Detection ===
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    # === NTP Service ===
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    # === Music Service ===
    ## NetEase
    - '+.music.163.com'
    - '*.126.net'
    ## Baidu
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    ## Kugou
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    ## Kuwo
    - '*.kuwo.cn'
    ## JOOX
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    ## QQ
    - '+.y.qq.com'
    - '+.music.tc.qq.com'
    - 'aqqmusic.tc.qq.com'
    - '+.stream.qqmusic.qq.com'
    ## Xiami
    - '*.xiami.com'
    ## Migu
    - '+.music.migu.cn'
    # === Game Service ===
    ## Nintendo Switch
    - '+.srv.nintendo.net'
    ## Sony PlayStation
    - '+.stun.playstation.net'
    ## Microsoft Xbox
    - 'xbox.*.microsoft.com'
    - '+.xboxlive.com'
    # === Other ===
    ## QQ Quick Login
    - 'localhost.ptlogin2.qq.com'
    ## Golang
    - 'proxy.golang.org'
    ## STUN Server
    - 'stun.*.*'
    - 'stun.*.*.*'
    default-nameserver: # Specify IP addresses only. These nameservers are used to resolve the DNS nameserver hostnames below.
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
    nameserver:
    - https://dns.alidns.com/dns-query
    - https://223.5.5.5/dns-query
    - https://dns.pub/dns-query
    fallback:
    - https://chrome.cloudflare-dns.com/dns-query
    - https://dns9.quad9.net/dns-query
    - https://dns.google/dns-query
    - https://1.0.0.1/dns-query
    fallback-filter:
      geoip: true
      ipcidr:
      - 0.0.0.0/32
      - 127.0.0.1/32
      - 240.0.0.0/4
      domain:
      - +.facebook.com
      - +.google.cn
      - +.google.com
      - +.googleapis.cn
      - +.gvt1.com
      - +.twitter.com
      - +.xn--ngstr-lra8j.com
      - +.youtube.com
```
