### ISSUE TITLE
[Bug]: 高概率出现使用 cmd + w 关闭 Clash for Windows (后简称 cfw) 时, cfw icon 仍然滞留于 dock 中

### ISSUE THREAD

**Issue by HaloWang** [Fndroid/clash_for_windows_pkg#3037]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.18

### 操作系统

macOS amd64(Intel)

### 系统版本

macOS 12.4 (21F79)

### 问题描述

高概率出现使用 `cmd + w` 关闭 Clash for Windows (后简称 cfw) 时, cfw icon 仍然滞留于 dock 中. 使用左上角的红色 close button 则能使 CFW icon 从 dock 中消失

第一次 `cmd + w` 可以 dismiss cfw from dock, 再次点击 status bar 中的 icon 打开 cfw 主界面后, 上述问题出现

期望:

`cmd + w` 和左上角关闭按钮均能使 cfw 在 Dock 中消失

### 复现步骤

同描述

### 其他补充

cfw-settings.yaml

```yaml
showNewVersionIcon: true
hideAfterStartup: true
randomControllerPort: false
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
editor: 1
theme: 1
fontFamily: Sarasa Mono SC Light
proxyOrder: 1
latencyUrl: https://www.google.com
latencyTimeout: 1000
trayScriptManualRunTime: 1649900858773
showNotifications: false
lightweightMode: false
bypassText: |
  bypass:
    - 127.0.0.1
    - 192.168.0.0/16
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 100.64.0.0/10
    - 17.0.0.0/8
    - localhost
    - '*.local'
    - 169.254.0.0/16
    - 224.0.0.0/4
    - 240.0.0.0/4
    - situnemall.com
    - 10.20.37.189
    - 10.20.37.188
connProxy: 1
connChainType: 2
shortcutSystemProxy: ""
```
