### ISSUE TITLE
在设置里，把模式从HTTP改为PAC可以解决steam下载问题。

### ISSUE THREAD

**Issue by DEiYdaIWVt** [Fndroid/clash_for_windows_pkg#3056]
在设置里，把模式从HTTP改为PAC可以解决steam下载问题。
 
> 不知道为啥装了tap虚拟网卡
> 然后配置中这样设置了
> 但是没有任何反应
> 我在虚拟机里试了下 也是同样问题。。。

如果还是想用tap模式的话，可以把这个放到了Mixin里，打开Mixin就是TAP模式，关闭就是普通模式。interface-name可以不填。
```yaml 
mixin:
  dns:
   enable: true
   enhanced-mode: redir-host
   listen: 0.0.0.0:53
   nameserver:
      - 223.5.5.5
```

_Originally posted by @Pearlulu in https://github.com/Fndroid/clash_for_windows_pkg/issues/958#issuecomment-735027040_
这个是没有用的，PAC一直开的话同样会遇到这个问题
