### ISSUE TITLE
[Bug]: 通过 Mixin 开启 TUN 模式，无法代理 CFW 本身

### ISSUE THREAD

**Issue by QuentinHsu** [Fndroid/clash_for_windows_pkg#3108]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

v 0.19.20

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

12.4

### 问题描述

通过 Mixin 开启 TUN 模式无法代理 CFW 本身。
直接开启 TUN Mode 选项可以，或者同时开启 System Proxy 才行。

由于，我的订阅转换地址域名（workers.dev）被墙，所以需要代理才可以正常下载配置文件。

代理规则里也是包含此域名的，且 log 中也显示是走了代理。但通过 Mixin 开启 TUN 模式无法下载。但其他软件比如 Telegram 能正常代理。

我的 Mixin 配置如下，之前就可用，但更新这版本后就太不行了

```
mixin: # object
  dns:
    enable: true
    ipv6: false # default is false
    #listen: 0.0.0.0:53 # 假如开启 tun，此项可以不用配置
    enhanced-mode: redir-host
    nameserver:
      - https://dns.alidns.com/dns-query
    fallback:
      - 8.8.8.8
    fallback-filter:
      geoip: true
      geoip-code: CN
      ipcidr:
        - 240.0.0.0/4
  tun:
    enable: true
    stack: system
    dns-hijack: # DNS 劫持
      - any:53
    auto-route: true
    auto-detect-interface: true
```

已全新安装并尝试，复现。

### 复现步骤

在描述中

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
