### ISSUE TITLE
[Bug]: tun模式下无法共享热点（非tun模式下正常共享）

### ISSUE THREAD

**Issue by Kobe972** [Fndroid/clash_for_windows_pkg#3191]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.19

### 操作系统

Windows x64

### 系统版本

windows 10 2021 LTSC

### 问题描述

没有使用clash的情况下，windows开启移动热点网络可以正常访问。但使用了clash的tun模式就不行了（tun模式下关闭移动热点才能保证本机wifi正常）

### 复现步骤

* Settings/Minxin/YAML如下设置：
```yaml
mixin: # object
  dns:
    enable: true
    enhanced-mode: redit-host
    nameserver:
        - 8.8.8.8
        - 119.29.29.29
        - 114.114.114.114
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 198.18.0.2
    auto-route: true
    auto-detect-interface: true
```
* general/TUN Mode右边点击设置按钮，然后save
* 下载service mode
* 开启移动热点，打开tun mode和allow lan
* 共享中心里找到clash虚拟网卡设置共享（共享栏全打勾，所有计算机可连）
* 打开浏览器，发现上不了网
* 关掉移动热点或tun mode，又可以恢复上网。
* 已经尝试把windows装回更新之前的，或是替换掉ipnat.sys，均不起作用。

没有clash的时候热点可以正常使用，因此感觉不是windows6月更新的问题

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

tun配置：
```yaml
mixin: # object
  dns:
    enable: true
    enhanced-mode: redit-host
    nameserver:
        - 8.8.8.8
        - 119.29.29.29
        - 114.114.114.114
  tun:
    enable: true
    stack: gvisor
    dns-hijack:
      - 198.18.0.2
    auto-route: true
    auto-detect-interface: true
```
