### ISSUE TITLE
[Help]:  如何配置TUN双网卡出口

### ISSUE THREAD

**Issue by qiangxinglin** [Fndroid/clash_for_windows_pkg#3268]
### 功能描述

现通过系统代理System Proxy的模式, 可以使用双网卡(内外网), 并通过配置nameserver-policy来解析内网域名
```
dns:
  enable: true
  listen: 0.0.0.0:53
  nameserver-policy:
    'some.local.domain': '10.x.x.x'
  nameserver:
    - 223.5.5.5
```
然后在route里去配置路由跃点达到内外网融合

请问如何使用TUN模式来达到这一目标? 
好像TUN只能设置单出口网卡, 并且设置的nameserver-policy也不起作用了
导致内网域名无法被解析

**Comment by Lemmingh** [comment]
或者换个思路，避开 Clash DNS server：

在 NRPT 指定用内网的 DNS 解析内网域名。

**Comment by qiangxinglin** [comment]
@Lemmingh 
1. 设置`fake-ip-filter`后, DNS交由系统处理, 但是由于公网NIC路由跃点较小, 导致DNS解析出了公网IP地址
我其实想将`some.local.domain`解析成内网ip, 有些服务只有通过内网才有权限访问

2. 不是windows server, 所以没有NRPT, 正在考虑另起一个DNS服务做这件事

**Comment by Lemmingh** [comment]
> 不是 Windows Server

Windows 客户端上也有 NRPT。用 PowerShell (`DnsClient` module) 或者 Group Policy Editor 即可修改。

注意，Group Policy Editor **无法** 呈现某些可以由 PowerShell 做出的设定，例如，在 `Namespace` 填入 array。

---

> 解析出了公网 IP 地址

👀

你的网络其实长这样？

```mermaid
flowchart LR

subgraph Client
    NicCorporate["Corporate NIC"]
    NicPublic["Public NIC"]
    NicTun["TUN"]

    NetworkClash(("Clash Virtual"))

    AppClash[["Clash"]]
end

subgraph Remote ["some.local.domain"]
    ServiceCorporate["Corporate"]
    ServicePublic["Public"]
end

NetworkCorporate(("Corporate"))
NetworkPublic(("Public"))

NicCorporate --- NetworkCorporate --- ServiceCorporate
NicPublic --- NetworkPublic --- ServicePublic
NicTun --- NetworkClash --- AppClash --- NicPublic
```

那还真得考虑 Windows 并发 DNS query 这件事。我也想不到更简单的办法：

* 要么用 NRPT 锁 DNS。

* 要么建 DNS server。

如果在本地搭建 DNS server，建议关闭 [NCSI 的 DNS lookup interface binding](<https://gpsearch.azurewebsites.net/#13690>)，否则，NCSI 容易误报无网络。

**Comment by qiangxinglin** [comment]
@Lemmingh 首先大佬的图非常的专业, 第一次在评论区见到, 很佩服
问题已解决, 按照上面的建议
1. 采用`dns.fake-ip-filter`, 加入`some.local.domain`
2. 在PowerShell中, `Add-DnsClientNrptRule -Namespace "some.local.domain" -NameServers "local.dns.server1", "local.dns.server2"`
3. 配置好路由跃点

**Comment by Lemmingh** [comment]
我再稍微演示一下如何配置本地 NRPT 吧。毕竟，初次接触确实会很难过。

```powershell
#Requires -Version 5.1
#Requires -Modules DnsClient
#Requires -RunAsAdministrator

[string[]]$DnsServerAddresses = @(
    # Cloudflare and APNIC: https://1.1.1.1/dns/
    '1.1.1.1', '1.0.0.1', '2606:4700:4700::1111', '2606:4700:4700::1001'
    # 阿里云公共 DNS: https://alidns.com/
    , '223.5.5.5', '223.6.6.6', '2400:3200::1', '2400:3200:baba::1'
)

# 我不建议往 Namespace 塞 array，所以，每个写一条。
$Rules = @(
    @{
        Namespace   = 'moshujia.cn'   # 可以匹配 FQDN
        NameServers = '192.168.124.1' # 可以设置一个 DNS
    },
    @{
        Namespace   = '.msftncsi.com'     # 可以匹配部分
        NameServers = $DnsServerAddresses # 可以设置一堆 DNS
    },
    @{
        Namespace   = 'www.msftconnecttest.com'
        NameServers = $DnsServerAddresses
    }
)

foreach ($Item in $Rules)
{
    Add-DnsClientNrptRule @Item
}
```

核对：

```powershell
Get-DnsClientNrptRule | Format-List Name, Namespace, NameServers
```

```yaml
Name        : {9C6769A8-10FC-4311-A9CF-51F678AD8525}
Namespace   : {moshujia.cn}
NameServers : 192.168.124.1

Name        : {D6AB69FE-87FE-40F6-8182-779D7E0C73B2}
Namespace   : {www.msftconnecttest.com}
NameServers : {1.1.1.1, 1.0.0.1, 2606:4700:4700::1111, 2606:4700:4700::1001…}

Name        : {E45245A2-4460-43A3-BD1F-00F73898A564}
Namespace   : {.msftncsi.com}
NameServers : {1.1.1.1, 1.0.0.1, 2606:4700:4700::1111, 2606:4700:4700::1001…}
```

设置符合预期。

但这个视图不友好。所以：

```powershell
Get-DnsClientNrptPolicy -Effective | Format-List Namespace, NameServers
```

```yaml
Namespace   : .msftncsi.com
NameServers : {1.1.1.1, 1.0.0.1, 2606:4700:4700::1111, 2606:4700:4700::1001…}

Namespace   : moshujia.cn
NameServers : 192.168.124.1

Namespace   : www.msftconnecttest.com
NameServers : {1.1.1.1, 1.0.0.1, 2606:4700:4700::1111, 2606:4700:4700::1001…}
```

显然已经生效。

**Comment by qiangxinglin** [comment]
@Lemmingh  一个题外话, 转换到TUN模式下后, 微软商店或者office登录都会直接报错网络问题, 是还需要设置什么么?
系统代理模式下都是没问题的

**Comment by yi-Xu-0100** [comment]
@qiangxinglin 我知道的是设置 fake-ip-filter ，截图保存下 tun 配置 ，reset 默认配置里有 ncsi 相关的。

**Comment by qiangxinglin** [comment]
@yi-Xu-0100 用的就是重置后的, 会有微软网络报错问题
```
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
    - "some.local.domain"  <-- local domain here
tun:
  enable: true
  stack: gvisor
  auto-route: true
  dns-hijack:
    - any:53
interface-name: Public NIC name
```
