### ISSUE TITLE
如何添加snell的代理

### ISSUE THREAD

**Issue by longlegmax** [Fndroid/clash_for_windows_pkg#327]
看的更新版本说已经支持snell代理，通过手动编辑配置文本后，启动出错

是否有考虑在程序界面中添加对snell代理的支持

**Comment by Fndroid** [comment]
```yaml
  # snell
  - name: "snell"
    type: snell
    server: server
    port: 44046
    psk: yourpsk
    # obfs-opts:
      # mode: http # or tls
      # host: bing.com
```
