### ISSUE TITLE
[求教]: 关于 Clash DNS 污染的一些疑惑

### ISSUE THREAD

**Issue by SpaceTimee** [Fndroid/clash_for_windows_pkg#3286]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.25

### 操作系统

Windows x64

### 系统版本

Windows 11 21H2

### 问题描述

根据 [DNS污染对Clash（for Windows）的影响](https://github.com/Fndroid/clash_for_windows_pkg/wiki/DNS%E6%B1%A1%E6%9F%93%E5%AF%B9Clash%EF%BC%88for-Windows%EF%BC%89%E7%9A%84%E5%BD%B1%E5%93%8D) 所述，在 Clash 的不同配置下，我使用 Ping 测试域名 的方式，测试了 DNS 解析结果是否会被污染 (均按照文中所教方式配置):

* 结果1: 在不启用 tun 配置项的情况下 (也未使用 tap)，无论是否启用 dns 配置项，是否启用系统代理，无论怎样配置 rules 配置项，Ping 出的结果始终有污染，但只要使用代理 (启用系统代理并正确配置 rules)，浏览器就可以正常访问测试域名，因此我猜想会不会是不启用 tun 的情况下，Ping 发出的数据包不能被 Clash 拦截，不知猜想是否正确

* 结果2: 在启用 tun 配置项的情况下，无论是否启用系统代理，Ping 发出的数据包都可以被 Clash 拦截，但只有同时启用 dns 配置项 (为测试方便使用 redir-host 并 正确配置了 DOT)，Ping 返回的结果才不会被污染，即使使用了代理，在不启用 dns 配置项的情况下 Ping 返回的结果依然有污染，但浏览器却可以正常访问，浏览器正常访问，应该可以说明 Clash 确实能够使用代理服务器进行远程 DNS 解析，并且返回的 ip 是无污染的，但为什么 Ping 的数据包被拦截后却返回了污染的 ip 呢

* 结果3: 在不启用 tun 配置项的情况下 (也未使用 tap)，我考虑到会不会是 需要把系统的 DNS 服务器设置为 127.0.0.1 才能让 Ping 的数据包 流进 Clash，但修改后发现 系统设置中的 DNS 服务器 设置项 无论怎样修改都不产生效果，即使乱输一气也始终可以正常上网 (访问 (没有被 Ban 的) 网站)，不清楚是为什么

初玩 Clash，有很多地方不太懂，还请大佬们见谅

### 复现步骤

修改 Mixin 或 Clash 配置文件，使用 ping 命令测试域名污染结果

### 其他补充

```
mixin:
  dns:
    enable: true
    listen: 0.0.0.0:53
    enhanced-mode: redir-host
    nameserver:
      - 'tls://dns.rubyfish.cn:853'
    fallback:
      - 'tls://1.1.1.1:853'
      - 'tcp://1.1.1.1:53'
      - 'tcp://208.67.222.222:443'
      - 'tls://dns.google'
  tun:
    enable: true
    stack: gvisor
    auto-route: true
    auto-detect-interface: true
    dns-hijack:
      - 198.18.0.2:53
```
仅当两个 enable 都为 true 时才能 Ping 到无污染的结果
