### ISSUE TITLE
[Bug]: 添加providers里direct的时候报错unmarshal error和deadline exceeded

### ISSUE THREAD

**Issue by wwwhahahaha** [Fndroid/clash_for_windows_pkg#3330]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.26

### 操作系统

Windows x64

### 系统版本

win10 21H1

### 问题描述

只有添加direct时报错，添加其他都正常。

![image](https://user-images.githubusercontent.com/29722342/184887155-0faf532f-e5c8-44e1-b39a-bf3901e40604.png)

### 复现步骤

我的配置文件如下：
```
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: rule
log-level: silent
external-controller: '0.0.0.0:9090'
secret: ''
dns:
enable: true
ipv6: false
listen: '0.0.0.0:53'
enhanced-mode: fake-ip
fake-ip-range: 198.18.0.1/16
nameserver:
- 119.29.29.29
- 1.1.1.1
fallback:
- 1.0.0.1
- 8.8.8.8
fallback-filter:
geoip: true
ipcidr:
- 240.0.0.0/4
rule-providers:

direct:
  type: http
  behavior: domain
  url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
  path: ./ruleset/direct.yaml
  interval: 86400
```

### 日志文件

<details><summary>logs</summary><p>

```
[2022-08-16-184659.log](https://github.com/Fndroid/clash_for_windows_pkg/files/9351279/2022-08-16-184659.log)

```

</p></details>
