### ISSUE TITLE
[Bug]: Windows PROCESS-NAME规则无效

### ISSUE THREAD

**Issue by threerog** [Fndroid/clash_for_windows_pkg#3350]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.27

### 操作系统

Windows x64

### 系统版本

win10专业版

### 问题描述

想通过PROCESS-NAME规则将常用的远程桌面软件进行设置策略组进行代理
测试了很多次 始终无法生效，而且clash连接和clash日志里都找不到相关信息

```
prepend-rules:
        - PROCESS-NAME,SunloginClient.exe,⚡ 远程桌面
        - PROCESS-NAME,ToDesk_Setup.exe,⚡ 远程桌面
        - PROCESS-NAME,ToDesk_Session.exe,⚡ 远程桌面
        - PROCESS-NAME,ToDesk_Service.exe,⚡ 远程桌面
        - PROCESS-NAME,ToDesk.exe,⚡ 远程桌面
        - PROCESS-NAME,mstsc.exe,⚡ 远程桌面
prepend-proxy-groups:
        - name: ⚡ 远程桌面
          proxies:
            - DIRECT
            - 🚀 节点选择
            - 🚀 手动切换
          type: select
```

### 复现步骤

在settings里的配置Profiles.Parsers

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Lemmingh** [comment]
Connections 中有 Process Path 信息吗？

如果操作系统拒绝向 Clash 提供进程信息，那么，`PROCESS-NAME` 规则就无用。

**Comment by threerog** [comment]
> Connections 中有 Process Path 信息吗？
> 
> 如果操作系统拒绝向 Clash 提供进程信息，那么，`PROCESS-NAME` 规则就无用。

1.Connections里没有任何与我配置相关的连接和进程信息
2.也尝试过管理员模式运行 仍然这样
<img width="167" alt="Snipaste_2022-08-22_20-46-03" src="https://user-images.githubusercontent.com/87128510/185924496-bf4e7632-27e8-4ef2-aefc-98c726749209.png">

**Comment by Lemmingh** [comment]
向日葵服从系统代理吗？这些 RD 软件一般都有独立的连网协议和方法，可能不走代理。

**Comment by yi-Xu-0100** [comment]
大概有几个问题需要确定：
1. 远程桌面使用的软件是否走系统代理，在软件设置中可以看到，如向日葵。

![image](https://user-images.githubusercontent.com/25523606/185940650-84fd0de3-ca7a-44c1-affc-97d51366e3cd.png)

2. 对于不走系统代理的软件，需要使用 tun 去接管软件。
3. 无论是 mixin 还是 parser 遵循 yaml 语法，需要考虑是否缩进有误，建议截图看看配置内容。

给出 parser 示例（一般来说，修改与策略相关配置建议用 parser，全局的控制如 tun 配置可以用 mixin ，当然限制可以直接用 tun mode 去控制了）

![image](https://user-images.githubusercontent.com/25523606/185942979-f9079098-3097-4a00-9abf-9f0dd9d06e33.png)

```yaml
parsers: # array
    - reg: '^.*$'
    # - reg: ^.*$ 匹配所有订阅
    # - url: https://example.com/profile.yaml 或者指定订阅
      yaml:
        prepend-rules:
            - PROCESS-NAME,SunloginClient.exe,⚡ 远程桌面
            - PROCESS-NAME,ToDesk_Setup.exe,⚡ 远程桌面
            - PROCESS-NAME,ToDesk_Session.exe,⚡ 远程桌面
            - PROCESS-NAME,ToDesk_Service.exe,⚡ 远程桌面
            - PROCESS-NAME,ToDesk.exe,⚡ 远程桌面
            - PROCESS-NAME,mstsc.exe,⚡ 远程桌面
        prepend-proxy-groups:
            - name: ⚡ 远程桌面
              type: select
              proxies:
                - DIRECT
                - 🚀 节点选择
                - 🚀 手动切换
```


parser 设置成功后，更新订阅，会让订阅内容更新，可以直接查看订阅内容是否包含相关内容。
