### ISSUE TITLE
[Bug]:  编辑Profile移除某地区分组的所有Proxies时,yaml文件解析失败导致无法选中

### ISSUE THREAD

**Issue by JemCheung** [Fndroid/clash_for_windows_pkg#3356]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.27

### 操作系统

macOS amd64(Intel)

### 系统版本

macOS Monterey 12.5.1

### 问题描述

编辑Profile(Profiles-Proxies)时,若移除某地区分组的所有节点,yaml格式不正确导致文件无法选择,提示“Could not switch to this profile! proxy group[x]: `use` or `proxies` missing”
举例,删除所有香港节点,yaml文件变化,删除前:
 ```
 - name: 🇭🇰 香港节点
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 🇭🇰 xxx1
      - 🇭🇰 xxx2
      - 🇭🇰 xxx3
 ```
删除后:
 ```
 - name: 🇭🇰 香港节点
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:[]
 ```
问题出在`proxies:[]`这儿格式不正确,如无节点显示以下格式可以正确解析yaml:
 ```
proxies:
   - DIRECT
```
希望以后版本尽快修复.

### 复现步骤

如上所述

### 日志文件

-

### 其他补充

只测试了macOS版本,此问题可能涉及多个版本.
