### ISSUE TITLE
[Feature Request]: 建议 parser 相关的功能能支持 yaml 锚点

### ISSUE THREAD

**Issue by lyfuci** [Fndroid/clash_for_windows_pkg#3362]
### 功能描述

想在parser使用时支持yaml的锚点功能:
具体例子如下，在parser中有如下输入:

```yaml
parsers:
    - url: url1
      yaml: &content
        prepend-rules:
          - DOMAIN-SUFFIX,demo.com,DIRECT # rules最前面增加一个规则
          - IP-CIDR,192.168.1.0/24,DIRECT
    - url: url2
      yaml:
        <<: *content
```

等价于下列输入:

```
parsers:
    - url: url1
      yaml:
        prepend-rules:
          - DOMAIN-SUFFIX,demo.com,DIRECT # rules最前面增加一个规则
          - IP-CIDR,192.168.1.0/24,DIRECT
    - url: url2
      yaml:
        prepend-rules:
          - DOMAIN-SUFFIX,demo.com,DIRECT # rules最前面增加一个规则
          - IP-CIDR,192.168.1.0/24,DIRECT
```

虽然现在parser功能支持本地文件直接引用如下图，但是内容不能完全自包含，总觉得使用起来比较麻烦，yaml本身支持锚点，麻烦考虑一下这个功能。
![image](https://user-images.githubusercontent.com/12745441/186740850-766f4747-3b4b-44c1-8952-f490be951cb3.png)
