### ISSUE TITLE
[Bug]: 如何写具体的ip的代理规则

### ISSUE THREAD

**Issue by threerog** [Fndroid/clash_for_windows_pkg#3388]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.29

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

我想让一个具体的ip走代理
但是在编写规则时无法生效
请问有示例吗
注意是具体的ip 不是ip段

### 复现步骤

..

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Wrandz** [comment]
IP-CIDR,119.29.29.29/32,翻墙。后面是32那就是一个具体的IP了

**Comment by threerog** [comment]
@Wrandz 那如果是一个具体的ip+端口呢

**Comment by Fndroid** [comment]
> @Wrandz 那如果是一个具体的ip+端口呢

```yaml
script:
  shortcuts:
    one: resolve_ip(host) == '1.1.1.1' and dst_port == 443  # 1.1.1.1是ip，443是端口

rules:
  SCRIPT,one,REJECT
```
