### ISSUE TITLE
[Bug]: ServiceMode地球显示绿色，TUN模式打开后浏览器无法上外网

### ISSUE THREAD

**Issue by dddfrozen** [Fndroid/clash_for_windows_pkg#3395]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.29

### 操作系统

Windows x64

### 系统版本

Windows 10专业版 21H1

### 问题描述

ServiceMode安装后地球显示绿色，TUN模式打开，配置都是默认的没有动过，虚拟网卡能正常出现Clash，但是不能上外网，只有打开系统代理才可以，用的谷歌浏览器已关闭“使用安全DNS”。不知道是哪里的问题
![1662098221(1)](https://user-images.githubusercontent.com/43923893/188068913-36ca186c-b94c-4b94-b7ff-610f09099f07.png)
![1662098256(1)](https://user-images.githubusercontent.com/43923893/188068952-83f03002-a29c-4a5a-8381-c88cad1f003f.jpg)

### 复现步骤

TUN模式无法上外网，只有系统代理可以

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
[2022-09-02-132914.log](https://github.com/Fndroid/clash_for_windows_pkg/files/9475229/2022-09-02-132914.log)

### 其他补充

TUN的配置，都是默认的
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53

**Comment by david223366** [comment]
我是两个都不能上 打开tun模式和系统模式都上不去

**Comment by Sakuzy0** [comment]
> 

应该是节点问题  看看延迟是否过高 分流是否正常

**Comment by Sakuzy0** [comment]
> 我是两个都不能上 打开tun模式和系统模式都上不去

应该是节点问题 看看延迟是否过高 分流是否正常

**Comment by david223366** [comment]
> > 我是两个都不能上 打开tun模式和系统模式都上不去
> 
> 应该是节点问题 看看延迟是否过高 分流是否正常

不是节点问题  延迟正常的

**Comment by CoolPlayLin** [comment]
这个配置文件好像有问题
试试这个配置？
```
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback:
    - 1.1.1.1
    - 8.8.4.4
  fake-ip-filter:
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - 198.18.0.2:53
```

**Comment by CoolPlayLin** [comment]
这个配置文件好像有问题
试试这个配置？
```
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback:
    - 1.1.1.1
    - 8.8.4.4
  fake-ip-filter:
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - 198.18.0.2:53
```
