### ISSUE TITLE
[Bug]: 三种System Proxy模式下均存在一些Bug

### ISSUE THREAD

**Issue by redapple0204** [Fndroid/clash_for_windows_pkg#3421]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.2

### 操作系统

Windows x64

### 系统版本

Windows10 LTSC

### 问题描述

system proxy指的是Setting里面的System Proxy
![image](https://user-images.githubusercontent.com/16254644/189511106-341404bd-7933-4512-a6ca-85f5a65f7a11.png)
### 1.当使用HTTP模式时
使用该模式，若在Pycharm中下载包时会报错
![image](https://user-images.githubusercontent.com/16254644/189511151-39e3a490-7f7c-40cb-a8c8-b881656dd510.png)
### 2.当使用HTTP模式并且把Specify Protocol打开时
使用iTunes对手机刷机时（或者检查更新时）会报错，例如把iPhone进入DFU模式，并且尝试联网刷机时，会报错
![image](https://user-images.githubusercontent.com/16254644/189511248-df4621b8-7303-4700-8f08-c935381e2ec8.png)
![image](https://user-images.githubusercontent.com/16254644/189511254-752abeef-0aaf-4540-8dcd-250703046dfb.png)
### 3.当使用PAC模式时
若在使用该模式时，同时配置DoT/DoH服务，则会导致DNS泄露
具体复现步骤：
1.配置DoT/DoH，我的配置文件如下
```
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  nameserver:
    - tls://223.5.5.5
    - tls://dot.pub
    - tls://dns.rubyfish.cn
    - https://doh.pub/dns-query
    - https://i.passcloud.xyz/dns-query
  fallback:
    - tls://223.6.6.6
    - tls://a.passcloud.xyz:5432
    - https://dns.alidns.com/dns-query
    - https://dns.rubyfish.cn/dns-query
```
2.把电脑睡眠，或者联网使用一段时间，并且打开wireshark（wireshark用来监测，不是复现步骤）
3.把电脑唤醒，会发现这个时候的DNS请求全部通过系统默认DNS进行明文请求，而不再走配置的DoH/DoT

### 复现步骤

已在上面描述
