### ISSUE TITLE
[Feature Request]: clash能设置指定域名解析DNS嘛？

### ISSUE THREAD

**Issue by rangluwme** [Fndroid/clash_for_windows_pkg#3535]
### 功能描述

如题，就比如quan里面就可以设置
server=/*.qq.com/119.29.29.29

**Comment by Lemmingh** [comment]
`dns.nameserver-policy`

详见
<https://github.com/Dreamacro/clash/wiki/Configuration>

在 CFW 中，需要通过 Mixin 注入。注意缩进。

**Comment by Lemmingh** [comment]
类似这样

```yaml
mixin:
  dns:
    enable: true
    nameserver:
      - '223.5.5.5'
      - '1.1.1.1'
      - '8.8.8.8'
    nameserver-policy:
      '+.qq.com': '119.29.29.29'
```
