### ISSUE TITLE
[Bug]: tun模式错误：[Inbound] start failed error

### ISSUE THREAD

**Issue by Yuan68** [Fndroid/clash_for_windows_pkg#3539]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.5

### 操作系统

Windows x64

### 系统版本

win7

### 问题描述

网络连接里Clash显示网络电缆已拔出，过一段时间后会消失。无法通过TUN模式上网。

### 复现步骤

界面打开tun模式的开关。

### 日志文件

<details><summary>logs</summary><p>

```
DBG [WinTUN] generate GUID: {330EAEF8-7578-5DF2-D97B-8DADC0EA85CB}
ERR [Inbound] start failed error=Element not found. type=TUN stackType=gvisor inet=198.18.0.1/16
```

</p></details>

### 其他补充

mixin:
  dns:
    enable: true
    enhanced-mode: fake-ip
    default-nameserver:
      - 223.5.5.5
    nameserver:
      - https://i.passcloud.xyz/dns-query
    fallback: []
    fake-ip-filter:
      - +.stun.*.*
      - +.stun.*.*.*
      - +.stun.*.*.*.*
      - +.stun.*.*.*.*.*
      - "*.n.n.srv.nintendo.net"
      - +.stun.playstation.net
      - xbox.*.*.microsoft.com
      - "*.*.xboxlive.com"
      - "*.msftncsi.com"
      - "*.msftconnecttest.com"

TUN模式：
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53

**Comment by rangluwme** [comment]
mixin里面设置tun模式为ture，跟在外边开启tun是一样的。假设已经开启了Tun(无论在内还是在外，tun模式里面的dns就可以删除了（因为mixin会覆盖），设置之后最好退出clash，重启），还有一个可能的问题是iqdns的地址，我一般用的是这个DOH： [https://worldwide.passcloud.xyz/dns-query ](https://worldwide.passcloud.xyz/dns-query ) 这里推荐一种配置，仅供参考
```
mixin:
  dns:
    enable: true
    listen: 0.0.0.0:53
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    default-nameserver:
      - 223.5.5.5
      - 1.1.1.1
    nameserver:
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
      - https://worldwide.passcloud.xyz/dns-query 
    fallback: 
      - https://dns.google/dns-query
      - https://cloudflare-dns.com/dns-query
      - https://dns.quad9.net/dns-query
    fake-ip-filter:
      geoip: false
      ipcidr:
        - 240.0.0.0/4
        - 0.0.0.0/32
        - 127.0.0.1/32
  tun:
    enable: true
    stack: gvisor
    auto-route: true
    auto-detect-interface: true
    dns-hijack:
    - any:53
```
