### ISSUE TITLE
[Bug]: tun模式下rule代理UDP始终直连

### ISSUE THREAD

**Issue by fsdfkefs** [Fndroid/clash_for_windows_pkg#3564]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.5

### 操作系统

Windows x64

### 系统版本

win10

### 问题描述

我设置了 22101 端口走代理节点，

在 tun 模式 rulu 规则下，如果是tcp数据请求 22101 端口，是正常走代理的，但udp数据始终直连。

如果切换到global模式走代理，这时udp数据是可以走代理的。

想问一下应该怎样配置才能使得udp数据在rulu规则下也走代理呢

###  下面是简要的配置文件

Clash config
```
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - {
      name: 
      server: 
      port: 443,
      type: trojan,
      password:
      sni:
      skip-cert-verify: false,
    }
proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - DIRECT
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
  
rules:
 - DST-PORT,22101,📲 电报信息
 - DST-PORT,22102,📲 电报信息
 - SRC-PORT,22101,📲 电报信息
 - SRC-PORT,22102,📲 电报信息
 - DOMAIN-SUFFIX,acl4.ssr,🎯 全球直连
```

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
节点如果支持udp，需要设置
```yaml
- {
      name: 
      server: 
      port: 443,
      type: trojan,
      password:
      sni:
      skip-cert-verify: false,
      udp: true                            // 加上！！！！！！
    }
```
