### ISSUE TITLE
TUN 模式下开启 fallback 后 Microsoft Edge 同步无法工作

### ISSUE THREAD

**Issue by imacte** [Fndroid/clash_for_windows_pkg#3575]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.5

### 操作系统

Windows x64

### 系统版本

Windows 11

### 问题描述

Mixin 中开启 TUN 模式，配置文件中配置了 fallback 后，Microsoft Edge 同步无法工作。
![](https://user-images.githubusercontent.com/88136217/195982808-bb316786-a248-4419-8c0c-aea4273f0a02.png)

## Mixin 配置文件
```
mixin:
  dns:
    enable: true 
    ipv6: true
    enhanced-mode: fake-ip
    default-nameserver:
      - 223.5.5.5
      - 223.6.6.6
      - 119.29.29.29
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter:
      # === Local ===
      - "*.lan"
      - "*.local"
      - WORKGROUP
      # === Microsoft Windows Serivice ===
      - edge.microsoft.com
      - activity.windows.com
      - edge-enterprise.activity.windows.com
      - edge.activity.windows.com
      - xbox.*.*.microsoft.com
      - "*.*.xboxlive.com"
      - "*.msftncsi.com"
      - "*.msftconnecttest.com"
      - "*.ipv6.microsoft.com"

    nameserver:
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    fallback:
      - https://doh.dns.sb/dns-query
      - https://dns.google/dns-query
      - https://1.1.1.1/dns-query
    fallback-filter:
      geoip: true
      geoip-code: CN
      ip-cidr:
        - 240.0.0.0/4
        - 127.0.0.1/8
        - 0.0.0.0/32
      domain:
        - +.google.com

  tun:
    enable: true
    stack: system
    dns-hijack:   
      - any:53
    auto-route: true
    auto-detect-interface: true
```
