### ISSUE TITLE
[求助]: TUN模式下怎么正常使用UU加速器的进程模式加速游戏

### ISSUE THREAD

**Issue by RealSeek** [Fndroid/clash_for_windows_pkg#3597]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.5

### 操作系统

Windows x64

### 系统版本

windows 10 LTSC

### 问题描述

我想在启用tun模式的情况下使用UU加速器的进程模式进行游戏加速,但只要开着tun就没办法通过进程模式连接上游戏的服务器
UU加速器有个TUN网卡兼容但是启用也是无效果的

### 复现步骤

 开启TUN模式 使用UU加速器模式四加速 启动游戏无法连接到游戏的服务器

### 日志文件

<details><summary>log</summary><p>

```

```

</p></details>

### 其他补充

mixin 配置内容如下
```
mixin: # Mixin 配置文件
  # DNS服务器
  dns:
    # 开启Clash内置DNS服务器
    # 默认为false
    enable: true

    # 使用 ipv6 解析
    # 默认为 false
    ipv6: true

    # DNS 监听端口
    listen: 0.0.0.0:53

    # 解析nameserver和fallback的DNS服务器
    # 填入纯IP的DNS服务器
    default-nameserver:
      - 114.114.114.114
      - 119.29.29.29
      - 223.5.5.5
      - 223.6.6.6
      - 8.8.8.8
      - 8.8.4.4
      - 4.2.2.1
      - 4.2.2.2
      - 1.1.1.1

    # 模式fake-ip  or  redir-host
    enhanced-mode: fake-ip

    # 使用本地 hosts 文件
    use-hosts: true

    nameserver:
      # 腾讯DoH DNS Server地址
      - https://doh.pub/dns-query
      - https://sm2.doh.pub/dns-query

      # 腾讯DoT DNS Server地址
      - tls://dot.pub

      # 阿里DoH DNS Server地址
      - https://dns.alidns.com/dns-query
      # 阿里DoT DNS Server地址
      - tls://dns.alidns.com

      # 360 DoH DNS Server地址
      - https://doh.360.cn
      # 360 DoT DNS Server地址
      - tls://dot.360.cn

    fallback:
      # Google DoH DNS Server地址
      - https://dns.google/dns-query
      # Google DoT DNS Server地址
      - tls://dns.google

    # fake-ip仅有
    fake-ip-filter:
      - "*.lan"
      - "*.local"
      - "*.localhost" 
      - "*.msftconnecttest.com"
      - "*.msftncsi.com"
      - msftconnecttest.com
      - msftncsi.com

    # fake-ip仅有
    fallback-filter:
      geoip: true
      geoip-code: CN
      ipcidr:
        - 0.0.0.0/8
        - 10.0.0.0/8
        - 100.64.0.0/10
        - 127.0.0.0/8
        - 169.254.0.0/16
        - 172.16.0.0/12
        - 192.0.0.0/24
        - 192.0.2.0/24
        - 192.168.0.0/16
        - 192.88.99.0/24
        - 198.18.0.0/15
        - 198.51.100.0/24
        - 203.0.113.0/24
        - 224.0.0.0/4
        - 240.0.0.0/4
        - 255.255.255.255/32
      domain:
        - '+.facebook.com'
        - '+.google.com'
        - '+.youtube.com'
  tun:
    enable: true
    stack: system
    auto-route: true
    auto-detect-interface: true
    dns-hijack:
      - any:53
```

**Comment by RealSeek** [comment]
已自行解决

**Comment by JasonLam90** [comment]
开了加速器后，科学梯子功能就自动失效了，是哪个网络层面冲突了？

**Comment by 2455DD** [comment]
@RealSeek 请问是如何解决的？遇到相同问题

**Comment by RealSeek** [comment]
> @RealSeek 请问是如何解决的？遇到相同问题

enhanced-mode 使用 redir-host

**Comment by 2455DD** [comment]
> > @RealSeek 请问是如何解决的？遇到相同问题
> 
> enhanced-mode 使用 redir-host

意思是使用mixin把enhanced-mode改成`redir-host`就行了是吧，不需要再修改cfw TUN选项提供的模板配置是吗

麻烦您看一下这个配置文件(部分)行不行
```
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
    - https://1.12.12.12/dns-query
  fallback:
    - tls://1.1.1.1:853
    - https://dns.google/dns-query
  fake-ip-filter:
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - "*.163.com"
    - "*.lan"
    - "*.local"
    - msftconnecttest.com
    - msftncsi.com
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - 198.18.0.2:53
```
