### ISSUE TITLE
[Bug]: 使用预处理 parsers 修改 proxy-groups 的字段没有生效

### ISSUE THREAD

**Issue by ASIjacket** [Fndroid/clash_for_windows_pkg#3609]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.6

### 操作系统

Windows x64

### 系统版本

win11 22H2

### 问题描述

使用预处理 parsers 修改 proxy-groups 的字段，始终无法匹配，
请问配置编写是否正确

### 待修改原配置
```
proxy-groups:
  - name: 🇺🇲 美国均衡
      type: load-balance
      strategy: consistent-hashing
      url: http://cp.cloudflare.com/generate_204
      interval: 300
      tolerance: 150
      proxies:
      - "🇺🇸 美国 01"
```

### Parsers -> Edit -> parsers 配置
```
parsers: # array
commands:
    - proxy-groups.(🇺🇲 美国均衡).strategy=round-robin
```

**Comment by yi-Xu-0100** [comment]
https://docs.cfw.lbyczf.com/contents/parser.html

**Comment by ASIjacket** [comment]
> https://docs.cfw.lbyczf.com/contents/parser.html



> https://docs.cfw.lbyczf.com/contents/parser.html

我确实参考了文档中 `Commands->定位` 一节的内容， 使用 `name` 值定位这个group，但是依然提示没有匹配

![image](https://user-images.githubusercontent.com/26643085/197998019-1cdad525-07c2-4031-a1f0-9c0625c0c08d.png)

**Comment by yi-Xu-0100** [comment]
你没有 url 或者 reg 去匹配任何配置。

**Comment by yi-Xu-0100** [comment]
![图片](https://user-images.githubusercontent.com/25523606/198008592-3017a7b2-4b6e-4a99-9ca3-8c8635a62f6f.png)

**Comment by ASIjacket** [comment]
修改了一下，这样就可以了

```
parsers:
    - reg: https://test.com.+$
      yaml:
        commands:
          - proxy-groups.(🇺🇲 美国均衡).strategy=round-robin
```

之前右键 `Profiles -> Parsers` 的逻辑，误以为 parsers 是和 profiles 绑定的，看了下配置文件和文档并不是这样，现在解决了。

感谢解惑。
