### ISSUE TITLE
[Bug]: 如何在Rules规则下添加proxy-group.0.name这样名称引用

### ISSUE THREAD

**Issue by why5684784** [Fndroid/clash_for_windows_pkg#3614]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.6

### 操作系统

Windows x64

### 系统版本

Win10 X64 21H2

### 问题描述

我想在预处理中插入条规则 想要的结果是 
```
prepend-rules:
    - DOMAIN，***.com,proxy-groups.0.name
```
但是`proxy-groups.0.name`无法正确解析成代理组名称

### 复现步骤

每次都可以出现

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

parser配置内容:
```
parsers: #array
 - reg: ^.*$
   yaml:
    prepend-rules:
     - DOMAIN,abyui.top,proxy-groups.0.name
    commands: 
     - proxy-groups.1.interval=60
     - proxy-groups.2.interval=60
```
