### ISSUE TITLE
[Bug]: proxy server无法以v6地址配置

### ISSUE THREAD

**Issue by AidonCason** [Fndroid/clash_for_windows_pkg#3616]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.26.0

### 操作系统

Windows x64

### 系统版本

win11 21H2

### 问题描述

server配置v6地址时能够保存，但连接请求报错

### 复现步骤

部分配置如：
```
proxies:
  - name: 'v2ray'
    type: vmess
    # server: v4addr
    # server: '[v6addr]:443'
    # server: '[v6addr]'
    server: v6addr
    port: 443
    ......
```
cfw只有用v4配置时正确生效；但这个配置在config.yaml给clash内核用是正确生效的

### 日志文件

<details><summary>logs</summary><p>

```
15:41:23 WRN [TCP] dial failed error=[xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:443 connect error: ip version error proxy=GLOBAL rAddr=github.com:443
```

</p></details>
