### ISSUE TITLE
[Bug]: 同时使用Mixin 和 System proxy 导致内网域名解析失败

### ISSUE THREAD

**Issue by brucmao** [Fndroid/clash_for_windows_pkg#3619]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.26.0

### 操作系统

Windows x64

### 系统版本

Windows 11 Pro 21H2

### 问题描述

当我只勾选System Proxy时，此时可以访问内网域名 jira.iot.xxx.com, clash请求日志如下
![image](https://user-images.githubusercontent.com/6119652/198502814-73703e6e-9efe-4c78-9cdd-dde020b5614e.png)
当我同时勾选system proxy 和 Mixin(Tun) 时，无法访问内网域名 jira.iot.xxx.com，clash请求日志如下
![image](https://user-images.githubusercontent.com/6119652/198503134-fa91eb5c-0b93-4635-ab7b-0aab7474117a.png)

### 复现步骤

在启用 System Proxy的情况下，只要打开Mixin就无法访问内网域名，我知道可以把内网域名放入到 bypass 可以解决这个问题。
不放入Bypass 是因为家里上网时，公司内网需要vpn访问，我是用 docker版本easyconnect穿透的socks5来连接,我在Proxies里面切换
![image](https://user-images.githubusercontent.com/6119652/198504778-319343ef-89a3-44b0-b169-25731d25992e.png)

现在我在办公室就用的直连模式，同时开启Mixin 和 System proxy 无法上网，只启用Mixin 或者 只启用System proxy都能访问内网域名

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

Mixin 配置
```
mixin:
  dns:
    enable: true                   # set true to enable dns (default is false)
    ipv6: false                    # default is false
    listen: 0.0.0.0:53
    enhanced-mode: fake-ip      # or redir-host
    # use-hosts: true                # lookup hosts and return IP record
    #nameserver-policy:
      #'*.saintartoria.cn': '119.29.29.29'
    default-nameserver:
      - 223.5.5.5 # 阿里DNS
      - 223.6.6.6 # 阿里DNS
      - 8.8.8.8 # Google DNS
      - 8.8.4.4 # Google DNS
      - 119.29.29.29 # 腾讯DNS(DNSPod)      - 
    fake-ip-range: 198.18.0.1/16   # if you don't know what it is, don't change it
    fake-ip-filter:                # fake ip white domain list, aka Always Real IP
      - '*.lan'
      - 'localhost.ptlogin2.qq.com'
      - '+.srv.nintendo.net'
      - '+.stun.playstation.net'
      - '+.msftncsi.com'
      - '+.xboxlive.com'
      - 'msftconnecttest.com'
      - 'xbox.*.microsoft.com'
      - 'dns.msftncsi.com'
      - 'www.msftncsi.com'
      - '*.iot.xxx.com'
    nameserver:
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    fallback: #与 nameserver 内的服务器列表同时发起请求，当规则符合 GEOIP 在 CN 以外时，fallback 列表内的域名服务器生效。
      - 8.8.8.8 # 谷歌DNS
      - 1.1.1.1 # Cloudflare DNS
      - tls://dns.rubyfish.cn:853
      - tls://1.0.0.1:853
      - tls://dns.google:853
      - https://dns.rubyfish.cn/dns-query
      - https://cloudflare-dns.com/dns-query
      - https://dns.google/dns-query
    fallback-filter: 
      geoip: true                  # default    
      ipcidr:                      # ips in these subnets will be considered polluted
        - 240.0.0.0/4
        - 127.0.0.1/8
        - 0.0.0.0/32
      domain:
        - '+.github.com'
        - '+.youtube.com'
        - '+.google.com'
        - '+.facebook.com'
        - '+.twitter.com'
        - '+.youtube.com'
        - '+.xn--ngstr-lra8j.com'
        - '+.google.cn'
        - '+.googleapis.cn'
        - '+.gvt1.com'
        - '+.digitalclouds.dev'
  tun:
    enable: true
    stack: system
    dns-hijack:
      - 198.18.0.2:53
    auto-route: true
    auto-detect-interface: true # 自动检测出口网卡
```

**Comment by yi-Xu-0100** [comment]
把listen注释掉，然后只开mixin看看成功的日志走的什么规则？试试放到fake-ip-filter里

**Comment by brucmao** [comment]
注释listen后，只开mixin可以看到访问 jira.iot.xxx.com 规则如下
![image](https://user-images.githubusercontent.com/6119652/198530772-82a74b8c-2890-4c44-8295-3f906380d298.png)
上面的配置中，我最开始就配置过
```
fake-ip-filter:               
      - '*.lan'
      ...      
      - '*.iot.xxx.com'
```

**Comment by yi-Xu-0100** [comment]
@brucmao 那我感觉你放入 bypass 里，tun会接管，仍然能够被接入clash，然后解析出内网ip然后走你的规则。

你不放 bypass的理由是什么？

然后你系统代理和 mixin 同时开，要不在 host 里指定下解析试试。

**Comment by brucmao** [comment]
@yi-Xu-0100 不放Bypass的原因是当我在家里使用时，想让公司内网域名或者ip走我自定义socks5代理（将公司vpn装在docker里，然后穿透一个socks5代理）
其实平时都不会同时启用Mixin 和 System Proxy。比如我在办公室一般只启用System Proxy，但是有时候想用 scoop安装软件时，就临时启用Minxin 让 Powershell 走代理.今天就是启用 Mixin 后发现内网域名无法解析。

**Comment by yi-Xu-0100** [comment]
> 不放Bypass的原因是当我在家里使用时，想让公司内网域名或者ip走我自定义socks5代理（将公司vpn装在docker里，然后穿透一个socks5代理）

如果只是临时用的话，那分别启用最好。

tun 配置中是需要设置 dns 的， dns 里有 host 配置和 use-host 的选项。

你同时用 system proxy 和 mixin 的时候，是走的 proxy 规则，然后应该直接交给你的代理 officeweb 了，解析不到 ip 也是你的代理 officeweb 给出的（相当于域名给了 officeweb 可能是这个意思）。而 进一步的 officeweb 的规则选择还是走直连，从图中没看出来，最好给更多的相关日志看看。

只开 system proxy 或 mixin 的时候，都好像解析完了，然后给 officeweb 了。二者走的规则不一致，或许你可以将域名判断的规则注释掉试试，让他们走同一个 ip 规则试试。

**Comment by brucmao** [comment]
我在Settings/Profiles/Parsers 对办公室局域网ip和域名定义的如下
```
parsers: # array
  - url: https://xxxx.top/api/v1/client/subscribe?token=xxxx
    yaml:
      prepend-rules:
         # officeweb
        - DOMAIN-SUFFIX,iot.xxx.com,officeweb        
        - IP-CIDR,172.18.1.0/24,officeweb
      prepend-proxies:
        - name: easyconnect
          type: socks5
          server: 127.0.0.1
          port: 1080
      prepend-proxy-groups:        
        - name: officeweb
          type: select
          proxies:
            - DIRECT
            - easyconnect 


        
```
其中 iot.xxx.com 会被内网dns 解析成172.18.1.203
officeweb我在办公室选择的DIRECT
这个前置规则的逻辑应该是：访问iot.xxx.com 会走DIRECT ?

另外 tun 模式中 use-host 在 enhanced-mode: fake-ip 下不起作用？（我记得有人说过得用redir-host）
