### ISSUE TITLE
0.20.7新版本vmess代理不能工作 

### ISSUE THREAD

**Issue by norangit** [Fndroid/clash_for_windows_pkg#3650]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.27.0

### 操作系统

Windows x64

### 系统版本

win11 22h2

### 问题描述

今天服务商更新了服务端，导致clash里vmess的都不能使用了，下载了服务商提供的配置文件，也看了本站wike里的vmess配置，找到一个不一样的配置的地方，不知道是不是这个问题

```
name: 'C01'
    type: vmess
    server: xx.com
    port: 443
    uuid: uuid
    alterId: 0
    cipher: auto
    udp: true
    servername: xx.com
    network: ws
    ws-opts:
      path: /api
      headers: { Host: xx.com }
    ws-path: /api
    ws-headers:
      Host: xx.com
    tls: true
```
重点在于 ws-opts下面的headers的不一样，本站wiki里的是这样的：

```
    ws-opts:
      path: /path
      headers:
        Host: v2ray.com
```
格式是没问题的话，现在只有 trojan 的一个节点可用

### 复现步骤

恩，咋复现呢，参考我上面贴的那个我的配置格式，试试？

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
```yaml
    ws-opts:
      path: /api
      headers: { Host: xx.com }
    ws-path: /api
    ws-headers:
      Host: xx.com
```

这里好像多了 ws-path 和 ws-headers ，不确定是否删除可用。。。
