### ISSUE TITLE
请教一个问题，这是我参考大佬的规则改的，我希望除了我主动配置的地址其他的都不走代理，这个配置对么？配置为DIRECT的代理会经过代理服务器吗？

### ISSUE THREAD

**Issue by SJJ-dot** [Fndroid/clash_for_windows_pkg#3686]
```yaml
parsers: # array
  # - reg: ^.*$ 匹配所有订阅，或  - url: https://example.com/profile.yaml 指定订阅
  - reg: ^.*$
  # 删除服务商提供的策略组和规则
    code: |
      module.exports.parse = (raw, { yaml }) => {
        const rawObj = yaml.parse(raw)
        const groups = []
        const rules = []
        return yaml.stringify({ ...rawObj, 'proxy-groups': groups, rules })
      } 
  # 建立自己的配置
    yaml:
      prepend-proxy-groups: # 建立策略组   
        - name: 🔯 代理模式 
          type: select
          url: http://www.gstatic.com/generate_204
          interval: 300
          tolerance: 50
          proxies:
            - ♻️ 自动选择
            - 🔰 手动选择
            - DIRECT
           
        - name: ♻️ 自动选择 
          type: url-test
          url: http://www.gstatic.com/generate_204
          interval: 300
          tolerance: 50
          
        - name: 🔰 手动选择 
          type: select
         
      commands:
        - proxy-groups.♻️ 自动选择.proxies=[]proxyNames # 向指定策略组添加订阅中的节点名，可使用正则过滤
        - proxy-groups.🔰 手动选择.proxies=[]proxyNames # 向指定策略组添加订阅中的节点名，可使用正则过滤

      prepend-rules: # 规则由上往下遍历，如上面规则已经命中，则不再往下处理
        - DOMAIN,goo.gle,🔯 代理模式
        - DOMAIN-SUFFIX,google.com,🔯 代理模式
        - MATCH,DIRECT # 规则之外的
```
