### ISSUE TITLE
[Bug]: TUN模式下DNS失效

### ISSUE THREAD

**Issue by joyoner** [Fndroid/clash_for_windows_pkg#3693]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.7

### 操作系统

Windows x64

### 系统版本

Win11 21H2

### 背景
Clash为全新安装0.20.7，非历史版本升级。
### 配置
1. TUN配置如下：
```
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
```
2. MIXIN配置如下：
```
mixin: # object
  dns:
    enable: true
    listen: 0.0.0.0:53
    enhanced-mode: fake-ip # redir-host or fake-ip
    ipv6: false 
    nameserver: 
      - 119.29.29.29
      - 223.5.5.5
    fallback:
      #- tls://8.8.8.8:853         # Google DNS over TLS 50ms
      # - tls://8.8.4.4:853         # cloudflare DNS over TLS 50ms
      # - https://1.1.1.1/dns-query # cloudflare DNS over HTTPS
      # - https://dns.google/dns-query # Google DNS over HTTPS
    fallback-filter:
      geoip: true
      geoip-code: CN
```

### 现象
1. Connections有TUN字样
2. 过一段时间，偶发/开合屏幕，通过域名网站无法访问
3. 出于定位考虑，测试使用IP:Port的方式可以正常访问
4. 在Logs/Connections里没有对应域名的解析记录
~~5. 在cmd控制台执行 ipconfig /flushdns可临时解决此问题~~
6. 终端CMD解析域名超时
```
C:\Windows\system32>nslookup ip111.cn
DNS request timed out.
    timeout was 2 seconds.
服务器:  UnKnown
Address:  198.18.0.2

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** 请求 UnKnown 超时
```

### 求助
1. 问题出现原因是什么，比如DNS污染？Clash未正常接管？
2. 如何进一步定位和排障

### 复现步骤

无法精准复现，使用一段时间，或者开合笔记本屏幕（休眠后唤醒）会出现 

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
