### ISSUE TITLE
[Feature Request]: parsers的file支持从网络获取

### ISSUE THREAD

**Issue by shelllee** [Fndroid/clash_for_windows_pkg#3736]
### 功能描述

parsers当前只支持本地文件：

```yaml
parsers:
  - reg: https://test.com.+$ # 第一个执行的parser
    file: "C:/Users/cfw/parser.yaml"
  - url: https://example.com/profile.yaml # 对上一个parser执行的结果进行处理
    file: "C:/Users/cfw/parser.js"
```

希望可以支持网络文件：

```yaml
parsers:
  - reg: https://test.com.+$ # 第一个执行的parser
    file: "https://.../parser.yaml"
  - url: https://example.com/profile.yaml # 对上一个parser执行的结果进行处理
    file: "https://.../parser.js"
```

**Comment by yi-Xu-0100** [comment]
哦，这里懂了

**Comment by Wdszj** [comment]
Xiexie

**Comment by shelllee** [comment]
> 哦，这里懂了

嗯，这个描述详细

**Comment by Fndroid** [comment]
最新版已经加入了，但要注意：

使用远端配置预处理器请选择可信的代码提供者，如不能信任代码提供者，可以从远端拷贝代码然后使用code填入而非使用remote方式引入！

**Comment by shelllee** [comment]
@Fndroid 没怎么搞过js，花了几个小时终于搞定了

- parsers

```
parsers: # array
  - reg: https://s.trojanflare.+$
    remote:
      url: https://github.com/shelllee/clash_rules/blob/main/clash_rules_parsers.js?raw=true
      cache: false
```

- parsers js

```
module.exports.parse = async (raw, { axios, yaml, notify, console }, { name, url, interval, selected }) => {
    const url_provider = 'https://github.com/shelllee/clash_rules/blob/main/clash_rules.yaml?raw=true'
    let { headers:{"subscription-userinfo": si = ""}={}, status, data } = await axios.get(url_provider)
    // si = si.replace(/;*$/g,'')
    if (status !== 200) {
        console.log('error ' + status)
        return raw
    }

    let content = yaml.parse(raw)
    let parser = yaml.parse(data)

    let content_key = 'rule-providers'
    let parser_key = 'mix-' + content_key

    if (parser[parser_key] !== undefined)
    {
        content[content_key] = parser[parser_key]
    }

    content_key = 'rules'
    parser_key = 'prepend-' + content_key

    if (parser[parser_key] !== undefined)
    {
        if (content[content_key] === undefined)
        {
            content[content_key] = []
        }

        content[content_key] = parser[parser_key].concat(content[content_key])
    }

    let result = yaml.stringify(content)

    console.log(result)

    return result
}
```

感觉最终会把内置的规则都解析一遍！
