### ISSUE TITLE
[Feature Request]: 求解答疑惑，TUN Mode 右边的小齿轮设置是否会覆盖配置文件

### ISSUE THREAD

**Issue by catch6** [Fndroid/clash_for_windows_pkg#3741]
### 功能描述

我目前是通过配置文件来启用tun，但是cfw的tun mode右边的小齿轮和启用按钮让我很迷惑，究竟是以配置文件的为准还是以界面上的为准，希望可以完全按配置文件来加载，这样复制给别人不需要再进行额外的手动配置

<img width="881" alt="image" src="https://user-images.githubusercontent.com/15259698/204225959-83fd2ba9-1416-4850-9cb0-9d717d0f6034.png">

配置文件
```yaml
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - 198.18.0.2:53

dns:
  enable: true
  listen: :53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 223.5.5.5
    - 8.8.8.8
    - 114.114.114.114
  nameserver:
    - 223.5.5.5
    - 8.8.8.8
    - 114.114.114.114
  fallback:
    - https://dns.alidns.com/dns-query
    - https://8888.google/dns-query
    - https://doh.pub/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
```
