### ISSUE TITLE
[Feature Request]: PROCESS程序分流

### ISSUE THREAD

**Issue by Goojoe** [Fndroid/clash_for_windows_pkg#3790]
### 功能描述

![图片](https://user-images.githubusercontent.com/78355492/206897587-733ff89d-52e6-4e2a-b643-18b8e2831ebd.png)

想给下载软件分流,例如NDM,IDM,Microsoft Store

国内的就直连,其他的一律代理

**Comment by Goojoe** [comment]
> @Goojoe 可以结合 script shortcut 的 resolve_process_xxx 和 其他几个用于匹配规则的 function 去实现。
> 
> https://github.com/Dreamacro/clash/wiki/Clash-Premium-Features#script-shortcut

对Js不是很熟悉,你能写一个代码示例吗,谢谢

**Comment by yi-Xu-0100** [comment]
```yaml
script:
  shortcuts:
    IDM_CN: resolve_process_name == 'IDM.exe' and geoip == 'CN'
rules:
  - SCRIPT,IDM_CN,DIRECT
```

仅供参考，没有实验，建议自己调试并测试。
