### ISSUE TITLE
预配置如何向策略组添加指定位置策略组?

### ISSUE THREAD

**Issue by Mortalit** [Fndroid/clash_for_windows_pkg#3821]
```yaml
parsers: 
  - url: https://example.com/profile.yaml
    yaml:
      append-proxy-groups: 
        - name: 漏网之鱼
          type: select
          proxies:
            - DIRECT
      commands:
```

下载的配置自带节点选择和自动选择等等组,但有时候机场又会取名为手动切换
想往自定义组加入自带组的第一个组,有办法做到吗
试过- proxy-groups. 漏网之鱼.proxies.0+proxy-groups.0.name没用
