### ISSUE TITLE
[Feature Request]: 赋予Clash TUN适配器网络访问权限

### ISSUE THREAD

**Issue by hongwen000** [Fndroid/clash_for_windows_pkg#3834]
### 功能描述

目前有Open Issue #3717 中提到了Clash TUN适配器显示无网络访问权限的问题， 最终讨论结果是关掉Clash TUN模式，而我希望请教让Clash TUN适配器获取网络访问权限的方法，因为该模式很有用，能够让一些不走http代理的应用也走代理。

目前有Closed Issue #1659 #2108 #3088 中提及了以下方法试图解决这个问题：

1. 修改fake ip配置从而允许Windows ncsi相关域名被正确解析。
2. 正确配置防火墙。
3. 执行ipconfig /renew。
4. 配置注册表/组策略禁用ncsi。

以上方法全部尝试，无效。此外尝试降级Clash至0.19.19, 0.18.7, 0.15.5版本，并尝试单独降低Clash Core，及反复调试CLash配置中涉及tun和dns的选项，依然无效。

也有Core Issue #1674 提及使用DDL注入的方式劫持NCSI结果，https://github.com/dantmnf/NCSIOverride，然而在新版Windows 11中调用NCSI的入口从nlasvc.dll变为了netprofmsvc.dll，导致该方法也无效。

希望能找到一个方法，使得Clash TUN适配器拥有网络访问权限。

**Comment by hongwen000** [comment]
以下为我现有的涉及TUN适配器的配置：
```
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 119.29.29.29
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - www.msftconnecttest.com
    - www.msftncsi.com
    - dns.msftncsi.com
    - resolver1.opendns.com
    - detectportal.firefox.com
    - dmd.metaservices.microsoft.com
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://doh.opendns.com/dns-query
    - https://dns.google/dns-query
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true
    ip-cidr:
      - 240.0.0.0/4
      - 127.0.0.1/8
      - 0.0.0.0/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.twitter.com
      - +.youtube.com
      - +.xn--ngstr-lra8j.com
      - +.google.cn
      - +.googleapis.cn
      - +.googleapis.com
      - +.gvt1.com
      - +.github.com
tun:
  enable: true
  stack: system
  dns-hijack:
    - 198.18.0.2:53
  auto-route: true
  auto-detect-interface: true
```
