### ISSUE TITLE
如何避免代理ipv6连接？

### ISSUE THREAD

**Issue by suiahae** [Fndroid/clash_for_windows_pkg#387]
开启代理后，无法访问纯ipv6页面，进行ipv6测试，也会得到测试失败的结果，请问如何解决这个问题呢？

查阅了CFW文档，但还是不会编写规则。

![image](https://user-images.githubusercontent.com/45323123/72661819-f9eeed80-3a19-11ea-85a8-8894fbc94404.png)
_截图来源：https://docs.cfw.lbyczf.com/contents/ui/profiles/rules.html_

ps. 但是如果在`Rule:`代码段中设置该网址直连如`- DOMAIN-SUFFIX,test-ipv6.com,DIRECT`，则测试通过。

**Comment by Fndroid** [comment]
两个地方排除一下：
1. 要访问的网站被直连
2. 配置文件中没有打开dns设置或者打开了dns设置同时设置了ipv6: true

**Comment by suiahae** [comment]
> 两个地方排除一下：
> 
> 1. 要访问的网站被直连
> 2. 配置文件中没有打开dns设置或者打开了dns设置同时设置了ipv6: true

_发现配置文件中没有打开dns设置_，但加入如下DNS设置后，通过代理进行ipv6测试，依然显示未检测到ipv6地址。（取消代理后，ipv6测试成功）

```
dns:
  enable: true
  ipv6: false # default is false
  nameserver:
    - 192.168.1.1 # 建议添加默认网关下发的 DNS 保证响应
    - tls://dns.rubyfish.cn
    - https://1.1.1.1/dns-query # dns over https
    - 1.1.1.1
    - 1.0.0.1
    - 223.5.5.5        # 这里开始的DNS可以换成其他DNS，尽可能多设置几个，无需考虑污染
```
