### ISSUE TITLE
[Bug]: proxy-providers 无法解析 Base64 编码的订阅地址

### ISSUE THREAD

**Issue by muink** [Fndroid/clash_for_windows_pkg#3921]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.12

### 操作系统

Windows x64

### 系统版本

Windows 10

### 问题描述

proxy-providers 无法解析 Base64 编码的订阅地址
有些机场的订阅下载来不是明文, 而是用 base64 预先编码过的
proxy-providers 在更新时并没有进行解码这个过程导致错误

### 复现步骤

示例
```yaml
proxy-providers:
  12345:
    type: http
    url: "https://sub.12345.com/Config/ClashConfig?u=3b514c27-d738-2a4b-a361-42bb6ccc3d01"
    interval: 504
    path: ./proxy-provider/12345.yml
    health-check:
      enable: true
      interval: 0
      url: http://www.gstatic.com/generate_204
```

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
