### ISSUE TITLE
[Bug]: provider一直无法更新，提示clash initial proxy provider file "suying666"must have a proxies field，找了很多资料找不到原因了

### ISSUE THREAD

**Issue by GrinderLee** [Fndroid/clash_for_windows_pkg#3931]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.14

### 操作系统

Windows x64

### 系统版本

windows 11 21H2

### 问题描述

![image](https://user-images.githubusercontent.com/102518713/214675098-d9cdd7ed-45d5-497b-b4cf-d406b43b2dac.png)

点击切换profiles后log里面就只有这一行，然后弹出窗口报错must have proxies

以前一直用的好好的，配置文件从来没有更改过，我的suying666.yaml的文件里开头第一行也一直是proxies: 。记得几个月前clash更新过一次后就这样无法更新providers里的proxy了，今天更新了这个版本后，直接无法选取以前这个profiles了，选取后弹出窗口后直接不能使用这个profiles了，求救，谢谢

### 复现步骤

点击切换profiles后log里面就只有这一行，然后弹出窗口报错must have proxies

以前一直用的好好的，配置文件从来没有更改过，我的suying666.yaml的文件里开头第一行也一直是proxies: 。记得几个月前clash更新过一次后就这样无法更新providers里的proxy了，今天更新了这个版本后，直接无法选取以前这个profiles了，选取后弹出窗口后直接不能使用这个profiles了，求救，谢谢

### 日志文件

02:29:04 INF [Config] start initial provider name=suying666

### 其他补充
profiles配置文件：

```
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: silent
external-controller: 0.0.0.0:9090
secret: ""
#ProxyList:
#    type: http
#    url: https://api.wcc.best/sub?target=clash&url=https
#    interval: 3600
#    path: ./profiles/proxies/suying666.yaml
#    health-check:
#      enable: true
#      url: http://www.gstatic.com/generate_204
#      interval: 300
proxy-providers:
  suying666:
    type: http
    url: https://api.wcc.best/sub?target=clash&url=https
    interval: 3600
    path: ./profiles/proxies/suying666.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

proxy-groups:
  - name: PROXY
    type: select
    use:
      - suying666
    proxies:
      - DIRECT

rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt
    path: ./ruleset/greatfire.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: ./ruleset/lancidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    path: ./ruleset/applications.yaml
    interval: 86400
rules:
  - DOMAIN-KEYWORD,sifang,PROXY
  - DOMAIN-KEYWORD,51cg,PROXY
  - DOMAIN-KEYWORD,ledger,PROXY
  - DOMAIN-KEYWORD,letstalk,PROXY
  - DOMAIN-KEYWORD,adxadserv,PROXY
  - DOMAIN-KEYWORD,155.fun,PROXY
  - DOMAIN-KEYWORD,suying,PROXY
  - DOMAIN-KEYWORD,gtowizard,PROXY
  - PROCESS-NAME,Streamlabs OBS.exe,PROXY
  - PROCESS-NAME,obs-browser-page.exe,PROXY
  - PROCESS-NAME,obs64.exe,PROXY
  - PROCESS-NAME,crashpad_database_util.exe,PROXY
  - PROCESS-NAME,crashpad_handler.exe,PROXY
  - PROCESS-NAME,crash-handler-process.exe,PROXY
  - DOMAIN-KEYWORD,flopzilla,PROXY
  - PROCESS-NAME,GGnet.exe,PROXY
  - DOMAIN-KEYWORD,persistence.biatalk.cc,PROXY
  - DOMAIN-KEYWORD,doax,PROXY
  - DOMAIN-KEYWORD,cloudflare,PROXY
  - DOMAIN-KEYWORD,epicgames,PROXY
  - DOMAIN-KEYWORD,proxyrarbg,PROXY
  - DOMAIN-KEYWORD,steam-chat.com,PROXY
  - DOMAIN-KEYWORD,cloudflare.steamstatic,PROXY
  - DOMAIN-KEYWORD,api.steampowered.com,PROXY
  - DOMAIN-KEYWORD,fandom.com,PROXY
  - DOMAIN-KEYWORD,h2n-up,PROXY
  - DOMAIN-KEYWORD,ohsoft,PROXY
  - PROCESS-NAME,MTGA.exe,PROXY
  - DOMAIN-KEYWORD,mtgo,PROXY
  - DOMAIN-KEYWORD,gyan.dev,PROXY
  - DOMAIN-KEYWORD,ffmpeg,PROXY
  - DOMAIN-KEYWORD,pypi,PROXY
  - DOMAIN-KEYWORD,pythonhost,PROXY
  - DOMAIN-KEYWORD,winget,PROXY
  - PROCESS-NAME,pr-downloader.exe,PROXY
  - PROCESS-NAME,Beyond-All-Reason.exe,PROXY
  - DOMAIN,repos.springrts.com,PROXY
  - DOMAIN-KEYWORD,springrts,PROXY
  - DOMAIN-KEYWORD,bnbstatic,PROXY
  - DOMAIN-KEYWORD,binance,PROXY
  - DOMAIN-KEYWORD,yandex,PROXY
  - DOMAIN-KEYWORD,captcha,PROXY
  - PROCESS-NAME,Discord.exe,PROXY
  - DOMAIN-KEYWORD,discord,PROXY
  - DOMAIN-KEYWORD,itunes.apple,PROXY
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,greatfire,PROXY
  - RULE-SET,telegramcidr,PROXY
  - MATCH,DIRECT
```
