### ISSUE TITLE
providers界面手动更新规则时，总会遇到context deadline exceeded 错误

### ISSUE THREAD

**Issue by chensimmons** [Fndroid/clash_for_windows_pkg#3957]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.15

### 操作系统

Windows x64

### 系统版本

winodws 10 专业版

### 问题描述

规则来源于 
https://github.com/Loyalsoldier/clash-rules，
在providers界面手动更新规则时，特别是direct和reject这两个规则，经常遇到 context deadline exceeded错误，
规则地址是 
https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
和
https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
网络是正常的，浏览器或CFW中都能正常打开上面两个链接，
连续几个版本都有这个问题，不知这个能不能改进

<img width="646" alt="Snipaste_2023-02-03_11-33-27" src="https://user-images.githubusercontent.com/31755429/216508753-d8949464-0fc5-4e9b-839e-7ce06fd0b115.png">

### 复现步骤

```
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./profiles/rules/reject.yaml
    interval: 86400
```

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
