### ISSUE TITLE
[Feature Request]: parsers支持远程yaml文件

### ISSUE THREAD

**Issue by shelllee** [Fndroid/clash_for_windows_pkg#3972]
### 功能描述

parsers当前只支持本地文件（yaml格式）：

```yaml
parsers:
  - reg: https://test.com.+$ # 第一个执行的parser
    file: "C:/Users/cfw/parser.yaml"
```

希望可以支持网络文件：

```
parsers: # array
  - reg: https://s.abcd.+$
    remote:
      url: https://github.com/shelllee/clash_rules/blob/main/clash_rules_parsers.yaml?raw=true
      cache: false
```

### 其他内容

该feature request https://github.com/Fndroid/clash_for_windows_pkg/issues/3736 提及了`远程js`与`远程yaml`两种模式，当时只实现了`远程js`，当时对我来说也可以满足需求，所以没有跟踪`远程yaml`需求

考虑以下几点原因，再开个`远程yaml`的feature request：
1. `远程js`的终极版是实现所有规则的解析，但是CFW已经内置了解析为何还需要外部再研究实现一遍
2. `远程yaml`完全没有`远程js`的天然安全问题
3. 今天看到有人回复也提及远程`yaml需求` https://github.com/Fndroid/clash_for_windows_pkg/issues/3736#issuecomment-1420282260
4. 补充：很多用户能配置yaml就不错了，不一定有能力写js

**Comment by Fndroid** [comment]
远程js是因为js能执行逻辑代码能做条件判断，yaml是不能的，如果是静态内容那为什么不直接写在本地

**Comment by shelllee** [comment]
> 远程js是因为js能执行逻辑代码能做条件判断，yaml是不能的，如果是静态内容那为什么不直接写在本地

考虑多端的情况，比如我有若干台式机，拷贝文件不如维护一份在线文件

**Comment by Fndroid** [comment]
但你多端也要写parser吧

**Comment by shelllee** [comment]
> 

粘贴三行代码，一劳永逸

```yaml
parsers:
  - reg: https://test.com.+$ # 第一个执行的parser
    file: "https://.../parser.yaml"
```

**Comment by shelllee** [comment]
补充：很多用户能配置yaml就不错了，不一定有能力写js

**Comment by Fndroid** [comment]
This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days

**Comment by shelllee** [comment]
remove `stale` label

**Comment by Fndroid** [comment]
This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days

**Comment by shelllee** [comment]
remove `stale` label

**Comment by Fndroid** [comment]
我还是认为没有太大的实用意义😢

**Comment by shelllee** [comment]
> 我还是认为没有太大的实用意义😢

我认为现阶段是有一定意义的，很多人并不会写js，也不懂如何调试，甚至日志是啥都不知道

而且这份js，最终可能各种规则完全都解析一遍，倒不如官方提供一份完整的解析，让用户按需改几行就能用，这样就最好了，不然每个人都要用很多时间去搞这个js，甚至可以意淫一下可以通过界面进行配置

如果没有的话，那我认为远程yaml文件会更加方便，覆盖更多有需求的用户

**Comment by Fndroid** [comment]
yaml没逻辑，你分享别人也用不了那为什么要远程。

远程yaml只能解决你说的一个人有n个电脑然后避免复制多个文件，但实际上你完全可以不单独开yaml文件，而直接写在parser里（用yaml的方式而不是file）。

跟写js没有什么关系，我只是说js有逻辑，yaml没逻辑并不能分享。

**Comment by shelllee** [comment]
抱歉，我的问题描述好像不准确，我知道本地yaml parsers是支持的，那远程是否能支持呢

```
parsers: # array
  - reg: https://s.abcd.+$
    remote:
      url: https://github.com/shelllee/clash_rules/blob/main/clash_rules_parsers.yaml?raw=true
      cache: false
```
