### ISSUE TITLE
连接vmess+ws+tls提示tls: internal error, 但v2ray连接正常.

### ISSUE THREAD

**Issue by gin419** [Fndroid/clash_for_windows_pkg#398]
增加了v2ray 服务器(vmess+ws+tls),配置过程中一直不成功,日志里面要么是 400 Bad request 要么是tls: internal error. 尝试不同参数不同取值以后依然是同样的情况.

但使用v2rayN 对比操作,是可以连上v2ray服务器并正常工作的, 表面上看是两者之间的个别参数的不同, 比如cipher 在CFW 必选而v2rayN 没有.

请看这个问题怎么解决呢?

两个软件的配置情况如下:
![v2rayN客户端配置](https://user-images.githubusercontent.com/28433485/73518407-2c94df00-4439-11ea-8405-dc96e361d864.PNG)

```
#CFW的服务器配置

Proxy:
- name: "GIA US 01"
  type: vmess
  server: ***.***.***.***
  port: 443
  uuid: /<uuid>/
  alterId: 233
  network: ws
  tls: true
  cipher: auto
  # udp: true
  # tls: true
  # skip-cert-verify: true
  # ws-path: /
  # ws-headers:
  # host: ****

Proxy Group:
- name: "Auto"
  type: url-test
  proxies:
    - "GIA US 01"
  url: 'http://www.gstatic.com/generate_204'
  interval: 300
```

另外, 使用的 https://github.com/233boy/v2ray/wiki/V2Ray%E4%B8%80%E9%94%AE%E5%AE%89%E8%A3%85%E8%84%9A%E6%9C%AC 来搭建的
