### ISSUE TITLE
[Feature Request]: disable quic protocol option?

### ISSUE THREAD

**Issue by joseidesuu** [Fndroid/clash_for_windows_pkg#3999]
### 功能描述

how do i disable the quic protocol, in openclash openwrt there is an option "disable quic" but in clash for windows there is not that option. so i am watching YouTube feels slow buffering

**Comment by yi-Xu-0100** [comment]
```yaml
  - reg: '^.*$'
  # - reg: ^.*$ 匹配所有订阅
    yaml:
      mix-object:
        script:
          shortcuts:
            quic: network == 'udp' and dst_port == 443
      prepend-rules:
        - SCRIPT,quic,REJECT
```

要不试试 parser 加这个？

**Comment by joseidesuu** [comment]
怎么做，使用mixin？

**Comment by yi-Xu-0100** [comment]
> 要不试试 parser 加这个?

@joseidesuu

**Comment by joseidesuu** [comment]
告诉我如何配置它

**Comment by yi-Xu-0100** [comment]
@joseidesuu https://docs.cfw.lbyczf.com/contents/parser.html

**Comment by joseidesuu** [comment]
> @joseidesuu https://docs.cfw.lbyczf.com/contents/parser.html

好的，对于部分 ```
- reg: ^.*$
``` 是必需的 url 吗？

**Comment by yi-Xu-0100** [comment]
@joseidesuu 这代表用正则去匹配，效果是匹配所有链接

https://docs.cfw.lbyczf.com/contents/parser.html#正则匹配

**Comment by joseidesuu** [comment]
> @joseidesuu 这代表用正则去匹配，效果是匹配所有链接
> 
> [https://docs.cfw.lbyczf.com/contents/parser.html#正则匹配](https://docs.cfw.lbyczf.com/contents/parser.html#%E6%AD%A3%E5%88%99%E5%8C%B9%E9%85%8D)

是这样吗？
![image](https://user-images.githubusercontent.com/116565260/218740783-dcdd4d0c-f279-4bd5-b7ab-aab7f2d35620.png)

**Comment by joseidesuu** [comment]
![image](https://user-images.githubusercontent.com/116565260/218743193-6dff53be-4060-4637-9650-03c809021574.png)

**Comment by yi-Xu-0100** [comment]
@joseidesuu 复制下面的吧，需要加上 parser 和注意缩进。

```yaml
parser:
  - reg: '^.*$'
  # - reg: ^.*$ 匹配所有订阅
    yaml:
      mix-object:
        script:
          shortcuts:
            quic: network == 'udp' and dst_port == 443
      prepend-rules:
        - SCRIPT,quic,REJECT
```

**Comment by joseidesuu** [comment]
> @joseidesuu 复制下面的吧，需要加上 parser 和注意缩进。
> 
> ```yaml
> parser:
>   - reg: '^.*$'
>   # - reg: ^.*$ 匹配所有订阅
>     yaml:
>       mix-object:
>         script:
>           shortcuts:
>             quic: network == 'udp' and dst_port == 443
>       prepend-rules:
>         - SCRIPT,quic,REJECT
> ```
还是行不通 😢 
![image](https://user-images.githubusercontent.com/116565260/218750630-16a137b1-81de-48d1-aea2-a92a16b5b3cd.png)

**Comment by yi-Xu-0100** [comment]
@joseidesuu 你更新订阅了吗？

**Comment by joseidesuu** [comment]
> @joseidesuu 你更新订阅了吗？ parser 是更新订阅后，会修改订阅的内容。更新完打开看下内容是否包含 script

你的意思是订阅是一个配置文件？

这是我目前使用的配置文件

```
proxies:
  - name: MSA ID WS 80
    server: 104.18.20.226
    port: 80
    type: vmess
    uuid: 2cc843ac-4246-4f2c-8d9e-956ca6af9ba7
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: msa.rcvpn.net
    udp: true
  - name: MSA ID SSL 443
    server: msa.rcvpn.net
    port: 443
    type: vmess
    uuid: 2cc843ac-4246-4f2c-8d9e-956ca6af9ba7
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: media.fcgk35-1.fna.whatsapp.net
    udp: true
    _index: 0
  - name: Linode Japan WS 80
    type: vmess
    server: 104.18.20.226
    port: 80
    uuid: a90c821f-9fc6-40f0-ba57-c9e5470e9b8c
    alterId: 0
    cipher: auto
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: jp.vmess1.xservs.xyz
  - name: Linode Japan SSL 443
    type: vmess
    server: jp.vmess1.xservs.xyz
    port: 443
    uuid: a90c821f-9fc6-40f0-ba57-c9e5470e9b8c
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: media.fcgk35-1.fna.whatsapp.net
proxy-groups:
  - name: v2ray
    proxies:
      - MSA ID SSL 443
      - MSA ID WS 80
    type: select
  - name: GeForce NOW
    proxies:
      - Linode Japan WS 80
      - Linode Japan SSL 443
    type: select
rules:
  - IP-CIDR,221.110.42.0/24,GeForce NOW
  - IP-CIDR,221.110.189.0/24,GeForce NOW
  - DOMAIN-SUFFIX,nvidia.com,GeForce NOW
  - DOMAIN-SUFFIX,geforcenow.com,GeForce NOW
  - DOMAIN-SUFFIX,nvidiagrid.net,GeForce NOW
  - DOMAIN-SUFFIX,games.geforce.com,GeForce NOW
  - DST-PORT,3478,DIRECT
  - DST-PORT,4244,DIRECT
  - DST-PORT,5288,DIRECT
  - DST-PORT,5242,DIRECT
  - DST-PORT,5349,DIRECT
  - DST-PORT,34784,DIRECT
  - DST-PORT,45395,DIRECT
  - DST-PORT,50318,DIRECT
  - DST-PORT,59234,DIRECT
  - MATCH,v2ray
```

**Comment by yi-Xu-0100** [comment]
@joseidesuu 首先我不建议分享个人配置，节点信息可能被泄露，建议删除上条回复

然后，你是指你的 profile 用的是个人本地的文件是吗？

那就直接在配置文件的 proxies 前加入 script 的内容

```yaml
script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
```

然后在 rules 的第一行，加入 `- SCRIPT,quic,REJECT`。注意缩进
