### ISSUE TITLE
[Bug]: provider提供的节点测延迟全部timeout

### ISSUE THREAD

**Issue by Creepercdn** [Fndroid/clash_for_windows_pkg#4006]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.16

### 操作系统

Windows x64

### 系统版本

22h2

### 问题描述

provider提供的节点测延迟全部timeout，proxy group测延迟正常，可以正常联网

### 复现步骤

使用“其他补充”中的配置，在proxies/rule对proxy group里的节点测延迟

### 日志文件

没有日志输出
<details><summary>logs</summary><p>

</p></details>

### 其他补充

config:
```
mixed-port: *******
external-controller: *****
proxy-providers:
  hooked:
    type: file
    path: ***********
proxy-groups:
  - name: proxyit
    type: select
    use:
      - hooked
rules:
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - IP-CIDR6,fc00::/7,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - IP-CIDR6,fd00::/8,DIRECT,no-resolve
  - MATCH,proxyit
```
