### ISSUE TITLE
[Bug]: Edge浏览器下 tun模式 访问不了chatgpt，但火狐可以。

### ISSUE THREAD

**Issue by ayuayue** [Fndroid/clash_for_windows_pkg#4040]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.15

### 操作系统

Windows x64

### 系统版本

win11

### 问题描述

这是我的配置文件
```
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback:
    - 1.1.1.1
    - 1.0.0.1
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
```
使用的是 tun 模式，在edge浏览器中，登录chatgpt会提示地区不行，但是在火狐浏览器就可以正常登录。没有开启浏览器插件代理。只用了 clash tun模式来接管。全局模式也不行，在火狐都可以。按理说tun模式不是会接管所有的流量吗？

### 复现步骤

使用 clash 的tun模式，
使用 edge 登录 chat.openai.com

### 日志文件

[2023-02-19-000111.log](https://github.com/Fndroid/clash_for_windows_pkg/files/10774780/2023-02-19-000111.log)
[2023-02-18-002347.log](https://github.com/Fndroid/clash_for_windows_pkg/files/10774781/2023-02-18-002347.log)
