### ISSUE TITLE
[Bug]: 「配置文件预处理」在配置文件中存在空白项时无法生效

### ISSUE THREAD

**Issue by cxplay** [Fndroid/clash_for_windows_pkg#4051]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.16

### 操作系统

Windows x64

### 系统版本

22H2 19045.2604

### 问题描述

现在有两个示例配置文件:

1. 无空白项的

   ``` yaml
   port: 7890
   socks-port: 7891
   allow-lan: true
   mode: Rule
   log-level: info
   external-controller: :9090
   proxies:
     - name: Node
       type: ss
       server: example.com
       port: 20203
       cipher: aes-256-gcm
       password: 0000-0000-0000-0000
       udp: true
   proxy-groups:
     - name: Auto
       type: select
       proxies:
         - DIRECT
         - Node
   rules:
     - GEOIP,CN,DIRECT
     ```

2. 有空白项的

   ```yaml
   port: 7890
   socks-port: 7891
   allow-lan: true
   mode: Rule
   log-level: info
   external-controller: :9090
   proxies:
     -
       name: Node
       type: ss
       server: example.com
       port: 20203
       cipher: aes-256-gcm
       password: 0000-0000-0000-0000
       udp: true
   proxy-groups:
     -
       name: Auto
       type: select
       proxies:
         - DIRECT
         - Node
   rules:
     - GEOIP,CN,DIRECT
   ```

使用下方的预处理配置同时处理以上两个配置文件:

```yaml
parsers:
  - url: https://example.com/the-first.yaml
  - url: https://example.com/the-second.yaml
    yaml:
      prepend-rules:
        - 'DOMAIN,github.com,DIRECT'
```

---

观察处理结果:

1. 无空白项的

   ```yaml
   port: 7890
   socks-port: 7891
   allow-lan: true
   mode: Rule
   log-level: info
   external-controller: :9090
   proxies:
     - name: Node
       type: ss
       server: example.com
       port: 20203
       cipher: aes-256-gcm
       password: 0000-0000-0000-0000
       udp: true
   proxy-groups:
     - name: Auto
       type: select
       proxies:
         - DIRECT
         - Node
   rules:
     - GEOIP,CN,DIRECT
     - DOMAIN,github.com,DIRECT
   ```

2. 有空白项的

   ```yaml
   port: 7890
   socks-port: 7891
   allow-lan: true
   mode: Rule
   log-level: info
   external-controller: :9090
   proxies:
     -
       name: Node
       type: ss
       server: example.com
       port: 20203
       cipher: aes-256-gcm
       password: 0000-0000-0000-0000
       udp: true
   proxy-groups:
     -
       name: Auto
       type: select
       proxies:
         - DIRECT
         - Node
   rules:
     - GEOIP,CN,DIRECT
   ```

---

因此得出结论: 对存在空白项的 YAML 配置文件, 配置文件预处理无法生效.

### 复现步骤

使用配置文件预处理去处理 proxies 中包含空白项的配置文件, 可观察到预处理没有生效..

### 日志文件

进行问题描述中的步骤时没有得到日志文件.

**Comment by yi-Xu-0100** [comment]
每一个匹配器（url 或者 reg）下，需要有内容才会处理。如果想要给多个 url 处理，建议使用 reg 去匹配，否则复制多份。

```yaml
parsers:
  - url: https://example.com/the-first.yaml
    yaml:
      prepend-rules:
        - 'DOMAIN,github.com,DIRECT'
  - url: https://example.com/the-second.yaml
    yaml:
      prepend-rules:
        - 'DOMAIN,github.com,DIRECT'
```
