### ISSUE TITLE
[Feature Request]: please make multi sni and bug config

### ISSUE THREAD

**Issue by volatilaq** [Fndroid/clash_for_windows_pkg#4075]
### 功能描述

why can't I input the yaml config like below
```yaml
# port: 9494
# socks-port: 9595
# mixed-port: 9696
redir-port: 9797
tproxy-port: 9898
mode: rule

allow-lan: true
unified-delay: true
bind-address: '*'
log-level: silent
ipv6: true
geodata-mode: true
geodata-loader: memconservative
external-controller: 0.0.0.0:9090
external-ui: ./dashboard/dist
# secret: ""
tcp-concurrent: false
enable-process: false
inbound-tfo: false
# interface-name: ""
# routing-mark: 233
# geox-url: {
  # mmdb: "",
  # geoip: "",
  # geosite: ""
# }
profile:
  store-selected: true
  store-fake-ip: false
experimental:
  sniff-tls-sni: true
  # fingerprint: ""
sniffer: # sniff domain name optional configuration
  enable: false
  # sniffing protocol required
  sniffing:
    - tls
    - http
  # force sniffing on this domain name
  force-domain:
    - +.v2ex.com
  # Sniff only on ports in the whitelist, default 443, 80
  port-whitelist:
    - 80
    - 443
  # force-dns-mapping: true
  # parse-pure-ip: true
tun:
  enable: false
  # biarkan default utun
  device: utun
  mtu: 9000
  stack: system
  dns-hijack:
    - any:53
  auto-route: false
  auto-detect-interface: false
  # inet4-address: 198.18.0.1/30
  # inet6-address: [fdfe:dcba:9876::1/126]
  strict-route: false
  # inet4-route-address:
    # - 0.0.0.0/1
    # - 128.0.0.0/1
  # inet6-route-address:
    # - '::/1'
    # - '8000::/1'
  # include-android-user:
    # - 0
    # - 10
dns:
  enable: true
  ipv6: true # false akan mengembalikan hasil kosong untuk AAAA
  prefer-h3: false
  default-nameserver:
    - 8.8.8.8
    # - tls://9.9.9.11:853
    - tls://1.0.0.1:853
  listen: 0.0.0.0:1053
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.local"
    - "*.localhost"
  # proxy-server-nameserver:
    # - '1.0.0.1'
  nameserver:
    - 8.8.8.8 # default value
    - tls://1.1.1.1:853 # DNS over TLS
    # - dhcp://rmnet_data+ # dns from dhcp
    # - https://doh.pub/dns-query # DNS over HTTPS
    # - https://dns.alidns.com/dns-query#h3=true  # Mandatory HTTP/3, irrelevant to perfer-h3, mandatory HTTP/3 support for DoH, if not supported, it will not work
    # - https://mozilla.cloudflare-dns.com/dns-query#DNS&h3=true # Specify policy group and use HTTP/3
    # - quic://dns.adguard.com:784 # DNS over QUIC
    # - '8.8.8.8#en0' # Compatible with designated DNS egress NIC
  # fallback:
    # - 'https://1.0.0.1/dns-query'
    # - 'https://9.9.9.9/dns-query'
  # fallback-filter:
    # geoip: false
    # geoip-code: '!ID'
    # # geosite:
      # # - gfw
    # # ipcidr:
      # # - 240.0.0.0/4
    # domain:
      # - '+.google.com'
      # - '+.facebook.com'
      # - '+.youtube.com'
# hosts: {
  # "ota.googlezip.net": "127.0.0.1",
  # "ota-cache1.googlezip.net": "127.0.0.1",
  # "ota-cache2.googlezip.net": "127.0.0.1"
  # }
base-bug:
  bug:
    - &bug-ip1 172.67.199.34
    - &bug-ip2 104.18.20.226
    - &bug-ip3 104.18.21.226
    - &bug-ip4 104.16.51.111
    - &bug-ip5 104.18.30.185
    - &bug-ip6 104.18.31.185
    - &bug-ip7 104.18.27.170
    - &bug-ip8 104.18.210.56
    - &bug-ip9 172.64.149.82
    - &bug-ip10 104.21.21.147
    - &bug-ip11 104.16.53.111
    - &bug-ip12 162.159.138.6
    - &bug-ip13 104.21.8.121
    - &bug-ip14 172.67.139.111
    - &host-nusa 43.229.254.206
    - &host-dtc 38.47.65.22
    - &host-shin 103.253.26.84
    - &host-sgdo 128.199.126.151
    - &host-rajasa 103.227.253.138
    - &host-sgdov 128.199.68.243
    - &host-herbal 128.199.126.151
    - &host-rackh 103.125.14.14
    - &host-howdy 103.253.24.216 #sghe3 howdy
    - &host-2howdy 103.253.24.248
    - &host-3howdy 103.253.24.212 
    - &host-sshkit 103.180.125.171 #sghe3 howdy
    - &bug-s1 presence.teams.live.com
    - &bug-s2 teams.microsoft.com
    - &bug-s3 zoom.us
    - &bug-s4 support.zoom.us
    - &bug-s5 cdn.zoom.us
    - &bug-s6 us07st-cf.zoom.us
    - &bug-s7 careers.zoom.us
    - &bug-s8 trouter2-azsc-uswe-3-a.trouter.teams.microsoft.com
    - &bug-s9 us01st-cf.zoom.us
    - &bug-s10 us02st-cf.zoom.us
    - &bug-s11 us03st-cf.zoom.us
    - &bug-s12 us04st-cf.zoom.us
    - &bug-s13 us05st-cf.zoom.us
    - &bug-s14 us06st-cf.zoom.us
    - &bug-s15 gost-bk.zoom.us
    - &bug-s16 billing.zoomgov.com
    - &bug-s17 porting.zoomgov.com
    - &bug-s18 marketplacecontent-cf.zoom.us
    - &bug-s19 marketplacefront-cf.zoom.us
    - &bug-s20 events.zoom.us
    - &bug-s21 gomarketplacecontent-cf.zoom.us
    - &bug-s22 brooklyn-cuny-edu.zoom.us
    - &bug-s23 payhawk.zoom.us
    - &bug-s24 nita.zoom.us
    - &bug-s25 zhinst.zoom.us
    - &bug-s26 teams.office.com
    - &bug-s27 classroom.google.com
    - &bug-s28 digicert.zoom.us
    - &bug-s29 st1.zoom.us
    - &bug-s30 st2.zoom.us
    - &bug-s31 st3.zoom.us
    - &bug-s32 support.liveon.id
    - &bug-s33 zendesk1.appsflyer.com
    - &bug-s34 beacon.liveon.id
base-proxy:
  vmess:
    - &basevmess
      type: vmess
      alterId: 0
      cipher: auto
      udp: true
      udp-over-tcp: true
      network: ws
      tls: true
      skip-cert-verify: true
  trojan:
    - &basetrojan
      type: trojan
      port: 443
      udp: true
      skip-cert-verify: true
      network: ws
  gfw:
    - &basegrpc
      type: trojan
      port: 443
      udp: true
      skip-cert-verify: true
base-proxy-group:
  url:
    - &url-gg http://www.gstatic.com/generate_204
    - &url-cf http://cp.cloudflare.com/generate_204
proxies:

  - &sshkit
    <<: *basevmess
    name: lb1
    server: *bug-ip11
    port: 80
    uuid: 6fea1649-425b-4092-bf53-29792152c925
    servername: id-lb.vhax.net
    ws-opts: 
      path: /sshkit/gracet4/63cdeec0419ef/
      headers: 
        Host: id-lb.vhax.net
        Early-Data: 1
  - <<: *sshkit
    name: lb2
    server: *bug-ip12
  - <<: *sshkit
    name: lb3
    server: *bug-ip13
  - <<: *sshkit
    name: lb4
    server: *bug-ip14
  - &sshkitsni
    <<: *basevmess
    name: lb s1
    server: *host-sshkit
    port: 443
    uuid: 6fea1649-425b-4092-bf53-29792152c925
    servername: *bug-s34
    ws-opts: 
      path: /sshkit/gracet4/63cdeec0419ef/
      headers: 
        Host: *bug-s34
        Early-Data: 1
  - <<: *sshkitsni
    name: lb s2
    servername: *bug-s12
  - <<: *sshkitsni
    name: lb s3
    servername: *bug-s13
  - <<: *sshkitsni
    name: lb s4
    servername: *bug-s14
  - <<: *sshkitsni
    name: lb s5
    servername: *bug-s5
  - <<: *sshkitsni
    name: lb s6
    servername: *bug-s6
  - <<: *sshkitsni
    name: lb s7
    servername: *bug-s7
  - <<: *sshkitsni
    name: lb s8
    servername: *bug-s8
  - <<: *sshkitsni
    name: lb s9
    servername: *bug-s9
  - <<: *sshkitsni
    name: lb s10
    servername: *bug-s10
  - <<: *sshkitsni
    name: lb s11
    servername: *bug-s11
  - <<: *sshkitsni
    name: lb s12
    servername: *bug-s32
  - <<: *sshkitsni
    name: lb s13
    servername: *bug-s33
  - <<: *sshkitsni
    name: lb s14
    servername: *bug-s14
  - <<: *sshkitsni
    name: lb s15
    servername: *bug-s15
  - <<: *sshkitsni
    name: lb s16
    servername: *bug-s16
  - <<: *sshkitsni
    name: lb s17
    servername: *bug-s17
  - <<: *sshkitsni
    name: lb s18
    servername: *bug-s18
  - <<: *sshkitsni
    name: lb s19
    servername: *bug-s19
  - <<: *sshkitsni
    name: lb s20
    servername: *bug-s20
  - <<: *sshkitsni
    name: lb s21
    servername: *bug-s21
  - <<: *sshkitsni
    name: lb s22
    servername: *bug-s22
  - <<: *sshkitsni
    name: lb s23
    servername: *bug-s23
  - <<: *sshkitsni
    name: lb s24
    servername: *bug-s24
  - <<: *sshkitsni
    name: lb s25
    servername: *bug-s25
proxy-groups:
  - name: final
    type: select
    disable-udp: false
    proxies:
      - SSHKIT™
      - SSHKIT✓
    health-check:
      enable: true
      url: *url-gg
      interval: 60
  - name: WIFIðŸ”µ
    type: select
    proxies: [DIRECT, final]
  - name: SHOPEEðŸ”¶
    type: select
    proxies: [final]
  - name: ADS-ALL
    type: select
    proxies: [REJECT, DIRECT, final]

  - name: SSHKIT✓
    type: load-balance
    strategy: round-robin
    disable-udp: false
    lazy: false
    proxies:
      - lb1
      - lb2
      - lb3
      - lb4
      - lb s1
      - lb s2
      - lb s3
      - lb s4
      - lb s5
      - lb s6
      - lb s7
      - lb s8
      - lb s9
      - lb s10
      - lb s11
      - lb s12
      - lb s13
      - lb s14
      - lb s15
      - lb s16
      - lb s17
      - lb s18
      - lb s19
      - lb s20
      - lb s21
      - lb s22
      - lb s23
      - lb s24
      - lb s25
    url: *url-gg
    interval: 60
  - name: SSHKIT™
    type: url-test
    tolerance: 0
    disable-udp: false
    lazy: false
    proxies:
      - lb1
      - lb2
      - lb3
      - lb4
      - lb s1
      - lb s2
      - lb s3
      - lb s4
      - lb s5
      - lb s6
      - lb s7
      - lb s8
      - lb s9
      - lb s10
      - lb s11
      - lb s12
      - lb s13
      - lb s14
      - lb s15
      - lb s16
      - lb s17
      - lb s18
      - lb s19
      - lb s20
      - lb s21
      - lb s22
      - lb s23
      - lb s24
      - lb s25
    url: *url-cf
    interval: 60
proxy-providers:
rule-providers:
  Rule-Shopee:
    type: file
    behavior: classical
    path: "./confs/ruleset/shopeee.yaml"
  HarusSG:
    type: file
    behavior: classical
    path: "./confs/ruleset/HarusSG.yaml"
  FairMail:
    type: file
    behavior: classical
    path: "./confs/ruleset/fairmail.yaml"
  Playstore:
    type: file
    behavior: classical
    path: "./confs/ruleset/Playstore.yaml"
  WHATSAPP:
    type: http
    behavior: classical
    path: ./confs/ruleset/whatsapp.yaml
  Whitelist:
    type: file
    behavior: classical
    path: "./confs/ruleset/whitelist.yaml"
rules:
  - DOMAIN-SUFFIX,googlesyndication.com,final
  - DOMAIN-SUFFIX,pagead2.googlesyndication.com,final
  - SRC-IP-CIDR, 192.168.0.1/24,WIFIðŸ”µ
  - DST-PORT,7895,REJECT
  - DST-PORT,7892,REJECT
  - AND, ((DST-PORT, 2408/4500/8080), (NETWORK, UDP)),final
  - AND,((GEOSITE,YOUTUBE),(NETWORK,UDP)),REJECT
#  - PROCESS-NAME,com.whatsapp,DIRECT
  - PROCESS-NAME,com.netflix.mediaclient,final
#  - PROCESS-NAME,eu.faircode.email,â­•TWHEâ­•
#  - PROCESS-NAME,com.google.android.apps.maps,DIRECT
#  - PROCESS-NAME,com.kitkagames.fallbuddies,ðŸ‡®ðŸ‡© ID ðŸ‡®ðŸ‡©
  - RULE-SET,Whitelist,final
#  - RULE-SET,WHATSAPP,DIRECT
#  - RULE-SET,HarusSG,AKRAB
  - RULE-SET,Rule-Shopee,final
  - RULE-SET,FairMail,final
#  - RULE-SET,Playstore,BUG IP
  - GEOSITE,CATEGORY-ADS-ALL,ADS-ALL
  - IP-CIDR,127.0.0.1/32,REJECT,no-resolve
  - IP-CIDR6,::1/128,REJECT,no-resolve
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - MATCH,final
#Notes : Netflix pakai server ID
#Fairmail pakai trojan SG
```

is there any solution?
