### ISSUE TITLE
[Bug]: 这是内存泄漏了吗？

### ISSUE THREAD

**Issue by XinSSS** [Fndroid/clash_for_windows_pkg#4122]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.17

### 操作系统

Windows x64

### 系统版本

Win10 22H2 19045.2673

### 问题描述

突然发现电脑无法访问网络， 并且Clash占用很多内存
![Snipaste_2023-03-09_12-01-14](https://user-images.githubusercontent.com/30732527/223997652-4cc2cc46-e15e-45c9-83b4-cd1abfb96650.png)

### 复现步骤

不知道怎么复现，都是正常使用电脑的

### 日志文件

突然发现Log文件很大，1G多， 压缩后还有一百多兆， 只能放网盘分享了

<details><summary>logs</summary><p>

```
https://mega.nz/file/ElQGkZ6L#v0gP0llpGNtWYiOPKH1peF4LjDJ6nC3e9sHvohCBlqQ

```

</p></details>

### 其他补充

不知道是否是我个人的问题， 我的电脑都是使用Tun模式代理的
电脑长时间使用不关机，经常能发现在进行下载的时候速度会很慢， 只能达到20M/S左右， 这个时候把clash重新启动后继续下载才能达到满速120M/S

**Comment by 1-1-2** [comment]
类似的情况：
1. 使用系统代理，一切正常
2. 使用TUN，clash自身对外的请求全都回环了，内存CPU占用瞬间爆炸

**Comment by Fndroid** [comment]
日志里基本都是qbittorrent.exe这个程序在请求，并且基本上都失败了，建议试试把TUN设置里Auto Detect Interface关掉，然后手动在下面输入框设置物理网卡的名称，一般是”WLAN“或者”以太网“

**Comment by XinSSS** [comment]
> 日志里基本都是qbittorrent.exe这个程序在请求，并且基本上都失败了，建议试试把TUN设置里Auto Detect Interface关掉，然后手动在下面输入框设置物理网卡的名称，一般是”WLAN“或者”以太网“

嗯嗯, 好的, 我设置下再用一段时间看看情况如何

**Comment by 1-1-2** [comment]
> 日志里基本都是qbittorrent.exe这个程序在请求，并且基本上都失败了，建议试试把TUN设置里Auto Detect Interface关掉，然后手动在下面输入框设置物理网卡的名称，一般是”WLAN“或者”以太网“

设置了连接名称为“以太网 2”后，问题还是存在。
![image](https://user-images.githubusercontent.com/50569812/224214542-1c2d9386-012c-421d-8498-2489357b1cdb.png)
![image](https://user-images.githubusercontent.com/50569812/224214815-6517d98f-ccb6-49b8-9fa4-3d9f848cd429.png)
注：码掉的是我的节点的域名，是clash-win64.exe发起的请求，192.168.123.8是我电脑的内网IP。

**Comment by yi-Xu-0100** [comment]
@1-1-2 给下tun配置

**Comment by 1-1-2** [comment]
> @1-1-2 给下tun配置

```yaml
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
tun:
  enable: true
  stack: gvisor
  auto-route: true
  dns-hijack:
    - any:53
interface-name: 以太网 2
```
除了 `interface-name` 都是默认的
