### ISSUE TITLE
Make dns object (except `fake-ip-filter`) in clash config independent of whether the TUN mode (with default settings) is enabled or disabled.

### ISSUE THREAD

**Issue by YouJiacheng** [Fndroid/clash_for_windows_pkg#4123]
When the TUN mode is disabled, the dns config is:
```yaml
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 119.29.29.29
    - 1.1.1.1
  fallback:
    - 1.0.0.1
    - 8.8.8.8
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
```
However, when the TUN mode is enabled with default settings, the dns object will be:
```yaml
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
```
DNS Cache Poisoning can cause name servers to misresolve the domain name of a proxy server, resulting in a connection error.

Some name servers may be able to resolve the domain name correctly, while others cannot.
Therefore, the set of name servers used by Clash determines whether the connection will be successful or not.

Ultimately, the behavior is dependent on whether the TUN mode is enabled or disabled, which can confuse users.

I expect it should be
```yaml
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 119.29.29.29
    - 1.1.1.1
  fallback:
    - 1.0.0.1
    - 8.8.8.8
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
```
Currently, I achieve this using `mixin`.
