### ISSUE TITLE
[Bug]: MacOS M2 13.2.1 正常使用，未开启tun模式，开启系统代理，会导致DNS修改到8.8.8.8，手动修改后过一会又会修改到8.8.8.8

### ISSUE THREAD

**Issue by gsy44355** [Fndroid/clash_for_windows_pkg#4142]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.17

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

13.2.1

### 问题描述

正常使用，未开启tun模式，开启系统代理，会导致DNS修改到8.8.8.8，手动修改成其他dns地址后，过一会又会修改到8.8.8.8

### 复现步骤

只需要在相同环境打开APP，开启代理就可以

### 日志文件

无

### 其他补充

均使用默认配置

**Comment by Fndroid** [comment]
看看你配置文件里是不是写了tun，有的话把enable改成false

**Comment by gsy44355** [comment]
> 看看你配置文件里是不是写了tun，有的话把enable改成false

下面是配置文件截图，并没有写tun模式，但是仍然会存在这个问题。
![image](https://user-images.githubusercontent.com/23741868/224887964-def2c305-fd1f-456d-b584-ec8fde14c520.png)

**Comment by gsy44355** [comment]
> 看看你配置文件里是不是写了tun，有的话把enable改成false

下面是配置文件proxies之前的内容，并没有tun模式，额外的一点可能就是 这个配置文件用的是rule-set，而不是直接写的规则，但我觉得应该不影响
```
port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893
mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: false
profile:
  tracing: true
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
    - 119.29.29.29
  fake-ip-filter:
    - "dns.msftncsi.com"
    - "*.srv.nintendo.net"
    - "*.stun.playstation.net"
    - "xbox.*.microsoft.com"
    - "*.xboxlive.com"

```
