### ISSUE TITLE
[Bug]: proxies-provider  open file error

### ISSUE THREAD

**Issue by fanlushuai** [Fndroid/clash_for_windows_pkg#4171]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.18

### 操作系统

Windows x64

### 系统版本

版本	Windows 11 专业版 版本	22H2 安装日期	‎2022/‎10/‎6 ‎星期四 操作系统版本	22621.1413 体验	Windows Feature Experience Pack 1000.22639.1000.0

### 问题描述

错误如下：
![image](https://user-images.githubusercontent.com/21078607/226236879-93f225b7-5631-4153-9eae-368e772f7864.png)

部分配置如下：
``` yml
proxy-providers:
  FreeProxy:
    type: http
    url: "******************"
    path: ./proxies/100Yuan.yaml
    interval: 3600 # one hour
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  United States:
    type: file
    path: ./proxies/100Yuan.yaml  # 《============ 这个位置找不到
    filter: "United States|美国"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
    interval: 3600
```

个人发现：
查看了配置目录，发现下载下来的文件是时间戳命名的。

我理解的typefile，是可以直接在本地文件进行过滤的。

### 复现步骤

使用proxies-provider，添加一个type是 url，一个是file。path指向相同的位置。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
因为http类型的provider会被修改path，你可以用右键profile然后找到上面这个provider，点show actual file，把里面这个文件作为下面这个provider的路径

**Comment by fanlushuai** [comment]
> 因为http类型的provider会被修改path，你可以用右键profile然后edit，找到上面这个provider，点show actual file，把里面这个文件作为下面这个provider的路径

那么相当于，path参数，是没有支持的？

**Comment by Fndroid** [comment]
支持，但是因为http涉及网络下载，有一定的安全风险所以路径被限制了。

**Comment by fanlushuai** [comment]
> 支持，但是因为http涉及网络下载，有一定的安全风险所以路径被限制了。

那么，我的需求是：

想要定义，http和file方式的path，两者用一个相同路径,，以及一个确定的文件名，如下面：

``` yml
proxy-providers:
  FreeProxy:
    type: http
    url: "**********************"
    path: /providers/proxy/100Yuan.yaml    ## 1. 定义文件，在限制的文件夹
    interval: 3600 # one hour
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Rate1.0:
    type: file
  #  path: /providers/proxy/384708abc8dc198a2148a090f620a543.yaml  
    path: /providers/proxy/100Yuan.yaml    # 2. 引用也在限制的文件夹，但是名字是确定的。
    filter: "1.0"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
    interval: 3600
```

能够支持吗？ 我目前观察到的，貌似不可以。

---

 >  path: /providers/proxy/384708abc8dc198a2148a090f620a543.yaml  

不用这种自动生成的，因为不确定，在换机器的时候，或者在换订阅连接的时候，这个文件名可能变化。目的，想要一个确定性的模板，仅仅需要替换url即可。这样可以实现自动化。而不是无法得知actul file导致下面的filter失败。
