### ISSUE TITLE
[Bug]: 使用diff功能时内容含有星号"*"更新后便无法解析

### ISSUE THREAD

**Issue by yeahjack** [Fndroid/clash_for_windows_pkg#4174]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.18

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

macOS 13.1

### 问题描述

我在使用diff编辑配置文件时，将已有的节点名称复制到我新建的一个category中。在update后，原有的节点名称中的星号（"*"）会丢失。详情见此图，为update后的diff文件。
[hided]

### 复现步骤

1. 右击配置文件点击diff
2. 复制原有的含有星号的节点名称到新建的一个category中
3. update配置并选中
4. 问题出现
[hided]

### 日志文件

<details><summary>logs</summary><p>
已查看，日志与此问题无关。
```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
有出现冲突吗

**Comment by yeahjack** [comment]
你好，会直接出现冲突，具体表现为新的category的代理无法解析使用。

**Comment by Fndroid** [comment]
理论上不会出现这种情况，你能把配置文件脱敏了发我看看吗，就保留proxy-groups这部分

**Comment by yeahjack** [comment]
好的，您可以提供一下您的邮箱嘛？还是说我直接发在这里。

**Comment by Fndroid** [comment]
在这里发吧，只要proxy-groups部分就好了

**Comment by yeahjack** [comment]
好的，以下是最主要的proxy-group中的一部分。我只是在diff中复制以下全部内容加为一个新组并改`name`就会在update后选中时出现错误：
```
  - name: 🚧Proxy
    type: select
    proxies:
    - DIRECT
    - ⓪TJ.US空灵 [备用]/10/NF*/D+/Yp
    - ❶gR.JP忍者/荐/1/NF/D+
    - ❶gR.JP星移/1/NF/D+/Yp
    - ❶gR.RU西亚/联通/1
    - ❶gR.UK威廉/BBC/1/NF/D+/Yp
    - ❶gR.US胜地/HBO/1/NF*/D+/Yp
    - ❷gR.JP星移/0.8/NF/D+/Yp
    - ❷gR.JP死神/1/NF/D+/Yp
    - ❷gR.SG烈焰/1/NF*/D+/Yp
    - ❷gR.TW台湾/动画疯/1/NF/D+/Yp
    - ❷gR.TW高雄/荐/1/NF/D+/Yp
    - ❷gR.US川谱/1/NF*/D+/Yp
    - ❷gR.US神像/荐/1.5/NF*/D+
    - ❷gR.US胜地/1/NF*/D+/Yp
```
