### ISSUE TITLE
[Bug]: 电脑(Mac)休眠后(盒盖后)再打开dhcp的dns失效, 报错address already in use

### ISSUE THREAD

**Issue by Ao-Last** [Fndroid/clash_for_windows_pkg#4176]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.18

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

Ventura 13.2.1

### 问题描述

1. clash一切运行正常
2. 电脑合盖, 进入休眠(Wi-Fi会断开)
3. 打开电脑, Wi-Fi重新连接
4. clash dns 中使用dhcp的dns失效, 错误:`listen udp4 0.0.0.0:68: bind: address already in use`
5. 重启clash, 一切恢复正常

### 复现步骤

同上.

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

### 其他补充

```yaml
dns:
  enable: true
  enhanced-mode: fake-ip
  default-nameserver:
    - 119.29.29.29
    - 8.8.8.8
    - 114.114.114.114
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - https://1.1.1.1/dns-query
    - dhcp://en0

tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
```
