### ISSUE TITLE
【求助】 内网有自己的dns服务器我该如何设置可以使用

### ISSUE THREAD

**Issue by ccchhh1** [Fndroid/clash_for_windows_pkg#4180]
### 功能描述

可使用自己手机热点链接
但如果在公司内网有公司自己的dns就无法连接
我应该怎么做才能够使用
谢谢大家
麻烦了

**Comment by Fndroid** [comment]
可以在Mixin配置DNS，然后打开Mixin的开关

```yaml
mixin: 
  dns:
    enable: true
    nameserver:
      - 8.8.8.8 # 这些可以保留，方便你在其他网络里用
      - 114.114.114.114 # 这个改成你内网DNS
```
