### ISSUE TITLE
开启tun模式后系统的dns会被自动改为8.8.8.8

### ISSUE THREAD

**Issue by shinji3887** [Fndroid/clash_for_windows_pkg#4185]
### 功能描述

操作系统：macOS apple silicon
cfw开启tun模式后，系统的dns会被自动改成8.8.8.8，想问下这个是在哪里设置的？
改成clash的dns 198.18.0.2:53以后可以正常解析域名，但是关了cfw再重新开，dns又会被改成8.8.8.8
不太想用dns-hijack方式，就直接改系统dns，这个具体在哪里设置默认值？
配置文件如下：
```yml
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - apps.apple.com
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
```
