### ISSUE TITLE
[Bug]: 同时打开TUN和电脑热点会无限生成连接

### ISSUE THREAD

**Issue by NXY666** [Fndroid/clash_for_windows_pkg#4203]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.19

### 操作系统

Windows x64

### 系统版本

Windows 11

### 问题描述

同时打开TUN和电脑热点会无限生成连接，然后电脑会出现断网的情况。

### 复现步骤

1. 启动热点
2. 启动TUN模式 

### 日志文件

<details><summary>logs</summary><p>

```
[2023-03-26-145304.log](https://github.com/Fndroid/clash_for_windows_pkg/files/11070971/2023-03-26-145304.log)
```

</p></details>

### 其他补充

TUN配置：
```
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
    - 210.34.0.14
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
tun:
  enable: true
  stack: gvisor
  auto-route: true
  dns-hijack:
    - any:53
interface-name: 以太网
```
