### ISSUE TITLE
[Bug]: 证书错误

### ISSUE THREAD

**Issue by verigle** [Fndroid/clash_for_windows_pkg#4241]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.19

### 操作系统

Linux

### 系统版本

Ubuntu 22.04

### 问题描述

![image](https://user-images.githubusercontent.com/32769358/229343171-251f1770-01e5-44a3-8817-2fb173be058a.png)
访问google,提示证书错误
证书居然是facebook

### 复现步骤

开启tun 模式，tun 模式配置如下
![image](https://user-images.githubusercontent.com/32769358/229343231-52ae6575-93a5-40eb-ad33-2a0a61f20720.png)

```
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - https://dns.google/dns-query
    - 223.5.5.5
    - 8.8.8.8
  fallback:
    - 8.8.8.8
    - 119.29.29.29
    - https://223.5.5.5/dns-query
    - tls://dns.google
    - tls://8.8.8.8:853
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - gitee.com
    - notion.so
    - storage.googleapis.com
    - todesk.com
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
auto-redir:
  enable: true
  auto-route: true
```

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
