### ISSUE TITLE
[Feature Request]: 快捷键跨平台自动转换

### ISSUE THREAD

**Issue by wenfangdu** [Fndroid/clash_for_windows_pkg#4283]
### 功能描述

比如现在有以下的快捷键：

```yml
shortcutSystemProxy: Meta+Shift+0
shortcutGlobalMode: Meta+Shift+-
shortcutRuleMode: Meta+Shift+=
```

在 windows 上**配置保持不变**，按下 `Alt` 就相当于按下 `Meta`，因为按键的位置都一样。
