### ISSUE TITLE
[Bug]: 代理测速切换

### ISSUE THREAD

**Issue by fanlushuai** [Fndroid/clash_for_windows_pkg#4289]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.20

### 操作系统

Windows x64

### 系统版本

win11

### 问题描述

1. 手动选择代理组中，配置了，自动切换的子代理组。未能实现通过子代理组中的代理自动切换来获取最终代理。

2. 现在的貌似，只能通过上层代理组的配置进行。点击图中黄色标志位置，其check的只是那个代理本身。而实际子代理组，并不是最快的。

![image](https://user-images.githubusercontent.com/21078607/230704640-f837721f-7913-413f-9f34-9ebced572b66.png)

3. 逻辑期待修改为：
当在父代理组中点击，选中的子代理组时，此时的，check方式。不单单是，选中上轮选择出来的代理，进行测速。而是应该，读取子代理组的类型配置，确认是否为url-test，如果是，就测试，子组中的所有代理，并进行切换。

### 复现步骤

关键配置如下：

``` yaml
proxy-providers:
  FreeProxy:
    type: http
    url: "***************************"
    path: /providers/proxy/100Yuan.yaml
    interval: 3600 # one hour
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Rate1.0:
    type: file
    path: /providers/proxy/100Yuan.yaml
    filter: "1.0"
    interval: 3600 # one hour
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300


proxy-groups:

  - name: PROXY                        #<------------------- 入口
    type: select
    proxies:
      - Mannul  # 在所有节点区间，手动选择
      - Auto All # 在所有节点  自动切换
      - Auto Rate1.0  # 所有费率1.0 自动切换
      - DIRECT 

  - name: Auto Rate1.0
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    use:
      - Rate1.0

  - name: Auto All
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    use:
      - FreeProxy

  - name: Mannul
    type: select
    proxies:
    use:
      - FreeProxy

rules:
  - MATCH,PROXY
```

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
