### ISSUE TITLE
[Feature Request]: tun模式内容可自定义

### ISSUE THREAD

**Issue by lhbdhr** [Fndroid/clash_for_windows_pkg#4302]
### 功能描述

感谢各位大佬的辛苦付出，CFW很好用。

我的需求是：
希望在tun模式设置的界面，右边儿的配置文件片段可以自行修改。

举例说一个我的使用场景：
用tunnels时， 节点的域名会被走代理，DNS走代理，代理域名又需要DNS，就会死循环
这时候``nameserver-policy``就很重要，但是配置tun时，**dns整个配置文件都会被覆盖掉**。
如果手动把tun写到配置文件里，导致软件界面tun开关完全没用了。

如果配置tun的界面可以手动修改右边儿的配置文件片段，就很完美了。

```yaml
dns:
  nameserver-policy:
    'mydomain.com': '223.5.5.5'
  fallback:
    - udp://127.0.0.1:25728
    - udp://127.0.0.1:25729

tunnels:
  - tcp/udp,127.0.0.1:25728,1.1.1.1:53,Proxy
  - tcp/udp,127.0.0.1:25729,8.8.8.8:53,Proxy

proxies:
  - name: SG-ORACLE-1
    server: mydomain.com
```
