### ISSUE TITLE
[Feature Request]: 想请教一下各位大神，怎么写一个规则，定时循环访问我的所有可用节点

### ISSUE THREAD

**Issue by yichen-liang** [Fndroid/clash_for_windows_pkg#4348]
### 功能描述

我看了大部分issue但是没有找到我想要的
想请教一下各位大神，怎么写一个规则，定时循环访问我的所有可用节点

**Comment by yiiyahui** [comment]
```
- name: "load-balance"
    type: load-balance
    proxies:
      - ss1
      - ss2
      - vmess1
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # strategy: consistent-hashing # or round-robin
 ```
