### ISSUE TITLE
软件功能需求：同时保留订阅规则和自定义规则的更新

### ISSUE THREAD

**Issue by decoclaire** [Fndroid/clash_for_windows_pkg#436]
现在CFW自定义的许多规则，机场订阅规则更新后会覆盖自定义的规则，很麻烦，可否在新版本中加入保留自定义规则的功能，这样能兼顾自定义规则和机场订阅规则，谢谢！

**Comment by LM-Firefly** [comment]
@decoclaire 静待后续

**Comment by Fndroid** [comment]
https://github.com/Dreamacro/clash/issues/272

BTW，既然软件是只认配置文件，为什么不去找提供配置文件的人提供这样的功能？

**Comment by luanshixiao** [comment]
> [Dreamacro/clash#272](https://github.com/Dreamacro/clash/issues/272)
> 
> BTW，既然软件是只认配置文件，为什么不去找提供配置文件的人提供这样的功能？

我一直认为Profiles应该只提供Proxy信息，而Proxy Group与Rule应该仅由config.yml提供，这样是否能更好地解决大多数人的自定义需要呢？

**Comment by Fndroid** [comment]
@luanshixiao 
- Proxy和Proxy Group以及Rule三者是相互关联的，其中一个变更不可能不影响其他
- 如果服务商支持，可以用Clash的Proxy Provider功能

**Comment by luanshixiao** [comment]
> @luanshixiao
> 
> * Proxy和Proxy Group以及Rule三者是相互关联的，其中一个变更不可能不影响其他
> * 如果服务商支持，可以用Clash的Proxy Provider功能

是的，这三者的确是关联的，但是可以通过在Proxy Group中通过正则表达式筛选并引入节点，做到Proxy与Proxy Group，Rule的分离。
如下所示：

```
# clash\profiles\sub.yml
# 从订阅获得Proxy
Proxy:
  - name: ~
    type: ~
    server: ~
    port: ~
----------------------------------------------------------
# clash\config.yaml
sub mode = 0 使用本地的Proxy Group，Rule
# sub mode = 1 使用订阅的Proxy Group，Rule
Proxy Group:
  - name: PROXY
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 600
    proxies: #通过正则表达式筛选从订阅获得的Proxy
      - .* #全部
      - (HGC|HKBN|PCCW|HKT|hk|港) #香港
      - (深台|彰化|新北|台|tw) #台湾
  - name: Others
    type: select
    proxies:
      - PROXY
      - DIRECT
Rule:
  - ~~~,PROXY
  - ~~~,REJECT
  - ~~~,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Others
```
这是否是个好的建议？
