### ISSUE TITLE
请教如何为某个特殊的domain设置dns

### ISSUE THREAD

**Issue by Kiswelrg** [Fndroid/clash_for_windows_pkg#4360]
想给 *.bing.com 设置dns8.8.8.8，这样就不会跳转cn bing，才能正常使用bing chat
如果直接设置电脑的dns优先8.8.8.8，又会有jd、某宝这些网站自动跳国际页面的问题，
所以如题想给bing单独设置dns不知道clash中如何实现，我读了clash的文档写了下面这样一块在yml里面：(但是没用
```
dns:
  enable: true
  listen: 0.0.0.0:53

  default-nameserver:
    - 8.8.8.8

  nameserver:
    - 8.8.8.8 # default value
    # Lookup domains via specific nameservers

  nameserver-policy:
    '+.bing.com': '8.8.8.8'
```

还有就是，规则里设置了bing.com走代理` - DOMAIN-SUFFIX,bing.com,Ⓜ️ 微软服务`，也没用，照样会跳转cn
<img width="287" alt="image" src="https://user-images.githubusercontent.com/20332775/233337071-82274c6f-c6b7-4eb7-a835-f0a5af6ca2c1.png">
