### ISSUE TITLE
proxy-providers 和 parsers 怎么同时试用

### ISSUE THREAD

**Issue by brucmao** [Fndroid/clash_for_windows_pkg#4489]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.23

### 操作系统

Windows x64

### 系统版本

win11

### 问题描述

我有两个机场main 和 other，主要用main机场，在parser 自定义一些自己的规则,
```
parsers: # array
  - url: http://main.com
    yaml:
      prepend-rules:
        - DOMAIN-KEYWORD,hottg.com,♻️ 自动选择
        - DOMAIN-KEYWORD,gravatar.com,♻️ 自动选择
        - DOMAIN-KEYWORD,imgix.net,♻️ 自动选择
        - DOMAIN-KEYWORD,club.tgfcer.com,♻️ 自动选择
        - DOMAIN-KEYWORD,xsijishe.com,♻️ 自动选择
```
现在我想把other 机场的香港节点加入main 机场下面的 **♻️ 自动选择** 代理组中，我先用在线转换提取了 other机场的香港节点
然后在main 机场的配置文件中加入下面配置
```
proxy-providers:
  ✈️ other:
    type: http
    url: https://api.10101.io/sub?target=clash.......
    path: ./other.yml
    interval: 86400
    health-check:
      enable: false
      interval: 600
      url: https://www.gstatic.com/generate_204

proxy-groups:
  - name: ♻️ 自动选择
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - 🇭🇰 香港 🄼 | A
      - 🇭🇰 香港 🄼 | B
      - 🇭🇰 香港 🄼 | C
    use:
      - ✈️ other
```

这样配置后，可以看到 **♻️ 自动选择** 代理组中增加了 other机场的香港节点，但是我点击配置更新之后，新加入的节点就消失了，猜测是更新后覆盖了配置文件。

怎么才能同时使用proxy-providers 和 parsers 呢

### 复现步骤

如上面描述

### 其他补充

或者有没有更好的方式使用多个机场订阅，parsers中能更新多个配置文件吗，比如下面这样
```
parsers: # array
  - url: http://main.com
    yaml:
      prepend-rules:
        ....
  - url: http://other.com
      yaml:
        prepend-rules:
          ....
```

**Comment by yi-Xu-0100** [comment]
@brucmao parser 可以添加节点。使用 commands 就好，然后 parser 是顺序执行的，但是仅修改本地，导入的不修改内容，也就是你 parser 修改的 other 通过 proxy-provider 导入是没用的。

**Comment by brucmao** [comment]
@yi-Xu-0100 parser 的commands  添加的节点怎么来? commands 添加的节点只能添加 main 机场的节点，other机场的节点如何添加进来呢

**Comment by brucmao** [comment]
我现在想到的方法是，使用在线转换，先将多个机场节点提取出来，再使用parser?

**Comment by yi-Xu-0100** [comment]
@brucmao provider 使用 other， commands 修改 uses 中增加 other ，就是能出现像你提供的示例那样。

**Comment by brucmao** [comment]
@yi-Xu-0100 将 `proxy-providers:`  写进 parser 里面吗？

**Comment by yi-Xu-0100** [comment]
@brucmao 是的，除非你本身订阅自带这个。

**Comment by brucmao** [comment]
@yi-Xu-0100  是这样吗，我尝试了没添加进来
```
parsers: 
  - url: https://main/api/v1/client/subscribe?token=xxx
    yaml:
      proxy-providers:
        ✈️ other:
          type: http
          url: https://api.10101.io/sub .....
          path: ./other.yml
          interval: 86400
          health-check:
            enable: false
            interval: 600
            url: https://www.gstatic.com/generate_204
      commands:
        - proxy-groups.(♻️ 自动选择).proxies=[]proxyNames|(🇭🇰 香港)
```
