### ISSUE TITLE
[Bug]: ip 类型规则在rule-provier的形式下失效

### ISSUE THREAD

**Issue by sun2ot** [Fndroid/clash_for_windows_pkg#4524]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.24

### 操作系统

Windows x64

### 系统版本

Win11 22H2 22621.1702

### 问题描述

发现一个很奇怪的问题，同一套配置文件，当规则集以rule-provider的形式挂载时，IP-CIDR规则无法生效，如下图
![QQ截图20230605134133](https://github.com/Fndroid/clash_for_windows_pkg/assets/84566015/cda4dfd5-25c3-4c37-8e72-844d596e3bd3)
`*.zhheo.com`域名其IP为国内IP，我确信已经加载相关规则，且没有指定`no-resolve`参数

但当我以普通规则列表挂载时（即非rule-provider模式），IP-CIDR规则又能正常生效
![QQ截图20230605134220](https://github.com/Fndroid/clash_for_windows_pkg/assets/84566015/1068a425-9dd4-4341-afd1-2e2d49b6c331)

### 复现步骤

上文已提供

### 其他补充

```yaml
rules:
  - RULE-SET,cnip,🎯 全球直连
rule-providers:
  cnip:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/sun2ot/ClashRules/main/RuleSet/cnip/cnip.yaml
    path: ./providers/rule-provider_cnip.yaml
    interval: 86400
```
