### ISSUE TITLE
提议：在config.yml中加入是否会被profile覆盖Proxy Group与Rule的功能

### ISSUE THREAD

**Issue by luanshixiao** [Fndroid/clash_for_windows_pkg#454]
机场自带profile的Proxy Group与Rule往往不能满足需要，因此可否加入如下的功能：在config.yml中只有Proxy会被替换，而Proxy Group和Rule不会被替换，如下所示：

```
# Will be ignored after profile selection
Proxy:
  - name: ~
    type: ~
    server: ~
    port: ~

# Will not be ignored after profile selection
Proxy Group:
  - name: 🚀 PROXY
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - .*
      - (HGC|HKBN) #正则
  - name: Ⓜ️ Microsoft
    type: select
    proxies:
      - DIRECT
      - 🚀 PROXY
  - name: 🍎 Apple
    type: select
    proxies:
      - DIRECT
      - 🚀 PROXY
  - name: 🐟 Others
    type: select
    proxies:
      - 🚀 PROXY
      - DIRECT

# Will not be ignored after profile selection
Rule:
  - ~~~,Ⓜ️ Microsoft
  - ~~~,🍎 Apple
  - ~~~,🚀 PROXY
  - ~~~,REJECT
  - ~~~,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,🐟 Others
```
