### ISSUE TITLE
[Bug]: Rule Providers页面中，每个Provider的规则计数是实际的两倍左右

### ISSUE THREAD

**Issue by xkww3n** [Fndroid/clash_for_windows_pkg#4565]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.25

### 操作系统

Windows x64

### 系统版本

22621.1848

### 问题描述

CFW的Providers界面会显示各个Rule Provider内含的规则计数，但这些数字总是大于Rule Provider实际上的规则数量。
基本而言，当Rule Provider内含有n条规则时，CFW将显示为2n条。但部分规则的显示数量会大于或小于2n。

### 复现步骤

在配置文件中定义Rule Provider：
```yaml
rule-providers:
  Test:
    type: http
    behavior: domain
    format: text
    url: https://example.com/rules.txt
    path: ./rules.txt
    interval: 86400
```
rules.txt内含有以下一条规则：
```
.example.com
```
打开CFW，切换到Provider页面，可以看到"HTTP Domain (2 Rules)"

### 其他补充

我实际使用的Rule Providers：
```yaml
rule-providers:
  Bahamut:
    type: http
    behavior: domain
    format: text
    url: https://rules.xkww3n.cyou/text-plus/bahamut.txt
    path: ./rules/bahamut.txt
    interval: 86400
  Bilibili:
    type: http
    behavior: domain
    format: text
    url: https://rules.xkww3n.cyou/text-plus/bilibili.txt
    path: ./rules/bilibili.txt
    interval: 86400
  Bing:
    type: http
    behavior: domain
    format: text
    url: https://rules.xkww3n.cyou/text-plus/bing.txt
    path: ./rules/bing.txt
    interval: 86400
  CJMarketing:
    type: http
    behavior: domain
    format: text
    url: https://rules.xkww3n.cyou/text-plus/cjmarketing.txt
    path: ./rules/cjmarketing.txt
    interval: 86400
  Domestic:
    type: http
    behavior: domain
    format: text
    url: https://rules.xkww3n.cyou/text-plus/domestic.txt
    path: ./rules/domestic.txt
    interval: 86400
  DMM:
    type: http
    behavior: domain
    format: text
    url: https://rules.xkww3n.cyou/text-plus/dmm.txt
    path: ./rules/dmm.txt
    interval: 86400
  Exceptions:
    type: http
    behavior: domain
    format: text
    url: https://rules.xkww3n.cyou/text-plus/exclude.txt
    path: ./rules/exclude.txt
    interval: 86400
  Microsoft:
    type: http
    behavior: domain
    format: text
    url: https://rules.xkww3n.cyou/text-plus/microsoft.txt
    path: ./rules/microsoft.txt
    interval: 86400
  PayPal:
    type: http
    behavior: domain
    format: text
    url: https://rules.xkww3n.cyou/text-plus/paypal.txt
    path: ./rules/paypal.txt
    interval: 86400
  Personal_Direct:
    type: http
    behavior: domain
    url: https://rules.xkww3n.cyou/text-plus/personal/direct.txt
    format: text
    path: ./rules/personal/direct.txt
    interval: 86400
  Protection:
    type: http
    behavior: domain
    format: text
    url: https://rules.xkww3n.cyou/text-plus/reject.txt
    path: ./rules/reject.txt
    interval: 86400
  Steam:
    type: http
    behavior: domain
    format: text
    url: https://rules.xkww3n.cyou/text-plus/steam.txt
    path: ./rules/steam.txt
    interval: 86400
```
CFW Providers页面截图：
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/30206355/184a676b-c7c6-40eb-82d8-4e064e6731b1)
