### ISSUE TITLE
[Feature Request]: 建议在代理组中增加一个OpenAI

### ISSUE THREAD

**Issue by FreeSky007** [Fndroid/clash_for_windows_pkg#4568]
### 功能描述

目前OpenAI比较热门，并且只能用美国节点访问，新加坡、台湾、香港都不可用，建议单独一个代理组

**Comment by Fndroid** [comment]
？

**Comment by yi-Xu-0100** [comment]
diff 或者 parser 或者 找节点提供者。

**Comment by lainbo** [comment]
这不是clash的工作范畴，可以通过写一个JavaScript的mixin解决
```js
module.exports.parse = ({ content }) => {
  const mustHaveKeywords = ['美国', 'United States']
  // 过滤掉美国节点中，包含以下关键字的节点（低质量节点）,每一项为正则，忽略大小写
  const mustNotHaveKeywords = ['实验性', '0\\.', 'b']

  const regexParts = []
  mustHaveKeywords.forEach(keyword => {
    const mustNotHavePart = mustNotHaveKeywords.map(k => `(?!.*${k})`).join('')
    regexParts.push(`(?=.*${keyword}${mustNotHavePart}).*`)
  })
  const regex = new RegExp(`^(${regexParts.join('|')})$`, 'i')

  const rules = [
    'DOMAIN-KEYWORD,cloudfare,ChatGPT',
    'DOMAIN-KEYWORD,openai,ChatGPT',
    'DOMAIN-KEYWORD,sentry,ChatGPT',
    'DOMAIN-SUFFIX,ai.com,ChatGPT',
    'DOMAIN-SUFFIX,auth0.com,ChatGPT',
    'DOMAIN-SUFFIX,challenges.cloudflare.com,ChatGPT',
    'DOMAIN-SUFFIX,client-api.arkoselabs.com,ChatGPT',
    'DOMAIN-SUFFIX,events.statsigapi.net,ChatGPT',
    'DOMAIN-SUFFIX,featuregates.org,ChatGPT',
    'DOMAIN-SUFFIX,identrust.com,ChatGPT',
    'DOMAIN-SUFFIX,ingest.sentry.io,ChatGPT',
    'DOMAIN-SUFFIX,intercom.io,ChatGPT',
    'DOMAIN-SUFFIX,intercomcdn.com,ChatGPT',
    'DOMAIN-SUFFIX,openai.com,ChatGPT',
    'DOMAIN-SUFFIX,openaiapi-site.azureedge.net,ChatGPT',
    'DOMAIN-SUFFIX,stripe.com,ChatGPT',
  ]
  const proxies = content.proxies
    .filter(e => regex.test(e.name))
    .map(e => e.name)
  const groups = content['proxy-groups']

  const newGroup = {
    name: 'ChatGPT',
    type: 'select',
    proxies,
  }

  if (groups.length > 1) {
    groups.splice(1, 0, newGroup)
    content.rules = rules.concat(content.rules)
  }
  return content
}
```

**Comment by IzayoiAster** [comment]
这不是应该向节点提供商反馈吗，你在Clash这里反馈有啥用，Clash本身又没有翻墙功能

**Comment by IzayoiAster** [comment]
这不是应该向节点提供商反馈吗，你在Cfw这里反馈有啥用，Clash本身又没有翻墙功能

**Comment by Atom2004** [comment]
分享一个方法，应该行得通，你可以试试。

进入这个 Parsers 之后，按照下面的规则增加 US 的分组和 openai 的规则。
<img width="302" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/22042246/391403b7-ac20-4b43-a6fc-f01664380945">

```yaml
parsers:
  # shadowsocks-lite
  - url: "上面截图那个 profile 对应的 url"
    yaml:
      append-proxy-groups:
        - name: US
          type: url-test
          url: https://openai.com/ # 换成你喜欢的测速目标也可以
          interval: 300
          proxies:
            - 美国-xxx
            - # 列出你的所有美国节点
      prepend-rules: # rules最前面增加一个规则
        - DOMAIN-SUFFIX,openai.com,US
```
