### ISSUE TITLE
[Bug]: 高于0.20.23版本似乎存在DNS泄漏？

### ISSUE THREAD

**Issue by svngxr** [Fndroid/clash_for_windows_pkg#4584]
### 请认真检查以下清单中的每一项

- [ ] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

高于0.20.23的版本

### 操作系统

Windows x64

### 系统版本

Windows11

### 问题描述

似乎存在DNS泄漏，因为最终走代理的域名不应该在本地进行DNS查询

### 复现步骤

开启Logs debug，可以观察到存在DNS泄漏
诸如

相同的配置文件在0.20.23版本正常无泄露，高于0.20.23版本存在DNS泄露
```
mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    # 已省略
  nameserver:
    - 114.114.114.114
    - 202.112.144.246
    - 223.5.5.5

rules:
  - RULE-SET, Direct, DIRECT, no-resolve
  - RULE-SET, Advertising, REJECT, no-resolve
  - RULE-SET, HTTPDNS, REJECT, no-resolve
  - DOMAIN, bard.google.com, 🇹🇼 Taiwan
  - RULE-SET, Global, 🌏 Global, no-resolve
  - RULE-SET, Microsoft, Ⓜ️ Microsoft, no-resolve
  - RULE-SET, Apple, 🍎 Apple, no-resolve
  - RULE-SET, China, DIRECT, no-resolve
  - GEOIP, CN, DIRECT
  - MATCH, ♾️ Final

```
图中google的域名是走代理的，并且在Global规则中有对应的域名，不应该在本地发起DNS请求
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/125230647/72ea0fe9-7014-42dd-814d-d0b0f1ad8086)
