### ISSUE TITLE
[Bug]: Slient Start 未按预期工作

### ISSUE THREAD

**Issue by yukixz** [Fndroid/clash_for_windows_pkg#4616]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.27

### 操作系统

Windows x64

### 系统版本

Windows 10 22H2

### 问题描述

开启Slient Start选项，开机登录后CFW弹出Dashboard。

- 没有开启Service Mode、Lightweight Mode功能，参见cfw-settings.yaml （#2977）
- 只有一个Logon启动项，没有Schedules Task和Service，参见Autoruns截图 （#2348）

还有其他情况会影响Slient Start功能吗？

### 复现步骤

无需

### 日志文件

<details><summary>cfw-settings.yaml</summary><p>

```
editor: 0
randomControllerPort: true
theme: 1
systemTheme: false
showNewVersionIcon: true
bypassText: |
  bypass:
    - localhost
    - 127.*
    - 10.*
    - 172.16.*
    - 172.17.*
    - 172.18.*
    - 172.19.*
    - 172.20.*
    - 172.21.*
    - 172.22.*
    - 172.23.*
    - 172.24.*
    - 172.25.*
    - 172.26.*
    - 172.27.*
    - 172.28.*
    - 172.29.*
    - 172.30.*
    - 172.31.*
    - 192.168.*
    - <local>
childProcessText: |
  processes: # array
hideAfterStartup: true
showNotifications: true
proxyOrder: 0
runTimeFormat: "hh : mm : ss"
lightweightMode: false
iconSpeed: false
specifyHttpProxyProtocol: false
mixinText: |-
  mixin: # object
    tun:
      enable: true
      stack: gvisor
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
randomMixedPort: false
connShowProcess: true
showTrayProxyDelayIndicator: true
unsafeURLsText: |
  urls: # array
useModeIcons: false
trayColorTransparent: false
connMode: false
useSystemEmoji: false
```

</p></details>

<details><summary>Autoruns</summary><p>

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/3337921/607225d2-154d-40e7-b2f0-af4aa06b48ca)
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/3337921/965d2520-82e0-4ae6-8a43-e18c9f9a5d38)

</p></details>
