### ISSUE TITLE
[Bug]: 配置文件写TUN模式PROCESS-NAME规则无法代理UDP，并且全部流量以IP直连，无法使用域名

### ISSUE THREAD

**Issue by wanzhiyu** [Fndroid/clash_for_windows_pkg#4622]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.27

### 操作系统

Windows x64

### 系统版本

Windows 10 专业版 22H2 19045.3155 Windows Feature Experience Pack 1000.19041.1000.0

### 问题描述

1. 无法使用TUN模式PROCESS-NAME规则代理UDP，所有的流量全是TCP流量，并且 https://browserleaks.com/webrtc 也显示没有代理webrtc的UDP流量，这不是预期的现象。
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/18503895/c9ad5c23-105a-47ce-93b7-357926d0fc38)
与此同时，可以看到一些走直连的UDP是能够连接的（图片里面的第1个）：
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/18503895/b8652a8d-1682-4845-8f4c-2e7702d11bfb)

2. 从上面这幅图也可以看到，所有的流量都是走IP，完全没有走域名的。而且，从日志看，也全部走的是IP连接。我想要opera和chrome的TCP和UDP都走SOCKS5代理，但是显然这样全是IP的规则是无法传递域名给SOCKS5代理的，导致SOCKS5代理中的域名规则无法正常工作。日志如下：
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/18503895/b96a952e-c9dd-4db4-8dde-e49b031641b5)

我知道TUN模式工作在网络层，但是我看网上似乎有人可以在TUN模式下看到域名的分流，但是没有使用PROCESS-NAME规则。我现在想要使用PROCESS-NAME规则代理opera和chrome的所有TCP和UDP请求，同时不要代理其他软件（例如QQ）的TCP和UDP。请问这个功能是可以实现的吗？我目前的配置有没有问题？（配置放在了下方）

### 复现步骤

我在本地搭建了支持UDP的SOCKS5代理（使用V2Ray的Inbound，settings设置UDP打开），我想要完成的需求是要使用PROCESS-NAME规则代理opera和chrome的所有TCP和UDP请求，全部转发到本地的SOCKS5代理，同时不要代理其他软件（例如QQ）的TCP和UDP。CFW的配置文件如下：
```
mode: rule
log-level: debug
proxies:
  - name: jp_transfer
    type: socks5
    server: 127.0.0.1
    port: 13920
    udp: true
  - name: us_transfer
    type: socks5
    server: 127.0.0.1
    port: 13910
    udp: true
proxy-groups:
  - name: jp_transfer_group
    type: select
    proxies:
      - jp_transfer
  - name: us_transfer_group
    type: select
    proxies:
      - us_transfer    
rules:
  - PROCESS-NAME,opera.exe,jp_transfer_group
  - PROCESS-NAME,chrome.exe,us_transfer_group
  - MATCH,DIRECT
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
```

由于配置文件中已经启用了tun，所以没有再在主页上开启“TUN Mode”，如下图所示：
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/18503895/33c13390-8a54-47cf-9353-03e7952824bb)
可以看到网络适配器里面出现了Clash的虚拟网卡：
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/18503895/b69e6efc-8ddb-4ca7-a8c9-50a7142035a9)

我理解的是只要匹配到了PROCESS-NAME为opera.exe的进程，由于我没有附加任何其他条件，那么opera.exe所有的TCP和UDP流量应该都走jp_transfer_group这个代理，由于DNS属于UDP流量，那么也应该全部走代理。然而，实际上没有实现预期。

另外需要说明的是，我没有配置DNS模块，原因是我查阅Clash的Github Issue，发现DNS模块只是在规则匹配的时候才用到，实际上还会经过代理解析DNS后查询真实的IP发起连接。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
日志文件太长，就以文件的形式放在了下方。
```

[2023-07-03-135941.log](https://github.com/Fndroid/clash_for_windows_pkg/files/11933779/2023-07-03-135941.log)

**Comment by Fndroid** [comment]
需要配置dns，不然域名无法反推，参考TUN Mode里的基础配置

**Comment by Fndroid** [comment]
你不是走了DIRECT吗，没发往代理服务器

**Comment by wanzhiyu** [comment]
> 你不是走了DIRECT吗，没发往代理服务器

这几个UDP请求是在使用opera.exe刷新了WebRTC Leak Test网页的时候出现的，它们没有PROCESS-NAME，其实它们应该匹配“PROCESS-NAME,opera.exe,jp_transfer_group”这条规则走代理的，但是它们没有PROCESS-NAME，不得不走了“MATCH,DIRECT”这条规则。
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/18503895/7b9163a4-67bf-4bca-9e08-a2d2bef4b520)

**Comment by Fndroid** [comment]
应该是上游的bug，下个版本看看有没有修复

**Comment by wanzhiyu** [comment]
> 

请问我是否需要向Clash的仓库提交相同的Issue？

**Comment by Fndroid** [comment]
不用，已经修了

**Comment by wanzhiyu** [comment]
> 不用，已经修了

谢谢大佬，请问我是否需要手动更新替换Clash Premium的内核？还是说等到下个CFW版本自动更新哈

**Comment by Fndroid** [comment]
下个版本会更新的，你想手动换了试试先也可以，解压后替换到`安装目录/resources/static/files/win/x64`里

[clash-x64.zip](https://github.com/Fndroid/clash_for_windows_pkg/files/11944918/clash-x64.zip)

**Comment by wanzhiyu** [comment]
> 下个版本会更新的，你想手动换了试试先也可以，解压后替换到`安装目录/resources/static/files/win/x64`里
> 
> [clash-x64.zip](https://github.com/Fndroid/clash_for_windows_pkg/files/11944918/clash-x64.zip)

已替换，现在确实可以实现对UDP的程序PROCESS-PATH的识别了，感谢！
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/18503895/f3a7a9bc-2307-4ac0-95d5-1fd6625ab954)

**Comment by wanzhiyu** [comment]
> 下个版本会更新的，你想手动换了试试先也可以，解压后替换到`安装目录/resources/static/files/win/x64`里
> 
> [clash-x64.zip](https://github.com/Fndroid/clash_for_windows_pkg/files/11944918/clash-x64.zip)

我在使用ipleak.net测试DNS泄露时，发现还有一个关于bug：
如果使用“PROCESS-NAME,msedge.exe,us_transfer_group”这样的规则，则完全不会出现DNS泄露，如下图所示：
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/18503895/36f84d42-b628-4452-9925-ff6db95d305d)
但是，如果使用下面这样的规则，理论上和上面的规则是等价的吧？但是下面的配置会出现明显的DNS泄露。
```
script:
  engine: expr
  shortcuts:
    browers: resolve_process_name() in ['msedge.exe']
rules:
    - SCRIPT,browers,us_transfer_group
```
如下图所示：出现了明显的DNS泄露：
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/18503895/db75c6de-b697-4eeb-b5ea-d00ee1ca9854)

会不会可能是Script Shortcut在实现上存在问题？
