### ISSUE TITLE
[Bug]: processes配置后，不能启动相应的程序

### ISSUE THREAD

**Issue by nmweizi** [Fndroid/clash_for_windows_pkg#4643]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0。20.28

### 操作系统

macOS amd64(Intel)

### 系统版本

13.4.1

### 问题描述

配置完成后，重新启动clash ,第三方应用没有启动。

### 复现步骤

在 setting的Child Processes 设置
```yaml
processes: # array
  - command: /Users/aa/bb/cc/wins.sh     # 程序名称
    log: true # 将在 cwd 目录生成输出日志
    options:
      cwd: /Users/aa/bb/cc # 子进程工作目录
```

### 日志文件

日志设为debug，并没有发现相关日志
