### ISSUE TITLE
[Feature Request]: 请教一下怎么在 Parsers 中对某一个现有的节点分组增加一个分组的引用？

### ISSUE THREAD

**Issue by Atom2004** [Fndroid/clash_for_windows_pkg#4690]
### 功能描述

在 Profiles 中 Update 完了，就自动有了一个 Proxy 的节点分组。

```yaml
proxy-groups:
  - name: Auto
    type: url-test
    url: http://xxx
    interval: 300
    proxies:
      - # 所有能用的节点
  - name: Proxy
    type: select
    proxies:
      - Auto
      - # 还列出了所有能用的节点
rules:
  - # 定义了大量使用 Proxy 的规则
```

然而我在 Parsers 中增加 JP分组 和 US分组
```yaml
parsers:
  - url: "xxx"
    yaml:
      append-proxy-groups:
        - name: JP
          type: url-test
          url: http://xxx
          interval: 300
          proxies:
            - # 所有我能用的 JP 节点
        - name: US
          type: url-test
          url: http://xxx
          interval: 300
          proxies:
            - # 所有我能用的 US 节点。
```

然而我现在想通过 Parser 在 proxy-groups 上增加 US 和 JP 的选项。就想原来的 Auto 那样。那么我在 Clash 的 UI 上选好了 US ，就可以所有原来定义了 Proxy 的规则，都走到 US 的节点上了。
请教一下大神应该怎么编写 Parsers ？
