### ISSUE TITLE
[Bug]: 请问一下为什么我开启了 TUN 模式，基于域名分流的规则组会失效，网站无法正常解析成 hostname

### ISSUE THREAD

**Issue by jiaxi0331** [Fndroid/clash_for_windows_pkg#4726]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.30

### 操作系统

macOS arm64(M1,M1*)

### 系统版本

13.4.1 (c) 

### 问题描述

开启 TUN 模式之后，所有的网络请求均直接显示 IP，不再显示域名，并且分流规则失效，只能通过 GEOIP 来判断是否走代理。
**期望：分流规则在 TUN模式下生效，我设置走直连的域名可以继续走直连，而不是走代理。**
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/11704601/b1d5929f-6dc5-48dc-b950-576c4a589f00)

### 复现步骤

1. Open Dashboard 
2. turn on TUN Mode
3. turn off system proxy

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
[2023-07-31-231656.log](https://github.com/Fndroid/clash_for_windows_pkg/files/12216654/2023-07-31-231656.log)

### 其他补充

```yaml
parsers: # array
  - url: {my subscription url }
    yaml:
      append-proxy-groups:
        - name: GPT
          type: select
          proxies:
            - Japan-TY1-Rate:1.0
            - Japan-TY2-Rate:1.0
            - Japan-OS1-Rate:1.0
            - Japan-OS2-Rate:1.0
            - Japan-OS3-Rate:1.0
      prepend-rules:
        - DOMAIN-SUFFIX,live.com,GPT
        - DOMAIN-SUFFIX,bing.com,GPT
        - DOMAIN,bard.google.com,GPT
        - DOMAIN-SUFFIX,openai.com,GPT
        - DOMAIN-SUFFIX,auth0.com,GPT
        - DOMAIN-SUFFIX,openai.azure.com,DIRECT
        - DOMAIN-SUFFIX,microsofttranslator.com,DIRECT
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53

dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - apps.apple.com
```
开启TUN 模式后，作为对比，我设置 proxy 为 Japan-OS3, GPT 分流选择 TY2, 但是分流规则均失效。
