### ISSUE TITLE
[Bug]: Script规则（仅测试了Process规则）与Rule-Set同时启用时，CPU占用率异常高

### ISSUE THREAD

**Issue by wanzhiyu** [Fndroid/clash_for_windows_pkg#4733]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.30

### 操作系统

Windows x64

### 系统版本

Windows 10 专业版 22H2 19045.3155 Windows Feature Experience Pack 1000.19041.1000.0

### 问题描述

我同时启用了一个rule-set https://github.com/Loyalsoldier/clash-rules 以及至少一个process-name规则时，会发现clash-win64的CPU占用率飙升，严重的时候飙到70%以上。也就是说，下面两行同时启用时，会出现异常。并且，无论我是否运行了chrome.exe都会出现异常，例如，虽然下面只是设置了针对chrome的规则，没有设置任何关于edge的规则，但是只要运行edge等其他联网程序，也会触发CPU的飙升。
```
- SCRIPT,chrome_canary,RU_ZZ,no-resolve
- RULE-SET,proxy,RU_ZZ,no-resolve
script:
  engine: expr
  shortcuts:
    chrome_canary: |
      resolve_process_path() matches 
      ".*\\\\Google\\\\Chrome SxS\\\\Application\\\\chrome\\.exe"

```
正常情况：
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/18503895/d07d7cc5-355b-43e8-b9b3-0f295c076f97)
启用后的异常情况：
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/18503895/39cb12df-9b54-4fe3-a184-32ee4c7ba85b)

但是，我注意到，下面情况都不会引起上述问题：
- 单独启用：
```
- SCRIPT,chrome_canary,RU_ZZ,no-resolve
```
- 单独启用：
```
- RULE-SET,proxy,RU_ZZ,no-resolve
```

### 复现步骤

如上所述，只要启用了上述规则分流，就会导致大量的判断，引起CPU占用率飙升，有没有办法优化域名匹配策略，类似于v2ray的mph？
又或者是Script规则与rule-set之间的重复匹配导致的问题？（我只测试了其中的process规则）

### 日志文件

[仅启用process.log](https://github.com/Fndroid/clash_for_windows_pkg/files/12241680/process.log)
[同时启用了Process和ruleset.log](https://github.com/Fndroid/clash_for_windows_pkg/files/12241681/Process.ruleset.log)

**Comment by wanzhiyu** [comment]
> #4722
> 
> 没有 log 你再重新开 issue 也没啥用，建议左转 taskmanager 社区报错。

抱歉，只是上一个issue改问题改了太多次，所以关掉了重开，不好意思打扰了。我明天抓紧把log加上。

**Comment by dogdie233** [comment]
> > 开了tun的话手动设置一下interface name试试
> 
> _Originally posted by @Fndroid in [#4707 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/issues/4707#issuecomment-1651531097)_

不太一样，这个issue是clash-win64占用高  
另一个issue是clash for Windows图形界面占用高

**Comment by wanzhiyu** [comment]
抱歉各位，现在我把两种情况的log传上来了：
[同时启用了Process和ruleset.log](https://github.com/Fndroid/clash_for_windows_pkg/files/12241699/Process.ruleset.log)
[仅启用process.log](https://github.com/Fndroid/clash_for_windows_pkg/files/12241702/process.log)

**Comment by Fndroid** [comment]
无法复现，提供一下最小复现的profile和tun mode的设置

**Comment by Fndroid** [comment]
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/16091562/bf38143c-cf20-4b20-a838-b94f38d06c34)

**Comment by wanzhiyu** [comment]
抱歉，我之前没有注意到一个事情，我只关注了process规则，但是忘记了我的process规则是通过script shortcut功能来实现的。
这个是正常运行的配置文件（clash-win64.exe不会大量占用CPU）：
```
mode: rule
rules:
  - SCRIPT,chrome_canary,RU_ZZ,no-resolve
  - MATCH,DIRECT
script:
  engine: expr
  shortcuts:
    chrome_canary: |
      resolve_process_path() matches 
      ".*\\\\Google\\\\Chrome SxS\\\\Application\\\\chrome\\.exe"
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5
    - 1.1.1.1
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
proxies:
  - name: ru_dest
    type: socks5
    server: 127.0.0.1
    port: 13830
    udp: true
  - name: ru_transfer
    type: socks5
    server: 127.0.0.1
    port: 13930
    udp: true
proxy-groups:
  - name: RU_dest
    type: select
    proxies:
      - ru_dest
  - name: RU_ZZ
    type: select
    proxies:
      - ru_transfer
rule-providers:
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./providers/rule/b38427df77d4e9f81682d0c8b394b20b.yaml
    interval: 86400
```
在这个配置中，仅启用了SCRIPT规则（根据Process进行筛选）。

这是会导致clash-win64.exe大量占用CPU的配置：
```
mode: rule
rules:
  - SCRIPT,chrome_canary,RU_ZZ,no-resolve
  - RULE-SET,proxy,RU_ZZ,no-resolve
  - MATCH,DIRECT
script:
  engine: expr
  shortcuts:
    chrome_canary: |
      resolve_process_path() matches 
      ".*\\\\Google\\\\Chrome SxS\\\\Application\\\\chrome\\.exe"
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5
    - 1.1.1.1
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
proxies:
  - name: ru_dest
    type: socks5
    server: 127.0.0.1
    port: 13830
    udp: true
  - name: ru_transfer
    type: socks5
    server: 127.0.0.1
    port: 13930
    udp: true
proxy-groups:
  - name: RU_dest
    type: select
    proxies:
      - ru_dest
  - name: RU_ZZ
    type: select
    proxies:
      - ru_transfer
rule-providers:
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./providers/rule/b38427df77d4e9f81682d0c8b394b20b.yaml
    interval: 86400
```
在这个配置中，SCRIPT和RULE-SET规则同时启用。在这个配置时，只要多开几个网页，尤其是图片链接比较多的网页，同时建立多个连接时，可以看到CPU占用率飙升。
