### ISSUE TITLE
[Bug]: 同时开启 TUN 的 Tailscale 的 Exit node 后客户机上不了网

### ISSUE THREAD

**Issue by IntangibleW** [Fndroid/clash_for_windows_pkg#4791]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.31

### 操作系统

Windows x64

### 系统版本

Windows 11 22H2 22621.2134

### 问题描述

我想使用 PC 通过 Tailscale 来共享 Clash 代理，但客户机连不上网

### 复现步骤

Tailscale for Windows 启用 `Run exit node`
Tailscale web 控制台在此设备的路由设置里启用 `Use as exit node`
Preferences里勾选:
`Allow incoming connections`
`Use Tailscale DNS settings`
`Use Tailscale subnets`
`Run unattended`
Clash for Windows 开启TUN Mode

使用其他设备连接 Tailscale VPN，Exit node 选择运行 Clash 的设备，无法访问互联网

### 日志文件

<details><summary>logs</summary><p>

```
No logs available
```

</p></details>

### 其他补充

```
dns:
  enable: true
  listen: localhost:8853
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  nameserver:
    - tls://alidns.com:853
    - tls://dot.pub:853
    - https://alidns.com/dns-query
    - https://doh.pub/dns-query
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
    - controlplane.tailscale.com
    - log.tailscale.io
    - http.docker.internal
```

```
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
```
