### ISSUE TITLE
[Bug]: Too many DNS resolve trials of server domain name.

### ISSUE THREAD

**Issue by L1H0n9Jun** [Fndroid/clash_for_windows_pkg#4797]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.32

### 操作系统

Windows x64

### 系统版本

Windows 11 22621.2134

### 问题描述

1. CFW (Clash) built-in DNS server configured as below:

```yaml
dns:
  enable: true
  listen: 127.0.0.1:53
  default-nameserver:
    - 223.6.6.6
    - 119.28.28.28
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: false
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
```

2. SS server with ***ipv6 only*** domain name (quote as `ipv6.server.tld`).

3. As for previous version 0.20.31, things went as expected:
- Open CFW, doh server names and ipv6.server.tld resolved and cached, ipv6.server.tld got ipv6 address and empty ipv4 address response ([]).
- For later connections, CFW won't try to resolve ipv6.server.tld to get ipv6 or ipv4 addresses as they have been cached.

4. As for CFW 0.20.32, after the initial DNS resolve, CFW won't try to resolve ipv6.server.tld‘s ipv6 address later. But
before each connection matching THE RULES you know (Global mode is the same), CFW will try to resolve ipv6.server.tld‘s ipv4 address (A record) repeatly and get empty response.
What as expected is CFW don't resolve the A record anymore.

5. Debug logs as below (visit google as example):
- Version 0.20.31 (No more DNS resolve of ipv6.server.tld):
![屏幕截图 2023-08-18 235356](https://github.com/Fndroid/clash_for_windows_pkg/assets/20871291/633a715e-9ea2-41f4-a590-8cc8be47f929)

- Version 0.20.32 (A record resolve trial repeatly; google domains resolved in server side):
![屏幕截图 2023-08-18 235304](https://github.com/Fndroid/clash_for_windows_pkg/assets/20871291/2f7b832f-e41a-4d66-9d04-7157bc279c2d)

6. Upstream issue? Not sure.

### 复现步骤

- CFW 0.20.32
- Server with ipv6 only domain name (whatever protocols, ss, vmess etc.)
- DNS server configured
- Make some traffic to the server.

### 日志文件

As above images.

### 其他补充

CFW works with SwitchyOmega in Edge. No TUN or TAP enabled.
Manually curated configure files by myself.
