### ISSUE TITLE
[Feature Request]: [浏览器插件] 建议制作浏览器插件，用来改进Chrome中的VPN的伪装性 #

### ISSUE THREAD

**Issue by Accademia** [Fndroid/clash_for_windows_pkg#4814]
### 功能描述

改进Chrome中的VPN的伪装性（根据规则，配置：时区信息）

之所以，需要一个Chrome插件，来实现下述配置，是为了绕过网站的VPN检测。可以使用如下链接，看看网站是否能检测出使用了VPN。
https://ipdog.io/

目前，虽然有Vytal插件，可以解决类似问题，
https://chrome.google.com/webstore/detail/vytal-spoof-timezone-geol/ncbknoohfjmcfneopnfkapmkblaenokb

但是Vytal插件，只支持全局配置，而用户在基于Clash代理软件的 VPN时，Clash会根据用户的规则分流，会涉及到不通国家的VPS落地机，而Vytal目前只能设置单一的全局配置（进行地理位置伪装），无法满分流时自动修改配置的需求。

-----------------------------

### 可能的解决方案

希望能做一个类似于的Vytal的Chrome插件，用来伪装自己使用的VPN。并且在这个插件中，支持类似Clash Rule那样的规则，实现基于规则的伪装，可伪装的信息如下：
- 时区 
- 浏览器语言
- 操作系统
- 浏览器

如：

```
# ---------------------
#  配置：位置配置的分组
# ---------------------
location-config-groups: 

  - name: Location_And_TimeZone_Config_for_US
     timezone: America/New_York
     locale: en-US
     location_city: Washingon, USA
     location_gps: 38.9072, -77.0369
     system_os: Linux
     language: en-US
     webrtc: Disbale

  - name: Location_And_TimeZone_Config_for_JP
     timezone: Asia/Tokyo
     locale: ja-JP
     location_city: Tokyo, Japan
     location_gps: 35.6895, 139.6917
     system_os: Linux
     language: ja-JP
     webrtc: Disbale

  - name: Location_And_TimeZone_Config_for_Final
     timezone: Default
     locale: Default
     location_city: Default
     location_gps: Default
     system_os: Default
     language: Default
     webrtc: Default

# ---------------------
# 配置：基于规则的分流
# ---------------------
rule:
    - DOMAIN-SUFFIX , us  ,  Location_And_TimeZone_Config_for_US
    - DOMAIN-SUFFIX , jp  , Location_And_TimeZone_Config_for_JP

    - GeoIP  , us  ,  Location_And_TimeZone_Config_for_US
    - GeoIP  , jp  , Location_And_TimeZone_Config_for_JP

    - IP-CIDR   , 103.41.167.0/24  , Location_And_TimeZone_Config_for_JP

   - RULE-SET , netflix_no_resolve   ,  Location_And_TimeZone_Config_for_US

   - MATCH ,  Location_And_TimeZone_Config_for_FINAL


# ---------------------
# 配置：订阅规则集
# ---------------------
rule-providers: 

  netflix_no_resolve: 
    type: http
    behavior: classical
    url: 'https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix_No_Resolve.yaml'
    path: ./ruleset/netflix_no_resolve.yaml
    interval: 86400
```
