### ISSUE TITLE
[Feature Request]: 固化代理服务器的IP

### ISSUE THREAD

**Issue by 0xCandy** [Fndroid/clash_for_windows_pkg#4853]
### General界面截图

略

### 功能描述

很多机场提供的代理服务器都是域名，每次通过该服务器链接外网时都会对代理服务器的域名进行DNS请求，这种请求是通过直连的方式获取的，并且这种DNS请求非常频繁（如果经常使用代理），这种奇怪的请求也可能被被其他DNS服务器（非本机）记录下来，从而被针对。

我想能否将代理服务器的域名与IP地址记录在本地，每次使用代理服务器时，直接使用域名即可，所以每个代理服务器只需一次DNS请求即可，这样不仅能够降低延迟，还更加安全。

**Comment by 0xCandy** [comment]
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/35843157/87947e7b-5c41-4015-9a93-ded6f4f88924)

找到解决办法了，在 CFW 里面 dns 里面增加一个配置"max-ttl: 60"，可以把缓存增加到60秒，默认情况好像只有几秒。

```
dns:
    enable: true
    listen: :53
    use-hosts: true
    max-ttl: 60
    enhanced-mode: fake-ip
    fake-ip-range: 136.95.0.1/16
```

大家可以尝试一下。
