### ISSUE TITLE
[Bug]: CFW latency test problem with domain servers

### ISSUE THREAD

**Issue by SSgumS** [Fndroid/clash_for_windows_pkg#4886]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图

![CFW General](https://github.com/Fndroid/clash_for_windows_pkg/assets/25867589/73776f2e-562b-4d52-911d-817140674c07)

### 操作系统

Windows x64

### 系统版本

10, 11

### 问题描述

Hello

Depending on the ISP, CFW's latency test may not work on domain servers. However, if the server is manually selected, it works even though the latency test is failing. 

On the other hand, the latency test works perfectly for the same servers on the Clash Core dashboard (the dashboard that appears when you click on Clash Core version).

Note: Tested servers were Trojan-GRPC-TLS.

### 复现步骤

This problem doesn't exist in all ISPs. So, it may not be reproducible for everyone.

Affected ISPs can see this problem by changing the proxy's 'server' field to a domain.

### 其他补充

I have captured packets for latency tests of both CFW dashboard (the one that times out) and Clash dashboard (the one that works). The pictures of each are below.

Clash Dashboard (Success):

At the 98th second, manual testing took place.

![Clash Dashboard](https://github.com/Fndroid/clash_for_windows_pkg/assets/25867589/9c4f8040-b637-4b50-b7ef-5ec4f7f5ca56)

CFW Dashboard (Failed):

Manual testing occurred at the beginning.

![CFW Dashboard](https://github.com/Fndroid/clash_for_windows_pkg/assets/25867589/79aa2634-f4ff-4be5-b766-592896f16418)

Note: `pcapng` files can be provided privately if needed.

**Comment by Fndroid** [comment]
Have you set these?
<img width="850" alt="image" src="https://github.com/Fndroid/clash_for_windows_pkg/assets/16091562/13d8b090-6e46-47d6-ba91-7ef0a028f71e">

**Comment by SSgumS** [comment]
> Have you set these? <img alt="image" width="850" src="https://user-images.githubusercontent.com/16091562/270079446-13d8b090-6e46-47d6-ba91-7ef0a028f71e.png">

The default URL does not work as well as the other URLs I tested. As long as a server address is a domain, CFW Dashboard cannot perform latency tests on them. Meanwhile, Clash Dashboard can run latency tests successfully on the same servers. I should emphasize that these servers work flawlessly despite the latency test results.

**Comment by Fndroid** [comment]
I compared delay test requests from two dashboards, and they are almost identical.

The default timeout for the Clash dashboard is 5000, while for CFW, it's 3000.

**Comment by SSgumS** [comment]
> I compared delay test requests from two dashboards, and they are almost identical.
> 
> The default timeout for the Clash dashboard is 5000, while for CFW, it's 3000.

As I tested today, it has something to do with the DNS resolving process. Below is my DNS configuration:

```

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  default-nameserver:
  - 178.22.122.100
  - 185.51.200.2
  - 1.1.1.2
  nameserver:
  - https://free.shecan.ir/dns-query
  fallback:
  - https://1.1.1.2/dns-query
  fallback-filter:
    geoip: true
    geoip-code: IR
    ipcidr:
    - 10.0.0.0/8
```

As a result of testing several changes, I determined that the CFW latency test has some issues with DNS over HTTPS. As soon as I add a normal DNS over UDP server to the fallback group, the CFW latency test is fixed. Like below:

```
  fallback:
  - 1.1.1.2
  - https://1.1.1.2/dns-query
```
