### ISSUE TITLE
[Bug]: 使用proxy-provider文件报错

### ISSUE THREAD

**Issue by lxy35326** [Fndroid/clash_for_windows_pkg#4940]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/31434724/30410702-8d73-4c14-9820-ff0443611030)

### 操作系统

Windows x64

### 系统版本

win11家庭版 22h2

### 问题描述

使用proxy_provider时，在切换配置文件时报错。在proxy_provider里填写某一个机场的订阅时报错，其他机场不报错。

#### 配置文件
```yaml
# 节点配置文件统一存放在 ./profiles/proxies/ 目录中
proxy-providers:
  # 从链接导入的配置文件
  foo:
    type: http
    path: ./profiles/proxies/foo.yaml
    url: https://************/api/v1/client/subscribe?token=***************&flag=clash（订阅地址）
    interval: 3600 
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
  - name: PROXY
    type: url-test
    interval: 3600 
    url: http://www.gstatic.com/generate_204
    use:
      - foo
```

已经尝试过，只要这里填入某一个机场的订阅就会在使用时报错。日志没看到异常。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
[2023-10-17-104834.log](https://github.com/Fndroid/clash_for_windows_pkg/files/12923725/2023-10-17-104834.log)

### 其他补充

无
