### ISSUE TITLE
[Bug]: TUN Mode Cannot Use EA app, but TAP mode can.

### ISSUE THREAD

**Issue by ETOgaosion** [Fndroid/clash_for_windows_pkg#4970]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### General界面截图

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/57280232/4bdd0970-94a3-45d2-9088-c58d816b87d6)

### 操作系统

Windows x64

### 系统版本

Windows 10 专业版 22H2

### 问题描述

TUN Mode无法连接EA App，试图用网络抓包方式更新fake-ip-filter，但wireshark没有在EA端口上发现网络包，EA打开后显示无网络，而且TUN Mode打开后无法使用加速器覆盖网络配置
微软商店，XBox正常
但是关闭TUN Mode打开TAP之后能够完美运行，看上去TAP才是终极答案

### 复现步骤

1. 下载EA App
2. 按照官方文档打开TUN Mode
3. 打开EA App
4. EA App显示无网络

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>
[renderer.log](https://github.com/Fndroid/clash_for_windows_pkg/files/13126215/renderer.log)

### 其他补充

yaml parsers:

```yaml
parsers:
  - url:
    yaml:
      prepend-rules:
      commands:
        - dns.fake-ip-filter.0+'+.stun.*.*'
        - dns.fake-ip-filter.0+'+.stun.*.*.*'
        - dns.fake-ip-filter.0+'+.stun.*.*.*.*'
        - dns.fake-ip-filter.0+'+.stun.*.*.*.*.*'
        - dns.fake-ip-filter.0+'lens.l.google.com'
        - dns.fake-ip-filter.0+'*.n.n.srv.nintendo.net'
        - dns.fake-ip-filter.0+'.stun.playstation.net'
        - dns.fake-ip-filter.0+'xbox.*.*.microsoft.com'
        - dns.fake-ip-filter.0+'*.*.xboxlive.com'
        - dns.fake-ip-filter.0+'*.msftncsi.com'
        - dns.fake-ip-filter.0+'*.msftconnecttest.com'
        - dns.fake-ip-filter.0+'*.mcdn.bilibilivideo.cn'
        - dns.fake-ip-filter.0+'*.qq.com'
```
