### ISSUE TITLE
使用cfw时，无法将 clash 作为 dns server

### ISSUE THREAD

**Issue by ShadowLyin** [Fndroid/clash_for_windows_pkg#62]
dns配置如下
```
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  # enhanced-mode: redir-host
  nameserver:
     - 119.29.29.29
     - 119.28.28.28
     - 1.2.4.8
     - 182.254.116.116
  fallback:
     - 119.29.29.29
     - 119.28.28.28
     - 1.2.4.8
     - 182.254.116.116
     - tls://dns.google:853
     - tls://1.1.1.1:853
```
单使用 clash 时，就可以作为dns server
clash版本：https://github.com/Dreamacro/clash/releases/tag/v0.10.2
