### ISSUE TITLE
cfw-profile-mixin 如何使用？

### ISSUE THREAD

**Issue by yi-Xu-0100** [Fndroid/clash_for_windows_pkg#624]
我在更新中看到了这个关键词，**增加 cfw-profile-mixin 方便在多个配置文件中加入内容**，但是我没找到相关的文档介绍用法，希望能给给个示例教程，麻烦了，谢谢

**Comment by Fndroid** [comment]
```yaml
cfw-profile-mixin:
  dns:
    enable: true
    listen: :53
    enhanced-mode: fake-ip
    nameserver:
      - 192.168.50.1
      - 1.1.1.1
      - 8.8.8.8
      - 114.114.114.114
  experimental:
    interface-name: WLAN
```
