### ISSUE TITLE
关于mixin的建议

### ISSUE THREAD

**Issue by pxw139** [Fndroid/clash_for_windows_pkg#680]
希望cfw-profile-mixin可以添加自定义的代理节点,策略组,还有规则
现阶段我使用这个功能添加这些会直接**替换**掉原有的配置
不知道是我操作问题还是什么情况，但是看描述应该是还不支持这些功能的样子

用途
每次更换配置文件时网易云代理都需要重新添加，如果可以直接丢在config.yaml里可以省下不少时间

这是我使用的配置
```
cfw-profile-mixin:
  Proxy:
    - name: 网易云解锁
      type: http
      server: xxx.com
      port: 8848
  Proxy Group:
    - name: Netease Music
      type: select
      proxies:
        - DIRECT
        - 网易云解锁
  Rule:
    #Domain规则
    - DOMAIN-SUFFIX,163yun.com,Netease Music
    - DOMAIN-SUFFIX,music.163.com,Netease Music
    - DOMAIN-SUFFIX,music.126.net,Netease Music
    - DOMAIN-SUFFIX,api.iplay.163.com,Netease Music
    - DOMAIN-SUFFIX,apm.music.163.com,Netease Music
    - DOMAIN-SUFFIX,apm3.music.163.com,Netease Music
    - DOMAIN-SUFFIX,interface.music.163.com,Netease Music
    - DOMAIN-SUFFIX,interface3.music.163.com,Netease Music
    - DOMAIN-SUFFIX,mam.netease.com,Netease Music
    - DOMAIN-SUFFIX,hz.netease.com,Netease Music
    #CIDR规则
    - IP-CIDR,39.105.63.80/32,Netease Music
    - IP-CIDR,45.254.48.1/32,Netease Music
    - IP-CIDR,47.100.127.239/32,Netease Music
    - IP-CIDR,59.111.21.14/31,Netease Music
    - IP-CIDR,59.111.179.214/32,Netease Music
    - IP-CIDR,59.111.181.38/32,Netease Music
    - IP-CIDR,59.111.181.60/32,Netease Music
    - IP-CIDR,59.111.160.195/32,Netease Music
    - IP-CIDR,59.111.160.197/32,Netease Music
    - IP-CIDR,59.111.181.35/32,Netease Music
    - IP-CIDR,59.111.238.29/32,Netease Music
    - IP-CIDR,101.71.154.241/32,Netease Music
    - IP-CIDR,103.126.92.132/32,Netease Music
    - IP-CIDR,103.126.92.133/32,Netease Music
    - IP-CIDR,112.13.119.17/32,Netease Music
    - IP-CIDR,112.13.122.1/32,Netease Music
    - IP-CIDR,115.236.118.33/32,Netease Music
    - IP-CIDR,115.236.121.1/32,Netease Music
    - IP-CIDR,118.24.63.156/32,Netease Music
    - IP-CIDR,193.112.159.225/32,Netease Music
    - IP-CIDR,223.252.199.66/32,Netease Music
    - IP-CIDR,223.252.199.67/32,Netease Music

```

软件真的很好用XD
