### ISSUE TITLE
更新到0.9.7版本后出现网络连接问题

### ISSUE THREAD

**Issue by linzyjx** [Fndroid/clash_for_windows_pkg#697]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [ x ] 已经尝试更新到最新版本，问题依旧存在
- [ x ] 软件从本仓库下载
- [ x ] 软件下载后未修改任何安装目录中的文件

**描述**
从0.9.6版本升级到0.9.7版本后，节点全部Timeout。打开规则列表显示为空。

日志报：
dial Proxy error: c■■■x.n■■■■t.live:1■■■1 connect error: All DNS requests failed, first error: dial tcp 169.■■■.■■■.104:0->1.1.1.1:853: connectex: A socket operation was attempted to an unreachable network.

回退到0.9.6版本正常

**截图**
![0.9.7的规则列表](https://user-images.githubusercontent.com/8017477/80173395-3e45e700-8622-11ea-8f95-857f27faf528.png)

**其他说明**
配置文件的DNS设置：

```
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
    - 119.29.29.29
    - 223.5.5.5

  fallback:
    # 与 nameserver 内的服务器列表同时发起请求，当规则符合 GEOIP 在 CN 以外时，fallback 列表内的域名服务器生效。
    - tls://1.1.1.1
    # - tls://dns.rubyfish.cn:853
    # - tls://dns.google
```
