### ISSUE TITLE
无法连接代理

### ISSUE THREAD

**Issue by Geylnu** [Fndroid/clash_for_windows_pkg#700]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
无法连接vmess代理，socks5代理有效，即使使用socks5依然无法连接代理
**复现**
请描述复现问题的步骤:
1. 安装使用
2. 修改配置文件，添加代理
3. socks5协议软件测试能够ping通，但无法通过端口连接
4. vmess协议无法连接

**预期行为**
能够通过端口连接，能够使用vmess协议

**截图**
![image](https://user-images.githubusercontent.com/37214688/80186251-4876de00-8640-11ea-8fa1-7760a0b4b7d9.png)

**其他说明**
```
time="2020-04-24T15:17:38+08:00" level=info msg="Start initial compatible provider Proxy"
time="2020-04-24T15:17:38+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2020-04-24T15:17:38+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"
time="2020-04-24T15:17:38+08:00" level=info msg="SOCKS proxy listening at: 127.0.0.1:7891"
time="2020-04-24T15:17:38+08:00" level=info msg="Redir proxy listening at: 127.0.0.1:7892"
time="2020-04-24T15:17:38+08:00" level=warning msg="Failed to start Redir UDP Listener: UDP redir not supported on current platform"
time="2020-04-24T15:17:53+08:00" level=warning msg="dial DIRECT error: dial tcp4 110.43.87.9:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2020-04-24T15:17:53+08:00" level=warning msg="dial DIRECT error: dial tcp4 110.43.87.9:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2020-04-24T15:17:55+08:00" level=warning msg="dial DIRECT error: dial tcp4 110.43.87.9:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2020-04-24T15:17:55+08:00" level=warning msg="dial DIRECT error: dial tcp4 110.43.87.9:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2020-04-24T15:17:55+08:00" level=warning msg="dial DIRECT error: dial tcp4 110.43.87.9:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
time="2020-04-24T15:17:55+08:00" level=warning msg="dial DIRECT error: dial tcp4 110.43.87.9:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions."
```

**Comment by Fndroid** [comment]
如果想用Clash内置的DNS，但又不使用TAP，需要将dns: listen去掉或监听在127.0.0.1上，不然会被误判成TAP模式，影响联网

**Comment by Geylnu** [comment]
我没有使用DNS设置，下面是我的配置文件
``` yml
port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: Global
log-level: info
external-controller: '127.0.0.1:9090'
secret: ''
  
# System proxy will ignore these domains(or ipnet)
cfw-bypass:
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>

# Proxies module latency test settings
cfw-latency-timeout: 3000 # seconds
cfw-latency-url: http://www.gstatic.com/generate_204

# Identify strategy of breaking connections after switching to a new proxy/profile/mode
# Options for proxy: none, chain(proxy group in connection chains), all
# Options for profile: true, false
# Options for mode: true, false
cfw-conn-break-strategy:
  proxy: none
  profile: true
  mode: false

# Run child process after CFW started
# Refer: https://docs.cfw.lbyczf.com/contents/childprocess.html
cfw-child-process: []

# Will be ignored after profile selection
Proxy:
  - name: 搬瓦工
    server: ********
    port: ********
    type: vmess
    uuid: ********
    alterId: 100
    cipher: auto
    tls: false
Proxy Group:
  - name: Proxy
    type: select
    proxies:
      - 搬瓦工
Rule:
  - 'MATCH,DIRECT'
```

我的系统版本是win10-2004-19041.205， 我使用了WSL2
