### ISSUE TITLE
无法使用TAP模式

### ISSUE THREAD

**Issue by nekronhuang** [Fndroid/clash_for_windows_pkg#716]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
TAP模式无法正常使用，看了几乎所有关于TAP的issue，似乎没有看到类似问题和解决方式。

**复现**
请描述复现问题的步骤:
配置文件：
```yaml
port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: silent
experimental:
  interface-name: WLAN
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host #fake-ip
  listen: 0.0.0.0:53
  nameserver:
    - 223.5.5.5
  fake-ip-filter: #这个应该跟我这个问题没啥关系。。
    - 'dns.msftncsi.com'
    - 'www.msftncsi.com'
    - 'www.msftconnecttest.com'
```
看日志会发现不停尝试本地端口去连接，并失败。。。

**截图**
![image](https://user-images.githubusercontent.com/6133789/80272520-fa73e000-86fc-11ea-81e5-758fb45292ab.png)

**其他说明**
clash-core的仓库也翻了一圈。。。不懂原理就是艰难啊
