### ISSUE TITLE
Clash TAP 网卡无法正确分配IP

### ISSUE THREAD

**Issue by kenvix** [Fndroid/clash_for_windows_pkg#725]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**

Clash 启用 TAP 模式后，TAP 网卡已连接上，但无法正确分配IP。在网卡管理中可以看到 IP 为 `169.254.xxx.xxx` 的链路本地地址，IPV4 连接状态为 *无网络访问权限*。

此时，所有节点均 timeout，可以看到日志：

```
time="2020-04-26T16:00:32+08:00" level=warning msg="dial Proxy error: *** connect error: All DNS requests failed, first error: dial tcp 169.254.175.146:0->8.8.8.8:853: connectex: A socket operation was attempted to an unreachable network."
```

**复现**
请描述复现问题的步骤:
1. 启用 TAP 模式
2. 启动 CFW

**预期行为**

正常分配IP，正常上网

**截图**

**其他说明**

配置文件
```yml
  dns:
    enable: true
    ipv6: false
    enhanced-mode: fake-ip
    listen: 0.0.0.0:53
    nameserver:
      - 119.29.29.29
      - 223.5.5.5
    fallback:
      - tls://1.1.1.1
      - tls://dns.rubyfish.cn:853
      - tls://dns.google
  experimental:
    interface-name: cfw-tap
```

本机局域网网络IP地址为 `10.0.0.2` 所在网络 `10.0.0.0/24` 请问是否是网络地址冲突引起的？
