### ISSUE TITLE
更新至0.99后，TAP无效, 无法从UI编辑节点和规则.

### ISSUE THREAD

**Issue by chy9002** [Fndroid/clash_for_windows_pkg#761]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
请具体并清楚地描述遇到的问题

**复现**
请描述复现问题的步骤:
1. 进入'...'
2. 点击'....'
3. 拖动到'....'
4. 触发问题

**预期行为**
1. 启用以下配置会使用TAP模式:
```yaml
dns:
   enable: true
   enhanced-mode: fake-ip # 或 redir-host
   listen: 0.0.0.0:53
   nameserver:
      - 119.29.29.29
      - 223.5.5.5
experimental:
  interface-name: '以太网' # WLAN 为物理网卡名
```
2.  无法从UI编辑节点和规则
从Profile标签进入Edit polices或Edit rules里面没有内容. 但是Proxies标签下能看到节点，以前的规则也在正常执行.

**截图**
1. 
![image](https://user-images.githubusercontent.com/7344772/81065503-2ddd1880-8f0e-11ea-8890-062f3803c121.png)
2. 
![image](https://user-images.githubusercontent.com/7344772/81065518-37ff1700-8f0e-11ea-9072-db3d30e2438b.png)
![image](https://user-images.githubusercontent.com/7344772/81065534-3e8d8e80-8f0e-11ea-9a60-70636af7cb33.png)

**其他说明**
0.9.8没有以上问题，都是升级后突然出现的，尝试过重启重装TAP都不行.
