### ISSUE TITLE
CFW无法正常显示实时流量及连接信息

### ISSUE THREAD

**Issue by maooyer** [Fndroid/clash_for_windows_pkg#788]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
CFW无法正常显示实时流量及连接信息。我确认 clash api 是有数据返回的，但 CFW 不能正常展示。节点切换及延迟检查功能正常

**预期行为**
可以正常显示实时流量及连接信息

**截图**
![screen](https://user-images.githubusercontent.com/1215295/81692081-7194cc80-9490-11ea-9501-6201e456ce3d.gif)

**Comment by Fndroid** [comment]
试试点右上角x关闭，再从任务栏打开看下有没有显示

**Comment by maooyer** [comment]
没有显示
![screen2](https://user-images.githubusercontent.com/1215295/81693182-2085d800-9492-11ea-8d99-2f912d385863.gif)

**Comment by Fndroid** [comment]
设置了secret吗General YAML里，Clash for Windows不是用http获取上下行速度的，而是用ws

**Comment by maooyer** [comment]
未设置 secret，config.yaml 如下
``` yaml
port: 9090
socks-port: 9091
#redir-port: 9092
allow-lan: true
mode: Rule
log-level: info
external-controller: '127.0.0.1:9093'
#secret: ''
cfw-bypass:
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - <local>
Proxy:
  - name: Shadowsocks
    type: socks5
    server: 127.0.0.1
    port: 1080
Proxy Group:
  - name: Proxy
    type: select
    proxies:
      - Shadowsocks
Rule:
  - 'MATCH,DIRECT'

```
ws 是监听的哪个接口，和 external-controller 相同么？
