### ISSUE TITLE
clash v0.9.10 TAP模式错误

### ISSUE THREAD

**Issue by RManLuo** [Fndroid/clash_for_windows_pkg#794]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**描述**
在使用TAP模式时，出现 "dial GLOBAL error: my_node_domain.com:443 connect error"，导致全部无法访问互联网。关闭TAP模式即可正常上网。

**复现**
请描述复现问题的步骤:
1. 进入全局config处设置
```
cfw-profile-mixin:
  dns:
    enable: true
    enhanced-mode: fake-ip # 或 redir-host
    listen: 0.0.0.0:53
    nameserver:
      - 119.29.29.29
      - 114.114.114.114
```
2. 点击`Mixin`
3. 在Log处出现大量错误信息，且无更多提示。
```
time="2020-05-14T02:30:07+08:00" level=warning msg="[UDP] dial GLOBAL error: my_node_domain.com:443 connect error"
time="2020-05-14T02:30:08+08:00" level=warning msg="dial GLOBAL error: my_node_domain.com:443 
```
**预期行为**
正常使用TAP访问互联网
**截图**
![](http://image.rman.top/20200514024038.jpg)

**Comment by Fndroid** [comment]
设置interface-name，https://docs.cfw.lbyczf.com/contents/tap.html

**Comment by RManLuo** [comment]
已增加interface-name，仍然同样错误
```
cfw-profile-mixin:
  dns:
    enable: true
    enhanced-mode: fake-ip # 或 redir-host
    listen: 0.0.0.0:53
    nameserver:
      - 119.29.29.29
      - 114.114.114.114
  experimental:
   interface-name: WLAN # 物理网卡名称
```
