### ISSUE TITLE
TAP 模式无法连接

### ISSUE THREAD

**Issue by everplus** [Fndroid/clash_for_windows_pkg#810]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [ x ] 已经尝试更新到最新版本，问题依旧存在
- [ x ] 软件从本仓库下载
- [ x ] 软件下载后未修改任何安装目录中的文件

**描述**
公司电脑 win 10，0.9.9, 0.9.10, 0.9.11 TAP 都用不了，0.9.8 可以，interface-name 有配置，名字不会错，cfw-tap 一直显示网络电缆被拔出 ( 开启关闭 clash 状态一直不会变 )，属性里 ip 地址和 dns 都已经设置上，重装 tap device 也不行，电脑有线网卡，有 hyper-v 虚拟网卡和 docker
家里电脑 win 10 一样配置所有版本 tap 都可以用

**截图**
![image](https://user-images.githubusercontent.com/2535751/82171103-ecc70a00-98f8-11ea-80e3-607c70e23bee.png)
![image](https://user-images.githubusercontent.com/2535751/82171124-f94b6280-98f8-11ea-9dc9-e107f5ae2f55.png)
![image](https://user-images.githubusercontent.com/2535751/82171145-0e27f600-98f9-11ea-8f24-6ac1545c78b6.png)

**Comment by Fndroid** [comment]
管理员模式启动的么

**Comment by everplus** [comment]
不是，就是普通双击启动，属性里也没有设置任何兼容选项，需要用管理员方式启动么？

**Comment by liangsiye** [comment]
@everplus 你好，可以贴出 配置文件 里如下的配置我看看吗

```yml
dns:
   enable: true
   enhanced-mode: fake-ip # 或 redir-host
   listen: 0.0.0.0:53
   nameserver:
      - 223.5.5.5
experimental:
   interface-name: WLAN # 物理网卡名称
```
