### ISSUE TITLE
【配置文件解析】未正确处理ipv6地址

### ISSUE THREAD

**Issue by 1-1-2** [Fndroid/clash_for_windows_pkg#844]
**信息**
如果符合，请将``[ ]``改为``[x]``
- [x ] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载
- [x ] 软件下载后未修改任何安装目录中的文件

**描述**
Clash支持`[]`包裹的ipv6地址的解析
但在clash for windows的使用中发现，如果DNS设置中包含ipv6地址会导致配置文件解析过程出错

**复现**
请描述复现问题的步骤:
1. 使用以下DNS设置
```yaml
dns:
  enable: true
  ipv6: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  fake-ip-filter:
##Custom DNS##
  nameserver:
  - 10.0.20.201
  - [2409:8057:2000:2::8]
  - [2409:8057:2000:6::8]
```
2. 拖动本地配置文件到profiles窗口
3. 点击刚导入的配置
4. 触发问题

**预期行为**
清晰地描述期望看到的行为

**截图**
如果可以，请提供对应问题的截图
![image](https://user-images.githubusercontent.com/50569812/83323827-dd9a7180-a293-11ea-9670-c6a3aaf816c9.png)

**其他说明**
其他补充内容

**Comment by Fndroid** [comment]
加引号引起来

**Comment by 1-1-2** [comment]
的确加了引号就好了，另外还必须补充接口

```yaml
dns:
  enable: true
  ipv6: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  fake-ip-filter:
  nameserver:
  - 114.114.114.114
  fallback:
  - tls://8.8.8.8:853
  - "[2409:8057:2000:6::8]:53"
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
```

谢谢大佬
