### ISSUE TITLE
现有配置下TAP无法连接

### ISSUE THREAD

**Issue by chewnglow** [Fndroid/clash_for_windows_pkg#876]
按照文档和GitHub issues说明的建议，仍无法实现TAP连接，logcat无输出，socks正常。每项改动均重启了clash，更改网卡名称后重启了系统，版本0.9.11/0.10.1。

--- 
profile配置情况：
```
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip  # redir-host也无效
  nameserver:
  - 略
  fallback:
  - 略
# experimental:  添加与否均无效
interface-name: '以太网'   #使用中文或英文'Ethernet'名称均无效
```

硬件配置情况：
- cfw-tap
![image](https://user-images.githubusercontent.com/22649869/83888854-f9fb4a00-a77c-11ea-8468-dd39e21b523a.png)
- 以太网：
![image](https://user-images.githubusercontent.com/22649869/83889004-30d16000-a77d-11ea-9cbe-f41637ccfd67.png)
- 网络适配器界面状态：
![image](https://user-images.githubusercontent.com/22649869/83889200-6bd39380-a77d-11ea-973c-b31bd8fb8f5d.png)
--- 
感谢您的关注！

**Comment by Fndroid** [comment]
experimental不能注释掉，interface-name是它的子键，缩进别弄错

**Comment by chewnglow** [comment]
感谢回复！目前该项配置为：
```
experimental:
  # ignore-resolve-fail: true
  interface-name: '以太网'
```
其余不变，仍无法实现，网关中没有tap网卡的地址。另外尝试过数个版本的TAP驱动，均无法正常使用

**Comment by Fndroid** [comment]
你上面两个图的设置都不对，cfw-tap的dns是127.0.0.1，以太网的dns不应该是127.0.0.1，哪里有说明要改这两个地方的么

**Comment by chewnglow** [comment]
cfw-tap是自动生成的，估计因为在10.0.0.0的大局域网段下面，不过我参考之前的issue手动改成127.0.0.1也是无效。物理网卡的设置参考了 https://www.xkww3n.life/2020/02/13/clash-tap-network-adapter/ 这篇文章。不过没有尝试物理网卡保持不变的情况下TAP网卡DNS为127.0.0.1的情况，稍后我尝试一下，谢谢！

**Comment by chewnglow** [comment]
修改为如下选项后重启电脑
![image](https://user-images.githubusercontent.com/22649869/83958212-d8e04980-a8a1-11ea-90c2-dc4ea4a45f32.png)
仍无法正常使用，链路表上找不到TAP设备IP，配置文件未作修改，为
```
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip  
  nameserver:

  fallback:

experimental:
  # ignore-resolve-fail: true
  interface-name: '以太网'

```

**Comment by Roarcannotprogramming** [comment]
> 修改为如下选项后重启电脑
> ![image](https://user-images.githubusercontent.com/22649869/83958212-d8e04980-a8a1-11ea-90c2-dc4ea4a45f32.png)
> 仍无法正常使用，链路表上找不到TAP设备IP，配置文件未作修改，为
> 
> ```
> dns:
>   enable: true
>   ipv6: false
>   listen: 0.0.0.0:53
>   enhanced-mode: fake-ip  
>   nameserver:
> 
>   fallback:
> 
> experimental:
>   # ignore-resolve-fail: true
>   interface-name: '以太网'
> ```

你是windows 2004吗

**Comment by chewnglow** [comment]
不是，是1909

**Comment by sipieng** [comment]
@chewnglow 试试打开mixin，在General YAML里面定义呢？
我就是这么做的，v0.10.1以及之前的版本都没有问题。
不行的话直接拷贝我用的代码试试（interface-name请自行更改）：
```
cfw-profile-mixin:
  dns:
    enable: true
    enhanced-mode: fake-ip # 或 redir-host
    listen: 0.0.0.0:53
    nameserver:
      - 8.8.8.8
      - 114.114.114.114
    fake-ip-filter:
      - 'dns.msftncsi.com'
      - 'www.msftncsi.com'
      - 'www.msftconnecttest.com'
experimental:
  interface-name: '以太网'
```

**Comment by tony1016** [comment]
我感觉网络层面啥都不要设置，都让自动获取，就杠杠的

**Comment by chewnglow** [comment]
感谢各位回复！最近重装了1909版的系统，按照之前的配置tap正常工作了。正确操作的确为不在系统中额外的设置，只需要修改当前配置文件（暂时没有用mixin）。
目前的硬件情况：
cfw-tap:（软件自带）
![image](https://user-images.githubusercontent.com/22649869/84103140-cd795380-aa44-11ea-93cd-8ca128226a25.png)
以太网未修改设置，IP和DNS自动获取
--- 
配置文件：
```
experimental:
  ignore-resolve-fail: true
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
  - ...
  fallback:
  - ...
```
