### ISSUE TITLE
cfw-profile-parsers 指定js文件相关问题

### ISSUE THREAD

**Issue by IceLitty** [Fndroid/clash_for_windows_pkg#905]
@Fndroid 
**信息**
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [ ] 软件下载后未修改任何安装目录中的文件
（这个不勾我认为改config也算改了吧，要是指二进制文件那没动过）

**描述**
针对新版本的`cfw-profile-parsers`其中的`path`功能，出现了疑似不执行的问题。

**复现**
`config.yml`中修改的配置（url隐去）：
```yaml
cfw-profile-parsers:
  - url: https://***.*******.***/*****/***********.yml?id=*******&password=********
    path: 'D:/Applications/Clash.for.Windows-win/resources/static/files/icyRuleProxy2.js'
    # code: |
    #   module.exports.parse = async (raw, { axios, yaml, notify }) => {
    #       const obj = yaml.parse(raw);
    #       notify("cfw", "update has been modified", false);
    #       return yaml.stringify(obj);
    #   }
```
`icyRuleProxy2.js`中的内容：
```javascript
module.exports.parse = async (raw, { axios, yaml, notify }) => {
    notify("cfw", "update has been modified", true);
    const obj = yaml.parse(raw);
    return yaml.stringify(obj);
}
```
看过 #877 后也试过这种写法：
```javascript
module.exports.parse = (raw, { yaml }) => {
    const obj = yaml.parse(raw);
    return yaml.stringify(obj);
}
```
若直接使用 #877 或你的[doc](https://docs.cfw.lbyczf.com/contents/parser.html)里的写法是正常的，例如上面注释掉的那部分，但是换成`path`之后似乎像不执行一样，没有任何结果。

**预期行为**
不知是我写错了还是有问题，等待修复。
另外希望能将js执行出的日志也输出出来方便调试？
以及上面链接的教程里的`- code`多了个`-`。
