### ISSUE TITLE
在线构建自定义配置有误？

### ISSUE THREAD

**Issue by jiid** [Fndroid/clash_for_windows_pkg#964]
**信息**

- [ x] 已经尝试更新到最新版本，问题依旧存在
- [x ] 软件从本仓库下载
- [x ] 软件下载后未修改任何安装目录中的文件

**系统**

win10最新系统，cfw v 0.11.1

**描述**

这里的默认配置，设置完报错，是否可以添加一份适合国情的默认示例
https://github.com/Fndroid/clash_for_windows_pkg/wiki/%E5%9C%A8%E7%BA%BF%E6%9E%84%E5%BB%BA%E8%87%AA%E5%AE%9A%E4%B9%89%E9%85%8D%E7%BD%AE

**截图**

![demo](https://user-images.githubusercontent.com/39921677/87864984-bd3c8880-c9a1-11ea-9977-e9ba7b929e24.png)

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/87865042-9894e080-c9a2-11ea-9149-fbebc5a81ad4.png)
这个勾勾上

**Comment by jiid** [comment]
弱弱问一下这个设置在哪里？我使用的是本地配置文件，实在没找到

**Comment by jiid** [comment]
我直接使用下面的配置，没有使用在线生成。默认配置一直报错，把Rule改成rules也一样
```
Proxy: []
Proxy Group:
  - name: UrlTest
    type: url-test
    proxies: 
      - DIRECT
    url: http://www.gstatic.com/generate_204
    interval: 300
  - name: PROXY
    type: select
    proxies:
      - UrlTest
  - name: Final
    type: select
    proxies:
      - PROXY
      - DIRECT
  - name: Apple
    type: select
    proxies:
      - DIRECT
      - PROXY
  - name: GlobalMedia
    type: select
    proxies:
      - PROXY
  - name: HKMTMedia
    type: select
    proxies:
      - DIRECT
Rule:
  - RULE-SET,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/Unbreak.list,DIRECT
  - RULE-SET,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/GlobalMedia.list,GlobalMedia
  - RULE-SET,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/HKMTMedia.list,HKMTMedia
  - RULE-SET,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/Global.list,PROXY
  - RULE-SET,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/Apple.list,Apple
  - RULE-SET,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/China.list,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Final
```
