### ISSUE TITLE
mixin有问题?还是我理解错误?TAP相关

### ISSUE THREAD

**Issue by kingcomxu** [Fndroid/clash_for_windows_pkg#974]
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载
- [x] 软件下载后未修改任何安装目录中的文件

**系统**
Windows 10 2004(19041.388) 

**描述**
  在settings里profile mixin里
填写
```
dns:
   enable: true
   enhanced-mode: redir-host # 或 fake-ip
   listen: 0.0.0.0:53
   nameserver:
      - 223.5.5.5
experimental:
   interface-name: '以太网' # 物理网卡名称 
```
手动重启后, tap网卡并不正常, 依然是网络线缆被拔出, 后来找了网上的资料, 说得在.config\clash\profiles里的具体profile里添加这段才正常, 为什么?
不是说mixin里会替换到profile里吗?

顺便提一个mixin界面比较让人迷惑的问题, 就是弹出来的界面默认有:
mixin: # object
这一行, 但又是可编辑的, 这时候不知道是要删掉还是保留, 如果必须保留的话, 我建议是不是可以把这一行显示出来并且是只读不可编辑的?
当然, 回到主问题, 我试了保留或删除, 但是都不生效.
